/**
 * 生物人教版初中题目种子数据
 *
 * 涵盖 7~8 年级共 8 个章节，总计 158 道题。
 *   7年级：生物和生物圈(12)、了解生物圈(16)、细胞是生命活动的基本单位(24)、细胞怎样构成生物体(20)
 *   8年级：生物圈中的绿色植物(20)、生物圈中的人(24)、生物圈中的其他生物(20)、生物的生殖与发育(22)
 *
 * 题型分布：choice ~45% | fill ~20% | short_answer ~25% | matching ~10%
 * 难度分布：difficulty 1(基础) ~40% | 2(中等) ~40% | 3(提高) ~20%
 */

import { prisma } from '../../src/config/database.js';

const questions = [
  {
    chapterKey: 'biology-renjiao-7-0',
    questionKey: 'biology-renjiao-7-0-0',
    type: 'choice',
    questionText: '下列不属于生物的是（）',
    answer: 'D',
    explanation: '钟乳石是自然沉积形成的无机物，不具有生命特征（如新陈代谢、生长繁殖、应激性等），不属于生物。含羞草、珊瑚虫和蘑菇都具有生命现象。',
    difficulty: 1,
    options: '["A. 含羞草","B. 珊瑚虫","C. 蘑菇","D. 钟乳石"]',
  },
  {
    chapterKey: 'biology-renjiao-7-0',
    questionKey: 'biology-renjiao-7-0-1',
    type: 'choice',
    questionText: '"种瓜得瓜，种豆得豆"描述的是生物的哪种特征（）',
    answer: 'A',
    explanation: '"种瓜得瓜，种豆得豆"描述的是亲子代之间的相似性，即遗传现象，属于生物的繁殖和遗传特征。',
    difficulty: 1,
    options: '["A. 遗传","B. 变异","C. 适应环境","D. 影响环境"]',
  },
  {
    chapterKey: 'biology-renjiao-7-0',
    questionKey: 'biology-renjiao-7-0-2',
    type: 'choice',
    questionText: '含羞草受到触碰后叶片合拢，这体现了生物的哪种特征（）',
    answer: 'B',
    explanation: '含羞草受到外界刺激后叶片合拢，是对外界刺激作出的反应，体现了生物的应激性。',
    difficulty: 1,
    options: '["A. 生长","B. 应激性","C. 繁殖","D. 呼吸"]',
  },
  {
    chapterKey: 'biology-renjiao-7-0',
    questionKey: 'biology-renjiao-7-0-3',
    type: 'choice',
    questionText: '下列哪种现象不能体现生物影响环境（）',
    answer: 'C',
    explanation: '大树底下好乘凉体现了植物通过蒸腾作用降低温度，是生物影响环境；蚯蚓疏松土壤是生物影响环境；千里冰雪是自然现象，不是生物影响环境；蝗虫啃食庄稼也是生物影响环境。',
    difficulty: 2,
    options: '["A. 大树底下好乘凉","B. 蚯蚓疏松土壤","C. 千里冰封，万里雪飘","D. 蝗虫啃食庄稼"]',
  },
  {
    chapterKey: 'biology-renjiao-7-0',
    questionKey: 'biology-renjiao-7-0-4',
    type: 'choice',
    questionText: '在探究"光对鼠妇生活的影响"实验中，实验变量是（）',
    answer: 'A',
    explanation: '该实验探究的是光对鼠妇生活的影响，因此光照是实验变量。其他条件（温度、湿度等）应当保持相同，即控制变量。',
    difficulty: 2,
    options: '["A. 光照","B. 温度","C. 湿度","D. 食物"]',
  },
  {
    chapterKey: 'biology-renjiao-7-0',
    questionKey: 'biology-renjiao-7-0-5',
    type: 'fill',
    questionText: '生物的生活需要一定的条件，如______、______、营养物质和适宜的温度等。',
    answer: '阳光、水',
    explanation: '生物的生活需要阳光、水、营养物质、适宜的温度和一定的生存空间等基本条件。',
    difficulty: 1,
    acceptableAnswers: '["阳光、水","水、阳光"]',
  },
  {
    chapterKey: 'biology-renjiao-7-0',
    questionKey: 'biology-renjiao-7-0-6',
    type: 'fill',
    questionText: '在探究实验中，除变量不同外，其他条件都应相同的实验叫做______实验。',
    answer: '对照',
    explanation: '对照实验是指在探究某种因素对实验对象的影响时，除了这个因素不同以外，其他因素都保持相同的实验。',
    difficulty: 1,
  },
  {
    chapterKey: 'biology-renjiao-7-0',
    questionKey: 'biology-renjiao-7-0-7',
    type: 'fill',
    questionText: '调查是科学探究的一种基本方法，调查时首先要明确调查______和调查______。',
    answer: '目的、范围',
    explanation: '调查是科学探究的常用方法之一，进行调查时首先要明确调查目的和调查范围，制定合理的调查方案。',
    difficulty: 2,
    acceptableAnswers: '["目的、范围","范围、目的"]',
  },
  {
    chapterKey: 'biology-renjiao-7-0',
    questionKey: 'biology-renjiao-7-0-8',
    type: 'short_answer',
    questionText: '请列举生物的五个基本特征。',
    answer: '①生物的生活需要营养；②生物能进行呼吸；③生物能排出身体内产生的废物；④生物能对外界刺激作出反应（应激性）；⑤生物能生长和繁殖；⑥生物都有遗传和变异的特性；⑦生物能适应和影响环境。（任答五点即可）',
    explanation: '生物的基本特征包括：需要营养、能呼吸、能排出废物、有应激性、能生长繁殖、有遗传变异特性、能适应和影响环境等。',
    difficulty: 2,
  },
  {
    chapterKey: 'biology-renjiao-7-0',
    questionKey: 'biology-renjiao-7-0-9',
    type: 'short_answer',
    questionText: '在设计探究实验时，为什么要设置重复组？',
    answer: '设置重复组可以减小实验误差，提高实验结果的可靠性。如果实验组数量太少，偶然性较大，设置多个重复组取平均值可以使结果更有说服力。',
    explanation: '设置重复组（多次实验或多个实验对象）是科学探究的重要原则，目的是减少偶然因素对实验结果的影响，提高实验数据的可靠性和准确性。',
    difficulty: 2,
  },
  {
    chapterKey: 'biology-renjiao-7-0',
    questionKey: 'biology-renjiao-7-0-10',
    type: 'short_answer',
    questionText: '某同学在探究"湿度对鼠妇生活的影响"实验中，在干燥和潮湿两组中都放入了10只鼠妇，观察10分钟后统计两组中鼠妇的数量。请指出该实验设计中的不合理之处，并改正。',
    answer: '不合理之处：只用了10只鼠妇，样本数量太少。改正：应增加鼠妇的数量，如每组放入20只或更多，以减少偶然性，提高实验结果的可靠性。',
    explanation: '科学实验中应使用足够数量的实验对象（即设置重复组），以减少偶然因素对实验结果的影响，提高实验结论的可靠性。',
    difficulty: 3,
  },
  {
    chapterKey: 'biology-renjiao-7-0',
    questionKey: 'biology-renjiao-7-0-11',
    type: 'matching',
    questionText: '请将下列生物特征与对应的实例连线匹配。',
    answer: '需要营养—植物从土壤中吸收水分和无机盐；能呼吸—鲸鱼喷出水柱；能排出废物—植物落叶；能生长繁殖—小猫长成大猫并产仔',
    explanation: '这些实例分别体现了生物的基本特征：营养摄取、呼吸作用、废物排出、生长和繁殖。',
    difficulty: 2,
    pairs: '[["需要营养","植物从土壤中吸收水分和无机盐"],["能呼吸","鲸鱼喷出水柱"],["能排出废物","植物落叶"],["能生长繁殖","小猫长成大猫并产仔"]]',
  },
  {
    chapterKey: 'biology-renjiao-7-1',
    questionKey: 'biology-renjiao-7-1-0',
    type: 'choice',
    questionText: '生物圈是指（）',
    answer: 'D',
    explanation: '生物圈是地球上所有生物与其生存的环境形成的一个统一的整体，包括大气圈的下层、整个水圈和岩石圈的上层，是最大的生态系统。',
    difficulty: 1,
    options: '["A. 大气圈","B. 水圈","C. 岩石圈","D. 地球上所有生物与其生存的环境构成的整体"]',
  },
  {
    chapterKey: 'biology-renjiao-7-1',
    questionKey: 'biology-renjiao-7-1-1',
    type: 'choice',
    questionText: '生态系统中，物质和能量流动的渠道是（）',
    answer: 'B',
    explanation: '在生态系统中，生产者和消费者之间通过吃与被吃的关系形成食物链和食物网，这就是物质和能量流动的渠道。',
    difficulty: 1,
    options: '["A. 非生物部分","B. 食物链和食物网","C. 分解者","D. 阳光"]',
  },
  {
    chapterKey: 'biology-renjiao-7-1',
    questionKey: 'biology-renjiao-7-1-2',
    type: 'choice',
    questionText: '在食物链"草→兔→狐"中，狐属于（）',
    answer: 'C',
    explanation: '狐以兔为食，兔以草为食。狐处于第三营养级，属于次级消费者。',
    difficulty: 1,
    options: '["A. 生产者","B. 初级消费者","C. 次级消费者","D. 三级消费者"]',
  },
  {
    chapterKey: 'biology-renjiao-7-1',
    questionKey: 'biology-renjiao-7-1-3',
    type: 'choice',
    questionText: '下列哪项是生态系统中分解者的作用（）',
    answer: 'B',
    explanation: '分解者（主要是细菌和真菌）能将动植物遗体和排泄物中的有机物分解为无机物，促进物质循环，归还到环境中。',
    difficulty: 1,
    options: '["A. 制造有机物","B. 分解有机物为无机物","C. 捕食其他生物","D. 进行光合作用"]',
  },
  {
    chapterKey: 'biology-renjiao-7-1',
    questionKey: 'biology-renjiao-7-1-4',
    type: 'choice',
    questionText: '在稻田生态系统中，若大量使用农药，最终受害最严重的可能是（）',
    answer: 'B',
    explanation: '农药进入食物链后，会通过食物链的逐级积累（生物富集作用），营养级越高的生物体内农药浓度越高，因此处于食物链顶端的生物受害最严重。',
    difficulty: 2,
    options: '["A. 水稻","B. 以水稻为食的鸟类","C. 稻田中的昆虫","D. 稻田中的杂草"]',
  },
  {
    chapterKey: 'biology-renjiao-7-1',
    questionKey: 'biology-renjiao-7-1-5',
    type: 'choice',
    questionText: '下列哪个是正确的食物链（）',
    answer: 'C',
    explanation: '食物链的起点必须是生产者（植物），箭头方向表示物质和能量的流动方向（被吃→吃），且食物链中不包含分解者和非生物因素。草→昆虫→蛙→蛇符合食物链的正确书写方式。',
    difficulty: 2,
    options: '["A. 阳光→草→兔→狐","B. 草←兔←狐","C. 草→昆虫→蛙→蛇","D. 草→兔→狐→细菌"]',
  },
  {
    chapterKey: 'biology-renjiao-7-1',
    questionKey: 'biology-renjiao-7-1-6',
    type: 'choice',
    questionText: '生态系统中，能量流动的特点是（）',
    answer: 'A',
    explanation: '生态系统中能量流动的特点是单向流动、逐级递减。能量沿食物链从低营养级流向高营养级，每个营养级大约只将10%~20%的能量传给下一个营养级。',
    difficulty: 2,
    options: '["A. 单向流动、逐级递减","B. 双向流动、逐级递减","C. 单向流动、逐级增加","D. 循环流动"]',
  },
  {
    chapterKey: 'biology-renjiao-7-1',
    questionKey: 'biology-renjiao-7-1-7',
    type: 'fill',
    questionText: '生态系统由______部分和______部分组成。',
    answer: '生物、非生物',
    explanation: '生态系统由生物部分（生产者、消费者、分解者）和非生物部分（阳光、空气、水等）组成。',
    difficulty: 1,
    acceptableAnswers: '["生物、非生物","非生物、生物"]',
  },
  {
    chapterKey: 'biology-renjiao-7-1',
    questionKey: 'biology-renjiao-7-1-8',
    type: 'fill',
    questionText: '在生态系统中，植物属于______者，动物属于______者。',
    answer: '生产、消费',
    explanation: '植物能通过光合作用制造有机物，属于生产者；动物不能自己制造有机物，必须直接或间接以植物为食，属于消费者。',
    difficulty: 1,
  },
  {
    chapterKey: 'biology-renjiao-7-1',
    questionKey: 'biology-renjiao-7-1-9',
    type: 'fill',
    questionText: '在一定地域内，______与______所形成的统一的整体叫做生态系统。',
    answer: '生物、环境',
    explanation: '在一定地域内，生物与环境所形成的统一的整体叫做生态系统。如一片森林、一个池塘等都可以看作是一个生态系统。',
    difficulty: 1,
    acceptableAnswers: '["生物、环境","环境、生物"]',
  },
  {
    chapterKey: 'biology-renjiao-7-1',
    questionKey: 'biology-renjiao-7-1-10',
    type: 'short_answer',
    questionText: '简述生态系统中生产者、消费者和分解者各自的作用。',
    answer: '生产者（主要是绿色植物）：通过光合作用将无机物转化为有机物，为其他生物提供物质和能量。消费者（主要是动物）：直接或间接以植物为食，获取有机物和能量。分解者（主要是细菌和真菌）：将动植物遗体和排泄物中的有机物分解为无机物，归还到环境中，促进物质循环。',
    explanation: '生产者、消费者和分解者在生态系统中各有不同分工，三者相互依存，共同维持生态系统的稳定。',
    difficulty: 2,
  },
  {
    chapterKey: 'biology-renjiao-7-1',
    questionKey: 'biology-renjiao-7-1-11',
    type: 'short_answer',
    questionText: '如果在一个生态系统中，将所有分解者都去除，会出现什么后果？',
    answer: '如果去除所有分解者，动植物的遗体和排泄物将无法被分解为无机物，有机物会大量堆积，营养物质无法循环利用，生态系统的物质循环将受到严重影响，最终导致生态系统崩溃。',
    explanation: '分解者在物质循环中起着不可替代的作用，没有分解者，物质循环就会中断，生态系统无法维持稳定。',
    difficulty: 3,
  },
  {
    chapterKey: 'biology-renjiao-7-1',
    questionKey: 'biology-renjiao-7-1-12',
    type: 'short_answer',
    questionText: '请写出一条包含四个生物的食物链，并标出生产者和消费者。',
    answer: '食物链：草→昆虫→青蛙→蛇。其中草是生产者，昆虫（初级消费者）、青蛙（次级消费者）、蛇（三级消费者）是消费者。',
    explanation: '食物链从生产者开始，到最高营养级的消费者结束，箭头指向取食方向。',
    difficulty: 2,
  },
  {
    chapterKey: 'biology-renjiao-7-1',
    questionKey: 'biology-renjiao-7-1-13',
    type: 'short_answer',
    questionText: '什么是生物富集作用？它对生态系统有什么危害？',
    answer: '生物富集作用是指环境中的一些有害物质（如重金属、农药等）通过食物链在生物体内逐渐积累和浓缩的现象。由于能量流动是逐级递减的，高营养级生物需要摄入大量低营养级生物体内的有害物质，导致体内有害物质浓度最高，可能引发中毒、繁殖能力下降等危害。',
    explanation: '生物富集作用导致有害物质在食物链高营养级生物体内浓度最高，这是保护顶级消费者（如猛禽、大型肉食动物）的重要原因之一。',
    difficulty: 3,
  },
  {
    chapterKey: 'biology-renjiao-7-1',
    questionKey: 'biology-renjiao-7-1-14',
    type: 'matching',
    questionText: '请将下列生态系统的组成成分与其功能匹配。',
    answer: '生产者—制造有机物；初级消费者—以植物为食；分解者—分解有机物为无机物；非生物部分—提供物质和能量基础',
    explanation: '各成分在生态系统中承担不同功能，共同维持生态系统的稳定。',
    difficulty: 1,
    pairs: '[["生产者","制造有机物"],["初级消费者","以植物为食"],["分解者","分解有机物为无机物"],["非生物部分","提供物质和能量基础"]]',
  },
  {
    chapterKey: 'biology-renjiao-7-1',
    questionKey: 'biology-renjiao-7-1-15',
    type: 'matching',
    questionText: '请将下列生物与其在生态系统中的角色匹配。',
    answer: '绿色植物—生产者；兔子—初级消费者；狼—次级消费者；蘑菇—分解者',
    explanation: '绿色植物通过光合作用制造有机物；兔子以植物为食；狼以兔子等动物为食；蘑菇分解有机物质。',
    difficulty: 1,
    pairs: '[["绿色植物","生产者"],["兔子","初级消费者"],["狼","次级消费者"],["蘑菇","分解者"]]',
  },
  {
    chapterKey: 'biology-renjiao-7-2',
    questionKey: 'biology-renjiao-7-2-0',
    type: 'choice',
    questionText: '细胞是生物体结构和功能的基本单位，这一结论的建立主要归功于（）',
    answer: 'B',
    explanation: '施莱登和施旺通过大量观察研究，提出了细胞学说，认为一切动植物都是由细胞发育而来，并由细胞和细胞产物所构成，细胞是生物体结构和功能的基本单位。',
    difficulty: 1,
    options: '["A. 列文虎克","B. 施莱登和施旺","C. 达尔文","D. 巴斯德"]',
  },
  {
    chapterKey: 'biology-renjiao-7-2',
    questionKey: 'biology-renjiao-7-2-1',
    type: 'choice',
    questionText: '下列哪种结构是植物细胞有而动物细胞没有的（）',
    answer: 'D',
    explanation: '植物细胞具有细胞壁、叶绿体和液泡，这些是大多数动物细胞所没有的。但需要注意的是，并非所有植物细胞都有叶绿体（如根尖细胞），不过细胞壁和液泡是植物细胞普遍具有的。',
    difficulty: 1,
    options: '["A. 细胞膜","B. 细胞质","C. 细胞核","D. 细胞壁"]',
  },
  {
    chapterKey: 'biology-renjiao-7-2',
    questionKey: 'biology-renjiao-7-2-2',
    type: 'choice',
    questionText: '在显微镜下观察到的物像偏左上方，要将其移到视野中央，应将装片向哪个方向移动（）',
    answer: 'C',
    explanation: '显微镜成的是倒立的像（上下左右都颠倒），物像偏左上方，实际标本偏右下方。要将物像移到中央，需要将装片向左上方移动。',
    difficulty: 1,
    options: '["A. 右下方","B. 右上方","C. 左上方","D. 左下方"]',
  },
  {
    chapterKey: 'biology-renjiao-7-2',
    questionKey: 'biology-renjiao-7-2-3',
    type: 'choice',
    questionText: '控制物质进出细胞的结构是（）',
    answer: 'A',
    explanation: '细胞膜具有控制物质进出细胞的功能，能让有用的物质进入细胞，把细胞产生的废物排出细胞，同时阻止有害物质进入细胞。',
    difficulty: 1,
    options: '["A. 细胞膜","B. 细胞壁","C. 细胞质","D. 细胞核"]',
  },
  {
    chapterKey: 'biology-renjiao-7-2',
    questionKey: 'biology-renjiao-7-2-4',
    type: 'choice',
    questionText: '细胞的控制中心是（）',
    answer: 'D',
    explanation: '细胞核是细胞的控制中心，其中含有遗传物质DNA，控制着生物的发育和遗传。',
    difficulty: 1,
    options: '["A. 细胞膜","B. 细胞质","C. 液泡","D. 细胞核"]',
  },
  {
    chapterKey: 'biology-renjiao-7-2',
    questionKey: 'biology-renjiao-7-2-5',
    type: 'choice',
    questionText: '洋葱表皮细胞和口腔上皮细胞共有的结构是（）',
    answer: 'C',
    explanation: '洋葱表皮细胞（植物细胞）和口腔上皮细胞（动物细胞）都具有细胞膜、细胞质、细胞核、线粒体等结构。细胞壁、叶绿体、液泡是植物细胞特有的。',
    difficulty: 1,
    options: '["A. 细胞壁","B. 叶绿体","C. 细胞核","D. 液泡"]',
  },
  {
    chapterKey: 'biology-renjiao-7-2',
    questionKey: 'biology-renjiao-7-2-6',
    type: 'choice',
    questionText: '植物细胞能量转换器是（）',
    answer: 'B',
    explanation: '植物细胞中的叶绿体能将光能转变为化学能储存在有机物中，线粒体能将有机物中的化学能释放出来供细胞利用。两者都是植物细胞的能量转换器。',
    difficulty: 2,
    options: '["A. 细胞核和液泡","B. 叶绿体和线粒体","C. 叶绿体和液泡","D. 线粒体和细胞膜"]',
  },
  {
    chapterKey: 'biology-renjiao-7-2',
    questionKey: 'biology-renjiao-7-2-7',
    type: 'choice',
    questionText: '染色体的主要成分是（）',
    answer: 'A',
    explanation: '染色体主要由DNA和蛋白质组成。DNA是遗传物质，能传递遗传信息。',
    difficulty: 1,
    options: '["A. DNA和蛋白质","B. 糖类和脂质","C. RNA和无机盐","D. 水和蛋白质"]',
  },
  {
    chapterKey: 'biology-renjiao-7-2',
    questionKey: 'biology-renjiao-7-2-8',
    type: 'choice',
    questionText: '在制作临时装片时，应用盖玻片的某一侧先接触水滴，然后缓缓放下，目的是（）',
    answer: 'B',
    explanation: '用盖玻片一侧先接触水滴再缓缓放下，可以避免产生气泡，有利于观察。',
    difficulty: 1,
    options: '["A. 使盖玻片更平整","B. 避免产生气泡","C. 使细胞分散开","D. 防止盖玻片破裂"]',
  },
  {
    chapterKey: 'biology-renjiao-7-2',
    questionKey: 'biology-renjiao-7-2-9',
    type: 'choice',
    questionText: '细胞的分裂过程中，最先进行分裂的结构是（）',
    answer: 'C',
    explanation: '细胞分裂时，细胞核先分裂，然后细胞质分成两份，最后形成新的细胞膜（植物细胞还形成新的细胞壁）。',
    difficulty: 2,
    options: '["A. 细胞膜","B. 细胞质","C. 细胞核","D. 液泡"]',
  },
  {
    chapterKey: 'biology-renjiao-7-2',
    questionKey: 'biology-renjiao-7-2-10',
    type: 'choice',
    questionText: '细胞生长过程中，体积增大主要依靠（）',
    answer: 'A',
    explanation: '细胞生长时，细胞从周围环境中吸收营养物质，体积逐渐增大，使细胞由小变大。',
    difficulty: 1,
    options: '["A. 从周围吸收营养物质","B. 细胞数量的增加","C. 细胞的分裂","D. 水分的蒸发"]',
  },
  {
    chapterKey: 'biology-renjiao-7-2',
    questionKey: 'biology-renjiao-7-2-11',
    type: 'fill',
    questionText: '植物细胞最外层的结构是______，它的功能是______细胞。',
    answer: '细胞壁、支持和保护',
    explanation: '植物细胞最外层是细胞壁，对细胞有支持和保护作用。',
    difficulty: 1,
  },
  {
    chapterKey: 'biology-renjiao-7-2',
    questionKey: 'biology-renjiao-7-2-12',
    type: 'fill',
    questionText: '在显微镜下，用碘液对洋葱表皮细胞进行染色，被染成深色的结构是______，因为它含有______物质。',
    answer: '细胞核、遗传',
    explanation: '碘液可以使细胞核染色，因为细胞核中含有遗传物质（DNA），易被碱性染料染色。',
    difficulty: 2,
  },
  {
    chapterKey: 'biology-renjiao-7-2',
    questionKey: 'biology-renjiao-7-2-13',
    type: 'fill',
    questionText: '动物细胞和植物细胞都有的能量转换器是______。',
    answer: '线粒体',
    explanation: '线粒体是动植物细胞共有的能量转换器，能将有机物中的化学能释放出来，供细胞利用。叶绿体是植物细胞特有的能量转换器。',
    difficulty: 1,
  },
  {
    chapterKey: 'biology-renjiao-7-2',
    questionKey: 'biology-renjiao-7-2-14',
    type: 'fill',
    questionText: 'DNA上有遗传信息的片段叫做______。',
    answer: '基因',
    explanation: '基因是DNA上有遗传效应的片段，是遗传信息的基本单位。',
    difficulty: 1,
  },
  {
    chapterKey: 'biology-renjiao-7-2',
    questionKey: 'biology-renjiao-7-2-15',
    type: 'fill',
    questionText: '细胞分裂时，______先分裂，然后______一分为二，最后形成新的细胞膜，植物细胞还形成新的______。',
    answer: '细胞核、细胞质、细胞壁',
    explanation: '细胞分裂的顺序是：细胞核先分裂，细胞质分成两份，形成新的细胞膜，植物细胞还在原来细胞壁的位置形成新的细胞壁。',
    difficulty: 2,
  },
  {
    chapterKey: 'biology-renjiao-7-2',
    questionKey: 'biology-renjiao-7-2-16',
    type: 'short_answer',
    questionText: '比较植物细胞和动物细胞的结构，列表说明它们的相同点和不同点。',
    answer: '相同点：都有细胞膜、细胞质、细胞核、线粒体。不同点：植物细胞有细胞壁、叶绿体、液泡，动物细胞没有这些结构。',
    explanation: '植物细胞和动物细胞在基本结构上相似，但植物细胞具有一些特有结构以适应其自养生活方式。',
    difficulty: 2,
  },
  {
    chapterKey: 'biology-renjiao-7-2',
    questionKey: 'biology-renjiao-7-2-17',
    type: 'short_answer',
    questionText: '简要描述制作洋葱鳞片叶表皮细胞临时装片的步骤。',
    answer: '①准备：擦净载玻片和盖玻片；②滴水：在载玻片中央滴一滴清水；③取材：用镊子撕取一小块洋葱鳞片叶内表皮；④展平：将表皮放入水滴中展平；⑤盖片：用盖玻片一侧先接触水滴再缓缓放下；⑥染色：在盖玻片一侧滴碘液，另一侧用吸水纸吸引。',
    explanation: '制作临时装片的步骤可概括为：擦、滴、取、展、盖、染。每一步都有特定目的和操作要领。',
    difficulty: 2,
  },
  {
    chapterKey: 'biology-renjiao-7-2',
    questionKey: 'biology-renjiao-7-2-18',
    type: 'short_answer',
    questionText: '为什么说细胞是生物体结构和功能的基本单位？',
    answer: '因为除病毒以外，生物体都是由细胞构成的。单细胞生物由一个细胞完成全部生命活动；多细胞生物体内的每个细胞都有特定的结构，承担一定的功能，共同完成生物体的各项生命活动。',
    explanation: '生命活动（如新陈代谢、生长发育、繁殖等）都是在细胞中进行的，或以细胞为基础实现的。',
    difficulty: 2,
  },
  {
    chapterKey: 'biology-renjiao-7-2',
    questionKey: 'biology-renjiao-7-2-19',
    type: 'short_answer',
    questionText: '什么是细胞分裂？细胞分裂有什么生物学意义？',
    answer: '细胞分裂是指一个细胞分成两个细胞的过程。其生物学意义：①单细胞生物通过细胞分裂增加个体数量；②多细胞生物通过细胞分裂使细胞数量增多，促进生物体的生长发育；③细胞分裂能产生新细胞以补充衰老死亡的细胞，维持生物体的正常功能。',
    explanation: '细胞分裂是生物体生长、发育和繁殖的基础。',
    difficulty: 2,
  },
  {
    chapterKey: 'biology-renjiao-7-2',
    questionKey: 'biology-renjiao-7-2-20',
    type: 'short_answer',
    questionText: '细胞中各结构分别有什么功能？请简述细胞膜、细胞质、细胞核和线粒体的主要功能。',
    answer: '细胞膜：控制物质进出细胞，保护细胞。细胞质：细胞内的液态物质，为各种生命活动提供场所，含有线粒体等多种细胞器。细胞核：含有遗传物质，控制细胞的生命活动和遗传。线粒体：进行呼吸作用，将有机物中的化学能释放出来，供细胞利用。',
    explanation: '细胞的各结构分工合作，共同完成各项生命活动。',
    difficulty: 2,
  },
  {
    chapterKey: 'biology-renjiao-7-2',
    questionKey: 'biology-renjiao-7-2-21',
    type: 'short_answer',
    questionText: '染色体、DNA和基因三者之间有什么关系？',
    answer: '染色体存在于细胞核中，主要由DNA和蛋白质组成。DNA是遗传物质，是双螺旋结构。基因是DNA上具有遗传效应的片段，是控制生物性状的基本单位。关系：细胞核中有染色体，染色体上有DNA，DNA上有基因。即：染色体→DNA→基因（从大到小）。',
    explanation: '基因是遗传的基本单位，DNA是遗传信息的载体，染色体是DNA和蛋白质的组合体。',
    difficulty: 3,
  },
  {
    chapterKey: 'biology-renjiao-7-2',
    questionKey: 'biology-renjiao-7-2-22',
    type: 'matching',
    questionText: '请将下列细胞结构与其对应的功能匹配。',
    answer: '细胞膜—控制物质进出；细胞核—储存遗传信息；线粒体—分解有机物释放能量；叶绿体—光合作用制造有机物；液泡—储存营养物质',
    explanation: '细胞的各结构都有特定的功能，相互配合完成生命活动。',
    difficulty: 1,
    pairs: '[["细胞膜","控制物质进出"],["细胞核","储存遗传信息"],["线粒体","分解有机物释放能量"],["叶绿体","光合作用制造有机物"],["液泡","储存营养物质"]]',
  },
  {
    chapterKey: 'biology-renjiao-7-2',
    questionKey: 'biology-renjiao-7-2-23',
    type: 'matching',
    questionText: '请将下列显微镜操作与其目的匹配。',
    answer: '调节粗准焦螺旋—使镜筒大幅度升降找物像；调节细准焦螺旋—使物像更清晰；转动转换器—更换物镜；调节光圈和反光镜—调节视野亮度',
    explanation: '显微镜各部件的操作有其特定目的，掌握这些操作是正确使用显微镜的基础。',
    difficulty: 2,
    pairs: '[["调节粗准焦螺旋","使镜筒大幅度升降找物像"],["调节细准焦螺旋","使物像更清晰"],["转动转换器","更换物镜"],["调节光圈和反光镜","调节视野亮度"]]',
  },
  {
    chapterKey: 'biology-renjiao-7-3',
    questionKey: 'biology-renjiao-7-3-0',
    type: 'choice',
    questionText: '动物体和植物体的结构层次中，不同的层次是（）',
    answer: 'C',
    explanation: '植物体的结构层次：细胞→组织→器官→植物体；动物体的结构层次：细胞→组织→器官→系统→动物体。植物体没有"系统"这一层次。',
    difficulty: 2,
    options: '["A. 细胞","B. 组织","C. 系统","D. 器官"]',
  },
  {
    chapterKey: 'biology-renjiao-7-3',
    questionKey: 'biology-renjiao-7-3-1',
    type: 'choice',
    questionText: '植物体的六大器官中，属于营养器官的是（）',
    answer: 'B',
    explanation: '植物的六大器官分为营养器官（根、茎、叶）和生殖器官（花、果实、种子）。',
    difficulty: 1,
    options: '["A. 花、果实、种子","B. 根、茎、叶","C. 根、花、果实","D. 茎、叶、种子"]',
  },
  {
    chapterKey: 'biology-renjiao-7-3',
    questionKey: 'biology-renjiao-7-3-2',
    type: 'choice',
    questionText: '人体的肌肉组织主要具有的功能是（）',
    answer: 'B',
    explanation: '肌肉组织由肌细胞组成，具有收缩和舒张的功能，能使机体产生运动。',
    difficulty: 1,
    options: '["A. 保护作用","B. 收缩和舒张产生运动","C. 传导兴奋","D. 分泌物质"]',
  },
  {
    chapterKey: 'biology-renjiao-7-3',
    questionKey: 'biology-renjiao-7-3-3',
    type: 'choice',
    questionText: '人体的血液属于（）',
    answer: 'A',
    explanation: '血液属于结缔组织，具有运输、防御等功能。结缔组织的特点是细胞间质发达。',
    difficulty: 1,
    options: '["A. 结缔组织","B. 上皮组织","C. 肌肉组织","D. 神经组织"]',
  },
  {
    chapterKey: 'biology-renjiao-7-3',
    questionKey: 'biology-renjiao-7-3-4',
    type: 'choice',
    questionText: '分生组织的细胞特点是（）',
    answer: 'D',
    explanation: '分生组织的细胞小、细胞壁薄、细胞核大、细胞质浓，具有很强的分裂能力，能不断分裂产生新细胞。',
    difficulty: 2,
    options: '["A. 细胞大，细胞核小","B. 细胞壁厚，液泡大","C. 细胞呈长方形","D. 细胞小，细胞壁薄，细胞核大"]',
  },
  {
    chapterKey: 'biology-renjiao-7-3',
    questionKey: 'biology-renjiao-7-3-5',
    type: 'choice',
    questionText: '下列属于器官的是（）',
    answer: 'B',
    explanation: '器官是由多种组织按照一定次序结合在一起形成的。西瓜是果实，属于生殖器官；血液是结缔组织，不是器官；洋葱表皮是保护组织；一个心肌细胞是细胞。',
    difficulty: 1,
    options: '["A. 血液","B. 西瓜","C. 洋葱表皮","D. 一个心肌细胞"]',
  },
  {
    chapterKey: 'biology-renjiao-7-3',
    questionKey: 'biology-renjiao-7-3-6',
    type: 'choice',
    questionText: '植物体中，具有保护功能、主要分布在植物体表面的组织是（）',
    answer: 'A',
    explanation: '保护组织一般由植物体表面的表皮细胞构成，细胞排列紧密，起保护内部柔嫩部分的作用。',
    difficulty: 1,
    options: '["A. 保护组织","B. 营养组织","C. 输导组织","D. 分生组织"]',
  },
  {
    chapterKey: 'biology-renjiao-7-3',
    questionKey: 'biology-renjiao-7-3-7',
    type: 'choice',
    questionText: '人体的消化系统由消化道和______组成（）',
    answer: 'C',
    explanation: '消化系统由消化道（口腔、咽、食管、胃、小肠、大肠、肛门）和消化腺（唾液腺、肝脏、胰腺、肠腺等）组成。',
    difficulty: 1,
    options: '["A. 呼吸道","B. 血管","C. 消化腺","D. 泌尿系统"]',
  },
  {
    chapterKey: 'biology-renjiao-7-3',
    questionKey: 'biology-renjiao-7-3-8',
    type: 'choice',
    questionText: '一粒西瓜籽是由发育而来的（）',
    answer: 'A',
    explanation: '种子由胚珠发育而来，其中胚珠内的受精卵发育成胚（种子中的主要部分），珠被发育成种皮。',
    difficulty: 2,
    options: '["A. 胚珠","B. 子房","C. 花瓣","D. 花药"]',
  },
  {
    chapterKey: 'biology-renjiao-7-3',
    questionKey: 'biology-renjiao-7-3-9',
    type: 'fill',
    questionText: '动物体的结构层次从小到大依次是：细胞→______→______→______→动物体。',
    answer: '组织、器官、系统',
    explanation: '动物体的结构层次：细胞→组织→器官→系统→动物体。',
    difficulty: 1,
  },
  {
    chapterKey: 'biology-renjiao-7-3',
    questionKey: 'biology-renjiao-7-3-10',
    type: 'fill',
    questionText: '人体的四大基本组织是上皮组织、______组织、肌肉组织和______组织。',
    answer: '结缔、神经',
    explanation: '人体的四大基本组织是上皮组织、结缔组织、肌肉组织和神经组织，各有不同的结构和功能。',
    difficulty: 1,
    acceptableAnswers: '["结缔、神经","神经、结缔"]',
  },
  {
    chapterKey: 'biology-renjiao-7-3',
    questionKey: 'biology-renjiao-7-3-11',
    type: 'fill',
    questionText: '植物体的主要组织有保护组织、营养组织、输导组织和______组织。',
    answer: '分生',
    explanation: '植物体的主要组织有分生组织、保护组织、营养组织和输导组织。分生组织具有分裂能力。',
    difficulty: 1,
  },
  {
    chapterKey: 'biology-renjiao-7-3',
    questionKey: 'biology-renjiao-7-3-12',
    type: 'fill',
    questionText: '受精卵是一个______，经过细胞分裂和______形成组织，由不同组织按照一定次序结合形成______。',
    answer: '细胞、分化、器官',
    explanation: '受精卵经过细胞分裂产生多个细胞，这些细胞在生长过程中发生分化，形成不同组织，进而构成器官。',
    difficulty: 2,
  },
  {
    chapterKey: 'biology-renjiao-7-3',
    questionKey: 'biology-renjiao-7-3-13',
    type: 'short_answer',
    questionText: '什么是细胞分化？它与细胞分裂有什么区别？',
    answer: '细胞分化是指在个体发育中，一个或一种细胞通过分裂产生后代，在形态、结构和生理功能上发生稳定性差异的过程。区别：细胞分裂使细胞数量增多，分裂后的细胞形态结构基本相同；细胞分化使细胞形态结构和功能产生差异，形成不同组织。细胞分裂是细胞分化的基础。',
    explanation: '细胞分裂增加细胞数量，细胞分化产生不同类型的细胞（组织），两者共同促进生物体的生长发育。',
    difficulty: 2,
  },
  {
    chapterKey: 'biology-renjiao-7-3',
    questionKey: 'biology-renjiao-7-3-14',
    type: 'short_answer',
    questionText: '简述植物的四大组织及其功能。',
    answer: '保护组织：覆盖在植物体表面，起保护作用；营养组织：细胞壁薄，液泡大，有储存营养物质的功能；输导组织：贯穿植物体全身，负责运输水分、无机盐和有机物；分生组织：细胞小、壁薄、核大，具有很强的分裂能力。',
    explanation: '这四种组织在植物体内各司其职，共同完成植物的生命活动。',
    difficulty: 2,
  },
  {
    chapterKey: 'biology-renjiao-7-3',
    questionKey: 'biology-renjiao-7-3-15',
    type: 'short_answer',
    questionText: '请说明植物体与动物体的结构层次有什么不同。',
    answer: '植物体的结构层次：细胞→组织→器官→植物体。动物体的结构层次：细胞→组织→器官→系统→动物体。主要区别：植物体没有"系统"这一层次，直接由器官构成植物体；而动物体由器官构成系统，再由系统构成动物体。',
    explanation: '植物和动物的结构层次差异体现了它们不同的生命活动方式和组织方式。',
    difficulty: 3,
  },
  {
    chapterKey: 'biology-renjiao-7-3',
    questionKey: 'biology-renjiao-7-3-16',
    type: 'short_answer',
    questionText: '一块骨骼肌（如肱二头肌）在结构上可以看作是一个器官吗？为什么？',
    answer: '可以。骨骼肌主要由肌肉组织构成，但还含有结缔组织（肌腱和筋膜）、神经组织（控制肌肉收缩的神经）和上皮组织（血管壁），是由多种组织按照一定次序结合在一起，具有一定功能的结构，因此可以看作是一个器官。',
    explanation: '器官由多种组织构成，骨骼肌虽以肌肉组织为主，但也包含其他组织，符合器官的定义。',
    difficulty: 3,
  },
  {
    chapterKey: 'biology-renjiao-7-3',
    questionKey: 'biology-renjiao-7-3-17',
    type: 'short_answer',
    questionText: '绿色开花植物的花、果实、种子分别由花中的哪些结构发育而来？',
    answer: '果实由子房发育而来；种子由胚珠发育而来；种子中的胚由受精卵发育而来；种皮由珠被发育而来；果皮由子房壁发育而来。',
    explanation: '花的结构中，子房发育为果实，子房壁发育为果皮，胚珠发育为种子，珠被发育为种皮，受精卵发育为胚。',
    difficulty: 2,
  },
  {
    chapterKey: 'biology-renjiao-7-3',
    questionKey: 'biology-renjiao-7-3-18',
    type: 'matching',
    questionText: '请将下列人体组织与其对应的功能和分布匹配。',
    answer: '上皮组织—保护、分泌功能，分布在体表和体内管腔内表面；肌肉组织—收缩舒张产生运动，分布在四肢、躯干、心脏等处；结缔组织—支持、连接、保护、营养功能，分布广泛（骨、血液、脂肪等）；神经组织—接受刺激、产生和传导兴奋，分布在脑、脊髓等',
    explanation: '四大组织各有不同的分布位置和功能，共同完成人体的各种生命活动。',
    difficulty: 2,
    pairs: '[["上皮组织","保护、分泌功能，分布在体表和体内管腔内表面"],["肌肉组织","收缩舒张产生运动，分布在四肢、躯干、心脏等处"],["结缔组织","支持、连接、保护、营养功能，分布广泛（骨、血液、脂肪等）"],["神经组织","接受刺激、产生和传导兴奋，分布在脑、脊髓等"]]',
  },
  {
    chapterKey: 'biology-renjiao-7-3',
    questionKey: 'biology-renjiao-7-3-19',
    type: 'matching',
    questionText: '请将下列植物组织与其特征和功能匹配。',
    answer: '保护组织—细胞排列紧密，起保护作用；营养组织—细胞壁薄液泡大，储存营养；输导组织—上下贯通，运输水分和养分；分生组织—细胞小核大，持续分裂',
    explanation: '植物各组织的细胞形态结构与其功能相适应。',
    difficulty: 1,
    pairs: '[["保护组织","细胞排列紧密，起保护作用"],["营养组织","细胞壁薄液泡大，储存营养"],["输导组织","上下贯通，运输水分和养分"],["分生组织","细胞小核大，持续分裂"]]',
  },
  {
    chapterKey: 'biology-renjiao-8-0',
    questionKey: 'biology-renjiao-8-0-0',
    type: 'choice',
    questionText: '种子植物比蕨类植物更适应陆地环境，最主要的原因是（）',
    answer: 'A',
    explanation: '种子植物能产生种子，种子中有丰富的营养物质供胚发育，且有种皮保护，抵抗不良环境能力强，繁殖和分布更有优势。',
    difficulty: 1,
    options: '["A. 能产生种子","B. 有发达的根系","C. 有根茎叶的分化","D. 能进行光合作用"]',
  },
  {
    chapterKey: 'biology-renjiao-8-0',
    questionKey: 'biology-renjiao-8-0-1',
    type: 'choice',
    questionText: '菜豆种子和玉米种子共有的结构是（）',
    answer: 'B',
    explanation: '菜豆种子（双子叶植物）和玉米种子（单子叶植物）都含有种皮和胚（胚包括胚根、胚芽、胚轴、子叶）。区别在于：菜豆种子无胚乳、两片子叶；玉米种子有胚乳、一片子叶。',
    difficulty: 1,
    options: '["A. 胚乳","B. 胚","C. 子叶的数量相同","D. 营养物质都储存在子叶中"]',
  },
  {
    chapterKey: 'biology-renjiao-8-0',
    questionKey: 'biology-renjiao-8-0-2',
    type: 'choice',
    questionText: '玉米种子的营养储存在（）',
    answer: 'D',
    explanation: '玉米是单子叶植物，其营养物质主要储存在胚乳中，而菜豆等双子叶植物的营养物质储存在子叶中。',
    difficulty: 1,
    options: '["A. 子叶","B. 种皮","C. 胚芽","D. 胚乳"]',
  },
  {
    chapterKey: 'biology-renjiao-8-0',
    questionKey: 'biology-renjiao-8-0-3',
    type: 'choice',
    questionText: '种子萌发所需要的外界条件是（）',
    answer: 'C',
    explanation: '种子萌发需要的外界条件是适量的水分、充足的空气和适宜的温度。',
    difficulty: 1,
    options: '["A. 阳光、土壤和水","B. 阳光、适宜的温度和水","C. 适量的水分、充足的空气和适宜的温度","D. 肥沃的土壤和阳光"]',
  },
  {
    chapterKey: 'biology-renjiao-8-0',
    questionKey: 'biology-renjiao-8-0-4',
    type: 'choice',
    questionText: '根尖中吸收水分和无机盐的主要部位是（）',
    answer: 'B',
    explanation: '根尖成熟区（根毛区）有大量根毛，大大增加了吸收水和无机盐的表面积，是根吸收水分和无机盐的主要部位。',
    difficulty: 1,
    options: '["A. 根冠","B. 成熟区","C. 伸长区","D. 分生区"]',
  },
  {
    chapterKey: 'biology-renjiao-8-0',
    questionKey: 'biology-renjiao-8-0-5',
    type: 'choice',
    questionText: '绿色植物光合作用的场所是（）',
    answer: 'A',
    explanation: '光合作用在叶绿体中进行。叶绿体中的叶绿素能吸收光能，将二氧化碳和水转化为有机物和氧气。',
    difficulty: 1,
    options: '["A. 叶绿体","B. 线粒体","C. 细胞核","D. 液泡"]',
  },
  {
    chapterKey: 'biology-renjiao-8-0',
    questionKey: 'biology-renjiao-8-0-6',
    type: 'choice',
    questionText: '植物进行光合作用时，吸入的气体和释放的气体分别是（）',
    answer: 'A',
    explanation: '光合作用的过程：利用光能，将二氧化碳和水转化为有机物（储存能量），同时释放氧气。',
    difficulty: 1,
    options: '["A. 二氧化碳、氧气","B. 氧气、二氧化碳","C. 氮气、氧气","D. 氧气、氮气"]',
  },
  {
    chapterKey: 'biology-renjiao-8-0',
    questionKey: 'biology-renjiao-8-0-7',
    type: 'choice',
    questionText: '下列哪项不是光合作用的意义（）',
    answer: 'C',
    explanation: '光合作用的意义：制造有机物；转化并储存太阳能；维持大气中碳-氧平衡；为生物提供食物和能量来源。分解有机物释放能量是呼吸作用的功能。',
    difficulty: 2,
    options: '["A. 为生物提供食物来源","B. 维持大气中碳-氧平衡","C. 分解有机物释放能量","D. 将光能转变为化学能"]',
  },
  {
    chapterKey: 'biology-renjiao-8-0',
    questionKey: 'biology-renjiao-8-0-8',
    type: 'choice',
    questionText: '植物的蒸腾作用的主要意义不包括（）',
    answer: 'D',
    explanation: '蒸腾作用的意义：促进植物对水分和无机盐的运输；降低叶片温度；提高大气湿度，增加降水。制造有机物是光合作用的功能，不是蒸腾作用的功能。',
    difficulty: 2,
    options: '["A. 促进水分和无机盐的运输","B. 降低叶片温度","C. 提高大气湿度","D. 制造有机物"]',
  },
  {
    chapterKey: 'biology-renjiao-8-0',
    questionKey: 'biology-renjiao-8-0-9',
    type: 'fill',
    questionText: '光合作用的表达式：二氧化碳+水→有机物+______（储存能量），场所是______。',
    answer: '氧气、叶绿体',
    explanation: '光合作用的文字表达式：二氧化碳+水→有机物（储存能量）+氧气，在叶绿体中进行，需要光能。',
    difficulty: 1,
  },
  {
    chapterKey: 'biology-renjiao-8-0',
    questionKey: 'biology-renjiao-8-0-10',
    type: 'fill',
    questionText: '植物的______作用能促进水分和无机盐在植物体内的运输，主要是通过叶片上的______完成的。',
    answer: '蒸腾、气孔',
    explanation: '蒸腾作用产生拉力，是水分在植物体内向上运输的主要动力，主要通过叶片上的气孔散失水分。',
    difficulty: 1,
  },
  {
    chapterKey: 'biology-renjiao-8-0',
    questionKey: 'biology-renjiao-8-0-11',
    type: 'fill',
    questionText: '一朵完整的花包括花柄、花托、花萼、______、______和花蕊（雄蕊和雌蕊）。',
    answer: '花瓣、花冠',
    explanation: '一朵完整的花由花柄、花托、花萼、花瓣（花冠）、雄蕊和雌蕊组成。其中雄蕊和雌蕊是花的主要结构（生殖结构）。',
    difficulty: 1,
  },
  {
    chapterKey: 'biology-renjiao-8-0',
    questionKey: 'biology-renjiao-8-0-12',
    type: 'fill',
    questionText: '绿色植物通过光合作用，不断消耗大气中的______，又不断释放______，维持了生物圈中的碳-氧平衡。',
    answer: '二氧化碳、氧气',
    explanation: '光合作用消耗二氧化碳、释放氧气，与生物的呼吸作用和燃料燃烧等过程相互平衡，维持大气中碳-氧平衡。',
    difficulty: 2,
  },
  {
    chapterKey: 'biology-renjiao-8-0',
    questionKey: 'biology-renjiao-8-0-13',
    type: 'short_answer',
    questionText: '什么是光合作用？写出光合作用的文字表达式并说明其意义。',
    answer: '光合作用是指绿色植物通过叶绿体，利用光能，把二氧化碳和水转变成储存能量的有机物，并释放出氧气的过程。表达式：二氧化碳+水→（光能，叶绿体）→有机物+氧气。意义：①制造有机物，为自身和其它生物提供食物；②转化光能为化学能储存起来；③维持大气中碳-氧平衡。',
    explanation: '光合作用是地球上最重要的化学反应之一，是一切生物生存的基础。',
    difficulty: 2,
  },
  {
    chapterKey: 'biology-renjiao-8-0',
    questionKey: 'biology-renjiao-8-0-14',
    type: 'short_answer',
    questionText: '植物根尖的四个区域各有什么功能？',
    answer: '根冠：保护根尖（最前端）；分生区：不断分裂产生新细胞；伸长区：细胞迅速伸长，是根生长最快的部位；成熟区（根毛区）：有大量根毛，是吸收水分和无机盐的主要部位，且细胞已分化形成导管。',
    explanation: '根尖的四个区域各司其职：保护、分裂、伸长、吸收，共同完成根的生长和吸收功能。',
    difficulty: 2,
  },
  {
    chapterKey: 'biology-renjiao-8-0',
    questionKey: 'biology-renjiao-8-0-15',
    type: 'short_answer',
    questionText: '简述种子萌发的过程。',
    answer: '种子在适宜条件下（水分、空气、温度），首先吸水膨胀，种皮变软。然后胚根突破种皮发育成根，胚芽发育成茎和叶，胚轴发育成连接根和茎的部分。子叶或胚乳中的营养物质被消耗，供胚发育所需。',
    explanation: '种子萌发的过程：吸水膨胀→胚根发育成根→胚芽发育成茎叶，需要适宜的外界条件。',
    difficulty: 2,
  },
  {
    chapterKey: 'biology-renjiao-8-0',
    questionKey: 'biology-renjiao-8-0-16',
    type: 'short_answer',
    questionText: '比较双子叶植物种子和单子叶植物种子的异同。',
    answer: '相同点：都有种皮和胚（胚包括胚根、胚芽、胚轴和子叶）。不同点：双子叶植物（如菜豆）种子无胚乳，营养物质储存在两片子叶中；单子叶植物（如玉米）种子有胚乳，营养物质储存在胚乳中，只有一片子叶。',
    explanation: '两类种子的主要区别在于营养物质的储存部位和子叶数量。',
    difficulty: 2,
  },
  {
    chapterKey: 'biology-renjiao-8-0',
    questionKey: 'biology-renjiao-8-0-17',
    type: 'short_answer',
    questionText: '绿色植物在生物圈中有什么重要作用？',
    answer: '①通过光合作用制造有机物，是生物圈中食物的来源和能量的最终来源；②通过光合作用维持生物圈中的碳-氧平衡；③通过蒸腾作用参与水循环，提高大气湿度；④为其他生物提供栖息场所；⑤绿色植物是生产者，处于食物链的基础环节。',
    explanation: '绿色植物作为生产者，在生物圈的物质循环、能量流动和维持生态平衡中起着不可替代的作用。',
    difficulty: 3,
  },
  {
    chapterKey: 'biology-renjiao-8-0',
    questionKey: 'biology-renjiao-8-0-18',
    type: 'matching',
    questionText: '请将下列植物的生理作用与其特征匹配。',
    answer: '光合作用—在叶绿体中进行，制造有机物；呼吸作用—在线粒体中进行，分解有机物释放能量；蒸腾作用—通过气孔散失水分，促进运输；吸收作用—通过根毛吸收水和无机盐',
    explanation: '植物的四大生理作用各有不同场所和功能，是植物生存的基础。',
    difficulty: 1,
    pairs: '[["光合作用","在叶绿体中进行，制造有机物"],["呼吸作用","在线粒体中进行，分解有机物释放能量"],["蒸腾作用","通过气孔散失水分，促进运输"],["吸收作用","通过根毛吸收水和无机盐"]]',
  },
  {
    chapterKey: 'biology-renjiao-8-0',
    questionKey: 'biology-renjiao-8-0-19',
    type: 'matching',
    questionText: '请将下列花的结构与发育后的果实结构匹配。',
    answer: '子房—果实；子房壁—果皮；胚珠—种子；受精卵—胚；珠被—种皮',
    explanation: '花经过传粉受精后，子房发育为果实，子房壁发育为果皮，胚珠发育为种子，受精卵发育为胚。',
    difficulty: 2,
    pairs: '[["子房","果实"],["子房壁","果皮"],["胚珠","种子"],["受精卵","胚"],["珠被","种皮"]]',
  },
  {
    chapterKey: 'biology-renjiao-8-1',
    questionKey: 'biology-renjiao-8-1-0',
    type: 'choice',
    questionText: '人体消化和吸收营养物质的主要场所是（）',
    answer: 'C',
    explanation: '小肠是消化和吸收的主要场所，其内壁有大量环形皱襞和小肠绒毛，大大增加了表面积，且含有多种消化液。',
    difficulty: 1,
    options: '["A. 胃","B. 大肠","C. 小肠","D. 口腔"]',
  },
  {
    chapterKey: 'biology-renjiao-8-1',
    questionKey: 'biology-renjiao-8-1-1',
    type: 'choice',
    questionText: '人体最大的消化腺是（）',
    answer: 'B',
    explanation: '肝脏是人体最大的消化腺，能分泌胆汁，胆汁储存在胆囊中，流入小肠参与脂肪的消化。注意：胆汁不含消化酶。',
    difficulty: 1,
    options: '["A. 唾液腺","B. 肝脏","C. 胰腺","D. 胃腺"]',
  },
  {
    chapterKey: 'biology-renjiao-8-1',
    questionKey: 'biology-renjiao-8-1-2',
    type: 'choice',
    questionText: '下列物质中，不需要消化就能被小肠直接吸收的是（）',
    answer: 'D',
    explanation: '水、无机盐和维生素是小分子物质，不需要消化即可被消化道直接吸收。淀粉、蛋白质和脂肪是大分子有机物，需要被消化分解。',
    difficulty: 1,
    options: '["A. 淀粉","B. 蛋白质","C. 脂肪","D. 维生素"]',
  },
  {
    chapterKey: 'biology-renjiao-8-1',
    questionKey: 'biology-renjiao-8-1-3',
    type: 'choice',
    questionText: '血细胞中，数量最多的是（）',
    answer: 'A',
    explanation: '血液由血浆和血细胞（红细胞、白细胞、血小板）组成。其中红细胞数量最多，成熟的红细胞没有细胞核，富含血红蛋白，能运输氧气。',
    difficulty: 1,
    options: '["A. 红细胞","B. 白细胞","C. 血小板","D. 淋巴细胞"]',
  },
  {
    chapterKey: 'biology-renjiao-8-1',
    questionKey: 'biology-renjiao-8-1-4',
    type: 'choice',
    questionText: '贫血是指血液中（）',
    answer: 'B',
    explanation: '贫血是指血液中红细胞数量过少或血红蛋白含量过低，导致血液运输氧气的能力下降。',
    difficulty: 1,
    options: '["A. 白细胞数量过少","B. 红细胞或血红蛋白数量过少","C. 血小板数量过少","D. 血浆过少"]',
  },
  {
    chapterKey: 'biology-renjiao-8-1',
    questionKey: 'biology-renjiao-8-1-5',
    type: 'choice',
    questionText: '人体呼吸系统的主要器官是（）',
    answer: 'A',
    explanation: '肺是呼吸系统的主要器官，是气体交换的场所。呼吸系统由呼吸道（鼻、咽、喉、气管、支气管）和肺组成。',
    difficulty: 1,
    options: '["A. 肺","B. 鼻","C. 气管","D. 咽喉"]',
  },
  {
    chapterKey: 'biology-renjiao-8-1',
    questionKey: 'biology-renjiao-8-1-6',
    type: 'choice',
    questionText: '人体血液循环中，将血液从心脏输送到全身各处的血管是（）',
    answer: 'B',
    explanation: '动脉是将血液从心脏输送到身体各部分去的血管，管壁厚、弹性大、血流速度快。',
    difficulty: 1,
    options: '["A. 静脉","B. 动脉","C. 毛细血管","D. 淋巴管"]',
  },
  {
    chapterKey: 'biology-renjiao-8-1',
    questionKey: 'biology-renjiao-8-1-7',
    type: 'choice',
    questionText: '下列哪种血型的人可以作为受血者接受其他所有血型的少量血液（）',
    answer: 'C',
    explanation: 'AB型血的人血清中没有抗A和抗B凝集素，可以接受其他所有血型的少量输血（应急情况下），被称为"万能受血者"。但大量输血仍需同型输血。',
    difficulty: 2,
    options: '["A. A型","B. O型","C. AB型","D. 任何血型都可以"]',
  },
  {
    chapterKey: 'biology-renjiao-8-1',
    questionKey: 'biology-renjiao-8-1-8',
    type: 'choice',
    questionText: '人体排泄的主要器官是（）',
    answer: 'A',
    explanation: '肾脏是排泄的主要器官，通过形成尿液排出代谢废物。皮肤（排汗）和肺（排出CO2）也能排出部分废物。',
    difficulty: 1,
    options: '["A. 肾脏","B. 皮肤","C. 肺","D. 肝脏"]',
  },
  {
    chapterKey: 'biology-renjiao-8-1',
    questionKey: 'biology-renjiao-8-1-9',
    type: 'choice',
    questionText: '尿的形成主要包括两个过程：肾小球______和肾小管______。',
    answer: 'A',
    explanation: '尿的形成过程：当血液流经肾小球时，通过肾小球的滤过作用形成原尿（含水和无机盐、葡萄糖、尿素等）；原尿流经肾小管时，肾小管的重吸收作用将大部分水、全部葡萄糖和部分无机盐重新吸收回血液，剩余的废物形成尿液。',
    difficulty: 2,
    options: '["A. 滤过作用、重吸收作用","B. 重吸收作用、滤过作用","C. 分泌作用、滤过作用","D. 吸收作用、分泌作用"]',
  },
  {
    chapterKey: 'biology-renjiao-8-1',
    questionKey: 'biology-renjiao-8-1-10',
    type: 'choice',
    questionText: '下列哪项不属于人体的排泄途径（）',
    answer: 'D',
    explanation: '排泄是指将体内代谢废物（如尿素、多余的水、CO2等）排出体外的过程，通过肾脏（尿液）、皮肤（汗液）和肺（CO2）三条途径。排便（排出食物残渣）不属于排泄，属于排遗。',
    difficulty: 2,
    options: '["A. 排尿","B. 排汗","C. 呼出二氧化碳","D. 排便"]',
  },
  {
    chapterKey: 'biology-renjiao-8-1',
    questionKey: 'biology-renjiao-8-1-11',
    type: 'fill',
    questionText: '食物中的大分子有机物中，______被分解为葡萄糖，蛋白质被分解为______。',
    answer: '淀粉、氨基酸',
    explanation: '淀粉在唾液淀粉酶、胰液和肠液的作用下被分解为葡萄糖；蛋白质在胃蛋白酶、胰液和肠液的作用下被分解为氨基酸。',
    difficulty: 1,
  },
  {
    chapterKey: 'biology-renjiao-8-1',
    questionKey: 'biology-renjiao-8-1-12',
    type: 'fill',
    questionText: '红细胞中富含______，它能在氧含量高的地方与氧结合，在氧含量低的地方与氧分离，因此红细胞能运输______。',
    answer: '血红蛋白、氧气',
    explanation: '血红蛋白是一种含铁的蛋白质，在氧浓度高的地方容易与氧结合（如肺部），在氧浓度低的地方容易与氧分离（如组织细胞处），因此红细胞能运输氧气。',
    difficulty: 1,
  },
  {
    chapterKey: 'biology-renjiao-8-1',
    questionKey: 'biology-renjiao-8-1-13',
    type: 'fill',
    questionText: '人体血液循环分为体循环和______循环两部分，两循环在______处汇合。',
    answer: '肺、心脏',
    explanation: '血液循环分为体循环和肺循环，两者同时进行，在心脏连通，组成完整的循环途径。',
    difficulty: 1,
  },
  {
    chapterKey: 'biology-renjiao-8-1',
    questionKey: 'biology-renjiao-8-1-14',
    type: 'fill',
    questionText: '吸气时，肋间肌和膈肌______，胸腔容积______，肺扩张，外界空气进入肺。',
    answer: '收缩、增大',
    explanation: '吸气时，肋间外肌收缩使肋骨上提，膈肌收缩使膈顶下降，胸腔容积增大，肺随之扩张，肺内气压低于外界气压，空气被吸入肺。',
    difficulty: 2,
  },
  {
    chapterKey: 'biology-renjiao-8-1',
    questionKey: 'biology-renjiao-8-1-15',
    type: 'fill',
    questionText: '人体神经系统的组成包括中枢神经系统（______和______）和周围神经系统。',
    answer: '脑、脊髓',
    explanation: '神经系统由中枢神经系统（脑和脊髓）和周围神经系统（脑神经和脊神经）组成。',
    difficulty: 1,
    acceptableAnswers: '["脑、脊髓","脊髓、脑"]',
  },
  {
    chapterKey: 'biology-renjiao-8-1',
    questionKey: 'biology-renjiao-8-1-16',
    type: 'short_answer',
    questionText: '简述人体消化系统中各主要消化腺分泌的消化液及其作用。',
    answer: '唾液腺：分泌唾液（含唾液淀粉酶），分解淀粉为麦芽糖。胃腺：分泌胃液（含胃蛋白酶），初步消化蛋白质。肝脏：分泌胆汁（不含消化酶），乳化脂肪。胰腺：分泌胰液（含多种消化酶），分解淀粉、蛋白质和脂肪。肠腺：分泌肠液（含多种消化酶），在小肠内继续消化。',
    explanation: '各消化腺分泌的消化液含有不同的消化酶（胆汁除外），在消化道不同部位参与食物的消化过程。',
    difficulty: 2,
  },
  {
    chapterKey: 'biology-renjiao-8-1',
    questionKey: 'biology-renjiao-8-1-17',
    type: 'short_answer',
    questionText: '比较动脉、静脉和毛细血管三种血管的结构特点和功能。',
    answer: '动脉：管壁厚、弹性大、血流速度快，将血液从心脏输送到全身。静脉：管壁较薄、弹性小、管腔大、血流速度慢，内有静脉瓣（防止血液倒流），将血液从全身送回心脏。毛细血管：管壁极薄（仅一层上皮细胞）、管径最小、血流最慢，是血液与组织细胞进行物质交换的场所。',
    explanation: '三种血管的结构特点与其功能相适应。',
    difficulty: 2,
  },
  {
    chapterKey: 'biology-renjiao-8-1',
    questionKey: 'biology-renjiao-8-1-18',
    type: 'short_answer',
    questionText: '简述血液循环的途径（体循环和肺循环）。',
    answer: '体循环：左心室→主动脉→全身各处毛细血管→上下腔静脉→右心房。在全身毛细血管处进行物质交换（氧气和营养物质进入组织细胞，CO2和废物进入血液），血液由动脉血变为静脉血。肺循环：右心室→肺动脉→肺部毛细血管→肺静脉→左心房。在肺部毛细血管处进行气体交换（释放CO2，结合O2），血液由静脉血变为动脉血。',
    explanation: '体循环和肺循环同时进行，通过心脏连通，完成气体运输和物质交换。',
    difficulty: 2,
  },
  {
    chapterKey: 'biology-renjiao-8-1',
    questionKey: 'biology-renjiao-8-1-19',
    type: 'short_answer',
    questionText: '什么是反射？简述反射弧的组成。',
    answer: '反射是指在中枢神经系统的参与下，人体对内外环境刺激作出的规律性应答。反射弧是完成反射的结构基础，由五部分组成：感受器→传入神经→神经中枢→传出神经→效应器。',
    explanation: '反射弧的五个部分缺一不可，任何一个部分受损，反射都不能正常进行。',
    difficulty: 2,
  },
  {
    chapterKey: 'biology-renjiao-8-1',
    questionKey: 'biology-renjiao-8-1-20',
    type: 'short_answer',
    questionText: '视觉和听觉的形成过程分别是什么？',
    answer: '视觉形成：外界光线→角膜→瞳孔→晶状体→玻璃体→视网膜（形成物像，感受光刺激）→视神经→大脑皮层视觉中枢（形成视觉）。听觉形成：外界声波→外耳道→鼓膜（振动）→听小骨（放大振动）→耳蜗（感受振动刺激）→听神经→大脑皮层听觉中枢（形成听觉）。',
    explanation: '视觉和听觉的形成都经过感受器接受刺激，通过神经传导到大脑皮层相应中枢才能形成感觉。',
    difficulty: 3,
  },
  {
    chapterKey: 'biology-renjiao-8-1',
    questionKey: 'biology-renjiao-8-1-21',
    type: 'short_answer',
    questionText: '人体每天需要的主要营养物质有哪些？各有什么作用？',
    answer: '糖类：主要的供能物质；蛋白质：构成人体组织细胞的基本物质，参与生长发育和组织更新；脂肪：备用的能源物质，保温；水：溶剂，参与化学反应，运输物质；无机盐：参与构成组织细胞（如钙构成骨骼）；维生素：维持正常生理功能（如维生素A保护视力，维生素C促进伤口愈合）。',
    explanation: '六类营养物质各有其功能，合理膳食才能保证人体健康。',
    difficulty: 3,
  },
  {
    chapterKey: 'biology-renjiao-8-1',
    questionKey: 'biology-renjiao-8-1-22',
    type: 'matching',
    questionText: '请将下列血液成分与其对应的功能匹配。',
    answer: '血浆—运输养料和废物；红细胞—运输氧气；白细胞—防御保护；血小板—止血和凝血',
    explanation: '血液的各成分有不同的功能，共同维持人体正常生理活动。',
    difficulty: 1,
    pairs: '[["血浆","运输养料和废物"],["红细胞","运输氧气"],["白细胞","防御保护"],["血小板","止血和凝血"]]',
  },
  {
    chapterKey: 'biology-renjiao-8-1',
    questionKey: 'biology-renjiao-8-1-23',
    type: 'matching',
    questionText: '请将下列营养素与其功能匹配。',
    answer: '糖类—主要的能源物质；蛋白质—构成细胞的基本物质；脂肪—备用能源物质；维生素—调节生理功能；水—溶剂和运输',
    explanation: '各类营养物质在人体中各司其职。',
    difficulty: 1,
    pairs: '[["糖类","主要的能源物质"],["蛋白质","构成细胞的基本物质"],["脂肪","备用能源物质"],["维生素","调节生理功能"],["水","溶剂和运输"]]',
  },
  {
    chapterKey: 'biology-renjiao-8-2',
    questionKey: 'biology-renjiao-8-2-0',
    type: 'choice',
    questionText: '下列动物中，属于脊椎动物的是（）',
    answer: 'B',
    explanation: '脊椎动物体内有由脊椎骨组成的脊柱，包括鱼类、两栖类、爬行类、鸟类和哺乳类。蚯蚓、蝴蝶和蜗牛都是无脊椎动物。',
    difficulty: 1,
    options: '["A. 蚯蚓","B. 青蛙","C. 蝴蝶","D. 蜗牛"]',
  },
  {
    chapterKey: 'biology-renjiao-8-2',
    questionKey: 'biology-renjiao-8-2-1',
    type: 'choice',
    questionText: '鱼类在水中呼吸的器官是（）',
    answer: 'A',
    explanation: '鱼类用鳃呼吸。鳃中有丰富的毛细血管，水流过鳃时，水中溶解的氧气进入血液，血液中的二氧化碳排入水中。',
    difficulty: 1,
    options: '["A. 鳃","B. 肺","C. 鳞片","D. 鳔"]',
  },
  {
    chapterKey: 'biology-renjiao-8-2',
    questionKey: 'biology-renjiao-8-2-2',
    type: 'choice',
    questionText: '下列哪种动物属于爬行动物（）',
    answer: 'C',
    explanation: '爬行动物（如龟、蜥蜴、蛇、鳄）体表有角质鳞片或甲，用肺呼吸，在陆地上产卵（有坚韧的卵壳）。青蛙是两栖动物，壁虎是爬行动物，蛇是爬行动物。',
    difficulty: 1,
    options: '["A. 青蛙","B. 蝙蝠","C. 壁虎","D. 麻雀"]',
  },
  {
    chapterKey: 'biology-renjiao-8-2',
    questionKey: 'biology-renjiao-8-2-3',
    type: 'choice',
    questionText: '鸟类适于飞行生活的特征不包括（）',
    answer: 'D',
    explanation: '鸟类适于飞行的特征：身体呈流线型；前肢变成翼；体表覆羽毛；骨骼中空轻巧；胸肌发达；有喙无齿；直肠短不储存粪便等。胎生哺乳是哺乳动物的特征。',
    difficulty: 2,
    options: '["A. 身体呈流线型","B. 前肢变成翼","C. 骨骼中空","D. 胎生哺乳"]',
  },
  {
    chapterKey: 'biology-renjiao-8-2',
    questionKey: 'biology-renjiao-8-2-4',
    type: 'choice',
    questionText: '下列哪项是哺乳动物最主要的特征（）',
    answer: 'B',
    explanation: '哺乳动物的主要特征：体表有毛；胎生、哺乳；牙齿有分化（门齿、犬齿、臼齿）。其中胎生哺乳是哺乳动物最典型的特征。',
    difficulty: 1,
    options: '["A. 体表有鳞片","B. 胎生、哺乳","C. 用鳃呼吸","D. 卵生"]',
  },
  {
    chapterKey: 'biology-renjiao-8-2',
    questionKey: 'biology-renjiao-8-2-5',
    type: 'choice',
    questionText: '细菌和真菌共有的特征是（）',
    answer: 'A',
    explanation: '细菌和真菌都没有叶绿体，不能自己制造有机物，只能利用现成的有机物（异养）。区别：细菌没有成形的细胞核（原核生物），真菌有成形的细胞核（真核生物）。',
    difficulty: 2,
    options: '["A. 异养","B. 有成形的细胞核","C. 能进行光合作用","D. 都有鞭毛"]',
  },
  {
    chapterKey: 'biology-renjiao-8-2',
    questionKey: 'biology-renjiao-8-2-6',
    type: 'choice',
    questionText: '下列生物中，属于单细胞生物的是（）',
    answer: 'C',
    explanation: '酵母菌、草履虫、变形虫、衣藻等都是单细胞生物。蘑菇是多细胞真菌，水螅是多细胞动物，苔藓是多细胞植物。',
    difficulty: 1,
    options: '["A. 蘑菇","B. 水螅","C. 草履虫","D. 苔藓"]',
  },
  {
    chapterKey: 'biology-renjiao-8-2',
    questionKey: 'biology-renjiao-8-2-7',
    type: 'choice',
    questionText: '细菌的细胞结构与植物细胞相比，缺少（）',
    answer: 'D',
    explanation: '细菌细胞有细胞壁、细胞膜、细胞质、核糖体，但没有成形的细胞核（只有DNA集中区域），没有叶绿体和液泡。',
    difficulty: 1,
    options: '["A. 细胞壁","B. 细胞膜","C. 细胞质","D. 成形的细胞核"]',
  },
  {
    chapterKey: 'biology-renjiao-8-2',
    questionKey: 'biology-renjiao-8-2-8',
    type: 'choice',
    questionText: '下列哪种方式不是细菌的繁殖方式（）',
    answer: 'A',
    explanation: '细菌通过分裂生殖进行繁殖（一个分成两个），在环境恶劣时形成芽孢休眠。不能进行有性生殖或孢子生殖（注意：芽孢不是繁殖方式，是休眠体）。',
    difficulty: 2,
    options: '["A. 孢子生殖","B. 分裂生殖","C. 形成芽孢（休眠）","D. A和C都不是"]',
  },
  {
    chapterKey: 'biology-renjiao-8-2',
    questionKey: 'biology-renjiao-8-2-9',
    type: 'fill',
    questionText: '动物根据体内有无脊柱，可分为______动物和______动物。',
    answer: '脊椎、无脊椎',
    explanation: '动物界中，体内有脊柱的叫脊椎动物（如鱼、蛙、龟、鸟、兽），体内没有脊柱的叫无脊椎动物（如昆虫、蚯蚓、蜗牛等）。',
    difficulty: 1,
    acceptableAnswers: '["脊椎、无脊椎","无脊椎、脊椎"]',
  },
  {
    chapterKey: 'biology-renjiao-8-2',
    questionKey: 'biology-renjiao-8-2-10',
    type: 'fill',
    questionText: '真菌的繁殖方式主要产生______来繁殖后代。',
    answer: '孢子',
    explanation: '真菌（如霉菌、蘑菇）通过产生大量的孢子进行繁殖，孢子在适宜条件下萌发长成新的菌体。',
    difficulty: 1,
  },
  {
    chapterKey: 'biology-renjiao-8-2',
    questionKey: 'biology-renjiao-8-2-11',
    type: 'fill',
    questionText: '病毒的结构简单，由______外壳和内部的______组成，没有细胞结构。',
    answer: '蛋白质、遗传物质',
    explanation: '病毒没有细胞结构，由蛋白质外壳和内部的遗传物质（DNA或RNA）组成，必须寄生在活细胞内才能生活和繁殖。',
    difficulty: 1,
    acceptableAnswers: '["蛋白质、遗传物质","蛋白质外壳、遗传物质"]',
  },
  {
    chapterKey: 'biology-renjiao-8-2',
    questionKey: 'biology-renjiao-8-2-12',
    type: 'fill',
    questionText: '______动物是动物界中种类和数量最多的一类，属于______动物。',
    answer: '昆虫、无脊椎',
    explanation: '昆虫属于节肢动物，是无脊椎动物中种类最多、数量最大的一类，已知种类超过100万种。',
    difficulty: 1,
  },
  {
    chapterKey: 'biology-renjiao-8-2',
    questionKey: 'biology-renjiao-8-2-13',
    type: 'short_answer',
    questionText: '比较细菌和真菌的异同点。',
    answer: '相同点：都没有叶绿体，不能自养，靠分解或吸收现成有机物生活。不同点：①细胞结构：细菌没有成形的细胞核（原核），真菌有成形的细胞核（真核）；②繁殖方式：细菌靠分裂生殖，真菌靠孢子生殖；③形态：细菌是个体微小的单细胞生物，真菌有单细胞（酵母菌）也有多细胞（霉菌、蘑菇）；④细菌有的有鞭毛能运动，真菌没有。',
    explanation: '细菌属于原核生物，真菌属于真核生物，两者虽然都是异养生物，但在细胞结构和繁殖方式上有显著区别。',
    difficulty: 2,
  },
  {
    chapterKey: 'biology-renjiao-8-2',
    questionKey: 'biology-renjiao-8-2-14',
    type: 'short_answer',
    questionText: '病毒有什么特点？病毒的生活方式有什么特殊性？',
    answer: '病毒的特点：个体微小，必须用电子显微镜才能看到；结构简单，由蛋白质外壳和内部遗传物质组成，无细胞结构；不能独立生活。病毒的生活方式：必须寄生在活细胞内，利用宿主细胞中的物质进行繁殖，对宿主造成危害。',
    explanation: '病毒是严格的寄生物，离开活细胞无法生存，在医学和农业上有重要的致病意义。',
    difficulty: 2,
  },
  {
    chapterKey: 'biology-renjiao-8-2',
    questionKey: 'biology-renjiao-8-2-15',
    type: 'short_answer',
    questionText: '从形态、呼吸、繁殖和体温四个方面，说明鱼类和两栖类有什么不同。',
    answer: '形态：鱼类体表有鳞片，用鳃呼吸；两栖类幼体用鳃、成体用肺呼吸，皮肤辅助呼吸。呼吸：鱼类终生用鳃；两栖类幼体用鳃，成体用肺。繁殖：鱼类多为卵生、体外受精；两栖类也是卵生、体外受精，但产在水中。体温：鱼类变温；两栖类也是变温动物，但需冬眠。',
    explanation: '两栖类是水生到陆生的过渡类型，幼体生活在水中、成体多在陆地，但繁殖不能离开水。',
    difficulty: 2,
  },
  {
    chapterKey: 'biology-renjiao-8-2',
    questionKey: 'biology-renjiao-8-2-16',
    type: 'short_answer',
    questionText: '生物分类的意义是什么？',
    answer: '生物分类的意义：①弄清不同生物之间的亲缘关系和进化关系；②揭示生物的多样性及其内在联系；③帮助人们更好地认识和保护生物；④为科学研究、资源利用和疾病防治提供依据。分类的基本单位是种，分类等级越低，共同特征越多，亲缘关系越近。',
    explanation: '生物分类学根据生物的形态结构、生理功能等特征进行分类，反映生物之间的亲缘关系和进化历程。',
    difficulty: 3,
  },
  {
    chapterKey: 'biology-renjiao-8-2',
    questionKey: 'biology-renjiao-8-2-17',
    type: 'matching',
    questionText: '请将下列动物类群与其特征匹配。',
    answer: '鱼类—用鳃呼吸、有鳞片；两栖类—幼体用鳃成体用肺；爬行类—体表有角质鳞片、卵生有壳；鸟类—前肢变翼、体温恒定；哺乳类—胎生哺乳、体表有毛',
    explanation: '各脊椎动物类群的特征体现了它们对不同环境的适应。',
    difficulty: 2,
    pairs: '[["鱼类","用鳃呼吸、有鳞片"],["两栖类","幼体用鳃成体用肺"],["爬行类","体表有角质鳞片、卵生有壳"],["鸟类","前肢变翼、体温恒定"],["哺乳类","胎生哺乳、体表有毛"]]',
  },
  {
    chapterKey: 'biology-renjiao-8-2',
    questionKey: 'biology-renjiao-8-2-18',
    type: 'matching',
    questionText: '请将下列微生物与其特征匹配。',
    answer: '细菌—无成形细胞核，分裂生殖；酵母菌—单细胞真菌，出芽生殖；霉菌—多细胞真菌，孢子生殖；蘑菇—大型真菌，孢子生殖；病毒—无细胞结构，寄生生活',
    explanation: '各种微生物在细胞结构和生活方式上有明显区别。',
    difficulty: 2,
    pairs: '[["细菌","无成形细胞核，分裂生殖"],["酵母菌","单细胞真菌，出芽生殖"],["霉菌","多细胞真菌，孢子生殖"],["蘑菇","大型真菌，孢子生殖"],["病毒","无细胞结构，寄生生活"]]',
  },
  {
    chapterKey: 'biology-renjiao-8-2',
    questionKey: 'biology-renjiao-8-2-19',
    type: 'matching',
    questionText: '请将下列节肢动物与所属类群匹配。',
    answer: '蜘蛛—蛛形纲；蝗虫—昆虫纲；虾—甲壳纲；蜈蚣—多足纲',
    explanation: '节肢动物是最大的动物门类，主要包括昆虫纲、甲壳纲、蛛形纲和多足纲。',
    difficulty: 1,
    pairs: '[["蜘蛛","蛛形纲"],["蝗虫","昆虫纲"],["虾","甲壳纲"],["蜈蚣","多足纲"]]',
  },
  {
    chapterKey: 'biology-renjiao-8-3',
    questionKey: 'biology-renjiao-8-3-0',
    type: 'choice',
    questionText: '植物的有性生殖过程中，受精作用发生在（）',
    answer: 'B',
    explanation: '有性生殖过程中，花粉落到柱头上萌发出花粉管，精子沿花粉管到达胚珠内部，与卵细胞结合完成受精。受精发生在胚珠内部。',
    difficulty: 1,
    options: '["A. 花粉管中","B. 胚珠内","C. 柱头上","D. 子房壁上"]',
  },
  {
    chapterKey: 'biology-renjiao-8-3',
    questionKey: 'biology-renjiao-8-3-1',
    type: 'choice',
    questionText: '下列属于无性生殖的是（）',
    answer: 'A',
    explanation: '无性生殖是不经过两性生殖细胞结合、由母体直接产生新个体的生殖方式。扦插、嫁接、压条和组织培养都属于无性生殖。种子繁殖需要经过两性生殖细胞的结合（受精），属于有性生殖。',
    difficulty: 1,
    options: '["A. 扦插","B. 用种子繁殖","C. 传粉受精","D. 杂交水稻"]',
  },
  {
    chapterKey: 'biology-renjiao-8-3',
    questionKey: 'biology-renjiao-8-3-2',
    type: 'choice',
    questionText: '嫁接成活的关键是（）',
    answer: 'C',
    explanation: '嫁接时，接穗和砧木的形成层紧密结合是成活的关键。形成层细胞能分裂产生新细胞，使接穗和砧木的组织愈合在一起。',
    difficulty: 1,
    options: '["A. 接穗和砧木的品种相同","B. 嫁接的时间选择","C. 接穗和砧木的形成层紧密结合","D. 选用粗壮的砧木"]',
  },
  {
    chapterKey: 'biology-renjiao-8-3',
    questionKey: 'biology-renjiao-8-3-3',
    type: 'choice',
    questionText: '昆虫的发育过程中，经历卵→幼虫→蛹→成虫四个阶段的发育方式叫做（）',
    answer: 'B',
    explanation: '完全变态发育包括卵、幼虫、蛹、成虫四个阶段，如蝴蝶、苍蝇、蜜蜂等。不完全变态发育经历卵、若虫、成虫三个阶段，如蝗虫、蟋蟀、蜻蜓等。',
    difficulty: 1,
    options: '["A. 不完全变态发育","B. 完全变态发育","C. 世代交替","D. 孤雌生殖"]',
  },
  {
    chapterKey: 'biology-renjiao-8-3',
    questionKey: 'biology-renjiao-8-3-4',
    type: 'choice',
    questionText: '下列昆虫中，属于不完全变态发育的是（）',
    answer: 'D',
    explanation: '蝗虫、蟋蟀、蜻蜓、蝼蛄等属于不完全变态发育（卵→若虫→成虫），没有蛹期。家蚕、蝴蝶、苍蝇、蚊子属于完全变态发育。',
    difficulty: 1,
    options: '["A. 蝴蝶","B. 家蚕","C. 苍蝇","D. 蝗虫"]',
  },
  {
    chapterKey: 'biology-renjiao-8-3',
    questionKey: 'biology-renjiao-8-3-5',
    type: 'choice',
    questionText: '青蛙的发育过程中，幼体与成体在形态结构上的主要区别是（）',
    answer: 'A',
    explanation: '青蛙的幼体（蝌蚪）生活在水中，用鳃呼吸、有尾巴；成体大多生活在陆地，用肺呼吸、无尾巴、有四肢。两者在形态结构和生活习性上有很大差异。',
    difficulty: 1,
    options: '["A. 幼体用鳃呼吸有尾，成体用肺呼吸无尾","B. 幼体用肺呼吸，成体用鳃呼吸","C. 幼体有四肢，成体无四肢","D. 两者无区别"]',
  },
  {
    chapterKey: 'biology-renjiao-8-3',
    questionKey: 'biology-renjiao-8-3-6',
    type: 'choice',
    questionText: '两栖动物的生殖特点是（）',
    answer: 'C',
    explanation: '两栖动物的生殖特点：有性生殖、体外受精、卵生。受精过程在水中进行，胚胎发育也在水中完成。',
    difficulty: 1,
    options: '["A. 体内受精、胎生","B. 体内受精、卵生","C. 体外受精、卵生","D. 无性生殖"]',
  },
  {
    chapterKey: 'biology-renjiao-8-3',
    questionKey: 'biology-renjiao-8-3-7',
    type: 'choice',
    questionText: '鸡卵中，能为胚胎发育提供营养物质的结构是（）',
    answer: 'D',
    explanation: '鸡卵的卵白（蛋白）和卵黄（蛋黄）都能为胚胎发育提供营养物质。卵黄是主要营养来源，卵白提供水分和少量营养。卵壳起保护作用，胚盘是胚胎发育的部位。',
    difficulty: 2,
    options: '["A. 卵壳","B. 卵壳膜","C. 气室","D. 卵白和卵黄"]',
  },
  {
    chapterKey: 'biology-renjiao-8-3',
    questionKey: 'biology-renjiao-8-3-8',
    type: 'choice',
    questionText: '鸟类的生殖和发育过程一般包括求偶、交配、筑巢、产卵、孵卵和育雏等阶段。下列哪种鸟的雏鸟属于早成雏（）',
    answer: 'A',
    explanation: '早成雏（如鸡、鸭、鹅）出壳时羽毛丰满、眼已睁开、能跟随亲鸟觅食。晚成雏（如麻雀、燕子）出壳时裸露无毛、眼未睁开，需要亲鸟喂养。',
    difficulty: 2,
    options: '["A. 鸡","B. 麻雀","C. 燕子","D. 鸽子"]',
  },
  {
    chapterKey: 'biology-renjiao-8-3',
    questionKey: 'biology-renjiao-8-3-9',
    type: 'choice',
    questionText: '下列哪种繁殖方式属于有性生殖（）',
    answer: 'B',
    explanation: '有性生殖经过两性生殖细胞的结合。种子繁殖是植物的有性生殖，需要精子和卵细胞的结合（受精）。嫁接、扦插、组织培养都属于无性生殖。',
    difficulty: 2,
    options: '["A. 嫁接","B. 用种子播种","C. 扦插","D. 植物组织培养"]',
  },
  {
    chapterKey: 'biology-renjiao-8-3',
    questionKey: 'biology-renjiao-8-3-10',
    type: 'fill',
    questionText: '植物的生殖方式分为______生殖和______生殖两大类。',
    answer: '有性、无性',
    explanation: '有性生殖需要两性生殖细胞的结合，无性生殖不需要两性生殖细胞的结合，由母体直接产生新个体。',
    difficulty: 1,
    acceptableAnswers: '["有性、无性","无性、有性"]',
  },
  {
    chapterKey: 'biology-renjiao-8-3',
    questionKey: 'biology-renjiao-8-3-11',
    type: 'fill',
    questionText: '在嫁接中，接上去的枝条叫______，被接的植物体叫______。',
    answer: '接穗、砧木',
    explanation: '嫁接时，接穗是提供优良品种特性的枝条或芽，砧木是承受接穗的植物体，提供根系。',
    difficulty: 1,
    acceptableAnswers: '["接穗、砧木","砧木、接穗"]',
  },
  {
    chapterKey: 'biology-renjiao-8-3',
    questionKey: 'biology-renjiao-8-3-12',
    type: 'fill',
    questionText: '完全变态发育经历卵→______→______→成虫四个阶段。',
    answer: '幼虫、蛹',
    explanation: '完全变态发育的四个阶段是卵、幼虫、蛹、成虫。幼虫和成体在形态结构和生活习性上有很大差异。',
    difficulty: 1,
  },
  {
    chapterKey: 'biology-renjiao-8-3',
    questionKey: 'biology-renjiao-8-3-13',
    type: 'fill',
    questionText: '青蛙的发育过程经历了四个阶段：受精卵→______→幼蛙→成蛙。这种发育方式叫做______发育。',
    answer: '蝌蚪、变态',
    explanation: '青蛙的发育经过受精卵→蝌蚪→幼蛙→成蛙四个阶段，幼体和成体在形态结构和生活习性上有很大差异，属于变态发育。',
    difficulty: 1,
  },
  {
    chapterKey: 'biology-renjiao-8-3',
    questionKey: 'biology-renjiao-8-3-14',
    type: 'short_answer',
    questionText: '比较植物有性生殖和无性生殖的区别，并各举一例。',
    answer: '有性生殖：经过两性生殖细胞（精子和卵细胞）的结合形成受精卵，再发育成新个体。后代具有双亲的遗传特性，变异丰富。如种子繁殖。无性生殖：不经过两性生殖细胞的结合，由母体直接产生新个体。后代遗传物质与母体基本一致，变异较少，繁殖速度快。如扦插、嫁接。',
    explanation: '有性生殖有利于种群适应环境变化，无性生殖有利于快速繁殖保持优良性状。',
    difficulty: 2,
  },
  {
    chapterKey: 'biology-renjiao-8-3',
    questionKey: 'biology-renjiao-8-3-15',
    type: 'short_answer',
    questionText: '简述组织培养技术的原理和优点。',
    answer: '原理：植物细胞具有全能性，即每个活的植物细胞在适宜条件下都有发育成完整植株的能力。优点：①繁殖速度快，短期内可获得大量植株；②可以培养无病毒植株；③可用于拯救濒危植物；④不受季节限制，可工厂化生产。',
    explanation: '组织培养是利用植物细胞全能性的无性繁殖技术，在农业和科研中有广泛应用。',
    difficulty: 2,
  },
  {
    chapterKey: 'biology-renjiao-8-3',
    questionKey: 'biology-renjiao-8-3-16',
    type: 'short_answer',
    questionText: '青蛙为什么属于两栖动物？其生殖和发育过程有什么特点？',
    answer: '青蛙属于两栖动物是因为其幼体生活在水中用鳃呼吸，成体多生活在陆地用肺呼吸（皮肤辅助呼吸），是水生向陆生的过渡类型。生殖特点：有性生殖，雌雄异体，体外受精（精子和卵细胞在水中结合）。发育特点：变态发育，经过受精卵→蝌蚪→幼蛙→成蛙，幼体与成体在形态结构和习性上有很大差异。',
    explanation: '两栖动物虽名为"两栖"，但繁殖过程不能完全脱离水环境。',
    difficulty: 2,
  },
  {
    chapterKey: 'biology-renjiao-8-3',
    questionKey: 'biology-renjiao-8-3-17',
    type: 'short_answer',
    questionText: '鸡卵的结构中，哪些结构分别对应以下功能？①保护卵细胞 ②提供营养 ③胚胎发育的部位 ④提供氧气',
    answer: '①保护卵细胞：卵壳和卵壳膜；②提供营养：卵黄（主要）和卵白；③胚胎发育的部位：胚盘（卵黄表面的小白点）；④提供氧气：气室（储存空气供胚胎呼吸）。',
    explanation: '鸡卵各结构分工明确，共同保障胚胎的正常发育。',
    difficulty: 2,
  },
  {
    chapterKey: 'biology-renjiao-8-3',
    questionKey: 'biology-renjiao-8-3-18',
    type: 'short_answer',
    questionText: '青蛙的生殖发育为什么不能完全脱离水环境？这给青蛙的生存带来什么影响？',
    answer: '青蛙的体外受精和幼体（蝌蚪）生活在水中，因此繁殖过程不能脱离水环境。影响：①青蛙的分布范围受到水源的限制；②水环境污染会直接影响青蛙的繁殖和生存；③气候变化导致水域减少，青蛙面临栖息地丧失的威胁；④青蛙是对环境变化非常敏感的指示动物。',
    explanation: '两栖动物对水环境的依赖是它们面临生存威胁的主要原因之一。',
    difficulty: 3,
  },
  {
    chapterKey: 'biology-renjiao-8-3',
    questionKey: 'biology-renjiao-8-3-19',
    type: 'matching',
    questionText: '请将下列植物的繁殖方式与对应的类型匹配。',
    answer: '扦插—无性生殖；嫁接—无性生殖；种子繁殖—有性生殖；组织培养—无性生殖；压条—无性生殖',
    explanation: '扦插、嫁接、组织培养和压条都不需要两性生殖细胞的结合，属于无性生殖。种子繁殖经过受精，属于有性生殖。',
    difficulty: 1,
    pairs: '[["扦插","无性生殖"],["嫁接","无性生殖"],["种子繁殖","有性生殖"],["组织培养","无性生殖"],["压条","无性生殖"]]',
  },
  {
    chapterKey: 'biology-renjiao-8-3',
    questionKey: 'biology-renjiao-8-3-20',
    type: 'matching',
    questionText: '请将下列昆虫与其发育方式匹配。',
    answer: '家蚕—完全变态发育（卵→幼虫→蛹→成虫）；蝗虫—不完全变态发育（卵→若虫→成虫）；蝴蝶—完全变态发育；蜜蜂—完全变态发育；蟋蟀—不完全变态发育',
    explanation: '不同昆虫的发育方式取决于其是否经历蛹期。',
    difficulty: 2,
    pairs: '[["家蚕","完全变态发育（卵→幼虫→蛹→成虫）"],["蝗虫","不完全变态发育（卵→若虫→成虫）"],["蝴蝶","完全变态发育"],["蜜蜂","完全变态发育"],["蟋蟀","不完全变态发育"]]',
  },
  {
    chapterKey: 'biology-renjiao-8-3',
    questionKey: 'biology-renjiao-8-3-21',
    type: 'matching',
    questionText: '请将下列动物类群与生殖方式匹配。',
    answer: '鱼类—体外受精、卵生；两栖类—体外受精、卵生（水中）；爬行类—体内受精、卵生（有壳）；鸟类—体内受精、卵生（有壳）；哺乳类—体内受精、胎生哺乳',
    explanation: '从鱼类到哺乳类，生殖方式逐渐从体外受精卵生过渡到体内受精胎生，对后代保护能力增强。',
    difficulty: 2,
    pairs: '[["鱼类","体外受精、卵生"],["两栖类","体外受精、卵生（水中）"],["爬行类","体内受精、卵生（有壳）"],["鸟类","体内受精、卵生（有壳）"],["哺乳类","体内受精、胎生哺乳"]]',
  }
];

export async function seedBiologyRenjiaoQuestions(): Promise<number> {
  const chapters = await prisma.chapter.findMany({
    where: { chapterKey: { startsWith: 'biology-renjiao' } },
  });
  const keyToId = new Map<string, string>();
  for (const ch of chapters) {
    keyToId.set(ch.chapterKey, ch.id);
  }

  const records = questions
    .map(q => {
      const chapterId = keyToId.get(q.chapterKey);
      if (!chapterId) return null;
      const { chapterKey: _, ...data } = q;
      return { ...data, chapterId };
    })
    .filter(Boolean);

  const BATCH_SIZE = 500;
  let inserted = 0;
  for (let i = 0; i < records.length; i += BATCH_SIZE) {
    const batch = records.slice(i, i + BATCH_SIZE);
    const result = await prisma.question.createMany({
      data: batch,
      skipDuplicates: true,
    });
    inserted += result.count;
  }
  console.log(`[seed-biology-renjiao] 共插入 ${inserted} 道生物人教版题目`);
  return inserted;
}
