/**
 * 英语人教版(PEP)初中题目种子数据
 *
 * 涵盖 7~9 年级共 12 个章节，总计 281 道题。
 * 章节对应 seed-data.ts 中 english-pep 的定义：
 *   7年级：My name's Gina(20)、This is my sister(22)、Is there a post office near here?(25)、I'm watching TV(24)
 *   8年级：Where did you go on vacation?(22)、How often do you exercise?(20)、I'm more outgoing than my sister(26)、What's the best movie theater?(22)
 *   9年级：How can we become good learners?(24)、I think that mooncakes are delicious!(26)、Could you please tell me where the restrooms are?(28)、We're trying to save the earth!(22)
 *
 * 题型分布：choice ~40% | fill ~30% | short_answer ~20% | matching ~10%
 * 难度分布：difficulty 1(基础) ~40% | 2(中等) ~40% | 3(提高) ~20%
 */

import { prisma } from '../src/config/database.js';

// ---------- 类型定义 ----------

interface RawQuestion {
  questionKey: string;
  type: 'choice' | 'fill' | 'short_answer' | 'matching';
  questionText: string;
  answer: string;
  explanation: string;
  difficulty: 1 | 2 | 3;
  options?: string;
  pairs?: string;
  acceptableAnswers?: string;
}

// ========== 7-0 My name's Gina (20题) =========
// 知识点：问候与自我介绍、be动词、物主代词、what/who引导的特殊疑问句

const chapter7_0: RawQuestion[] = [
  // ---- choice 8题 ----
  {
    questionKey: 'english-pep-7-0-0',
    type: 'choice',
    questionText: '—What's your name? —My name ___ Gina.',
    answer: 'C',
    explanation: "主语 My name 是第三人称单数，be动词用 is，缩写为 's。",
    difficulty: 1,
    options: '["A. am", "B. are", "C. is", "D. be"]',
  },
  {
    questionKey: 'english-pep-7-0-1',
    type: 'choice',
    questionText: '—Nice to meet you. —___',
    answer: 'A',
    explanation: "Nice to meet you 的固定回答是 Nice to meet you, too.，意为"我也很高兴见到你"。",
    difficulty: 1,
    options: '["A. Nice to meet you, too.", "B. Thank you.", "C. How are you?", "D. I\'m fine."]',
  },
  {
    questionKey: 'english-pep-7-0-2',
    type: 'choice',
    questionText: '—What's ___ name? —His name is Jack.',
    answer: 'D',
    explanation: "根据回答 His name 可知问的是"他的"名字，应用 his。",
    difficulty: 1,
    options: '["A. my", "B. your", "C. her", "D. his"]',
  },
  {
    questionKey: 'english-pep-7-0-3',
    type: 'choice',
    questionText: '—Are you Mary? —Yes, ___.',
    answer: 'B',
    explanation: '一般疑问句用 be 动词开头，肯定回答为 Yes, I am.，否定回答为 No, I\'m not.。',
    difficulty: 1,
    options: '["A. I\'m", "B. I am", "C. I\'m not", "D. am"]',
  },
  {
    questionKey: 'english-pep-7-0-4',
    type: 'choice',
    questionText: 'Her phone number ___ 886-7532.',
    answer: 'A',
    explanation: '主语 Her phone number 是第三人称单数，be 动词用 is。',
    difficulty: 1,
    options: '["A. is", "B. are", "C. am", "D. be"]',
  },
  {
    questionKey: 'english-pep-7-0-5',
    type: 'choice',
    questionText: '___ name is Tom. ___ is my friend.',
    answer: 'C',
    explanation: '第一空主语是 name（名字），是男性名字，用 His；第二空指代 Tom（男），用 He。His 是形容词性物主代词，He 是主格。',
    difficulty: 2,
    options: '["A. He; He", "B. His; His", "C. His; He", "D. He; His"]',
  },
  {
    questionKey: 'english-pep-7-0-6',
    type: 'choice',
    questionText: '—Is she your sister? —___. She is my friend.',
    answer: 'D',
    explanation: '根据后句"她是我朋友"可知，她不是姐姐（妹妹），故选 No, she isn\'t.。',
    difficulty: 2,
    options: '["A. Yes, she is.", "B. Yes, she isn\'t.", "C. No, she is.", "D. No, she isn\'t."]',
  },
  {
    questionKey: 'english-pep-7-0-7',
    type: 'choice',
    questionText: 'My friend is in China. ___ family name is Li. You can call ___ Li Hua.',
    answer: 'B',
    explanation: "第一空修饰 family name，用形容词性物主代词 His；第二空作 call 的宾语，用人称代词宾格 him。",
    difficulty: 3,
    options: '["A. His; he", "B. His; him", "C. He; him", "D. He; his"]',
  },
  // ---- fill 6题 ----
  {
    questionKey: 'english-pep-7-0-8',
    type: 'fill',
    questionText: '—___ is your name? —My name is Alice.',
    answer: 'What',
    explanation: '对名字提问用 What，"What\'s your name?"是固定句型。',
    difficulty: 1,
    acceptableAnswers: '["what", "WHAT"]',
  },
  {
    questionKey: 'english-pep-7-0-9',
    type: 'fill',
    questionText: '—___ your telephone number? —It\'s 283-9567.',
    answer: 'What\'s',
    explanation: '对电话号码提问用 "What\'s your telephone number?"。',
    difficulty: 1,
    acceptableAnswers: '["What is", "What\'s", "what\'s", "what is"]',
  },
  {
    questionKey: 'english-pep-7-0-10',
    type: 'fill',
    questionText: 'Nice to ___ (meet) you.',
    answer: 'meet',
    explanation: "Nice to meet you 是固定搭配，to 后接动词原形。",
    difficulty: 1,
    acceptableAnswers: '["meet", "Meet"]',
  },
  {
    questionKey: 'english-pep-7-0-11',
    type: 'fill',
    questionText: '___ (I) name is Linda. ___ (she) name is Kate.',
    answer: 'My; Her',
    explanation: '第一空修饰 name，用形容词性物主代词 My；第二空修饰 name，指女性，用 Her。',
    difficulty: 2,
    acceptableAnswers: '["My; Her", "my; her", "My; her", "my; Her"]',
  },
  {
    questionKey: 'english-pep-7-0-12',
    type: 'fill',
    questionText: 'He ___ (be) my brother. His ___ (one) name is Peter.',
    answer: 'is; first',
    explanation: 'He 是第三人称单数，be 动词用 is；first name 意为"名字"（与 last name "姓氏"对应）。',
    difficulty: 2,
    acceptableAnswers: '["is; first", "is; First"]',
  },
  {
    questionKey: 'english-pep-7-0-13',
    type: 'fill',
    questionText: 'Is ___ (this) your pen? Yes, ___ (it) is.',
    answer: 'this; it',
    explanation: "this 指近处的物品；回答中用 it 指代 this 提到的事物。",
    difficulty: 3,
    acceptableAnswers: '["this; it", "This; it", "this; It"]',
  },
  // ---- short_answer 4题 ----
  {
    questionKey: 'english-pep-7-0-14',
    type: 'short_answer',
    questionText: '请用英语写出三个问候语。',
    answer: 'Good morning! / Good afternoon! / Good evening! / How are you? / Hello! / Hi!（任选三个）',
    explanation: '常见的英语问候语有 Good morning/afternoon/evening, How are you, Hello, Hi 等。',
    difficulty: 1,
  },
  {
    questionKey: 'english-pep-7-0-15',
    type: 'short_answer',
    questionText: '请写出英语中介绍自己的完整句子（包含名字）。
提示：我的名字叫李明。',
    answer: 'My name is Li Ming. / I am Li Ming. / I\'m Li Ming.',
    explanation: '介绍自己可以用 My name is... 或 I\'m... 两种句型。',
    difficulty: 2,
    acceptableAnswers: '["My name is Li Ming.", "I am Li Ming.", "I\'m Li Ming."]',
  },
  {
    questionKey: 'english-pep-7-0-16',
    type: 'short_answer',
    questionText: '将下列句子改为一般疑问句并作肯定和否定回答：He is my friend.',
    answer: 'Is he your friend? —Yes, he is. / —No, he isn\'t.',
    explanation: 'be 动词 is 提到句首构成一般疑问句，my 改为 your，he 保持不变。',
    difficulty: 2,
  },
  {
    questionKey: 'english-pep-7-0-17',
    type: 'short_answer',
    questionText: '用英语回答：在中英文名字中，first name 和 last name 的含义分别是什么？中国人的名字和英文名字的顺序有什么不同？',
    answer: 'first name = 名（given name），last name = 姓（family name）。英文名字顺序是 first name + last name（名在前、姓在后）；中文名字顺序是姓在前、名在后。',
    explanation: '英语国家人名先名后姓，如 John Smith 中 John 是 first name，Smith 是 last name。中国人先姓后名，如 Li Ming 中 Li 是姓，Ming 是名。',
    difficulty: 3,
  },
  // ---- matching 2题 ----
  {
    questionKey: 'english-pep-7-0-18',
    type: 'matching',
    questionText: '请将左栏的英语问候语与右栏的恰当回答配对。',
    answer: '1-C, 2-D, 3-A, 4-B',
    explanation: '1. Hello! → Hi!  2. Good morning! → Good morning!  3. How are you? → I\'m fine, thanks.  4. Nice to meet you. → Nice to meet you, too.',
    difficulty: 1,
    pairs: '[{"left":"1. Hello!","right":"A. I\'m fine, thanks."},{"left":"2. Good morning!","right":"B. Nice to meet you, too."},{"left":"3. How are you?","right":"C. Hi!"},{"left":"4. Nice to meet you.","right":"D. Good morning!"}]',
  },
  {
    questionKey: 'english-pep-7-0-19',
    type: 'matching',
    questionText: '请将左栏的代词与右栏对应的中文含义配对。',
    answer: '1-B, 2-A, 3-D, 4-C',
    explanation: 'I（我）、my（我的）、he（他）、his（他的）是本单元核心代词。',
    difficulty: 2,
    pairs: '[{"left":"1. I","right":"A. 我的"},{"left":"2. my","right":"B. 我"},{"left":"3. he","right":"C. 他的"},{"left":"4. his","right":"D. 他"}]',
  },
];

// ========== 7-1 This is my sister (22题) =========
// 知识点：家庭成员、指示代词this/that/these/those、名词复数、所有格's

const chapter7_1: RawQuestion[] = [
  // ---- choice 9题 ----
  {
    questionKey: 'english-pep-7-1-0',
    type: 'choice',
    questionText: 'This ___ my mother. That ___ my father.',
    answer: 'B',
    explanation: 'This 和 That 都是第三人称单数，be 动词用 is。',
    difficulty: 1,
    options: '["A. are; are", "B. is; is", "C. is; are", "D. are; is"]',
  },
  {
    questionKey: 'english-pep-7-1-1',
    type: 'choice',
    questionText: '___ are my brothers, Tom and Jack.',
    answer: 'A',
    explanation: 'brothers 是复数名词，指示代词用 These。',
    difficulty: 1,
    options: '["A. These", "B. This", "C. That", "D. It"]',
  },
  {
    questionKey: 'english-pep-7-1-2',
    type: 'choice',
    questionText: '—Who is she? —She is my ___.',
    answer: 'C',
    explanation: '根据 she 可知是女性家庭成员，sister（姐姐/妹妹）符合。',
    difficulty: 1,
    options: '["A. father", "B. brother", "C. sister", "D. grandfather"]',
  },
  {
    questionKey: 'english-pep-7-1-3',
    type: 'choice',
    questionText: 'Here is a photo ___ my family.',
    answer: 'D',
    explanation: '"a photo of..."表示"……的一张照片"，of 表示所属关系。',
    difficulty: 1,
    options: '["A. at", "B. in", "C. on", "D. of"]',
  },
  {
    questionKey: 'english-pep-7-1-4',
    type: 'choice',
    questionText: 'Those are my ___.',
    answer: 'B',
    explanation: 'Those 是复数指示代词，后面跟复数名词。friend 的复数形式是 friends。',
    difficulty: 2,
    options: '["A. friend", "B. friends", "C. a friend", "D. friendes"]',
  },
  {
    questionKey: 'english-pep-7-1-5',
    type: 'choice',
    questionText: '—Is that your aunt? —___.',
    answer: 'C',
    explanation: '问句用 that，回答用 it 替代。肯定回答 Yes, it is.，否定回答 No, it isn\'t.。此处为肯定回答。',
    difficulty: 2,
    options: '["A. Yes, that is.", "B. Yes, he is.", "C. Yes, it is.", "D. Yes, she is."]',
  },
  {
    questionKey: 'english-pep-7-1-6',
    type: 'choice',
    questionText: 'My mother\'s mother is my ___.',
    answer: 'A',
    explanation: '妈妈的妈妈就是 grandmother（祖母/外祖母）。',
    difficulty: 1,
    options: '["A. grandmother", "B. grandfather", "C. aunt", "D. sister"]',
  },
  {
    questionKey: 'english-pep-7-1-7',
    type: 'choice',
    questionText: 'Have a good day! —___.',
    answer: 'D',
    explanation: '"Have a good day!"意为"祝你今天过得愉快！"，回答常用 "Thanks! You, too." 或 "Thank you."。',
    difficulty: 2,
    options: '["A. I\'m fine.", "B. How are you?", "C. Hello.", "D. Thanks! You, too."]',
  },
  {
    questionKey: 'english-pep-7-1-8',
    type: 'choice',
    questionText: '—Who ___ those girls? —They ___ my cousins.',
    answer: 'B',
    explanation: 'girls 是复数，who 引导的疑问句中 be 动词用 are；回答中 They 后也用 are。',
    difficulty: 2,
    options: '["A. is; is", "B. are; are", "C. is; are", "D. are; is"]',
  },
  // ---- fill 7题 ----
  {
    questionKey: 'english-pep-7-1-9',
    type: 'fill',
    questionText: 'This is my ___ (father) brother. He is my uncle.',
    answer: 'father\'s',
    explanation: "这里需要表示"父亲的"，用名词所有格 father's。",
    difficulty: 2,
    acceptableAnswers: '["father\'s", "Father\'s"]',
  },
  {
    questionKey: 'english-pep-7-1-10',
    type: 'fill',
    questionText: 'Those ___ (be) my parents.',
    answer: 'are',
    explanation: 'Those 后接复数名词 parents，be 动词用 are。',
    difficulty: 1,
    acceptableAnswers: '["are", "Are"]',
  },
  {
    questionKey: 'english-pep-7-1-11',
    type: 'fill',
    questionText: '___ (this) are my grandparents.',
    answer: 'These',
    explanation: "后面是复数 grandparents，指示代词用 These。",
    difficulty: 1,
    acceptableAnswers: '["These", "these"]',
  },
  {
    questionKey: 'english-pep-7-1-12',
    type: 'fill',
    questionText: 'My ___ (parent) are teachers.',
    answer: 'parents',
    explanation: 'parent 的复数形式是 parents（把 f/fe 变为 ves 的规则不适用于 parent，直接加 s）。',
    difficulty: 1,
    acceptableAnswers: '["parents", "Parents"]',
  },
  {
    questionKey: 'english-pep-7-1-13',
    type: 'fill',
    questionText: '—Is ___ (that) your sister? —Yes, ___ (her) is.',
    answer: 'that; she',
    explanation: "问句用 that 提问远处的人；回答中用 she 作主语代替 your sister。",
    difficulty: 2,
    acceptableAnswers: '["that; she", "That; she", "that; She"]',
  },
  {
    questionKey: 'english-pep-7-1-14',
    type: 'fill',
    questionText: 'Here are two ___ (photo) of my family.',
    answer: 'photos',
    explanation: 'photo 的复数形式是 photos（以 o 结尾，有生命加 es，但 photo 是例外，直接加 s）。',
    difficulty: 3,
    acceptableAnswers: '["photos", "Photos"]',
  },
  {
    questionKey: 'english-pep-7-1-15',
    type: 'fill',
    questionText: 'My uncle\'s daughter is my ___.',
    answer: 'cousin',
    explanation: '叔叔/舅舅的女儿是 cousin（堂/表姐妹）。',
    difficulty: 2,
    acceptableAnswers: '["cousin", "Cousin"]',
  },
  // ---- short_answer 4题 ----
  {
    questionKey: 'english-pep-7-1-16',
    type: 'short_answer',
    questionText: '请写出五个家庭成员的英语单词。',
    answer: 'father, mother, brother, sister, grandfather, grandmother, uncle, aunt, cousin 等（任选五个）',
    explanation: '家庭成员词汇：father（父亲）、mother（母亲）、brother（兄弟）、sister（姐妹）、grandfather（祖父/外祖父）、grandmother（祖母/外祖母）、uncle（叔/舅/伯）等。',
    difficulty: 1,
  },
  {
    questionKey: 'english-pep-7-1-17',
    type: 'short_answer',
    questionText: '请用英语介绍你的家庭（至少3句话）。
提示：你可以介绍家庭成员的数量和他们的身份。',
    answer: 'There are three people in my family. They are my father, my mother and me. My father is a teacher. My mother is a doctor. I love my family.（示例答案）',
    explanation: '介绍家庭时可以用 There be 句型说明人数，然后用 This/That is... 介绍每位成员。',
    difficulty: 2,
  },
  {
    questionKey: 'english-pep-7-1-18',
    type: 'short_answer',
    questionText: '将下列句子变为复数句：This is my friend.',
    answer: 'These are my friends.',
    explanation: '单数变复数：this → these, is → are, friend → friends, my 不变。',
    difficulty: 2,
  },
  {
    questionKey: 'english-pep-7-1-19',
    type: 'short_answer',
    questionText: '用英语写出家庭树（family tree）中从你往上三代的亲属关系。
例如：father\'s father = grandfather',
    answer: 'father\'s father = grandfather, father\'s mother = grandmother, mother\'s father = grandfather, mother\'s mother = grandmother, father\'s brother = uncle, mother\'s sister = aunt',
    explanation: '家庭树中，上一代是 parents（父母），上二代是 grandparents（祖父母/外祖父母），父母的兄弟是 uncle，父母的姐妹是 aunt。',
    difficulty: 3,
  },
  // ---- matching 2题 ----
  {
    questionKey: 'english-pep-7-1-20',
    type: 'matching',
    questionText: '请将左栏的英文单词与右栏的中文意思配对。',
    answer: '1-D, 2-B, 3-A, 4-C',
    explanation: 'grandfather 祖父, cousin 堂/表兄弟姐妹, daughter 女儿, uncle 叔/舅。',
    difficulty: 1,
    pairs: '[{"left":"1. grandfather","right":"A. 女儿"},{"left":"2. cousin","right":"B. 堂（表）兄弟姐妹"},{"left":"3. daughter","right":"C. 叔/舅/伯"},{"left":"4. uncle","right":"D. 祖父（外祖父）"}]',
  },
  {
    questionKey: 'english-pep-7-1-21',
    type: 'matching',
    questionText: '请将左栏的单数指示代词与右栏对应的复数形式配对。',
    answer: '1-B, 2-A, 3-D, 4-C',
    explanation: 'this → these, that → those, he → they, she → they。',
    difficulty: 2,
    pairs: '[{"left":"1. this","right":"A. those"},{"left":"2. that","right":"B. these"},{"left":"3. he","right":"C. them"},{"left":"4. she","right":"D. they"}]',
  },
];

// ========== 7-2 Is there a post office near here? (25题) =========
// 知识点：there be 句型、方位介词、问路指路、祈使句

const chapter7_2: RawQuestion[] = [
  // ---- choice 10题 ----
  {
    questionKey: 'english-pep-7-2-0',
    type: 'choice',
    questionText: '—Is there a bank near here? —___.',
    answer: 'A',
    explanation: "There be 句型的一般疑问句，肯定回答 Yes, there is.，否定回答 No, there isn't.。",
    difficulty: 1,
    options: '["A. Yes, there is.", "B. Yes, it is.", "C. Yes, there are.", "D. Yes, they are."]',
  },
  {
    questionKey: 'english-pep-7-2-1',
    type: 'choice',
    questionText: 'The park is ___ the library and the hospital.',
    answer: 'B',
    explanation: 'between...and... 表示"在……和……之间"。',
    difficulty: 1,
    options: '["A. in", "B. between", "C. next", "D. across"]',
  },
  {
    questionKey: 'english-pep-7-2-2',
    type: 'choice',
    questionText: 'There ___ a book and two pens on the desk.',
    answer: 'C',
    explanation: "There be 句型遵循"就近原则"，be 动词的形式由紧挨着它的名词决定。a book 是单数，所以用 is。",
    difficulty: 2,
    options: '["A. are", "B. have", "C. is", "D. has"]',
  },
  {
    questionKey: 'english-pep-7-2-3',
    type: 'choice',
    questionText: '—Where is the post office? —It\'s ___ Bridge Street.',
    answer: 'D',
    explanation: 'on 表示"在（街道）上"，是表示街道方位的固定介词。',
    difficulty: 1,
    options: '["A. in", "B. at", "C. to", "D. on"]',
  },
  {
    questionKey: 'english-pep-7-2-4',
    type: 'choice',
    questionText: '___ left at the first crossing and you\'ll see the school.',
    answer: 'A',
    explanation: '"Turn left"表示"左转"，是祈使句用法。',
    difficulty: 1,
    options: '["A. Turn", "B. Take", "C. Go", "D. Walk"]',
  },
  {
    questionKey: 'english-pep-7-2-5',
    type: 'choice',
    questionText: 'The hotel is ___ from the bank.',
    answer: 'B',
    explanation: 'be across from 表示"在……的对面"。',
    difficulty: 2,
    options: '["A. cross", "B. across", "C. crossing", "D. crossed"]',
  },
  {
    questionKey: 'english-pep-7-2-6',
    type: 'choice',
    questionText: '—How can I get to the hospital? —Go along this street and ___ right.',
    answer: 'D',
    explanation: '"turn right"表示"右转"，与"turn left"（左转）对应。',
    difficulty: 1,
    options: '["A. take", "B. make", "C. walk", "D. turn"]',
  },
  {
    questionKey: 'english-pep-7-2-7',
    type: 'choice',
    questionText: 'There ___ some milk in the glass.',
    answer: 'A',
    explanation: 'milk 是不可数名词，there be 句型中用 is。',
    difficulty: 2,
    options: '["A. is", "B. are", "C. has", "D. have"]',
  },
  {
    questionKey: 'english-pep-7-2-8',
    type: 'choice',
    questionText: 'The supermarket is ___ the neighborhood.',
    answer: 'C',
    explanation: 'in the neighborhood 表示"在附近/在街区里"。',
    difficulty: 1,
    options: '["A. on", "B. at", "C. in", "D. to"]',
  },
  {
    questionKey: 'english-pep-7-2-9',
    type: 'choice',
    questionText: 'I enjoy ___ (read) books in the library.',
    answer: 'B',
    explanation: 'enjoy 后接动名词（doing）作宾语，enjoy doing sth. 表示"喜欢做某事"。',
    difficulty: 2,
    options: '["A. read", "B. reading", "C. to read", "D. reads"]',
  },
  // ---- fill 8题 ----
  {
    questionKey: 'english-pep-7-2-10',
    type: 'fill',
    questionText: 'There ___ (be) a restaurant near my home.',
    answer: 'is',
    explanation: 'a restaurant 是单数，there be 句型中用 is。',
    difficulty: 1,
    acceptableAnswers: '["is", "Is"]',
  },
  {
    questionKey: 'english-pep-7-2-11',
    type: 'fill',
    questionText: 'The pay phone is ___ (在……对面) the library.',
    answer: 'across from',
    explanation: 'across from 意为"在……的对面"。',
    difficulty: 1,
    acceptableAnswers: '["across from", "across from the"]',
  },
  {
    questionKey: 'english-pep-7-2-12',
    type: 'fill',
    questionText: 'Go ___ (along) Center Street and turn left.',
    answer: 'along',
    explanation: 'go along 意为"沿着……走"。',
    difficulty: 1,
    acceptableAnswers: '["along", "Along", "down", "Down"]',
  },
  {
    questionKey: 'english-pep-7-2-13',
    type: 'fill',
    questionText: 'The park is ___ (在……后面) the school.',
    answer: 'behind',
    explanation: 'behind 意为"在……后面"。',
    difficulty: 1,
    acceptableAnswers: '["behind", "Behind"]',
  },
  {
    questionKey: 'english-pep-7-2-14',
    type: 'fill',
    questionText: 'There ___ (be) two supermarkets and a bank on this street.',
    answer: 'are',
    explanation: "There be 句型就近原则，紧挨着 be 的是 two supermarkets（复数），用 are。",
    difficulty: 2,
    acceptableAnswers: '["are", "Are"]',
  },
  {
    questionKey: 'english-pep-7-2-15',
    type: 'fill',
    questionText: '___ (turn) right at the second crossing.',
    answer: 'Turn',
    explanation: '祈使句以动词原形开头，Turn right 表示"右转"。',
    difficulty: 2,
    acceptableAnswers: '["Turn", "turn"]',
  },
  {
    questionKey: 'english-pep-7-2-16',
    type: 'fill',
    questionText: 'I spend much time ___ (play) basketball after school.',
    answer: 'playing',
    explanation: 'spend time doing sth. 是固定搭配，表示"花时间做某事"。',
    difficulty: 3,
    acceptableAnswers: '["playing", "Playing"]',
  },
  {
    questionKey: 'english-pep-7-2-17',
    type: 'fill',
    questionText: 'To get there, you just need ___ (walk) along the road.',
    answer: 'to walk',
    explanation: 'need to do sth. 表示"需要做某事"，to 后接动词原形。',
    difficulty: 3,
    acceptableAnswers: '["to walk", "To walk"]',
  },
  // ---- short_answer 5题 ----
  {
    questionKey: 'english-pep-7-2-18',
    type: 'short_answer',
    questionText: '请写出三个表示方位的介词短语。',
    answer: 'next to（在……旁边）、across from（在……对面）、behind（在……后面）、in front of（在……前面）、between...and...（在……和……之间）等（任选三个）',
    explanation: '本单元学习的方位介词有 next to, across from, behind, in front of, between...and..., on, near 等。',
    difficulty: 1,
  },
  {
    questionKey: 'english-pep-7-2-19',
    type: 'short_answer',
    questionText: '请用英语描述从你家到学校怎么走（至少3句话）。
提示：使用 turn left/right, go along 等短语。',
    answer: 'Go along Center Street and turn left at the first crossing. Then go straight and you will see the school on your right. It\'s next to the library.（示例答案）',
    explanation: '指路常用句型：Go along... and turn left/right at...; Go straight; It\'s on your left/right; It\'s next to/across from...。',
    difficulty: 2,
  },
  {
    questionKey: 'english-pep-7-2-20',
    type: 'short_answer',
    questionText: '将下列句子改为否定句：There is a post office near here.',
    answer: 'There isn\'t a post office near here. / There is no post office near here.',
    explanation: 'There be 句型的否定形式是在 be 后加 not，即 There isn\'t...；也可以用 There is no...。',
    difficulty: 2,
  },
  {
    questionKey: 'english-pep-7-2-21',
    type: 'short_answer',
    questionText: '请用 there be 句型描述你的学校附近有哪些场所（至少写3个场所）。',
    answer: 'There is a library near my school. There are two supermarkets across from the school. There is a park behind the school.（示例答案）',
    explanation: '使用 There is/are... 描述某处有某物，注意 is 用于单数/不可数名词，are 用于复数名词。',
    difficulty: 2,
  },
  {
    questionKey: 'english-pep-7-2-22',
    type: 'short_answer',
    questionText: '请将下面的中文翻译成英语：邮局在图书馆和银行之间。',
    answer: 'The post office is between the library and the bank.',
    explanation: 'between...and... 表示"在……和……之间"，注意 the post office 用单数 is。',
    difficulty: 3,
  },
  // ---- matching 2题 ----
  {
    questionKey: 'english-pep-7-2-23',
    type: 'matching',
    questionText: '请将左栏的场所名称与右栏的中文意思配对。',
    answer: '1-D, 2-A, 3-C, 4-B',
    explanation: 'post office 邮局, hospital 医院, restaurant 餐厅, supermarket 超市。',
    difficulty: 1,
    pairs: '[{"left":"1. post office","right":"A. 医院"},{"left":"2. hospital","right":"B. 超市"},{"left":"3. restaurant","right":"C. 餐厅"},{"left":"4. supermarket","right":"D. 邮局"}]',
  },
  {
    questionKey: 'english-pep-7-2-24',
    type: 'matching',
    questionText: '请将左栏的指路用语与右栏对应的中文意思配对。',
    answer: '1-B, 2-D, 3-A, 4-C',
    explanation: 'turn left 左转, go straight 直走, across from 在……对面, next to 在……旁边。',
    difficulty: 2,
    pairs: '[{"left":"1. turn left","right":"A. 在……对面"},{"left":"2. go straight","right":"B. 左转"},{"left":"3. across from","right":"C. 在……旁边"},{"left":"4. next to","right":"D. 直走"}]',
  },
];

// ========== 7-3 I'm watching TV (24题) =========
// 知识点：现在进行时 (be + doing)、日常活动词汇、what引导的特殊疑问句

const chapter7_3: RawQuestion[] = [
  // ---- choice 10题 ----
  {
    questionKey: 'english-pep-7-3-0',
    type: 'choice',
    questionText: '—What are you doing? —I ___ TV.',
    answer: 'A',
    explanation: '现在进行时由"be动词 + 动词-ing"构成，主语 I 用 am，watch 变为 watching。',
    difficulty: 1,
    options: '["A. am watching", "B. watch", "C. watches", "D. watched"]',
  },
  {
    questionKey: 'english-pep-7-3-1',
    type: 'choice',
    questionText: 'Listen! Someone ___ in the next room.',
    answer: 'B',
    explanation: 'Listen! 提示正在发生的事情，用现在进行时。Someone 是第三人称单数，用 is singing。',
    difficulty: 1,
    options: '["A. sings", "B. is singing", "C. sing", "D. sang"]',
  },
  {
    questionKey: 'english-pep-7-3-2',
    type: 'choice',
    questionText: 'They ___ basketball now.',
    answer: 'C',
    explanation: 'now 提示用现在进行时，They 用 are，play 变为 playing。',
    difficulty: 1,
    options: '["A. play", "B. plays", "C. are playing", "D. is playing"]',
  },
  {
    questionKey: 'english-pep-7-3-3',
    type: 'choice',
    questionText: '—___ he ___ his homework? —Yes, he is.',
    answer: 'D',
    explanation: '现在进行时的疑问句把 be 动词提前：Is he doing his homework?',
    difficulty: 1,
    options: '["A. Do; do", "B. Does; do", "C. Is; does", "D. Is; doing"]',
  },
  {
    questionKey: 'english-pep-7-3-4',
    type: 'choice',
    questionText: 'My mother ___ dinner in the kitchen.',
    answer: 'B',
    explanation: 'My mother 是第三人称单数，现在进行时用 is cooking。',
    difficulty: 2,
    options: '["A. cooks", "B. is cooking", "C. cook", "D. are cooking"]',
  },
  {
    questionKey: 'english-pep-7-3-5',
    type: 'choice',
    questionText: 'Look! The children ___ in the park.',
    answer: 'A',
    explanation: 'Look! 提示正在进行的动作，用现在进行时。children 是复数，用 are playing。',
    difficulty: 1,
    options: '["A. are playing", "B. play", "C. plays", "D. is playing"]',
  },
  {
    questionKey: 'english-pep-7-3-6',
    type: 'choice',
    questionText: '—Where is Tom? —He ___ computer games in his room.',
    answer: 'C',
    explanation: '根据语境"Tom 在哪里"，回答他正在做的事，用现在进行时 is playing。',
    difficulty: 2,
    options: '["A. plays", "B. play", "C. is playing", "D. played"]',
  },
  {
    questionKey: 'english-pep-7-3-7',
    type: 'choice',
    questionText: 'I\'m ___ (write) a letter to my pen pal.',
    answer: 'B',
    explanation: '现在进行时中 write 变为 writing（去 e 加 ing）。',
    difficulty: 1,
    options: '["A. writeing", "B. writing", "C. writes", "D. wrote"]',
  },
  {
    questionKey: 'english-pep-7-3-8',
    type: 'choice',
    questionText: 'She ___ to music at the moment.',
    answer: 'D',
    explanation: 'at the moment 表示"此刻"，用现在进行时。is listening。',
    difficulty: 2,
    options: '["A. listen", "B. listens", "C. listened", "D. is listening"]',
  },
  {
    questionKey: 'english-pep-7-3-9',
    type: 'choice',
    questionText: '—Let\'s go to the movies. —That sounds ___. But I\'m ___ my homework now.',
    answer: 'A',
    explanation: "That sounds good 表示"听起来不错"；now 提示正在进行，用 doing 形式。",
    difficulty: 3,
    options: '["A. good; doing", "B. well; doing", "C. good; do", "D. well; do"]',
  },
  // ---- fill 7题 ----
  {
    questionKey: 'english-pep-7-3-10',
    type: 'fill',
    questionText: 'My father ___ (read) a newspaper now.',
    answer: 'is reading',
    explanation: 'now 提示用现在进行时，My father 是第三人称单数，用 is reading。',
    difficulty: 1,
    acceptableAnswers: '["is reading", "Is reading"]',
  },
  {
    questionKey: 'english-pep-7-3-11',
    type: 'fill',
    questionText: '—What ___ your parents ___ (do)? —They ___ (clean) the house.',
    answer: 'are; doing; are cleaning',
    explanation: 'your parents 是复数，用 are doing 提问；回答也用 are cleaning。',
    difficulty: 1,
    acceptableAnswers: '["are; doing; are cleaning", "Are; doing; are cleaning"]',
  },
  {
    questionKey: 'english-pep-7-3-12',
    type: 'fill',
    questionText: 'Be quiet! The baby ___ (sleep).',
    answer: 'is sleeping',
    explanation: 'Be quiet!（安静！）提示正在进行，baby 是第三人称单数，用 is sleeping。',
    difficulty: 1,
    acceptableAnswers: '["is sleeping", "Is sleeping"]',
  },
  {
    questionKey: 'english-pep-7-3-13',
    type: 'fill',
    questionText: 'Tom ___ (not watch) TV right now. He ___ (study) for the test.',
    answer: 'is not watching; is studying',
    explanation: 'right now 提示现在进行时，否定形式是 is not watching（或 isn\'t watching）；第二句也是现在进行时 is studying。',
    difficulty: 2,
    acceptableAnswers: '["is not watching; is studying", "isn\'t watching; is studying", "is not watching; Is studying"]',
  },
  {
    questionKey: 'english-pep-7-3-14',
    type: 'fill',
    questionText: 'It\'s 8:00 p.m. My family and I ___ (have) dinner.',
    answer: 'are having',
    explanation: '语境表示此时此刻正在做某事，用现在进行时。My family and I 是复数，用 are having。',
    difficulty: 2,
    acceptableAnswers: '["are having", "Are having"]',
  },
  {
    questionKey: 'english-pep-7-3-15',
    type: 'fill',
    questionText: 'She ___ (run) in the park every morning, but today she ___ (swim) in the pool.',
    answer: 'runs; is swimming',
    explanation: 'every morning 用一般现在时 runs；today 语境下用现在进行时 is swimming，表示此刻正在做与平时不同的事。',
    difficulty: 3,
    acceptableAnswers: '["runs; is swimming", "Runs; is swimming"]',
  },
  {
    questionKey: 'english-pep-7-3-16',
    type: 'fill',
    questionText: 'Thank you for ___ (help) me with my English.',
    answer: 'helping',
    explanation: 'Thank you for doing sth. 是固定搭配，for 是介词，后接动名词。',
    difficulty: 2,
    acceptableAnswers: '["helping", "Helping"]',
  },
  // ---- short_answer 5题 ----
  {
    questionKey: 'english-pep-7-3-17',
    type: 'short_answer',
    questionText: '请写出五个表示日常活动的英语动词短语（用 v.-ing 形式）。',
    answer: 'watching TV, doing homework, reading a book, playing basketball, listening to music, cleaning the room, eating dinner 等（任选五个）',
    explanation: '本单元核心活动词汇：watch TV, do homework, read, play basketball, listen to music, clean, eat dinner 等。',
    difficulty: 1,
  },
  {
    questionKey: 'english-pep-7-3-18',
    type: 'short_answer',
    questionText: '请用现在进行时描述你一家人此刻正在做的事情（至少3句话）。',
    answer: 'It\'s 7:00 p.m. now. My father is reading a newspaper. My mother is cooking dinner. I am doing my homework.（示例答案）',
    explanation: '使用"主语 + is/am/are + doing"结构描述每个人正在做的事。',
    difficulty: 2,
  },
  {
    questionKey: 'english-pep-7-3-19',
    type: 'short_answer',
    questionText: '将下列句子改为现在进行时的否定句：They are playing soccer.',
    answer: 'They are not playing soccer. / They aren\'t playing soccer.',
    explanation: '现在进行时的否定形式是在 be 动词后加 not：are not → aren\'t。',
    difficulty: 2,
  },
  {
    questionKey: 'english-pep-7-3-20',
    type: 'short_answer',
    questionText: '请写出动词 write, swim, run, make 的现在分词（-ing）形式，并说明变化规则。',
    answer: 'writing（去 e 加 ing）、swimming（双写末尾辅音字母加 ing）、running（双写末尾辅音字母加 ing）、making（去 e 加 ing）。',
    explanation: '现在分词变化规则：①一般直接加 ing；②以不发音的 e 结尾，去 e 加 ing；③重读闭音节，双写末尾辅音字母加 ing。',
    difficulty: 3,
  },
  {
    questionKey: 'english-pep-7-3-21',
    type: 'short_answer',
    questionText: '将下列句子变成一般疑问句并作否定回答：She is washing the dishes.',
    answer: 'Is she washing the dishes? —No, she isn\'t. / —No, she is not.',
    explanation: '现在进行时的一般疑问句将 be 动词提到主语前：Is she washing...? 否定回答 No, she isn\'t.',
    difficulty: 2,
  },
  // ---- matching 2题 ----
  {
    questionKey: 'english-pep-7-3-22',
    type: 'matching',
    questionText: '请将左栏的活动图片描述与右栏对应的动词-ing形式配对。',
    answer: '1-C, 2-A, 3-D, 4-B',
    explanation: '在图书馆看书 → reading, 在厨房做饭 → cooking, 在操场上跑步 → running, 在客厅看电视 → watching TV。',
    difficulty: 1,
    pairs: '[{"left":"1. 在图书馆看书","right":"A. cooking"},{"left":"2. 在厨房做饭","right":"B. watching TV"},{"left":"3. 在操场上跑步","right":"C. reading"},{"left":"4. 在客厅看电视","right":"D. running"}]',
  },
  {
    questionKey: 'english-pep-7-3-23',
    type: 'matching',
    questionText: '请将左栏的句子与右栏正确的时态配对。',
    answer: '1-B, 2-A, 3-D, 4-C',
    explanation: 'every day → 一般现在时, Look! → 现在进行时, right now → 现在进行时, on weekends → 一般现在时。',
    difficulty: 2,
    pairs: '[{"left":"1. He plays soccer every day.","right":"A. 现在进行时"},{"left":"2. Look! He is playing soccer.","right":"B. 一般现在时"},{"left":"3. She is reading right now.","right":"C. 一般现在时"},{"left":"4. They go to school on weekends.","right":"D. 现在进行时"}]',
  },
];

// ========== 8-0 Where did you go on vacation? (22题) =========
// 知识点：一般过去时、不定代词（anyone/something/anything/nothing等）、复合形容词

const chapter8_0: RawQuestion[] = [
  // ---- choice 9题 ----
  {
    questionKey: 'english-pep-8-0-0',
    type: 'choice',
    questionText: '—Where ___ you go on vacation? —I went to Beijing.',
    answer: 'C',
    explanation: '问句和答语都用一般过去时，主语 you 搭配 did。',
    difficulty: 1,
    options: '["A. do", "B. are", "C. did", "D. were"]',
  },
  {
    questionKey: 'english-pep-8-0-1',
    type: 'choice',
    questionText: '—Did you go to the beach? —___. I went to the mountains.',
    answer: 'B',
    explanation: 'Did 开头的一般疑问句，否定回答是 No, I didn\'t.。',
    difficulty: 1,
    options: '["A. Yes, I did.", "B. No, I didn\'t.", "C. Yes, I do.", "D. No, I don\'t."]',
  },
  {
    questionKey: 'english-pep-8-0-2',
    type: 'choice',
    questionText: 'I didn\'t buy ___ in the store. Everything was too expensive.',
    answer: 'D',
    explanation: '否定句中用 anything 表示"任何东西"。nothing 也可但语义稍有不同，此处 anything 更强调"什么都没买"。',
    difficulty: 2,
    options: '["A. something", "B. everything", "C. nothing", "D. anything"]',
  },
  {
    questionKey: 'english-pep-8-0-3',
    type: 'choice',
    questionText: 'The food there was really ___. I liked it very much.',
    answer: 'A',
    explanation: '根据"I liked it very much"可知食物很好吃，用 delicious（美味的）。',
    difficulty: 1,
    options: '["A. delicious", "B. terrible", "C. boring", "D. expensive"]',
  },
  {
    questionKey: 'english-pep-8-0-4',
    type: 'choice',
    questionText: '—___ was the weather there? —It was sunny and hot.',
    answer: 'C',
    explanation: '对天气状况提问用 How。',
    difficulty: 1,
    options: '["A. What", "B. Where", "C. How", "D. When"]',
  },
  {
    questionKey: 'english-pep-8-0-5',
    type: 'choice',
    questionText: 'We had great fun ___ (play) in the water.',
    answer: 'B',
    explanation: 'have fun doing sth. 是固定搭配，意为"做某事很开心"。',
    difficulty: 2,
    options: '["A. play", "B. playing", "C. to play", "D. played"]',
  },
  {
    questionKey: 'english-pep-8-0-6',
    type: 'choice',
    questionText: 'I found a small girl ___ (cry) in the corner.',
    answer: 'A',
    explanation: 'find sb. doing sth. 表示"发现某人正在做某事"，cry 变为 crying。',
    difficulty: 2,
    options: '["A. crying", "B. cries", "C. cried", "D. to cry"]',
  },
  {
    questionKey: 'english-pep-8-0-7',
    type: 'choice',
    questionText: '—Did you go with ___? —Yes, I went with my family.',
    answer: 'C',
    explanation: '根据回答"我和家人一起去的"，问句是"你和谁一起去的？"，用 anyone（任何人）在疑问句中。',
    difficulty: 2,
    options: '["A. someone", "B. no one", "C. anyone", "D. everyone"]',
  },
  {
    questionKey: 'english-pep-8-0-8',
    type: 'choice',
    questionText: 'She ___ (not go) to school yesterday because she ___ (be) ill.',
    answer: 'D',
    explanation: 'yesterday 提示一般过去时，否定形式 didn\'t go；be 的过去式是 was（第三人称单数）。',
    difficulty: 2,
    options: '["A. doesn\'t go; is", "B. don\'t go; was", "C. not go; is", "D. didn\'t go; was"]',
  },
  // ---- fill 6题 ----
  {
    questionKey: 'english-pep-8-0-9',
    type: 'fill',
    questionText: 'I ___ (visit) my grandparents last weekend.',
    answer: 'visited',
    explanation: 'last weekend 提示一般过去时，visit 的过去式是 visited。',
    difficulty: 1,
    acceptableAnswers: '["visited", "Visited"]',
  },
  {
    questionKey: 'english-pep-8-0-10',
    type: 'fill',
    questionText: '___ you ___ (go) to the museum yesterday?',
    answer: 'Did; go',
    explanation: '一般过去时的一般疑问句用 Did 开头，后接动词原形 go。',
    difficulty: 1,
    acceptableAnswers: '["Did; go", "did; go"]',
  },
  {
    questionKey: 'english-pep-8-0-11',
    type: 'fill',
    questionText: 'We ___ (not do) anything special on vacation. We just ___ (stay) at home.',
    answer: 'didn\'t do; stayed',
    explanation: '一般过去时否定用 didn\'t + 动词原形；第二空 stayed 是 stay 的过去式。',
    difficulty: 2,
    acceptableAnswers: '["didn\'t do; stayed", "did not do; stayed"]',
  },
  {
    questionKey: 'english-pep-8-0-12',
    type: 'fill',
    questionText: 'Everyone ___ (be) tired after the long trip.',
    answer: 'was',
    explanation: 'everyone 作主语时谓语用第三人称单数形式，一般过去时中用 was。',
    difficulty: 2,
    acceptableAnswers: '["was", "Was"]',
  },
  {
    questionKey: 'english-pep-8-0-13',
    type: 'fill',
    questionText: 'There ___ (be) many people in the park yesterday.',
    answer: 'were',
    explanation: 'many people 是复数，一般过去时中 there be 用 were。',
    difficulty: 1,
    acceptableAnswers: '["were", "Were"]',
  },
  {
    questionKey: 'english-pep-8-0-14',
    type: 'fill',
    questionText: 'The trip was ___ (excite). We all had a good time.',
    answer: 'exciting',
    explanation: '修饰事物（trip）用 -ing 形容词 exciting（令人兴奋的）；修饰人用 -ed 形容词 excited（感到兴奋的）。',
    difficulty: 3,
    acceptableAnswers: '["exciting", "Exciting"]',
  },
  // ---- short_answer 5题 ----
  {
    questionKey: 'english-pep-8-0-15',
    type: 'short_answer',
    questionText: '请写出以下动词的过去式：go, eat, buy, take, see, have',
    answer: 'go → went, eat → ate, buy → bought, take → took, see → saw, have → had',
    explanation: '这些都是不规则动词的过去式，需要逐一记忆。',
    difficulty: 1,
  },
  {
    questionKey: 'english-pep-8-0-16',
    type: 'short_answer',
    questionText: '请用一般过去时写一段话描述你的上一个假期（至少4句话）。
提示：去了哪里？和谁一起？做了什么？感觉如何？',
    answer: 'Last summer vacation, I went to Shanghai with my family. We visited the Oriental Pearl Tower and ate delicious food. The weather was hot but we had a great time. I hope to go there again.（示例答案）',
    explanation: '描述过去的经历用一般过去时，注意动词过去式的正确使用。',
    difficulty: 2,
  },
  {
    questionKey: 'english-pep-8-0-17',
    type: 'short_answer',
    questionText: '请将下列句子改为一般过去时：I go to the beach every summer.',
    answer: 'I went to the beach last summer. / I went to the beach.',
    explanation: '一般现在时变为一般过去时：go → went，时间状语也要相应改变。',
    difficulty: 2,
  },
  {
    questionKey: 'english-pep-8-0-18',
    type: 'short_answer',
    questionText: '请将下面的中文翻译成英语：昨天的天气怎么样？——很晴朗。',
    answer: '—What was the weather like yesterday? / —How was the weather yesterday? —It was sunny.',
    explanation: '询问天气可用 What was the weather like? 或 How was the weather?，注意用一般过去时。',
    difficulty: 2,
  },
  {
    questionKey: 'english-pep-8-0-19',
    type: 'short_answer',
    questionText: '请说明 something, anything, nothing, everything 在肯定句、否定句和疑问句中的使用规则，并各造一个句子。',
    answer: 'something 用于肯定句：I found something interesting. / anything 用于否定句和疑问句：I didn\'t do anything. Did you meet anyone? / nothing 用于表示"什么都没有"：There is nothing in the box. / everything 用于肯定句或疑问句：Everything is ready.',
    explanation: 'something 一般用于肯定句，anything 用于否定句和疑问句，nothing 本身含有否定意义，everything 用于肯定句或疑问句。但在表示请求、建议的疑问句中可用 something。',
    difficulty: 3,
  },
  // ---- matching 2题 ----
  {
    questionKey: 'english-pep-8-0-20',
    type: 'matching',
    questionText: '请将左栏的动词原形与右栏对应的过去式配对。',
    answer: '1-D, 2-A, 3-B, 4-C',
    explanation: 'go → went, buy → bought, see → saw, eat → ate。',
    difficulty: 1,
    pairs: '[{"left":"1. go","right":"A. bought"},{"left":"2. buy","right":"B. saw"},{"left":"3. see","right":"C. ate"},{"left":"4. eat","right":"D. went"}]',
  },
  {
    questionKey: 'english-pep-8-0-21',
    type: 'matching',
    questionText: '请将左栏的描述性形容词与右栏的中文含义配对。',
    answer: '1-B, 2-C, 3-A, 4-D',
    explanation: 'delicious 美味的, expensive 昂贵的, boring 无聊的, exciting 令人兴奋的。',
    difficulty: 2,
    pairs: '[{"left":"1. delicious","right":"A. 无聊的"},{"left":"2. expensive","right":"B. 美味的"},{"left":"3. boring","right":"C. 昂贵的"},{"left":"4. exciting","right":"D. 令人兴奋的"}]',
  },
];

// ========== 8-1 How often do you exercise? (20题) =========
// 知识点：频率副词、一般现在时、健康生活方式

const chapter8_1: RawQuestion[] = [
  // ---- choice 8题 ----
  {
    questionKey: 'english-pep-8-1-0',
    type: 'choice',
    questionText: '—How often do you exercise? —___.',
    answer: 'C',
    explanation: 'How often 询问频率，回答应使用频率副词或表示频率的短语。',
    difficulty: 1,
    options: '["A. Yes, I do.", "B. I like it.", "C. Twice a week.", "D. At 7:00."]',
  },
  {
    questionKey: 'english-pep-8-1-1',
    type: 'choice',
    questionText: 'My mother ___ shops. She ___ goes shopping.',
    answer: 'A',
    explanation: '根据后句"她几乎不购物"可知前句是"我妈妈不常购物"，用 hardly ever。',
    difficulty: 1,
    options: '["A. hardly ever", "B. always", "C. usually", "D. often"]',
  },
  {
    questionKey: 'english-pep-8-1-2',
    type: 'choice',
    questionText: '—What do you usually do ___ weekends? —I often read books.',
    answer: 'D',
    explanation: '"on weekends"表示"在周末"，是固定搭配。',
    difficulty: 1,
    options: '["A. in", "B. at", "C. for", "D. on"]',
  },
  {
    questionKey: 'english-pep-8-1-3',
    type: 'choice',
    questionText: '___ he ___ to school every day?',
    answer: 'B',
    explanation: 'every day 提示一般现在时，主语 he 是第三人称单数，用 Does...go?。',
    difficulty: 1,
    options: '["A. Do; go", "B. Does; go", "C. Does; goes", "D. Do; goes"]',
  },
  {
    questionKey: 'english-pep-8-1-4',
    type: 'choice',
    questionText: 'She ___ (help) with housework once a week.',
    answer: 'A',
    explanation: '主语 She 是第三人称单数，一般现在时动词加 s，helps。',
    difficulty: 2,
    options: '["A. helps", "B. help", "C. helping", "D. helped"]',
  },
  {
    questionKey: 'english-pep-8-1-5',
    type: 'choice',
    questionText: 'Eating junk food is bad ___ your health.',
    answer: 'C',
    explanation: 'be bad for... 表示"对……有害/不好"，是固定搭配。',
    difficulty: 2,
    options: '["A. at", "B. in", "C. for", "D. with"]',
  },
  {
    questionKey: 'english-pep-8-1-6',
    type: 'choice',
    questionText: 'I try ___ (eat) a lot of vegetables.',
    answer: 'D',
    explanation: 'try to do sth. 表示"尽力做某事"，to 后接动词原形 eat。',
    difficulty: 2,
    options: '["A. eating", "B. eat", "C. ate", "D. to eat"]',
  },
  {
    questionKey: 'english-pep-8-1-7',
    type: 'choice',
    questionText: 'Tom is good ___ playing basketball. He plays it every day.',
    answer: 'B',
    explanation: 'be good at... 表示"擅长做某事"，at 是介词，后接动名词。',
    difficulty: 2,
    options: '["A. for", "B. at", "C. in", "D. with"]',
  },
  // ---- fill 6题 ----
  {
    questionKey: 'english-pep-8-1-8',
    type: 'fill',
    questionText: 'He ___ (hardly ever) goes to the cinema. He ___ (usual) stays at home.',
    answer: 'hardly ever; usually',
    explanation: 'hardly ever 意为"几乎不"，usually 意为"通常"，都是频率副词，放在 be 动词之后、实义动词之前。',
    difficulty: 1,
    acceptableAnswers: '["hardly ever; usually", "Hardly ever; usually"]',
  },
  {
    questionKey: 'english-pep-8-1-9',
    type: 'fill',
    questionText: 'My sister ___ (not like) drinking milk. She ___ (drink) coffee.',
    answer: "doesn't like; drinks",
    explanation: '主语 My sister 是第三人称单数，否定用 doesn\'t like；肯定句动词加 s。',
    difficulty: 1,
    acceptableAnswers: '["doesn\'t like; drinks", "does not like; drinks"]',
  },
  {
    questionKey: 'english-pep-8-1-10',
    type: 'fill',
    questionText: '___ (多少小时) do you sleep every night?',
    answer: 'How many hours',
    explanation: '对可数名词 hours 提问用 How many。',
    difficulty: 1,
    acceptableAnswers: '["How many hours", "how many hours"]',
  },
  {
    questionKey: 'english-pep-8-1-11',
    type: 'fill',
    questionText: 'It is important ___ (learn) English well.',
    answer: 'to learn',
    explanation: 'It is important to do sth. 是固定句型，it 是形式主语，to learn 是真正的主语。',
    difficulty: 2,
    acceptableAnswers: '["to learn", "To learn"]',
  },
  {
    questionKey: 'english-pep-8-1-12',
    type: 'fill',
    questionText: 'Exercising is good ___ our ___.',
    answer: 'for; health',
    explanation: 'be good for... 表示"对……有益"，health 意为"健康"。',
    difficulty: 2,
    acceptableAnswers: '["for; health", "for; Health"]',
  },
  {
    questionKey: 'english-pep-8-1-13',
    type: 'fill',
    questionText: 'The results ___ (show) that most students exercise three ___ (time) a week.',
    answer: 'show; times',
    explanation: 'The results 是复数主语，用 show；three times a week 表示"一周三次"，time 此处意为"次数"。',
    difficulty: 3,
    acceptableAnswers: '["show; times", "Show; times"]',
  },
  // ---- short_answer 4题 ----
  {
    questionKey: 'english-pep-8-1-14',
    type: 'short_answer',
    questionText: '请按频率从高到低排列以下频率副词：always, sometimes, hardly ever, usually, often, never',
    answer: 'always（总是）> usually（通常）> often（经常）> sometimes（有时）> hardly ever（几乎不）> never（从不）',
    explanation: '频率副词按频率从高到低：always (100%) > usually (80%) > often (60%) > sometimes (30%) > hardly ever (5%) > never (0%)。',
    difficulty: 1,
  },
  {
    questionKey: 'english-pep-8-1-15',
    type: 'short_answer',
    questionText: '请用英语描述你的日常健康习惯（至少4句话）。
提示：运动频率、饮食、睡眠等。',
    answer: 'I exercise every day. I usually run in the morning for 30 minutes. I eat vegetables every day and hardly ever eat junk food. I sleep about 8 hours every night.（示例答案）',
    explanation: '描述日常习惯用一般现在时，结合频率副词（always, usually, often, sometimes, hardly ever, never）表达频率。',
    difficulty: 2,
  },
  {
    questionKey: 'english-pep-8-1-16',
    type: 'short_answer',
    questionText: '请将下面的中文翻译成英语：你多久看一次电视？——我一周看两次电视。',
    answer: '—How often do you watch TV? —I watch TV twice a week.',
    explanation: 'How often 询问频率，回答用"次数 + a week/month/year"等结构。',
    difficulty: 2,
  },
  {
    questionKey: 'english-pep-8-1-17',
    type: 'short_answer',
    questionText: '请写出至少3条保持健康的建议（用英语），并使用 should 或 had better。',
    answer: 'You should exercise every day. You should eat more vegetables and fruit. You had better not eat too much junk food. You should get enough sleep.（示例答案）',
    explanation: 'should 表示"应该"，had better 表示"最好"，后接动词原形，常用于提出建议。',
    difficulty: 3,
  },
  // ---- matching 2题 ----
  {
    questionKey: 'english-pep-8-1-18',
    type: 'matching',
    questionText: '请将左栏的频率副词与右栏对应的频率百分比配对。',
    answer: '1-D, 2-B, 3-C, 4-A',
    explanation: 'always 约100%, usually 约80%, sometimes 约30%, never 0%。',
    difficulty: 1,
    pairs: '[{"left":"1. always","right":"A. 0%"},{"left":"2. usually","right":"B. 80%"},{"left":"3. sometimes","right":"C. 30%"},{"left":"4. never","right":"D. 100%"}]',
  },
  {
    questionKey: 'english-pep-8-1-19',
    type: 'matching',
    questionText: '请将左栏的活动与右栏对应的频率表达配对。',
    answer: '1-C, 2-A, 3-D, 4-B',
    explanation: '每三次, 每月一次, 每天两次, 一年三次。',
    difficulty: 2,
    pairs: '[{"left":"1. 刷牙","right":"A. once a month"},{"left":"2. 去电影院","right":"B. three times a year"},{"left":"3. 吃饭","right":"C. three times a day"},{"left":"4. 回老家","right":"D. twice a day"}]',
  },
];

// ========== 8-2 I'm more outgoing than my sister (26题) =========
// 知识点：形容词比较级、as...as 同级比较、both/neither/all/none

const chapter8_2: RawQuestion[] = [
  // ---- choice 10题 ----
  {
    questionKey: 'english-pep-8-2-0',
    type: 'choice',
    questionText: 'Tom is ___ than his brother.',
    answer: 'A',
    explanation: 'than 提示用比较级，outgoing 是多音节形容词，比较级前面加 more。',
    difficulty: 1,
    options: '["A. more outgoing", "B. outgoinger", "C. most outgoing", "D. the more outgoing"]',
  },
  {
    questionKey: 'english-pep-8-2-1',
    type: 'choice',
    questionText: 'She is ___ (tall) than me.',
    answer: 'B',
    explanation: 'tall 是单音节形容词，比较级直接加 -er：taller。',
    difficulty: 1,
    options: '["A. more tall", "B. taller", "C. tallest", "D. the taller"]',
  },
  {
    questionKey: 'english-pep-8-2-2',
    type: 'choice',
    questionText: 'My hair is longer than ___.',
    answer: 'C',
    explanation: '比较级中比较对象要对等，用名词性物主代词 hers（= her hair）。',
    difficulty: 2,
    options: '["A. she", "B. her", "C. hers", "D. she\'s"]',
  },
  {
    questionKey: 'english-pep-8-2-3',
    type: 'choice',
    questionText: 'Li Lei is ___ (good) at math than Wang Lin.',
    answer: 'D',
    explanation: 'good 是不规则形容词，比较级是 better，不是 gooder 或 more good。',
    difficulty: 2,
    options: '["A. more good", "B. gooder", "C. best", "D. better"]',
  },
  {
    questionKey: 'english-pep-8-2-4',
    type: 'choice',
    questionText: '—Is Tom ___ (funny) than Sam? —Yes, he is.',
    answer: 'A',
    explanation: 'funny 以辅音字母+y 结尾，变比较级时去 y 变 i 加 -er：funnier。',
    difficulty: 1,
    options: '["A. funnier", "B. more funny", "C. funnyer", "D. funniest"]',
  },
  {
    questionKey: 'english-pep-8-2-5',
    type: 'choice',
    questionText: 'Tina is as ___ (smart) as her sister.',
    answer: 'B',
    explanation: 'as...as 中间用形容词原级，不用比较级。',
    difficulty: 2,
    options: '["A. smarter", "B. smart", "C. smartest", "D. more smart"]',
  },
  {
    questionKey: 'english-pep-8-2-6',
    type: 'choice',
    questionText: 'This box is ___ (heavy) than that one. I can\'t carry it.',
    answer: 'C',
    explanation: 'heavy 以辅音字母+y 结尾，比较级去 y 变 i 加 -er：heavier。',
    difficulty: 2,
    options: '["A. more heavy", "B. heavyer", "C. heavier", "D. heaviest"]',
  },
  {
    questionKey: 'english-pep-8-2-7',
    type: 'choice',
    questionText: '___ Tom ___ Jack wants to go. They both like staying at home.',
    answer: 'A',
    explanation: '根据"They both like staying at home"可知两人都不想去，用 Neither...nor...。',
    difficulty: 3,
    options: '["A. Neither; nor", "B. Both; and", "C. Either; or", "D. Not only; but also"]',
  },
  {
    questionKey: 'english-pep-8-2-8',
    type: 'choice',
    questionText: 'The ___ (much) you read, the ___ (good) you will be.',
    answer: 'A',
    explanation: '"the + 比较级, the + 比较级"表示"越……越……"。much → more, good → better。',
    difficulty: 3,
    options: '["A. more; better", "B. most; best", "C. much; good", "D. more; gooder"]',
  },
  {
    questionKey: 'english-pep-8-2-9',
    type: 'choice',
    questionText: 'My sister is ___ (outgoing) than me, but I am ___ (hard-working) than her.',
    answer: 'A',
    explanation: 'outgoing 多音节，比较级加 more outgoing；hard-working 多音节加 more hard-working。',
    difficulty: 2,
    options: '["A. more outgoing; more hard-working", "B. outgoinger; more hard-working", "C. more outgoing; hard-workinger", "D. less outgoing; more hard-working"]',
  },
  // ---- fill 8题 ----
  {
    questionKey: 'english-pep-8-2-10',
    type: 'fill',
    questionText: 'She is ___ (quiet) than her sister.',
    answer: 'quieter',
    explanation: 'quiet 以不发音的 e 结尾，比较级直接加 -r：quieter。',
    difficulty: 1,
    acceptableAnswers: '["quieter", "Quieter"]',
  },
  {
    questionKey: 'english-pep-8-2-11',
    type: 'fill',
    questionText: 'Tom is ___ (athletic) than Sam. He runs faster.',
    answer: 'more athletic',
    explanation: 'athletic 是多音节形容词，比较级用 more athletic。',
    difficulty: 1,
    acceptableAnswers: '["more athletic", "More athletic"]',
  },
  {
    questionKey: 'english-pep-8-2-12',
    type: 'fill',
    questionText: 'My mother is as ___ (friend) as my teacher.',
    answer: 'friendly',
    explanation: 'as...as 之间用原级，friendly 的原级就是 friendly。',
    difficulty: 1,
    acceptableAnswers: '["friendly", "Friendly"]',
  },
  {
    questionKey: 'english-pep-8-2-13',
    type: 'fill',
    questionText: 'This book is ___ (interesting) than that one.',
    answer: 'more interesting',
    explanation: 'interesting 是多音节形容词，比较级用 more interesting。',
    difficulty: 2,
    acceptableAnswers: '["more interesting", "More interesting"]',
  },
  {
    questionKey: 'english-pep-8-2-14',
    type: 'fill',
    questionText: 'I am ___ (good) at English than my brother.',
    answer: 'better',
    explanation: 'good 的比较级是不规则的 better。',
    difficulty: 2,
    acceptableAnswers: '["better", "Better"]',
  },
  {
    questionKey: 'english-pep-8-2-15',
    type: 'fill',
    questionText: 'He is ___ (bad) at sports than me.',
    answer: 'worse',
    explanation: 'bad 的比较级是不规则的 worse。',
    difficulty: 2,
    acceptableAnswers: '["worse", "Worse"]',
  },
  {
    questionKey: 'english-pep-8-2-16',
    type: 'fill',
    questionText: 'She doesn\'t study as ___ (hard) as her classmates.',
    answer: 'hard',
    explanation: 'as...as 中间用形容词/副词原级，hard 的原级就是 hard。',
    difficulty: 2,
    acceptableAnswers: '["hard", "Hard"]',
  },
  {
    questionKey: 'english-pep-8-2-17',
    type: 'fill',
    questionText: '___ of the two boys is tall. They are both short.',
    answer: 'Neither',
    explanation: 'Neither of... 表示"两个都不"，后接复数名词或代词，但谓语用单数。',
    difficulty: 3,
    acceptableAnswers: '["Neither", "neither"]',
  },
  // ---- short_answer 6题 ----
  {
    questionKey: 'english-pep-8-2-18',
    type: 'short_answer',
    questionText: '请写出以下形容词的比较级：tall, short, long, heavy, big, hot, easy, funny',
    answer: 'tall → taller, short → shorter, long → longer, heavy → heavier, big → bigger, hot → hotter, easy → easier, funny → funnier',
    explanation: '比较级规则：一般加 -er；以 e 结尾加 -r；重读闭音节双写末尾辅音加 -er；辅音字母+y 结尾变 y 为 i 加 -er。',
    difficulty: 1,
  },
  {
    questionKey: 'english-pep-8-2-19',
    type: 'short_answer',
    questionText: '请比较你和你最好朋友的不同之处（至少4句话），使用比较级。
提示：外貌、性格、爱好等方面。',
    answer: 'My friend Tom is taller than me. I am more outgoing than him. He is better at math than I am, but I am better at English. He has shorter hair than me.（示例答案）',
    explanation: '比较两个人用"A + be + 比较级 + than + B"结构。',
    difficulty: 2,
  },
  {
    questionKey: 'english-pep-8-2-20',
    type: 'short_answer',
    questionText: '将下列句子改为同义句：Tom is 1.7 meters tall. Jack is 1.8 meters tall. (合并为一句)',
    answer: 'Jack is taller than Tom. / Tom is not as tall as Jack. / Tom is shorter than Jack.',
    explanation: '可以用比较级句型或 as...as 句型来表达相同的意思。',
    difficulty: 2,
  },
  {
    questionKey: 'english-pep-8-2-21',
    type: 'short_answer',
    questionText: '请写出 good, bad, many/much, little 四个不规则形容词/副词的比较级和最高级。',
    answer: 'good/well → better → best; bad/badly → worse → worst; many/much → more → most; little → less → least',
    explanation: '这四个是不规则变化的形容词/副词，其比较级和最高级需要特别记忆。',
    difficulty: 2,
  },
  {
    questionKey: 'english-pep-8-2-22',
    type: 'short_answer',
    questionText: '请将下面的中文翻译成英语：我妹妹和我一样高。',
    answer: 'My sister is as tall as me. / My sister is as tall as I am.',
    explanation: 'as...as 表示"和……一样"，中间用形容词/副词原级。',
    difficulty: 2,
  },
  {
    questionKey: 'english-pep-8-2-23',
    type: 'short_answer',
    questionText: '请用英语解释 "The more careful you are, the fewer mistakes you will make." 这句话的意思，并仿造一个类似的句子。',
    answer: '意思是：你越仔细，犯的错误就越少。仿写：The harder you study, the better grades you will get.（你越努力，成绩就越好。）',
    explanation: '"the + 比较级, the + 比较级" 是固定句型，表示"越……，越……"。',
    difficulty: 3,
  },
  // ---- matching 2题 ----
  {
    questionKey: 'english-pep-8-2-24',
    type: 'matching',
    questionText: '请将左栏的形容词原级与右栏对应的比较级配对。',
    answer: '1-C, 2-D, 3-A, 4-B',
    explanation: 'good → better, bad → worse, many → more, little → less。',
    difficulty: 1,
    pairs: '[{"left":"1. good","right":"A. more"},{"left":"2. bad","right":"B. less"},{"left":"3. many","right":"C. better"},{"left":"4. little","right":"D. worse"}]',
  },
  {
    questionKey: 'english-pep-8-2-25',
    type: 'matching',
    questionText: '请将左栏的描述性短语与右栏对应的含义配对。',
    answer: '1-B, 2-D, 3-A, 4-C',
    explanation: 'be similar to 与……相似, be different from 与……不同, be the same as 与……相同, be good at 擅长于。',
    difficulty: 2,
    pairs: '[{"left":"1. be similar to","right":"A. 与……相同"},{"left":"2. be different from","right":"B. 与……相似"},{"left":"3. be the same as","right":"C. 擅长于"},{"left":"4. be good at","right":"D. 与……不同"}]',
  },
];

// ========== 8-3 What's the best movie theater? (22题) =========
// 知识点：形容词最高级、选择与比较

const chapter8_3: RawQuestion[] = [
  // ---- choice 9题 ----
  {
    questionKey: 'english-pep-8-3-0',
    type: 'choice',
    questionText: 'This is ___ (good) movie I have ever seen.',
    answer: 'C',
    explanation: '"the + 最高级"表示"最……的"，good 的最高级是 best。',
    difficulty: 1,
    options: '["A. good", "B. better", "C. the best", "D. the better"]',
  },
  {
    questionKey: 'english-pep-8-3-1',
    type: 'choice',
    questionText: 'Town Cinema has ___ (comfortable) seats in town.',
    answer: 'A',
    explanation: 'comfortable 是多音节形容词，最高级用 the most comfortable。',
    difficulty: 1,
    options: '["A. the most comfortable", "B. the comfortablest", "C. most comfortable", "D. comfortablest"]',
  },
  {
    questionKey: 'english-pep-8-3-2',
    type: 'choice',
    questionText: 'Which is ___ (big), the sun, the moon or the earth?',
    answer: 'B',
    explanation: '三者比较用最高级，big 的最高级是 the biggest。',
    difficulty: 1,
    options: '["A. bigger", "B. the biggest", "C. biggest", "D. the bigger"]',
  },
  {
    questionKey: 'english-pep-8-3-3',
    type: 'choice',
    questionText: 'Screen City is ___ (popular) than Town Cinema.',
    answer: 'D',
    explanation: 'than 提示用比较级，popular 的比较级是 more popular。',
    difficulty: 1,
    options: '["A. popularer", "B. the most popular", "C. popularest", "D. more popular"]',
  },
  {
    questionKey: 'english-pep-8-3-4',
    type: 'choice',
    questionText: 'Of all the students, Tom is ___ (creative).',
    answer: 'A',
    explanation: '"Of all..."表示在所有之中，用最高级。creative 的最高级是 the most creative。',
    difficulty: 2,
    options: '["A. the most creative", "B. the creativest", "C. more creative", "D. creativest"]',
  },
  {
    questionKey: 'english-pep-8-3-5',
    type: 'choice',
    questionText: '—Who is ___ (thin), Lily or Lucy? —Lucy is.',
    answer: 'C',
    explanation: '两者之间比较用比较级，thin 的比较级是 thinner（双写 n 加 -er）。',
    difficulty: 2,
    options: '["A. the thinnest", "B. more thin", "C. thinner", "D. thinest"]',
  },
  {
    questionKey: 'english-pep-8-3-6',
    type: 'choice',
    questionText: 'You can buy clothes the ___ (cheap) in Dream Clothes.',
    answer: 'B',
    explanation: 'cheap 的最高级是 the cheapest。the + 最高级 表示"最……的"。',
    difficulty: 2,
    options: '["A. more cheap", "B. cheapest", "C. most cheap", "D. cheapper"]',
  },
  {
    questionKey: 'english-pep-8-3-7',
    type: 'choice',
    questionText: 'He is one of ___ (good) students in our class.',
    answer: 'D',
    explanation: 'one of + the + 最高级 + 复数名词，表示"最……之一"。',
    difficulty: 3,
    options: '["A. good", "B. better", "C. the better", "D. the best"]',
  },
  {
    questionKey: 'english-pep-8-3-8',
    type: 'choice',
    questionText: 'The movie is ___ (bore). I don\'t want to watch it.',
    answer: 'A',
    explanation: '修饰物用 -ing 形容词 boring（令人无聊的）。此处根据语境应选 boring。',
    difficulty: 2,
    options: '["A. boring", "B. bored", "C. bore", "D. boringly"]',
  },
  // ---- fill 6题 ----
  {
    questionKey: 'english-pep-8-3-9',
    type: 'fill',
    questionText: 'This is ___ (bad) movie of the year.',
    answer: 'the worst',
    explanation: 'bad 的最高级是 the worst，表示"最差的"。',
    difficulty: 1,
    acceptableAnswers: '["the worst", "The worst"]',
  },
  {
    questionKey: 'english-pep-8-3-10',
    type: 'fill',
    questionText: 'Module Town has ___ (friendly) service of all.',
    answer: 'the friendliest',
    explanation: 'friendly 以 y 结尾，最高级去 y 变 i 加 -est：the friendliest。',
    difficulty: 2,
    acceptableAnswers: '["the friendliest", "The friendliest", "the most friendly", "The most friendly"]',
  },
  {
    questionKey: 'english-pep-8-3-11',
    type: 'fill',
    questionText: 'It has ___ (big) screens and ___ (good) sound.',
    answer: 'the biggest; the best',
    explanation: 'big 的最高级是 the biggest（双写 g 加 -est），good 的最高级是 the best。',
    difficulty: 1,
    acceptableAnswers: '["the biggest; the best", "The biggest; the best"]',
  },
  {
    questionKey: 'english-pep-8-3-12',
    type: 'fill',
    questionText: 'Thank you for ___ (tell) me about the restaurants.',
    answer: 'telling',
    explanation: 'for 是介词，后接动名词 telling。',
    difficulty: 2,
    acceptableAnswers: '["telling", "Telling"]',
  },
  {
    questionKey: 'english-pep-8-3-13',
    type: 'fill',
    questionText: 'The restaurant is close ___ my home. I can ___ (easy) walk there.',
    answer: 'to; easily',
    explanation: 'be close to 表示"离……近"；修饰动词 walk 用副词 easily。',
    difficulty: 3,
    acceptableAnswers: '["to; easily", "to; Easily"]',
  },
  {
    questionKey: 'english-pep-8-3-14',
    type: 'fill',
    questionText: 'She chose the ___ (expensive) one because it had the ___ (good) quality.',
    answer: 'most expensive; best',
    explanation: 'expensive 是多音节，最高级 the most expensive；good 的最高级 the best。',
    difficulty: 3,
    acceptableAnswers: '["most expensive; best", "most expensive; Best"]',
  },
  // ---- short_answer 5题 ----
  {
    questionKey: 'english-pep-8-3-15',
    type: 'short_answer',
    questionText: '请写出以下形容词的最高级：tall, short, big, heavy, good, bad, popular, comfortable',
    answer: 'tall → tallest, short → shortest, big → biggest, heavy → heaviest, good → best, bad → worst, popular → most popular, comfortable → most comfortable',
    explanation: '单音节词加 -est；以 e 结尾加 -st；重读闭音节双写加 -est；辅音+y 变 i 加 -est；多音节前加 most；good/bad 为不规则变化。',
    difficulty: 1,
  },
  {
    questionKey: 'english-pep-8-3-16',
    type: 'short_answer',
    questionText: '请用英语比较你所在城市的三家电影院（至少4句话），使用最高级。
提示：从座位、屏幕、价格、服务等方面比较。',
    answer: 'There are three movie theaters in my city. Star Cinema has the biggest screens. Town Cinema has the most comfortable seats. Movie World is the cheapest. I think Town Cinema is the best because it has the friendliest service.（示例答案）',
    explanation: '三者或三者以上比较用最高级，结构为"the + 最高级 + of/in..."。',
    difficulty: 2,
  },
  {
    questionKey: 'english-pep-8-3-17',
    type: 'short_answer',
    questionText: '将下列句子改为同义句：No other student is taller than Tom in our class.',
    answer: 'Tom is the tallest student in our class.',
    explanation: '"No other + 名词 + 比较级 + than" 等同于"the + 最高级"。',
    difficulty: 2,
  },
  {
    questionKey: 'english-pep-8-3-18',
    type: 'short_answer',
    questionText: '请将下面的中文翻译成英语：这家餐厅是镇上最便宜的。',
    answer: 'This restaurant is the cheapest in town.',
    explanation: '最高级句式：主语 + is + the + 最高级 + in/of...。',
    difficulty: 2,
  },
  {
    questionKey: 'english-pep-8-3-19',
    type: 'short_answer',
    questionText: '请用 "one of the + 最高级 + 复数名词" 造两个句子。',
    answer: '1. The Great Wall is one of the most famous places in China. 2. She is one of the best students in our school.',
    explanation: 'one of the + 最高级 + 复数名词表示"最……的……之一"，注意后面的名词一定要用复数。',
    difficulty: 3,
  },
  // ---- matching 2题 ----
  {
    questionKey: 'english-pep-8-3-20',
    type: 'matching',
    questionText: '请将左栏的形容词原级与右栏对应的最高级配对。',
    answer: '1-D, 2-A, 3-C, 4-B',
    explanation: 'good → best, bad → worst, far → farthest/furthest, little → least。',
    difficulty: 1,
    pairs: '[{"left":"1. good","right":"A. worst"},{"left":"2. bad","right":"B. least"},{"left":"3. far","right":"C. farthest"},{"left":"4. little","right":"D. best"}]',
  },
  {
    questionKey: 'english-pep-8-3-21',
    type: 'matching',
    questionText: '请将左栏的句子与右栏对应的功能配对。',
    answer: '1-B, 2-D, 3-A, 4-C',
    explanation: 'What\'s the best...? 询问最好的, How far...? 询问距离, How much...? 询问价格, What do you think of...? 询问看法。',
    difficulty: 2,
    pairs: '[{"left":"1. What\'s the best movie theater?","right":"A. 询问价格"},{"left":"2. How far is it from your home?","right":"B. 询问最好的"},{"left":"3. How much is a ticket?","right":"C. 询问看法"},{"left":"4. What do you think of the movie?","right":"D. 询问距离"}]',
  },
];

// ========== 9-0 How can we become good learners? (24题) =========
// 知识点：by + doing（方式状语）、动词不定式、学习策略

const chapter9_0: RawQuestion[] = [
  // ---- choice 10题 ----
  {
    questionKey: 'english-pep-9-0-0',
    type: 'choice',
    questionText: '—How do you study for a test? —I study ___ working with a group.',
    answer: 'A',
    explanation: '"by + doing" 表示"通过做某事（方式/方法）"。',
    difficulty: 1,
    options: '["A. by", "B. with", "C. in", "D. on"]',
  },
  {
    questionKey: 'english-pep-9-0-1',
    type: 'choice',
    questionText: 'She improves her English ___ (read) English books.',
    answer: 'B',
    explanation: 'by + doing 表示方式，read 变为 reading。',
    difficulty: 1,
    options: '["A. by read", "B. by reading", "C. by to read", "D. by reads"]',
  },
  {
    questionKey: 'english-pep-9-0-2',
    type: 'choice',
    questionText: 'I find it difficult ___ (learn) English grammar.',
    answer: 'C',
    explanation: 'find it + 形容词 + to do sth. 是固定句型，it 是形式宾语，to learn 是真正的宾语。',
    difficulty: 2,
    options: '["A. learn", "B. learning", "C. to learn", "D. learned"]',
  },
  {
    questionKey: 'english-pep-9-0-3',
    type: 'choice',
    questionText: 'The more you practice, the ___ (good) you will be.',
    answer: 'D',
    explanation: '"the + 比较级, the + 比较级" 表示"越……越……"。good 的比较级是 better。',
    difficulty: 2,
    options: '["A. good", "B. best", "C. well", "D. better"]',
  },
  {
    questionKey: 'english-pep-9-0-4',
    type: 'choice',
    questionText: '___ (watch) English movies is a good way to learn English.',
    answer: 'A',
    explanation: '动名词（-ing）作主语，谓语用第三人称单数。Watching English movies is...。',
    difficulty: 2,
    options: '["A. Watching", "B. Watch", "C. To watching", "D. Watched"]',
  },
  {
    questionKey: 'english-pep-9-0-5',
    type: 'choice',
    questionText: 'He is afraid ___ (speak) in class because he is shy.',
    answer: 'B',
    explanation: 'be afraid to do sth. 表示"害怕做某事"。',
    difficulty: 2,
    options: '["A. of speak", "B. to speak", "C. speaking", "D. spoke"]',
  },
  {
    questionKey: 'english-pep-9-0-6',
    type: 'choice',
    questionText: 'Whether or not you can learn English well depends ___ your learning habits.',
    answer: 'C',
    explanation: 'depend on 表示"取决于"，是固定搭配。',
    difficulty: 2,
    options: '["A. in", "B. at", "C. on", "D. with"]',
  },
  {
    questionKey: 'english-pep-9-0-7',
    type: 'choice',
    questionText: 'I don\'t know how ___ (increase) my reading speed.',
    answer: 'D',
    explanation: '"疑问词 + to do" 作宾语，how to increase 表示"如何提高"。',
    difficulty: 2,
    options: '["A. increase", "B. increasing", "C. increased", "D. to increase"]',
  },
  {
    questionKey: 'english-pep-9-0-8',
    type: 'choice',
    questionText: 'The teacher told us ___ (not be) late for class.',
    answer: 'A',
    explanation: 'tell sb. (not) to do sth. 表示"告诉某人（不要）做某事"，否定形式是 not to be。',
    difficulty: 3,
    options: '["A. not to be", "B. to not be", "C. don\'t be", "D. not be"]',
  },
  {
    questionKey: 'english-pep-9-0-9',
    type: 'choice',
    questionText: 'She was born ___ the ability ___ (learn) languages quickly.',
    answer: 'C',
    explanation: 'be born with 意为"天生具有"；ability 后接 to do sth.。',
    difficulty: 3,
    options: '["A. with; of learning", "B. in; to learn", "C. with; to learn", "D. in; of learning"]',
  },
  // ---- fill 7题 ----
  {
    questionKey: 'english-pep-9-0-10',
    type: 'fill',
    questionText: 'You can improve your pronunciation by ___ (listen) to tapes.',
    answer: 'listening',
    explanation: 'by 是介词，后接动名词 listening。',
    difficulty: 1,
    acceptableAnswers: '["listening", "Listening"]',
  },
  {
    questionKey: 'english-pep-9-0-11',
    type: 'fill',
    questionText: 'I learn English ___ (make) word cards.',
    answer: 'by making',
    explanation: 'by + doing 表示"通过做某事"，make → making。',
    difficulty: 1,
    acceptableAnswers: '["by making", "By making"]',
  },
  {
    questionKey: 'english-pep-9-0-12',
    type: 'fill',
    questionText: 'He learns English ___ (watch) English movies.',
    answer: 'by watching',
    explanation: 'by + doing，watch 变为 watching。',
    difficulty: 1,
    acceptableAnswers: '["by watching", "By watching"]',
  },
  {
    questionKey: 'english-pep-9-0-13',
    type: 'fill',
    questionText: 'She has a partner ___ (practice) English with.',
    answer: 'to practice',
    explanation: '动词不定式 to practice 作后置定语，修饰 partner。',
    difficulty: 2,
    acceptableAnswers: '["to practice", "To practice"]',
  },
  {
    questionKey: 'english-pep-9-0-14',
    type: 'fill',
    questionText: '___ (pay) attention to the pronunciation is important.',
    answer: 'Paying',
    explanation: '动名词 Paying 作主语，谓语动词用 is。',
    difficulty: 2,
    acceptableAnswers: '["Paying", "paying"]',
  },
  {
    questionKey: 'english-pep-9-0-15',
    type: 'fill',
    questionText: 'I want to learn how ___ (improve) my writing skills.',
    answer: 'to improve',
    explanation: '"how + to do" 结构，to improve 作 learn 的宾语。',
    difficulty: 2,
    acceptableAnswers: '["to improve", "To improve"]',
  },
  {
    questionKey: 'english-pep-9-0-16',
    type: 'fill',
    questionText: 'Knowledge comes from ___ (question).',
    answer: 'questioning',
    explanation: 'questioning 在此处是动名词，意为"提问"。Knowledge comes from questioning 意为"知识来源于提问"。',
    difficulty: 3,
    acceptableAnswers: '["questioning", "Questioning"]',
  },
  // ---- short_answer 5题 ----
  {
    questionKey: 'english-pep-9-0-17',
    type: 'short_answer',
    questionText: '请列出三种学习英语的方法（用英语），使用 "by + doing" 结构。',
    answer: '1. I learn English by reading English books. 2. I learn English by watching English movies. 3. I learn English by listening to tapes. 4. I learn English by making word cards.（任选三种）',
    explanation: 'by + doing 是表达学习方式的核心结构，如 by reading, by watching, by listening, by making 等。',
    difficulty: 1,
  },
  {
    questionKey: 'english-pep-9-0-18',
    type: 'short_answer',
    questionText: '请用英语写出你认为成为优秀学习者的三个关键习惯，并说明原因。',
    answer: '1. Creating an interest in what they learn — because interest is the best teacher. 2. Practicing and learning from mistakes — because practice makes perfect. 3. Developing study skills — because good study skills help us learn better.（示例答案）',
    explanation: '本单元核心内容：成为优秀学习者的关键习惯包括培养兴趣、练习并从错误中学习、发展学习技巧等。',
    difficulty: 2,
  },
  {
    questionKey: 'english-pep-9-0-19',
    type: 'short_answer',
    questionText: '将下列句子改为同义句：I study English by reading books.',
    answer: 'I learn English by reading books. / Reading books helps me study English.',
    explanation: 'study 和 learn 在此处可互换；也可以用动名词作主语的句型。',
    difficulty: 2,
  },
  {
    questionKey: 'english-pep-9-0-20',
    type: 'short_answer',
    questionText: '请将下面的中文翻译成英语：你读得越多，你了解得就越多。',
    answer: 'The more you read, the more you will know.',
    explanation: '"the + 比较级, the + 比较级" 句型，表示"越……，越……"。',
    difficulty: 2,
  },
  {
    questionKey: 'english-pep-9-0-21',
    type: 'short_answer',
    questionText: '请解释 "find it + adj. + to do sth." 这个句型的结构，并造两个例句。',
    answer: '结构：find + it（形式宾语）+ 形容词（宾语补足语）+ to do sth.（真正宾语）。例句：1. I find it easy to learn English words. 2. She finds it difficult to remember grammar rules.',
    explanation: 'it 是形式宾语，真正的宾语是后面的不定式短语。当宾语较长时，常用 it 来占位。',
    difficulty: 3,
  },
  // ---- matching 2题 ----
  {
    questionKey: 'english-pep-9-0-22',
    type: 'matching',
    questionText: '请将左栏的学习方法与右栏对应的英文表达配对。',
    answer: '1-C, 2-D, 3-A, 4-B',
    explanation: '制作单词卡 → making word cards, 看英语电影 → watching English movies, 大声朗读 → reading aloud, 和小组一起学习 → working with a group。',
    difficulty: 1,
    pairs: '[{"left":"1. 制作单词卡","right":"A. reading aloud"},{"left":"2. 看英语电影","right":"B. working with a group"},{"left":"3. 大声朗读","right":"C. making word cards"},{"left":"4. 和小组一起学习","right":"D. watching English movies"}]',
  },
  {
    questionKey: 'english-pep-9-0-23',
    type: 'matching',
    questionText: '请将左栏的动词结构与右栏对应的用法说明配对。',
    answer: '1-B, 2-A, 3-D, 4-C',
    explanation: 'by doing 表示方式, want to do 表示想要, find it adj. to do 表示发现, how to do 表示如何做。',
    difficulty: 2,
    pairs: '[{"left":"1. by + doing","right":"A. 想要做某事"},{"left":"2. want to do","right":"B. 通过做某事（方式）"},{"left":"3. find it + adj. + to do","right":"C. 如何做某事"},{"left":"4. how to do","right":"D. 发现做某事……"}]',
  },
];

// ========== 9-1 I think that mooncakes are delicious! (26题) =========
// 知识点：宾语从句（that/if/whether引导）、感叹句、节日文化

const chapter9_1: RawQuestion[] = [
  // ---- choice 10题 ----
  {
    questionKey: 'english-pep-9-1-0',
    type: 'choice',
    questionText: 'I think ___ the Spring Festival is the most important festival in China.',
    answer: 'A',
    explanation: 'that 引导宾语从句，在口语中可以省略。think 后接 that 从句表示"认为……"。',
    difficulty: 1,
    options: '["A. that", "B. what", "C. if", "D. where"]',
  },
  {
    questionKey: 'english-pep-9-1-1',
    type: 'choice',
    questionText: 'I wonder ___ he will come to the party or not.',
    answer: 'C',
    explanation: 'whether...or not 是固定搭配，表示"是否"，引导宾语从句。',
    difficulty: 2,
    options: '["A. that", "B. what", "C. whether", "D. which"]',
  },
  {
    questionKey: 'english-pep-9-1-2',
    type: 'choice',
    questionText: '___ delicious the mooncakes are!',
    answer: 'B',
    explanation: 'What + a/an + 形容词 + 可数名词单数 + 主语 + 谓语! 或 How + 形容词/副词 + 主语 + 谓语!。delicious 是形容词，用 How。',
    difficulty: 1,
    options: '["A. What", "B. How", "C. What a", "D. How a"]',
  },
  {
    questionKey: 'english-pep-9-1-3',
    type: 'choice',
    questionText: '___ interesting the story is!',
    answer: 'D',
    explanation: 'How + 形容词 + 主语 + 谓语! interesting 是形容词，用 How。',
    difficulty: 1,
    options: '["A. What", "B. What an", "C. What a", "D. How"]',
  },
  {
    questionKey: 'english-pep-9-1-4',
    type: 'choice',
    questionText: 'He asked me ___ I liked the Mid-Autumn Festival.',
    answer: 'A',
    explanation: '一般疑问句改为宾语从句时用 if/whether 引导。',
    difficulty: 2,
    options: '["A. if", "B. that", "C. what", "D. which"]',
  },
  {
    questionKey: 'english-pep-9-1-5',
    type: 'choice',
    questionText: 'I don\'t know ___ he is. Can you tell me?',
    answer: 'B',
    explanation: '对"他是谁"提问用 who，宾语从句中用 who 引导。',
    difficulty: 2,
    options: '["A. what", "B. who", "C. which", "D. where"]',
  },
  {
    questionKey: 'english-pep-9-1-6',
    type: 'choice',
    questionText: '___ a beautiful girl she is!',
    answer: 'C',
    explanation: 'What + a/an + 形容词 + 可数名词单数 + 主语 + 谓语! girl 是可数名词单数。',
    difficulty: 1,
    options: '["A. How", "B. What", "C. What a", "D. How a"]',
  },
  {
    questionKey: 'english-pep-9-1-7',
    type: 'choice',
    questionText: 'She told me ___ she would go to Shanghai the next day.',
    answer: 'A',
    explanation: '陈述句变宾语从句用 that 引导（可省略），注意时态和人称的变化。',
    difficulty: 2,
    options: '["A. (that)", "B. if", "C. what", "D. how"]',
  },
  {
    questionKey: 'english-pep-9-1-8',
    type: 'choice',
    questionText: 'I know that the Water Festival ___ (be) really fun.',
    answer: 'D',
    explanation: '宾语从句中主语 the Water Festival 是第三人称单数，用 is。',
    difficulty: 2,
    options: '["A. are", "B. were", "C. am", "D. is"]',
  },
  {
    questionKey: 'english-pep-9-1-9',
    type: 'choice',
    questionText: 'He wonders ___ they will have the party. He doesn\'t know the date.',
    answer: 'C',
    explanation: '根据"He doesn\'t know the date"可知问的是时间，用 when 引导。',
    difficulty: 3,
    options: '["A. what", "B. that", "C. when", "D. if"]',
  },
  // ---- fill 8题 ----
  {
    questionKey: 'english-pep-9-1-10',
    type: 'fill',
    questionText: 'I believe ___ Spring Festival is a time for family reunion.',
    answer: 'that',
    explanation: 'that 引导宾语从句，在口语中常可省略。',
    difficulty: 1,
    acceptableAnswers: '["that", "(that)", ""]',
  },
  {
    questionKey: 'english-pep-9-1-11',
    type: 'fill',
    questionText: '___ kind the old man is!',
    answer: 'How',
    explanation: 'How + 形容词 + 主语 + 谓语! kind 是形容词。',
    difficulty: 1,
    acceptableAnswers: '["How", "how"]',
  },
  {
    questionKey: 'english-pep-9-1-12',
    type: 'fill',
    questionText: '___ interesting book it is!',
    answer: 'What an',
    explanation: 'What + a/an + 形容词 + 可数名词单数 + ...! interesting 以元音音素开头，用 an。',
    difficulty: 1,
    acceptableAnswers: '["What an", "what an"]',
  },
  {
    questionKey: 'english-pep-9-1-13',
    type: 'fill',
    questionText: 'I\'m not sure ___ he will come ___ not.',
    answer: 'whether; or',
    explanation: 'whether...or not 是固定搭配，表示"是否"。',
    difficulty: 2,
    acceptableAnswers: '["whether; or", "Whether; or"]',
  },
  {
    questionKey: 'english-pep-9-1-14',
    type: 'fill',
    questionText: 'Could you tell me where I ___ (can buy) some mooncakes?',
    answer: 'can buy',
    explanation: '宾语从句用陈述语序，can buy 保持原来的时态。',
    difficulty: 2,
    acceptableAnswers: '["can buy", "Can buy"]',
  },
  {
    questionKey: 'english-pep-9-1-15',
    type: 'fill',
    questionText: 'He said that he ___ (will go) to Beijing the next week.',
    answer: 'would go',
    explanation: '主句是一般过去时 said，从句时态要向过去推移：will → would。',
    difficulty: 3,
    acceptableAnswers: '["would go", "Would go"]',
  },
  {
    questionKey: 'english-pep-9-1-16',
    type: 'fill',
    questionText: '___ heavy the rain is!',
    answer: 'How',
    explanation: 'How + 形容词 + 主语 + 谓语! heavy 是形容词。',
    difficulty: 1,
    acceptableAnswers: '["How", "how"]',
  },
  {
    questionKey: 'english-pep-9-1-17',
    type: 'fill',
    questionText: 'I want to know ___ he likes Chinese food ___ Western food.',
    answer: 'whether; or',
    explanation: 'whether...or... 表示"是……还是……"，引导宾语从句表示选择。',
    difficulty: 3,
    acceptableAnswers: '["whether; or", "Whether; or", "if; or"]',
  },
  // ---- short_answer 6题 ----
  {
    questionKey: 'english-pep-9-1-18',
    type: 'short_answer',
    questionText: '请写出四个中国传统节日的英文名称及其对应的日期或时间。',
    answer: '1. the Spring Festival（春节）— in January or February  2. the Mid-Autumn Festival（中秋节）— on the 15th day of the 8th lunar month  3. the Dragon Boat Festival（端午节）— on the 5th day of the 5th lunar month  4. the Lantern Festival（元宵节）— on the 15th day of the 1st lunar month',
    explanation: '本单元学习了中国传统节日的英文名称和相关文化知识。',
    difficulty: 1,
  },
  {
    questionKey: 'english-pep-9-1-19',
    type: 'short_answer',
    questionText: '请将下列直接引语改为间接引语（宾语从句）："I like the Mid-Autumn Festival," she said.',
    answer: 'She said (that) she liked the Mid-Autumn Festival.',
    explanation: '直接引语变间接引语：引导词用 that（可省略），人称 I → she，时态 like → liked。',
    difficulty: 2,
  },
  {
    questionKey: 'english-pep-9-1-20',
    type: 'short_answer',
    questionText: '请将下列句子改为感叹句：The mooncakes are very delicious.',
    answer: 'How delicious the mooncakes are! / What delicious mooncakes they are!',
    explanation: '感叹句两种形式：How + 形容词 + 主语 + 谓语! 或 What + 形容词 + 不可数名词/复数名词 + 主语 + 谓语!',
    difficulty: 2,
  },
  {
    questionKey: 'english-pep-9-1-21',
    type: 'short_answer',
    questionText: '请用英语简要介绍中秋节（至少3句话）。
提示：时间、食物、活动、寓意。',
    answer: 'The Mid-Autumn Festival falls on the 15th day of the 8th lunar month. People eat mooncakes and admire the moon with their families. Mooncakes are round and symbolize family reunion.（示例答案）',
    explanation: '介绍节日时可以涵盖时间、传统食物、活动方式和文化寓意等方面。',
    difficulty: 2,
  },
  {
    questionKey: 'english-pep-9-1-22',
    type: 'short_answer',
    questionText: '请将下面的中文翻译成英语：你知道他是否喜欢春节吗？',
    answer: 'Do you know if/whether he likes the Spring Festival?',
    explanation: '一般疑问句变宾语从句用 if 或 whether 引导，从句用陈述语序。',
    difficulty: 2,
  },
  {
    questionKey: 'english-pep-9-1-23',
    type: 'short_answer',
    questionText: '请总结感叹句的两种基本句型结构，并各举一个例子。',
    answer: '句型一：How + 形容词/副词 + 主语 + 谓语! 例：How beautiful the flower is! 句型二：What + (a/an) + 形容词 + 名词 + 主语 + 谓语! 例：What a good boy he is!',
    explanation: 'How 后接形容词或副词，What 后接名词短语。判断用 How 还是 What：去掉主谓后看剩下的是形容词/副词（用 How）还是名词短语（用 What）。',
    difficulty: 3,
  },
  // ---- matching 2题 ----
  {
    questionKey: 'english-pep-9-1-24',
    type: 'matching',
    questionText: '请将左栏的节日名称与右栏对应的中文配对。',
    answer: '1-C, 2-D, 3-A, 4-B',
    explanation: 'the Water Festival 泼水节, the Dragon Boat Festival 端午节, the Spring Festival 春节, the Lantern Festival 元宵节。',
    difficulty: 1,
    pairs: '[{"left":"1. the Water Festival","right":"A. 春节"},{"left":"2. the Dragon Boat Festival","right":"B. 元宵节"},{"left":"3. the Spring Festival","right":"C. 泼水节"},{"left":"4. the Lantern Festival","right":"D. 端午节"}]',
  },
  {
    questionKey: 'english-pep-9-1-25',
    type: 'matching',
    questionText: '请将左栏的宾语从句引导词与右栏对应的用法配对。',
    answer: '1-B, 2-A, 3-C, 4-D',
    explanation: 'that 引导陈述句变来的从句, if/whether 引导一般疑问句变来的从句, wh- 引导特殊疑问句变来的从句, wh- 也可引导表示疑问的从句。',
    difficulty: 2,
    pairs: '[{"left":"1. that","right":"A. 引导一般疑问句变来的从句"},{"left":"2. if/whether","right":"B. 引导陈述句变来的从句"},{"left":"3. what","right":"C. 引导特殊疑问句变来的从句"},{"left":"4. where","right":"D. 引导特殊疑问句变来的从句"}]',
  },
];

// ========== 9-2 Could you please tell me where the restrooms are? (28题) =========
// 知识点：宾语从句（wh-引导）、礼貌用语、指路

const chapter9_2: RawQuestion[] = [
  // ---- choice 11题 ----
  {
    questionKey: 'english-pep-9-2-0',
    type: 'choice',
    questionText: 'Could you please tell me ___ the restrooms are?',
    answer: 'A',
    explanation: '对地点提问用 where，引导宾语从句时用陈述语序。',
    difficulty: 1,
    options: '["A. where", "B. what", "C. how", "D. which"]',
  },
  {
    questionKey: 'english-pep-9-2-1',
    type: 'choice',
    questionText: 'Excuse me, do you know ___ I can get to the post office?',
    answer: 'C',
    explanation: '对方式提问用 how，"how I can get to..." 表示"我怎样才能到……"。',
    difficulty: 1,
    options: '["A. what", "B. where", "C. how", "D. when"]',
  },
  {
    questionKey: 'english-pep-9-2-2',
    type: 'choice',
    questionText: 'I wonder ___ we will go to the party or not.',
    answer: 'B',
    explanation: 'whether...or not 引导宾语从句，表示"是否"。',
    difficulty: 1,
    options: '["A. that", "B. whether", "C. what", "D. which"]',
  },
  {
    questionKey: 'english-pep-9-2-3',
    type: 'choice',
    questionText: 'Pardon me, could you tell me where ___ (be) the bookstore?',
    answer: 'D',
    explanation: '宾语从句用陈述语序，the bookstore 是复数/不可数概念，但 bookstore 是单数，用 is。',
    difficulty: 2,
    options: '["A. are", "B. were", "C. will", "D. is"]',
  },
  {
    questionKey: 'english-pep-9-2-4',
    type: 'choice',
    questionText: 'Could you tell me ___ the library opens?',
    answer: 'A',
    explanation: '对时间提问用 when，"when the library opens" 表示"图书馆什么时候开门"。',
    difficulty: 2,
    options: '["A. when", "B. where", "C. how", "D. what"]',
  },
  {
    questionKey: 'english-pep-9-2-5',
    type: 'choice',
    questionText: 'I don\'t know ___ to do next.',
    answer: 'C',
    explanation: '"疑问词 + to do" 作宾语，what to do 表示"做什么"。',
    difficulty: 2,
    options: '["A. how", "B. where", "C. what", "D. which"]',
  },
  {
    questionKey: 'english-pep-9-2-6',
    type: 'choice',
    questionText: 'She asked me ___ I came from.',
    answer: 'B',
    explanation: '对地点提问用 where，"where I came from" 表示"我来自哪里"。',
    difficulty: 2,
    options: '["A. what", "B. where", "C. how", "D. when"]',
  },
  {
    questionKey: 'english-pep-9-2-7',
    type: 'choice',
    questionText: 'Do you know ___ the meeting will begin?',
    answer: 'D',
    explanation: '对时间提问用 when。',
    difficulty: 1,
    options: '["A. what", "B. where", "C. how", "D. when"]',
  },
  {
    questionKey: 'english-pep-9-2-8',
    type: 'choice',
    questionText: 'He asked me ___ I liked English ___ Chinese.',
    answer: 'A',
    explanation: 'whether...or... 表示"是……还是……"，引导选择型宾语从句。',
    difficulty: 3,
    options: '["A. whether; or", "B. that; and", "C. if; or", "D. what; and"]',
  },
  {
    questionKey: 'english-pep-9-2-9',
    type: 'choice',
    questionText: 'The clerk suggested ___ (go) to the second floor.',
    answer: 'B',
    explanation: 'suggest 后接动名词作宾语，suggest doing sth. 表示"建议做某事"。',
    difficulty: 3,
    options: '["A. to go", "B. going", "C. go", "D. went"]',
  },
  {
    questionKey: 'english-pep-9-2-10',
    type: 'choice',
    questionText: '—Excuse me, could you tell me where the bank is? —___. Go along this street and turn left.',
    answer: 'C',
    explanation: '根据后文的指路信息，回答应该是"Sure"（当然可以）。',
    difficulty: 1,
    options: '["A. Yes, I could.", "B. No, I couldn\'t.", "C. Sure.", "D. I don\'t know."]',
  },
  // ---- fill 8题 ----
  {
    questionKey: 'english-pep-9-2-11',
    type: 'fill',
    questionText: 'Could you tell me where I ___ (can buy) some stamps?',
    answer: 'can buy',
    explanation: '宾语从句用陈述语序，时态保持不变。',
    difficulty: 1,
    acceptableAnswers: '["can buy", "Can buy"]',
  },
  {
    questionKey: 'english-pep-9-2-12',
    type: 'fill',
    questionText: 'I wonder ___ the restaurant opens at 6:00 p.m.',
    answer: 'if',
    explanation: '一般疑问句变宾语从句用 if/whether 引导，此处 if 即可。',
    difficulty: 2,
    acceptableAnswers: '["if", "If", "whether", "Whether"]',
  },
  {
    questionKey: 'english-pep-9-2-13',
    type: 'fill',
    questionText: 'Do you know ___ there is a good restaurant near here?',
    answer: 'if',
    explanation: '"Is there...?"变宾语从句用 if 引导，改为陈述语序。',
    difficulty: 2,
    acceptableAnswers: '["if", "If", "whether", "Whether"]',
  },
  {
    questionKey: 'english-pep-9-2-14',
    type: 'fill',
    questionText: 'She asked me ___ I lived.',
    answer: 'where',
    explanation: '"Where do you live?"变宾语从句：引导词 where，陈述语序，去掉助动词 do。',
    difficulty: 2,
    acceptableAnswers: '["where", "Where"]',
  },
  {
    questionKey: 'english-pep-9-2-15',
    type: 'fill',
    questionText: 'I don\'t know how ___ (get) to the train station.',
    answer: 'to get',
    explanation: '"how + to do" 结构，how to get 表示"如何到达"。',
    difficulty: 2,
    acceptableAnswers: '["to get", "To get"]',
  },
  {
    questionKey: 'english-pep-9-2-16',
    type: 'fill',
    questionText: 'He wants to know ___ the next train will arrive.',
    answer: 'when',
    explanation: '对时间提问用 when，"when the next train will arrive" 表示"下一趟火车什么时候到"。',
    difficulty: 2,
    acceptableAnswers: '["when", "When"]',
  },
  {
    questionKey: 'english-pep-9-2-17',
    type: 'fill',
    questionText: 'Could you please tell me where I ___ (can find) a hospital?',
    answer: 'can find',
    explanation: '宾语从句保持陈述语序和原来的时态。',
    difficulty: 3,
    acceptableAnswers: '["can find", "Can find"]',
  },
  {
    questionKey: 'english-pep-9-2-18',
    type: 'fill',
    questionText: 'I don\'t know ___ book is his. They look the same.',
    answer: 'which',
    explanation: '在有限范围内选择用 which，"which book" 表示"哪本书"。',
    difficulty: 3,
    acceptableAnswers: '["which", "Which"]',
  },
  // ---- short_answer 7题 ----
  {
    questionKey: 'english-pep-9-2-19',
    type: 'short_answer',
    questionText: '请写出三个问路时常用的礼貌用语（用英语）。',
    answer: 'Excuse me, could you please tell me...? / Pardon me, do you know...? / I wonder if you could...? / Could you tell me how to get to...?（任选三个）',
    explanation: '问路时常用的礼貌用语包括 Excuse me, could you please...?, Pardon me, do you know...?, I wonder if... 等。',
    difficulty: 1,
  },
  {
    questionKey: 'english-pep-9-2-20',
    type: 'short_answer',
    questionText: '请将下列特殊疑问句改为宾语从句：Where does he live?',
    answer: 'I want to know where he lives. / Could you tell me where he lives?',
    explanation: '特殊疑问句变宾语从句：保留特殊疑问词，改为陈述语序（去掉 does，动词变三单）。',
    difficulty: 2,
  },
  {
    questionKey: 'english-pep-9-2-21',
    type: 'short_answer',
    questionText: '请将下列一般疑问句改为宾语从句：Are there any restaurants near here?',
    answer: 'Could you tell me if/whether there are any restaurants near here?',
    explanation: '一般疑问句变宾语从句用 if/whether 引导，改为陈述语序。',
    difficulty: 2,
  },
  {
    questionKey: 'english-pep-9-2-22',
    type: 'short_answer',
    questionText: '请将下面的中文翻译成英语：请问你能告诉我怎样去火车站吗？',
    answer: 'Could you please tell me how to get to the train station? / Excuse me, could you tell me how I can get to the train station?',
    explanation: '问路时用 Could you please tell me...? 或 Excuse me, could you tell me...? 使语气更礼貌。',
    difficulty: 2,
  },
  {
    questionKey: 'english-pep-9-2-23',
    type: 'short_answer',
    questionText: '请用英语描述从学校到你家的路线（至少3句话）。
提示：使用 go along, turn left/right, on your left/right 等短语。',
    answer: 'Go along Center Street and turn right at the second crossing. Then walk past the post office. You will see my house on your left. It\'s next to a supermarket.（示例答案）',
    explanation: '指路常用句型：Go along...; Turn left/right at...; Walk past...; It\'s on your left/right; It\'s next to...。',
    difficulty: 2,
  },
  {
    questionKey: 'english-pep-9-2-24',
    type: 'short_answer',
    questionText: '请说明直接引语变间接引语时（宾语从句），人称、时态和语序分别需要注意什么变化？',
    answer: '1. 人称变化：根据主句的主语和宾语调整，如 I → he/she。2. 时态变化：主句为过去时，从句时态整体向过去推移（如 am/is → was, will → would, can → could）。3. 语序变化：疑问句变为陈述语序。',
    explanation: '直接引语变间接引语（宾语从句）需要调整人称、时态和语序，但主句为现在时或客观真理时时态不变。',
    difficulty: 3,
  },
  {
    questionKey: 'english-pep-9-2-25',
    type: 'short_answer',
    questionText: '请用 "I wonder..." 造两个含有宾语从句的句子，一个用 if 引导，一个用 wh- 词引导。',
    answer: '1. I wonder if he will come to the party. 2. I wonder where she went yesterday.',
    explanation: 'I wonder 后可接 if/whether 引导的宾语从句（表示"是否"），也可接 wh- 引导的宾语从句（表示"……"）。',
    difficulty: 3,
  },
  // ---- matching 2题 ----
  {
    questionKey: 'english-pep-9-2-26',
    type: 'matching',
    questionText: '请将左栏的礼貌问路与右栏对应的回答配对。',
    answer: '1-C, 2-D, 3-A, 4-B',
    explanation: '问路的礼貌回答包括指明方向、告知距离和位置。',
    difficulty: 1,
    pairs: '[{"left":"1. Could you tell me where the bank is?","right":"A. It\'s about 10 minutes\' walk."},{"left":"2. Do you know when the store closes?","right":"B. Go straight and turn left."},{"left":"3. How far is it from here?","right":"C. It\'s on Center Street."},{"left":"4. Which is the way to the park?","right":"D. It closes at 9:00 p.m."}]',
  },
  {
    questionKey: 'english-pep-9-2-27',
    type: 'matching',
    questionText: '请将左栏的宾语从句引导词与右栏对应的特殊疑问句配对。',
    answer: '1-B, 2-D, 3-A, 4-C',
    explanation: 'what → What is this?, where → Where does he live?, when → When did you arrive?, how → How do you get there?',
    difficulty: 2,
    pairs: '[{"left":"1. where","right":"A. When did you arrive?"},{"left":"2. what","right":"B. Where does he live?"},{"left":"3. when","right":"C. How do you get there?"},{"left":"4. how","right":"D. What is this?"}]',
  },
];

// ========== 9-3 We're trying to save the earth! (22题) =========
// 知识点：现在完成时、环保词汇、should/must 表建议和义务

const chapter9_3: RawQuestion[] = [
  // ---- choice 9题 ----
  {
    questionKey: 'english-pep-9-3-0',
    type: 'choice',
    questionText: 'We should ___ (protect) the environment.',
    answer: 'C',
    explanation: 'should 是情态动词，后接动词原形 protect。',
    difficulty: 1,
    options: '["A. protecting", "B. protected", "C. protect", "D. to protect"]',
  },
  {
    questionKey: 'english-pep-9-3-1',
    type: 'choice',
    questionText: 'The air pollution is ___ (get) worse and worse.',
    answer: 'A',
    explanation: '"get + 比较级"表示"变得越来越……"，此处用现在进行时 is getting。',
    difficulty: 2,
    options: '["A. getting", "B. get", "C. gets", "D. got"]',
  },
  {
    questionKey: 'english-pep-9-3-2',
    type: 'choice',
    questionText: 'We ___ (live) in this city since 2010.',
    answer: 'D',
    explanation: '"since + 过去时间点"与现在完成时连用，主语 We 用 have lived。',
    difficulty: 2,
    options: '["A. live", "B. lived", "C. are living", "D. have lived"]',
  },
  {
    questionKey: 'english-pep-9-3-3',
    type: 'choice',
    questionText: 'You must ___ (stop) using plastic bags.',
    answer: 'B',
    explanation: 'must 是情态动词，后接动词原形 stop。',
    difficulty: 1,
    options: '["A. to stop", "B. stop", "C. stopping", "D. stopped"]',
  },
  {
    questionKey: 'english-pep-9-3-4',
    type: 'choice',
    questionText: 'She has ___ (be) to Beijing twice.',
    answer: 'C',
    explanation: '"have/has been to + 地点"表示"去过某地"（已回来），用现在完成时 has been。',
    difficulty: 2,
    options: '["A. be", "B. being", "C. been", "D. was"]',
  },
  {
    questionKey: 'english-pep-9-3-5',
    type: 'choice',
    questionText: '—Have you ___ (see) the movie before? —Yes, I have.',
    answer: 'A',
    explanation: '现在完成时结构：have/has + 过去分词，see 的过去分词是 seen。',
    difficulty: 2,
    options: '["A. seen", "B. saw", "C. see", "D. seeing"]',
  },
  {
    questionKey: 'english-pep-9-3-6',
    type: 'choice',
    questionText: 'We should take action ___ (protect) the earth.',
    answer: 'D',
    explanation: '"take action to do sth." 表示"采取行动做某事"，to 后接动词原形。',
    difficulty: 2,
    options: '["A. protect", "B. protecting", "C. protected", "D. to protect"]',
  },
  {
    questionKey: 'english-pep-9-3-7',
    type: 'choice',
    questionText: 'People ___ (cut) down too many trees in the past few years.',
    answer: 'B',
    explanation: '"in the past few years" 与现在完成时连用，主语 people 是复数，用 have cut。',
    difficulty: 3,
    options: '["A. cut", "B. have cut", "C. has cut", "D. cutting"]',
  },
  {
    questionKey: 'english-pep-9-3-8',
    type: 'choice',
    questionText: 'The river ___ (be) very dirty. But it ___ (be) clean five years ago.',
    answer: 'C',
    explanation: '第一空描述现在的情况用一般现在时 is；第二空 five years ago 提示一般过去时 was。',
    difficulty: 2,
    options: '["A. is; is", "B. was; is", "C. is; was", "D. was; was"]',
  },
  // ---- fill 7题 ----
  {
    questionKey: 'english-pep-9-3-9',
    type: 'fill',
    questionText: 'We should ride bikes instead ___ driving.',
    answer: 'of',
    explanation: 'instead of 是固定搭配，意为"代替/而不是"，of 是介词。',
    difficulty: 1,
    acceptableAnswers: '["of", "Of"]',
  },
  {
    questionKey: 'english-pep-9-3-10',
    type: 'fill',
    questionText: 'We can help ___ (save) the earth by ___ (recycle) paper.',
    answer: 'save; recycling',
    explanation: 'help (to) do sth.，to 可省略；by + doing，recycle → recycling。',
    difficulty: 1,
    acceptableAnswers: '["save; recycling", "to save; recycling"]',
  },
  {
    questionKey: 'english-pep-9-3-11',
    type: 'fill',
    questionText: 'Pollution is ___ (harm) to our health.',
    answer: 'harmful',
    explanation: 'be harmful to 表示"对……有害"，harmful 是形容词。',
    difficulty: 2,
    acceptableAnswers: '["harmful", "Harmful"]',
  },
  {
    questionKey: 'english-pep-9-3-12',
    type: 'fill',
    questionText: 'He ___ (live) in Shanghai for three years.',
    answer: 'has lived',
    explanation: '"for + 时间段"与现在完成时连用，主语 He 用 has lived。',
    difficulty: 2,
    acceptableAnswers: '["has lived", "Has lived"]',
  },
  {
    questionKey: 'english-pep-9-3-13',
    type: 'fill',
    questionText: 'I ___ already ___ (finish) my homework.',
    answer: 'have; finished',
    explanation: '现在完成时：have/has + 过去分词。finish 的过去分词是 finished。already 常用于肯定句。',
    difficulty: 2,
    acceptableAnswers: '["have; finished", "Have; finished"]',
  },
  {
    questionKey: 'english-pep-9-3-14',
    type: 'fill',
    questionText: 'The government is trying ___ (reduce) air pollution.',
    answer: 'to reduce',
    explanation: 'try to do sth. 表示"尽力做某事"，to 后接动词原形。',
    difficulty: 2,
    acceptableAnswers: '["to reduce", "To reduce"]',
  },
  {
    questionKey: 'english-pep-9-3-15',
    type: 'fill',
    questionText: 'She has never ___ (be) to a water park.',
    answer: 'been',
    explanation: '现在完成时：has + been（be 的过去分词）。never 是否定副词。',
    difficulty: 3,
    acceptableAnswers: '["been", "Been"]',
  },
  // ---- short_answer 4题 ----
  {
    questionKey: 'english-pep-9-3-16',
    type: 'short_answer',
    questionText: '请写出以下动词的过去分词：go, eat, see, take, write, build',
    answer: 'go → gone, eat → eaten, see → seen, take → taken, write → written, build → built',
    explanation: '不规则动词的过去分词需要逐一记忆，有些与过去式相同（如 build → built），有些不同（如 go → gone）。',
    difficulty: 1,
  },
  {
    questionKey: 'english-pep-9-3-17',
    type: 'short_answer',
    questionText: '请写出至少三种保护环境的措施（用英语），并使用 should/must/mustn\'t。',
    answer: '1. We should plant more trees. 2. We must stop using plastic bags. 3. We mustn\'t throw rubbish into rivers. 4. We should recycle paper and bottles.（示例答案）',
    explanation: 'should 表示"应该"，must 表示"必须"，mustn\'t 表示"禁止"，常用于提出建议和规定。',
    difficulty: 2,
  },
  {
    questionKey: 'english-pep-9-3-18',
    type: 'short_answer',
    questionText: '请将下面的中文翻译成英语：我们在这个城市已经住了十年了。',
    answer: 'We have lived in this city for ten years.',
    explanation: '"for + 时间段"与现在完成时连用，表示从过去持续到现在的动作或状态。',
    difficulty: 2,
  },
  {
    questionKey: 'english-pep-9-3-19',
    type: 'short_answer',
    questionText: '请说明 have been to 和 have gone to 的区别，并各造一个句子。',
    answer: 'have been to 表示"去过某地（已回来）"：I have been to Beijing.（我去过北京。）have gone to 表示"去了某地（还没回来）"：He has gone to Beijing.（他去了北京，不在这里。）',
    explanation: 'have been to 强调"经历"（去了又回来了）；have gone to 强调"去向"（去了还没回来），不能用于第一人称。',
    difficulty: 3,
  },
  // ---- matching 2题 ----
  {
    questionKey: 'english-pep-9-3-20',
    type: 'matching',
    questionText: '请将左栏的环保词汇与右栏对应的中文含义配对。',
    answer: '1-D, 2-A, 3-B, 4-C',
    explanation: 'pollution 污染, recycle 回收利用, protection 保护, waste 废物/浪费。',
    difficulty: 1,
    pairs: '[{"left":"1. pollution","right":"A. 回收利用"},{"left":"2. recycle","right":"B. 保护"},{"left":"3. protection","right":"C. 废物"},{"left":"4. waste","right":"D. 污染"}]',
  },
  {
    questionKey: 'english-pep-9-3-21',
    type: 'matching',
    questionText: '请将左栏的动词原形与右栏对应的过去分词配对。',
    answer: '1-C, 2-A, 3-D, 4-B',
    explanation: 'go → gone, write → written, see → seen, take → taken。',
    difficulty: 2,
    pairs: '[{"left":"1. go","right":"A. written"},{"left":"2. write","right":"B. taken"},{"left":"3. see","right":"C. gone"},{"left":"4. take","right":"D. seen"}]',
  },
];

// ========== 章节映射与导出函数 ==========

const chapterKeyToData: Record<string, RawQuestion[]> = {
  'english-pep-7-0': chapter7_0,
  'english-pep-7-1': chapter7_1,
  'english-pep-7-2': chapter7_2,
  'english-pep-7-3': chapter7_3,
  'english-pep-8-0': chapter8_0,
  'english-pep-8-1': chapter8_1,
  'english-pep-8-2': chapter8_2,
  'english-pep-8-3': chapter8_3,
  'english-pep-9-0': chapter9_0,
  'english-pep-9-1': chapter9_1,
  'english-pep-9-2': chapter9_2,
  'english-pep-9-3': chapter9_3,
};

export async function seedEnglishPepQuestions(): Promise<number> {
  // 1. 查找所有英语人教版章节
  const chapters = await prisma.chapter.findMany({
    where: { chapterKey: { startsWith: 'english-pep' } },
  });

  // 2. 构建 chapterKey -> chapterId 映射
  const keyToId = new Map<string, string>();
  for (const ch of chapters) {
    keyToId.set(ch.chapterKey, ch.id);
  }

  // 3. 收集所有待插入的记录
  const records: Array<{
    chapterId: string;
    questionKey: string;
    type: string;
    questionText: string;
    answer: string;
    explanation: string;
    difficulty: number;
    options?: string;
    pairs?: string;
    acceptableAnswers?: string;
    isActive: boolean;
  }> = [];

  for (const [chapterKey, questions] of Object.entries(chapterKeyToData)) {
    const chapterId = keyToId.get(chapterKey);
    if (!chapterId) {
      console.warn(`[seed-english-pep] 章节 "${chapterKey}" 未找到，跳过 ${questions.length} 道题`);
      continue;
    }

    for (const q of questions) {
      records.push({
        chapterId,
        questionKey: q.questionKey,
        type: q.type,
        questionText: q.questionText,
        answer: q.answer,
        explanation: q.explanation,
        difficulty: q.difficulty,
        options: q.options,
        pairs: q.pairs,
        acceptableAnswers: q.acceptableAnswers,
        isActive: true,
      });
    }
  }

  // 4. 批量插入（分批处理以适配 SQLite 限制）
  const BATCH_SIZE = 500;
  let inserted = 0;
  for (let i = 0; i < records.length; i += BATCH_SIZE) {
    const batch = records.slice(i, i + BATCH_SIZE);
    const result = await prisma.question.createMany({
      data: batch,
      skipDuplicates: true,
    });
    inserted += result.count;
  }

  console.log(`[seed-english-pep] 共插入 ${inserted} 道英语人教版题目`);
  return inserted;
}
