/**
 * 历史人教版（部编版）初中题目种子数据
 *
 * 涵盖 7~9 年级共 12 个章节，总计 242 道题。
 *   7年级：中国境内早期人类与文明的起源(20)、夏商周时期(24)、秦汉时期(28)、三国两晋南北朝时期(22)
 *   8年级：隋唐时期(28)、宋元时期(26)、明清时期(24)、中国开始沦为半殖民地半封建社会(24)
 *   9年级：近代化的早期探索(24)、新民主主义革命的开始(28)、中华民族的抗日战争(24)、人民解放战争的胜利(22)
 *
 * 题型分布：choice ~45% | fill ~20% | short_answer ~25% | matching ~10%
 * 难度分布：difficulty 1(基础) ~40% | 2(中等) ~40% | 3(提高) ~20%
 */

import { prisma } from '../../src/config/database.js';

const questions = [
  // ========== 7-0 中国境内早期人类与文明的起源 (20题) ==========

  // choice 9题
  {
    chapterKey: 'history-bubian-7-0',
    questionKey: 'history-bubian-7-0-0',
    type: 'choice',
    questionText: '目前已知中国境内最早的古人类是（）',
    answer: 'A',
    explanation: '元谋人距今约170万年，是我国境内目前已确认的最早的古人类。',
    difficulty: 1,
    options: '["A. 元谋人","B. 北京人","C. 山顶洞人","D. 河姆渡人"]',
  },
  {
    chapterKey: 'history-bubian-7-0',
    questionKey: 'history-bubian-7-0-1',
    type: 'choice',
    questionText: '北京人使用天然火的主要意义在于（）',
    answer: 'B',
    explanation: '使用天然火是人类进化史上的重大进步，火可以用来照明、防寒、驱赶野兽、烧烤食物，增强了人类适应自然的能力。',
    difficulty: 1,
    options: '["A. 可以用来烧制陶器","B. 增强了人类适应自然的能力","C. 可以用来冶炼金属","D. 标志着农耕文明的开始"]',
  },
  {
    chapterKey: 'history-bubian-7-0',
    questionKey: 'history-bubian-7-0-2',
    type: 'choice',
    questionText: '下列远古居民中，最早掌握磨制石器和钻孔技术的是（）',
    answer: 'C',
    explanation: '山顶洞人已掌握磨制石器和钻孔技术，还会制作骨针，具有审美的观念。',
    difficulty: 2,
    options: '["A. 元谋人","B. 北京人","C. 山顶洞人","D. 半坡人"]',
  },
  {
    chapterKey: 'history-bubian-7-0',
    questionKey: 'history-bubian-7-0-3',
    type: 'choice',
    questionText: '河姆渡原始居民主要种植的农作物是（）',
    answer: 'A',
    explanation: '河姆渡人生活在长江流域，距今约7000年，主要种植水稻。',
    difficulty: 1,
    options: '["A. 水稻","B. 粟","C. 小麦","D. 玉米"]',
  },
  {
    chapterKey: 'history-bubian-7-0',
    questionKey: 'history-bubian-7-0-4',
    type: 'choice',
    questionText: '半坡原始居民居住的房屋样式是（）',
    answer: 'B',
    explanation: '半坡人生活在黄河流域的陕西西安半坡村，居住半地穴式圆形房屋，适应北方干旱寒冷的气候。',
    difficulty: 1,
    options: '["A. 干栏式房屋","B. 半地穴式圆形房屋","C. 地面方形房屋","D. 窑洞"]',
  },
  {
    chapterKey: 'history-bubian-7-0',
    questionKey: 'history-bubian-7-0-5',
    type: 'choice',
    questionText: '被尊为中华民族"人文初祖"的是（）',
    answer: 'D',
    explanation: '炎帝和黄帝被后人尊为中华民族的人文初祖，华夏族逐渐形成。',
    difficulty: 1,
    options: '["A. 炎帝","B. 黄帝","C. 蚩尤","D. 炎帝和黄帝"]',
  },
  {
    chapterKey: 'history-bubian-7-0',
    questionKey: 'history-bubian-7-0-6',
    type: 'choice',
    questionText: '传说中"三过家门而不入"的治水英雄是（）',
    answer: 'C',
    explanation: '大禹受命治水，三过家门而不入，采用疏导的方法成功治理了水患。',
    difficulty: 1,
    options: '["A. 黄帝","B. 舜","C. 禹","D. 鲧"]',
  },
  {
    chapterKey: 'history-bubian-7-0',
    questionKey: 'history-bubian-7-0-7',
    type: 'choice',
    questionText: '河姆渡原始居民的房屋样式与半坡原始居民不同，根本原因是（）',
    answer: 'D',
    explanation: '河姆渡人居住干栏式房屋，半坡人居住半地穴式房屋，根本原因是两地自然地理环境不同：河姆渡地处湿热多雨的长江流域，半坡地处干燥的黄河流域。',
    difficulty: 3,
    options: '["A. 生产工具不同","B. 劳动技术不同","C. 生活习惯不同","D. 自然地理环境不同"]',
  },
  {
    chapterKey: 'history-bubian-7-0',
    questionKey: 'history-bubian-7-0-8',
    type: 'choice',
    questionText: '尧舜禹时期，部落联盟首领的更替实行（）',
    answer: 'A',
    explanation: '尧舜禹时期实行禅让制，将首领位置传给贤德之人。',
    difficulty: 1,
    options: '["A. 禅让制","B. 世袭制","C. 分封制","D. 选举制"]',
  },

  // fill 4题
  {
    chapterKey: 'history-bubian-7-0',
    questionKey: 'history-bubian-7-0-9',
    type: 'fill',
    questionText: '北京人距今约______万年，发现地点在北京______。',
    answer: '70-20；周口店龙骨山',
    explanation: '北京人距今约70万年至20万年，发现于北京西南周口店龙骨山。',
    difficulty: 1,
    acceptableAnswers: '["70至20；周口店龙骨山","70~20；周口店龙骨山"]',
  },
  {
    chapterKey: 'history-bubian-7-0',
    questionKey: 'history-bubian-7-0-10',
    type: 'fill',
    questionText: '半坡原始居民生活在______流域，主要种植______。',
    answer: '黄河；粟',
    explanation: '半坡人生活在黄河流域的陕西西安半坡村，主要种植粟。',
    difficulty: 1,
  },
  {
    chapterKey: 'history-bubian-7-0',
    questionKey: 'history-bubian-7-0-11',
    type: 'fill',
    questionText: '______的发明改变了人类茹毛饮血的生活方式。',
    answer: '火',
    explanation: '火的发明和使用使人类可以吃熟食，促进了脑的发育和体质的进步。',
    difficulty: 1,
  },
  {
    chapterKey: 'history-bubian-7-0',
    questionKey: 'history-bubian-7-0-12',
    type: 'fill',
    questionText: '河姆渡原始居民生活在______流域，距今约______年。',
    answer: '长江；7000',
    explanation: '河姆渡人距今约7000年，生活在长江流域的浙江余姚河姆渡村。',
    difficulty: 2,
  },

  // short_answer 5题
  {
    chapterKey: 'history-bubian-7-0',
    questionKey: 'history-bubian-7-0-13',
    type: 'short_answer',
    questionText: '简述北京人的生产和生活状况。',
    answer: '北京人会使用打制石器（旧石器时代），使用天然火，以采集和狩猎为生，群居生活。',
    explanation: '北京人已经会使用打制石器，使用并保存天然火，靠采集、狩猎为生，过着群居生活。',
    difficulty: 1,
  },
  {
    chapterKey: 'history-bubian-7-0',
    questionKey: 'history-bubian-7-0-14',
    type: 'short_answer',
    questionText: '比较河姆渡人和半坡人在生产生活上的主要区别。',
    answer: '河姆渡人生活在长江流域，种植水稻，居住干栏式房屋；半坡人生活在黄河流域，种植粟，居住半地穴式圆形房屋。两者都使用磨制石器，会制造陶器。',
    explanation: '两者分别代表了长江流域和黄河流域的农耕文明，因自然环境不同而在农作物种类和房屋样式上存在差异。',
    difficulty: 2,
  },
  {
    chapterKey: 'history-bubian-7-0',
    questionKey: 'history-bubian-7-0-15',
    type: 'short_answer',
    questionText: '传说中炎帝和黄帝有哪些发明贡献？',
    answer: '炎帝教民开垦耕种，制作生产工具，种植五谷蔬菜，制作陶器，发明纺织，会煮盐，教人们通商交换。黄帝能建造宫室，制作衣裳，挖掘水井，制造船只，会炼铜，发明弓箭。其下属还发明了文字、历法、算术和音乐。',
    explanation: '这些传说反映了中华文明起源时期先民们的伟大创造。',
    difficulty: 2,
  },
  {
    chapterKey: 'history-bubian-7-0',
    questionKey: 'history-bubian-7-0-16',
    type: 'short_answer',
    questionText: '什么是禅让制？',
    answer: '禅让制是尧舜禹时期推举部落联盟首领的办法，即将首领之位传给贤德之人。尧传位于舜，舜传位于禹，都是通过禅让的方式实现的。',
    explanation: '禅让制体现了原始社会民主推选首领的制度，与后来的王位世袭制形成鲜明对比。',
    difficulty: 1,
  },
  {
    chapterKey: 'history-bubian-7-0',
    questionKey: 'history-bubian-7-0-17',
    type: 'short_answer',
    questionText: '大禹治水为什么能取得成功？给我们什么启示？',
    answer: '大禹治水成功的原因：采用了科学疏导的方法（而不是他父亲鲧的堵截方法），三过家门而不入，身先士卒，有献身精神。启示：面对困难要勇于担当，采用科学方法解决问题。',
    explanation: '大禹治水成功的关键在于方法得当和坚持不懈的精神。',
    difficulty: 3,
  },

  // matching 2题
  {
    chapterKey: 'history-bubian-7-0',
    questionKey: 'history-bubian-7-0-18',
    type: 'matching',
    questionText: '请将下列远古居民与其生活的流域连线匹配。',
    answer: '元谋人—长江流域；北京人—黄河流域；河姆渡人—长江流域；半坡人—黄河流域；山顶洞人—黄河流域',
    explanation: '元谋人发现于云南（长江上游），北京人和山顶洞人在北京周口店（黄河流域），河姆渡人在浙江余姚（长江下游），半坡人在陕西西安（黄河中游）。',
    difficulty: 1,
    pairs: '[["元谋人","长江流域"],["北京人","黄河流域"],["河姆渡人","长江流域"],["半坡人","黄河流域"],["山顶洞人","黄河流域"]]',
  },
  {
    chapterKey: 'history-bubian-7-0',
    questionKey: 'history-bubian-7-0-19',
    type: 'matching',
    questionText: '请将下列原始居民与其种植的农作物和居住房屋匹配。',
    answer: '河姆渡人—水稻—干栏式房屋；半坡人—粟—半地穴式房屋；北京人—未种植—天然洞穴',
    explanation: '河姆渡人种水稻住干栏式，半坡人种粟住半地穴式，北京人以采集狩猎为生住天然洞穴。',
    difficulty: 2,
    pairs: '[["河姆渡人","水稻—干栏式房屋"],["半坡人","粟—半地穴式房屋"],["北京人","未种植—天然洞穴"]]',
  },

  // ========== 7-1 夏商周时期 (24题) ==========

  // choice 11题
  {
    chapterKey: 'history-bubian-7-1',
    questionKey: 'history-bubian-7-1-0',
    type: 'choice',
    questionText: '我国历史上第一个王朝是（）',
    answer: 'A',
    explanation: '约公元前2070年，禹建立夏朝，这是我国历史上第一个王朝，标志着中国早期国家的产生。',
    difficulty: 1,
    options: '["A. 夏朝","B. 商朝","C. 西周","D. 秦朝"]',
  },
  {
    chapterKey: 'history-bubian-7-1',
    questionKey: 'history-bubian-7-1-1',
    type: 'choice',
    questionText: '夏朝的建立者是（）',
    answer: 'C',
    explanation: '约公元前2070年，禹建立夏朝。',
    difficulty: 1,
    options: '["A. 启","B. 桀","C. 禹","D. 汤"]',
  },
  {
    chapterKey: 'history-bubian-7-1',
    questionKey: 'history-bubian-7-1-2',
    type: 'choice',
    questionText: '西周实行的政治制度中，最重要的是（）',
    answer: 'B',
    explanation: '西周实行分封制，周天子将土地和平民、奴隶分封给亲属和功臣，让他们建立诸侯国，拱卫王室。',
    difficulty: 1,
    options: '["A. 禅让制","B. 分封制","C. 郡县制","D. 世袭制"]',
  },
  {
    chapterKey: 'history-bubian-7-1',
    questionKey: 'history-bubian-7-1-3',
    type: 'choice',
    questionText: '商朝的文字刻写在龟甲和兽骨上，被称为（）',
    answer: 'D',
    explanation: '商朝人刻写在龟甲和兽骨上的文字被称为甲骨文，是我国已发现的古代文字中年代最早、体系较为完整的文字。',
    difficulty: 1,
    options: '["A. 金文","B. 小篆","C. 隶书","D. 甲骨文"]',
  },
  {
    chapterKey: 'history-bubian-7-1',
    questionKey: 'history-bubian-7-1-4',
    type: 'choice',
    questionText: '商朝的最后一个国王是（）',
    answer: 'C',
    explanation: '商朝末年，国王纣残暴无道，公元前1046年，周武王联合各部族在牧野大败商军，商朝灭亡。',
    difficulty: 1,
    options: '["A. 桀","B. 汤","C. 纣","D. 厉王"]',
  },
  {
    chapterKey: 'history-bubian-7-1',
    questionKey: 'history-bubian-7-1-5',
    type: 'choice',
    questionText: '下列青铜器中，是世界上现存最大的青铜器的是（）',
    answer: 'B',
    explanation: '商朝的司母戊鼎（又称后母戊鼎）是世界上现存最大的青铜器，重约832.84千克。',
    difficulty: 1,
    options: '["A. 四羊方尊","B. 司母戊鼎","C. 三星堆青铜面具","D. 毛公鼎"]',
  },
  {
    chapterKey: 'history-bubian-7-1',
    questionKey: 'history-bubian-7-1-6',
    type: 'choice',
    questionText: '春秋时期第一个称霸的诸侯是（）',
    answer: 'A',
    explanation: '春秋时期，齐桓公任用管仲为相进行改革，以"尊王攘夷"为号召，成为第一个霸主。',
    difficulty: 1,
    options: '["A. 齐桓公","B. 晋文公","C. 楚庄王","D. 秦穆公"]',
  },
  {
    chapterKey: 'history-bubian-7-1',
    questionKey: 'history-bubian-7-1-7',
    type: 'choice',
    questionText: '战国时期，秦国的变法改革是（）',
    answer: 'D',
    explanation: '公元前356年，秦孝公任用商鞅变法，使秦国的经济得到发展，军队战斗力不断增强，成为战国后期最强大的国家。',
    difficulty: 1,
    options: '["A. 管仲改革","B. 李悝变法","C. 吴起变法","D. 商鞅变法"]',
  },
  {
    chapterKey: 'history-bubian-7-1',
    questionKey: 'history-bubian-7-1-8',
    type: 'choice',
    questionText: '老子是道家学派的创始人，其核心思想是（）',
    answer: 'B',
    explanation: '老子认为万物运行有其自然规律，提出"无为而治"的政治主张。他的学说记录在《道德经》中。',
    difficulty: 2,
    options: '["A. 仁","B. 无为而治","C. 兼爱","D. 法治"]',
  },
  {
    chapterKey: 'history-bubian-7-1',
    questionKey: 'history-bubian-7-1-9',
    type: 'choice',
    questionText: '儒家学派的创始人是（）',
    answer: 'A',
    explanation: '孔子是春秋末期鲁国人，儒家学派创始人，核心思想是"仁"，主张"仁者爱人"。',
    difficulty: 1,
    options: '["A. 孔子","B. 孟子","C. 荀子","D. 老子"]',
  },
  {
    chapterKey: 'history-bubian-7-1',
    questionKey: 'history-bubian-7-1-10',
    type: 'choice',
    questionText: '商鞅变法中对后世影响最深远的措施是（）',
    answer: 'D',
    explanation: '商鞅变法中确立县制，由国君直接派官吏治理，这为以后建立中央集权制度奠定了基础。',
    difficulty: 3,
    options: '["A. 编定户口","B. 奖励生产","C. 奖励军功","D. 确立县制"]',
  },

  // fill 5题
  {
    chapterKey: 'history-bubian-7-1',
    questionKey: 'history-bubian-7-1-11',
    type: 'fill',
    questionText: '约公元前______年，禹建立______朝，这是我国历史上第一个王朝。',
    answer: '2070；夏',
    explanation: '约公元前2070年，禹建立夏朝，我国早期国家产生。',
    difficulty: 1,
  },
  {
    chapterKey: 'history-bubian-7-1',
    questionKey: 'history-bubian-7-1-12',
    type: 'fill',
    questionText: '商朝的文字刻写在龟甲和兽骨上，被称为______，我国有文字可考的历史从______朝开始。',
    answer: '甲骨文；商',
    explanation: '甲骨文是商朝刻写在龟甲兽骨上的文字，中国有文字可考的历史从商朝开始。',
    difficulty: 1,
  },
  {
    chapterKey: 'history-bubian-7-1',
    questionKey: 'history-bubian-7-1-13',
    type: 'fill',
    questionText: '西周实行的政治制度是______，统治者等级从高到低依次为______。',
    answer: '分封制；天子—诸侯—卿大夫—士',
    explanation: '西周实行分封制，形成了天子、诸侯、卿大夫、士的等级序列。',
    difficulty: 2,
  },
  {
    chapterKey: 'history-bubian-7-1',
    questionKey: 'history-bubian-7-1-14',
    type: 'fill',
    questionText: '公元前1046年，______通过牧野之战灭商，建立______朝。',
    answer: '周武王；周（西周）',
    explanation: '周武王联合各部族在牧野击败商军，商朝灭亡，周朝建立（定都镐京，史称西周）。',
    difficulty: 1,
    acceptableAnswers: '["周武王；周","周武王；西周"]',
  },
  {
    chapterKey: 'history-bubian-7-1',
    questionKey: 'history-bubian-7-1-15',
    type: 'fill',
    questionText: '墨家学派的创始人是______，其核心主张是______。',
    answer: '墨子；兼爱、非攻',
    explanation: '墨子是墨家创始人，主张"兼爱""非攻"，希望人们互助互爱，反对不义战争。',
    difficulty: 2,
  },

  // short_answer 6题
  {
    chapterKey: 'history-bubian-7-1',
    questionKey: 'history-bubian-7-1-16',
    type: 'short_answer',
    questionText: '简述分封制的主要内容和作用。',
    answer: '内容：周天子将土地和平民、奴隶分封给宗亲和功臣等，让他们建立诸侯国，拱卫王室。作用：稳定了政局，扩大了统治范围。但诸侯在自己的领地内享有较大的独立性，随着时间推移，诸侯之间兼并战争日益激烈，周天子逐渐失去控制。',
    explanation: '分封制是西周的重要政治制度，前期巩固了统治，后期导致了分裂割据。',
    difficulty: 2,
  },
  {
    chapterKey: 'history-bubian-7-1',
    questionKey: 'history-bubian-7-1-17',
    type: 'short_answer',
    questionText: '商鞅变法的主要内容有哪些？',
    answer: '（1）政治上：确立县制，由国君直接派官吏治理；废除贵族的世袭特权；改革户籍制度，加强对人民的管控。（2）经济上：废除井田制，允许土地自由买卖；鼓励耕织，生产粮食和布帛多的人可免除徭役；统一度量衡。（3）军事上：奖励军功，对有军功者授予爵位并赏赐土地。',
    explanation: '商鞅变法使秦国富国强兵，为统一六国奠定了基础。',
    difficulty: 2,
  },
  {
    chapterKey: 'history-bubian-7-1',
    questionKey: 'history-bubian-7-1-18',
    type: 'short_answer',
    questionText: '简述甲骨文的历史意义。',
    answer: '甲骨文是中国已发现的古代文字中年代最早、体系较为完整的成熟文字。我国有文字可考的历史从商朝开始。甲骨文记载的内容十分丰富，涉及祭祀、战争、农牧业、官制等，是研究商朝历史的珍贵资料。甲骨文已经具备了汉字的基本结构，很多字体与今天的汉字一脉相承。',
    explanation: '甲骨文是中华文明的重要标志，对研究上古历史和汉字演变具有重大价值。',
    difficulty: 2,
  },
  {
    chapterKey: 'history-bubian-7-1',
    questionKey: 'history-bubian-7-1-19',
    type: 'short_answer',
    questionText: '百家争鸣局面出现的历史背景和意义是什么？',
    answer: '背景：战国时期社会急剧变化，各诸侯国纷纷变法图强。旧的社会制度进一步瓦解，新的社会制度逐步确立。许多思想家和学者纷纷发表见解，形成不同的学派。意义：促进了思想和学术的繁荣，成为中国古代第一次思想文化发展的高峰，为中国古代文化的发展奠定了基础。',
    explanation: '百家争鸣是春秋战国时期社会大变革的产物，是思想文化繁荣的黄金时期。',
    difficulty: 3,
  },
  {
    chapterKey: 'history-bubian-7-1',
    questionKey: 'history-bubian-7-1-20',
    type: 'short_answer',
    questionText: '孔子在教育方面有哪些主要贡献？',
    answer: '孔子不仅是一位伟大的思想家，也是一位伟大的教育家。他创办私学，打破了贵族对教育的垄断。他主张"有教无类"，不论贫富贵贱，都可入学。他注重因材施教，善于启发学生思考。他的教育思想和教学方法对后世影响深远。',
    explanation: '孔子的教育理念和实践奠定了中国古代教育的基础。',
    difficulty: 2,
  },
  {
    chapterKey: 'history-bubian-7-1',
    questionKey: 'history-bubian-7-1-21',
    type: 'short_answer',
    questionText: '春秋战国时期，哪些变法改革最为著名？各有何成效？',
    answer: '（1）管仲改革：齐桓公任用管仲改革，使齐国经济和军事实力大增，成为春秋首霸。（2）商鞅变法：秦孝公任用商鞅变法，使秦国经济发展、军力增强，成为战国最强盛的国家，为后来统一六国奠定了基础。其中商鞅变法最为彻底，成效最大。',
    explanation: '变法改革是春秋战国时期的时代潮流，推动了社会进步和国家富强。',
    difficulty: 3,
  },

  // matching 2题
  {
    chapterKey: 'history-bubian-7-1',
    questionKey: 'history-bubian-7-1-22',
    type: 'matching',
    questionText: '请将下列思想家与其所属学派及核心主张匹配。',
    answer: '孔子—儒家—仁；老子—道家—无为而治；墨子—墨家—兼爱非攻；韩非—法家—以法治国',
    explanation: '诸子百家各有自己的核心思想主张。',
    difficulty: 2,
    pairs: '[["孔子","儒家—仁"],["老子","道家—无为而治"],["墨子","墨家—兼爱非攻"],["韩非","法家—以法治国"]]',
  },
  {
    chapterKey: 'history-bubian-7-1',
    questionKey: 'history-bubian-7-1-23',
    type: 'matching',
    questionText: '请将下列历史事件与其对应的时间和人物匹配。',
    answer: '夏朝建立—约前2070年—禹；牧野之战—前1046年—周武王；商鞅变法—前356年—商鞅；齐桓公称霸—前7世纪中期—齐桓公',
    explanation: '这些是夏商周时期的重要历史事件及其对应时间。',
    difficulty: 2,
    pairs: '[["夏朝建立","约前2070年—禹"],["牧野之战","前1046年—周武王"],["商鞅变法","前356年—商鞅"],["齐桓公称霸","前7世纪中期—齐桓公"]]',
  },

  // ========== 7-2 秦汉时期 (28题) ==========

  // choice 13题
  {
    chapterKey: 'history-bubian-7-2',
    questionKey: 'history-bubian-7-2-0',
    type: 'choice',
    questionText: '秦统一六国是在（）',
    answer: 'B',
    explanation: '公元前230年—公元前221年，秦王嬴政陆续灭掉韩、赵、魏、楚、燕、齐六国，完成了统一大业。',
    difficulty: 1,
    options: '["A. 公元前230年","B. 公元前221年","C. 公元前210年","D. 公元前256年"]',
  },
  {
    chapterKey: 'history-bubian-7-2',
    questionKey: 'history-bubian-7-2-1',
    type: 'choice',
    questionText: '秦始皇创立的政治制度是（）',
    answer: 'C',
    explanation: '秦始皇建立了专制主义中央集权制度，皇帝总揽大权，中央设丞相、太尉、御史大夫，地方推行郡县制。',
    difficulty: 1,
    options: '["A. 分封制","B. 禅让制","C. 专制主义中央集权制度","D. 民主制度"]',
  },
  {
    chapterKey: 'history-bubian-7-2',
    questionKey: 'history-bubian-7-2-2',
    type: 'choice',
    questionText: '秦统一后，规定全国统一使用的文字是（）',
    answer: 'A',
    explanation: '秦始皇统一文字为小篆，后又推行更为简便的隶书，促进了文化的交流和统一。',
    difficulty: 1,
    options: '["A. 小篆","B. 楷书","C. 甲骨文","D. 金文"]',
  },
  {
    chapterKey: 'history-bubian-7-2',
    questionKey: 'history-bubian-7-2-3',
    type: 'choice',
    questionText: '秦朝修筑的抵御北方匈奴的伟大工程是（）',
    answer: 'D',
    explanation: '秦始皇为了防御匈奴，修筑了西起临洮、东到辽东的万里长城。',
    difficulty: 1,
    options: '["A. 灵渠","B. 都江堰","C. 郑国渠","D. 长城"]',
  },
  {
    chapterKey: 'history-bubian-7-2',
    questionKey: 'history-bubian-7-2-4',
    type: 'choice',
    questionText: '秦朝灭亡的根本原因是（）',
    answer: 'B',
    explanation: '秦朝的暴政（繁重的徭役、沉重的赋税、严酷的刑罚）使人民苦不堪言，阶级矛盾激化，是秦亡的根本原因。',
    difficulty: 2,
    options: '["A. 匈奴入侵","B. 秦的暴政","C. 陈胜吴广起义","D. 项羽刘邦起义"]',
  },
  {
    chapterKey: 'history-bubian-7-2',
    questionKey: 'history-bubian-7-2-5',
    type: 'choice',
    questionText: '中国历史上第一次大规模农民起义是（）',
    answer: 'A',
    explanation: '公元前209年，陈胜、吴广在大泽乡起义，这是中国历史上第一次大规模农民起义。',
    difficulty: 1,
    options: '["A. 大泽乡起义","B. 黄巾起义","C. 绿林赤眉起义","D. 李自成起义"]',
  },
  {
    chapterKey: 'history-bubian-7-2',
    questionKey: 'history-bubian-7-2-6',
    type: 'choice',
    questionText: '西汉的建立者是（）',
    answer: 'C',
    explanation: '公元前202年，刘邦（汉高祖）建立汉朝，定都长安，史称西汉。',
    difficulty: 1,
    options: '["A. 刘恒","B. 刘彻","C. 刘邦","D. 刘秀"]',
  },
  {
    chapterKey: 'history-bubian-7-2',
    questionKey: 'history-bubian-7-2-7',
    type: 'choice',
    questionText: '汉武帝为加强思想统一采取的措施是（）',
    answer: 'D',
    explanation: '汉武帝接受董仲舒的建议，"罢黜百家，独尊儒术"，把儒家学说立为正统思想。',
    difficulty: 1,
    options: '["A. 焚书坑儒","B. 推恩令","C. 设立太学","D. 罢黜百家，独尊儒术"]',
  },
  {
    chapterKey: 'history-bubian-7-2',
    questionKey: 'history-bubian-7-2-8',
    type: 'choice',
    questionText: '汉武帝削弱诸侯势力的措施是（）',
    answer: 'B',
    explanation: '汉武帝采纳主父偃的"推恩令"，允许诸侯王将自己的封地分给子弟，由皇帝赐予侯爵，不解除他们的封地。',
    difficulty: 2,
    options: '["A. 废除分封制","B. 推恩令","C. 削藩","D. 八股取士"]',
  },
  {
    chapterKey: 'history-bubian-7-2',
    questionKey: 'history-bubian-7-2-9',
    type: 'choice',
    questionText: '东汉的建立者是（）',
    answer: 'A',
    explanation: '公元25年，刘秀（汉光武帝）称帝，定都洛阳，史称东汉。',
    difficulty: 1,
    options: '["A. 刘秀","B. 刘邦","C. 刘备","D. 刘彻"]',
  },
  {
    chapterKey: 'history-bubian-7-2',
    questionKey: 'history-bubian-7-2-10',
    type: 'choice',
    questionText: '丝绸之路的开拓者是（）',
    answer: 'C',
    explanation: '张骞出使西域（第一次在前138年，第二次在前119年），开辟了通往西域的道路，即丝绸之路。',
    difficulty: 1,
    options: '["A. 卫青","B. 霍去病","C. 张骞","D. 班超"]',
  },
  {
    chapterKey: 'history-bubian-7-2',
    questionKey: 'history-bubian-7-2-11',
    type: 'choice',
    questionText: '东汉时期改进造纸术的是（）',
    answer: 'D',
    explanation: '东汉蔡伦改进造纸术，用树皮、麻头、破布、旧渔网等制作纸张，大大降低了造纸成本。',
    difficulty: 1,
    options: '["A. 张仲景","B. 华佗","C. 张衡","D. 蔡伦"]',
  },
  {
    chapterKey: 'history-bubian-7-2',
    questionKey: 'history-bubian-7-2-12',
    type: 'choice',
    questionText: '被后世尊为"医圣"的是（）',
    answer: 'A',
    explanation: '东汉末年张仲景写成《伤寒杂病论》，总结了各种疾病的辨证施治方法，被后世尊为"医圣"。',
    difficulty: 1,
    options: '["A. 张仲景","B. 华佗","C. 扁鹊","D. 李时珍"]',
  },

  // fill 6题
  {
    chapterKey: 'history-bubian-7-2',
    questionKey: 'history-bubian-7-2-13',
    type: 'fill',
    questionText: '秦王嬴政灭六国后，自称______，确立专制主义中央集权制度。',
    answer: '始皇帝（秦始皇）',
    explanation: '嬴政认为自己"德兼三皇，功盖五帝"，因此自创"皇帝"称号，自称始皇帝。',
    difficulty: 1,
    acceptableAnswers: '["始皇帝","秦始皇"]',
  },
  {
    chapterKey: 'history-bubian-7-2',
    questionKey: 'history-bubian-7-2-14',
    type: 'fill',
    questionText: '秦始皇在地方推行的行政制度是______，全国分为______郡。',
    answer: '郡县制；36',
    explanation: '秦始皇废除分封制，在全国推行郡县制，初分36郡，后增至40多郡。',
    difficulty: 1,
  },
  {
    chapterKey: 'history-bubian-7-2',
    questionKey: 'history-bubian-7-2-15',
    type: 'fill',
    questionText: '秦统一后，全国统一使用的货币是______，圆形______。',
    answer: '半两钱；方孔',
    explanation: '秦始皇统一货币为圆形方孔半两钱，统一了度量衡。',
    difficulty: 1,
  },
  {
    chapterKey: 'history-bubian-7-2',
    questionKey: 'history-bubian-7-2-16',
    type: 'fill',
    questionText: '______年，陈胜、吴广在______发动起义。',
    answer: '公元前209；大泽乡',
    explanation: '公元前209年，陈胜吴广在大泽乡揭竿而起，打响反抗秦朝暴政的第一枪。',
    difficulty: 1,
  },
  {
    chapterKey: 'history-bubian-7-2',
    questionKey: 'history-bubian-7-2-17',
    type: 'fill',
    questionText: '丝绸之路从______出发，经河西走廊，通往______，最远到达______。',
    answer: '长安；西域；大秦（罗马帝国）',
    explanation: '丝绸之路从长安出发，经河西走廊、西域，越过葱岭，可达中亚、西亚，最远到达大秦。',
    difficulty: 2,
    acceptableAnswers: '["长安；西域；欧洲","长安；西域；罗马"]',
  },
  {
    chapterKey: 'history-bubian-7-2',
    questionKey: 'history-bubian-7-2-18',
    type: 'fill',
    questionText: '东汉______发明了地动仪，这是世界上最早的地震测量仪器。',
    answer: '张衡',
    explanation: '东汉张衡发明地动仪，能够准确测定地震方位，是世界上最早的地震测量仪器。',
    difficulty: 1,
  },

  // short_answer 7题
  {
    chapterKey: 'history-bubian-7-2',
    questionKey: 'history-bubian-7-2-19',
    type: 'short_answer',
    questionText: '简述秦始皇巩固统一的措施。',
    answer: '（1）政治：建立专制主义中央集权制度，皇帝总揽大权，中央设丞相、太尉、御史大夫，地方推行郡县制。（2）经济：统一货币（半两钱）、统一度量衡。（3）文化：统一文字（小篆）。（4）交通和军事：统一车轨，修筑驰道、长城和灵渠。（5）思想：焚书坑儒。',
    explanation: '秦始皇采取一系列措施巩固了统一的多民族国家。',
    difficulty: 2,
  },
  {
    chapterKey: 'history-bubian-7-2',
    questionKey: 'history-bubian-7-2-20',
    type: 'short_answer',
    questionText: '秦朝的暴政主要表现在哪些方面？',
    answer: '（1）沉重的赋税，约把农民收获的三分之二上交国家。（2）繁重的徭役和兵役，修长城、建阿房宫和骊山陵墓等耗费大量人力物力。（3）严酷的法律，动辄判处死刑或连坐族诛。（4）秦始皇和秦二世生活奢侈，加重了对人民的剥削。',
    explanation: '秦的暴政使社会矛盾尖锐，最终导致了农民起义和秦朝的灭亡。',
    difficulty: 2,
  },
  {
    chapterKey: 'history-bubian-7-2',
    questionKey: 'history-bubian-7-2-21',
    type: 'short_answer',
    questionText: '简述汉武帝加强中央集权的措施。',
    answer: '（1）政治：采纳主父偃"推恩令"削弱诸侯，设刺史监察地方。（2）思想：接受董仲舒建议，"罢黜百家，独尊儒术"。（3）经济：收回盐铁经营权为中央所有，统一铸造五铢钱。（4）军事：派卫青、霍去病北击匈奴，解除匈奴威胁。（5）外交：派张骞出使西域，开辟丝绸之路。',
    explanation: '汉武帝从多方面加强中央集权，使西汉进入鼎盛时期。',
    difficulty: 2,
  },
  {
    chapterKey: 'history-bubian-7-2',
    questionKey: 'history-bubian-7-2-22',
    type: 'short_answer',
    questionText: '简述张骞出使西域的经过和意义。',
    answer: '经过：公元前138年，张骞第一次出使西域，目的是联络大月氏夹击匈奴，但未能完成使命，却了解了西域各国的地形、物产和风俗。公元前119年，张骞第二次出使西域，与西域各国建立了友好关系。意义：张骞出使西域开辟了丝绸之路，促进了汉朝与西域乃至欧洲的经济文化交流。',
    explanation: '张骞出使西域是中国古代对外交流史上的壮举。',
    difficulty: 2,
  },
  {
    chapterKey: 'history-bubian-7-2',
    questionKey: 'history-bubian-7-2-23',
    type: 'short_answer',
    questionText: '东汉时期有哪些重要的科技成就？',
    answer: '（1）蔡伦改进造纸术，用树皮、麻头等廉价材料制成植物纤维纸。（2）张衡发明地动仪，是世界上最早的地震测量仪器。（3）华佗发明麻醉药"麻沸散"，创编"五禽戏"。（4）张仲景写成《伤寒杂病论》，提出辨证施治，被尊为"医圣"。',
    explanation: '东汉科技成就辉煌，造纸术更是四大发明之一。',
    difficulty: 3,
  },
  {
    chapterKey: 'history-bubian-7-2',
    questionKey: 'history-bubian-7-2-24',
    type: 'short_answer',
    questionText: '秦朝速亡的原因和教训是什么？',
    answer: '原因：秦的暴政导致社会矛盾尖锐，陈胜吴广起义揭开了农民起义的序幕，最终推翻秦朝。教训：统治者应爱惜民力、轻徭薄赋、实行仁政，才能长治久安。"得民心者得天下，失民心者失天下"。',
    explanation: '秦的速亡对后世统治者提供了深刻的历史教训。',
    difficulty: 3,
  },
  {
    chapterKey: 'history-bubian-7-2',
    questionKey: 'history-bubian-7-2-25',
    type: 'short_answer',
    questionText: '丝绸之路在中外交流中有何重要作用？',
    answer: '丝绸之路是古代东西方之间的交通要道。通过丝绸之路，中国的丝绸、瓷器、铁器等商品输往西方，西方的良马、毛皮、香料等也传入中国。它促进了东西方的经济文化交流，加深了各国之间的友好往来，是古代最重要的国际通道之一。',
    explanation: '丝绸之路是沟通古代东西方文明的桥梁。',
    difficulty: 2,
  },

  // matching 2题
  {
    chapterKey: 'history-bubian-7-2',
    questionKey: 'history-bubian-7-2-26',
    type: 'matching',
    questionText: '请将下列历史人物与其主要成就匹配。',
    answer: '秦始皇—统一六国，建立中央集权；汉武帝—巩固统一，独尊儒术；张骞—出使西域，开辟丝路；蔡伦—改进造纸术；张仲景—写成《伤寒杂病论》',
    explanation: '这些都是秦汉时期的重要历史人物及其贡献。',
    difficulty: 2,
    pairs: '[["秦始皇","统一六国，建立中央集权"],["汉武帝","巩固统一，独尊儒术"],["张骞","出使西域，开辟丝路"],["蔡伦","改进造纸术"],["张仲景","写成伤寒杂病论"]]',
  },
  {
    chapterKey: 'history-bubian-7-2',
    questionKey: 'history-bubian-7-2-27',
    type: 'matching',
    questionText: '请将下列朝代与其对应的时间和都城匹配。',
    answer: '秦朝—前221年—咸阳；西汉—前202年—长安；新朝—公元8年—长安；东汉—25年—洛阳',
    explanation: '秦汉时期各朝代建立的时间及都城。',
    difficulty: 2,
    pairs: '[["秦朝","前221年—咸阳"],["西汉","前202年—长安"],["新朝","公元8年—长安"],["东汉","25年—洛阳"]]',
  },

  // ========== 7-3 三国两晋南北朝时期 (22题) ==========

  // choice 10题
  {
    chapterKey: 'history-bubian-7-3',
    questionKey: 'history-bubian-7-3-0',
    type: 'choice',
    questionText: '三国鼎立的局面形成于（）之后。',
    answer: 'B',
    explanation: '208年赤壁之战后，曹操退回北方，孙权巩固了江东，刘备占领荆州并进入益州，三国鼎立的局面基本形成。220年曹丕建魏，221年刘备建蜀汉，222年孙权称吴王（229年称帝），三国正式鼎立。',
    difficulty: 1,
    options: '["A. 官渡之战","B. 赤壁之战","C. 淝水之战","D. 夷陵之战"]',
  },
  {
    chapterKey: 'history-bubian-7-3',
    questionKey: 'history-bubian-7-3-1',
    type: 'choice',
    questionText: '赤壁之战中，孙刘联军使用的战术是（）',
    answer: 'A',
    explanation: '赤壁之战中，孙刘联军采用火攻战术，借东南风火烧曹军战船，大败曹操。',
    difficulty: 1,
    options: '["A. 火攻","B. 水淹","C. 奇袭","D. 围困"]',
  },
  {
    chapterKey: 'history-bubian-7-3',
    questionKey: 'history-bubian-7-3-2',
    type: 'choice',
    questionText: '三国时期，魏国的建立者是（）',
    answer: 'C',
    explanation: '220年，曹操之子曹丕废汉献帝，自立为帝，国号魏，定都洛阳。',
    difficulty: 1,
    options: '["A. 曹操","B. 曹植","C. 曹丕","D. 司马炎"]',
  },
  {
    chapterKey: 'history-bubian-7-3',
    questionKey: 'history-bubian-7-3-3',
    type: 'choice',
    questionText: '西晋的统一时间是（）',
    answer: 'A',
    explanation: '266年司马炎建立西晋，280年西晋灭吴，完成统一。',
    difficulty: 2,
    options: '["A. 280年","B. 266年","C. 316年","D. 220年"]',
  },
  {
    chapterKey: 'history-bubian-7-3',
    questionKey: 'history-bubian-7-3-4',
    type: 'choice',
    questionText: '东晋南朝时期，江南地区得到开发的最主要原因是（）',
    answer: 'C',
    explanation: '北民南迁给江南地区带来了大量劳动力、先进的生产工具和 技术，促进了江南经济的发展。',
    difficulty: 2,
    options: '["A. 江南自然条件优越","B. 南方统治者重视农业","C. 北方人口大量南迁","D. 战争促进科技进步"]',
  },
  {
    chapterKey: 'history-bubian-7-3',
    questionKey: 'history-bubian-7-3-5',
    type: 'choice',
    questionText: '北魏孝文帝改革的根本目的是（）',
    answer: 'B',
    explanation: '北魏孝文帝推行汉化改革的根本目的是学习汉族先进文化，加强对中原地区的控制，巩固北魏统治。',
    difficulty: 2,
    options: '["A. 发展经济","B. 巩固北魏统治","C. 统一全国","D. 促进民族融合"]',
  },
  {
    chapterKey: 'history-bubian-7-3',
    questionKey: 'history-bubian-7-3-6',
    type: 'choice',
    questionText: '北魏孝文帝迁都到（）',
    answer: 'D',
    explanation: '494年，北魏孝文帝将都城从平城迁到洛阳，以便于学习和接受汉族先进文化。',
    difficulty: 1,
    options: '["A. 长安","B. 咸阳","C. 开封","D. 洛阳"]',
  },
  {
    chapterKey: 'history-bubian-7-3',
    questionKey: 'history-bubian-7-3-7',
    type: 'choice',
    questionText: '东晋的建立者是（）',
    answer: 'A',
    explanation: '317年，司马睿建立东晋，定都建康（今南京）。',
    difficulty: 1,
    options: '["A. 司马睿","B. 司马炎","C. 司马昭","D. 司马懿"]',
  },
  {
    chapterKey: 'history-bubian-7-3',
    questionKey: 'history-bubian-7-3-8',
    type: 'choice',
    questionText: '淝水之战中，以少胜多打败前秦的是（）',
    answer: 'B',
    explanation: '383年，东晋以8万军队击败前秦苻坚的80多万大军，这是著名的以少胜多的战役。',
    difficulty: 1,
    options: '["A. 西晋","B. 东晋","C. 南朝","D. 北魏"]',
  },
  {
    chapterKey: 'history-bubian-7-3',
    questionKey: 'history-bubian-7-3-9',
    type: 'choice',
    questionText: '被称为"书圣"的东晋书法家是（）',
    answer: 'A',
    explanation: '东晋书法家王羲之被称为"书圣"，其代表作《兰亭集序》被称为"天下第一行书"。',
    difficulty: 1,
    options: '["A. 王羲之","B. 颜真卿","C. 柳公权","D. 欧阳询"]',
  },

  // fill 4题
  {
    chapterKey: 'history-bubian-7-3',
    questionKey: 'history-bubian-7-3-10',
    type: 'fill',
    questionText: '208年，孙刘联军与曹军在______交战，奠定了______局面形成的基础。',
    answer: '赤壁；三国鼎立',
    explanation: '赤壁之战是三国鼎立局面形成的关键战役。',
    difficulty: 1,
  },
  {
    chapterKey: 'history-bubian-7-3',
    questionKey: 'history-bubian-7-3-11',
    type: 'fill',
    questionText: '东晋南朝时期，北方人口大量南迁，给南方带来了______和______，促进了江南地区的开发。',
    answer: '劳动力；先进的生产技术',
    explanation: '北民南迁为江南开发提供了劳动力和先进技术。',
    difficulty: 1,
  },
  {
    chapterKey: 'history-bubian-7-3',
    questionKey: 'history-bubian-7-3-12',
    type: 'fill',
    questionText: '北魏孝文帝改革中，规定官员在朝廷中必须使用______，禁用______。',
    answer: '汉语；鲜卑语',
    explanation: '孝文帝推行汉化政策，要求说汉语、穿汉服、用汉姓、与汉族通婚。',
    difficulty: 1,
  },
  {
    chapterKey: 'history-bubian-7-3',
    questionKey: 'history-bubian-7-3-13',
    type: 'fill',
    questionText: '南朝包括______、______、______、______四个朝代。',
    answer: '宋；齐；梁；陈',
    explanation: '南朝（420—589年）依次为宋、齐、梁、陈四个朝代，都城都在建康。',
    difficulty: 2,
  },

  // short_answer 6题
  {
    chapterKey: 'history-bubian-7-3',
    questionKey: 'history-bubian-7-3-14',
    type: 'short_answer',
    questionText: '简述三国鼎立局面形成的过程。',
    answer: '200年官渡之战，曹操打败袁绍，统一北方。208年赤壁之战，孙刘联军大败曹操，奠定三分天下格局。220年曹丕建魏（洛阳），221年刘备建蜀汉（成都），229年孙权建吴（建业），三国鼎立局面正式形成。280年西晋灭吴，三国结束。',
    explanation: '从官渡之战到赤壁之战再到三国建立，是三国鼎立局面形成的过程。',
    difficulty: 2,
  },
  {
    chapterKey: 'history-bubian-7-3',
    questionKey: 'history-bubian-7-3-15',
    type: 'short_answer',
    questionText: '江南地区在三国两晋南北朝时期得到开发的原因和表现。',
    answer: '原因：（1）北方人口大量南迁，带来劳动力和先进技术。（2）江南地区自然条件优越。（3）南方战乱较少，社会相对安定。（4）南北方劳动人民的共同开发。表现：修建水利工程，开垦荒地，农业、手工业和商业迅速发展，南方的经济水平逐渐接近北方。',
    explanation: '江南经济的开发为后来经济重心南移奠定了基础。',
    difficulty: 2,
  },
  {
    chapterKey: 'history-bubian-7-3',
    questionKey: 'history-bubian-7-3-16',
    type: 'short_answer',
    questionText: '简述北魏孝文帝改革的内容和意义。',
    answer: '内容：（1）迁都洛阳。（2）说汉语：官员在朝廷中必须使用汉语，禁用鲜卑语。（3）穿汉服：以汉服代替鲜卑服。（4）改汉姓：将鲜卑姓氏改为汉姓（如拓跋改为元）。（5）与汉通婚：鼓励鲜卑贵族与汉族贵族通婚。（6）用汉制：采用汉族官制、律令。意义：促进了民族融合，推动了北方经济文化的发展。',
    explanation: '北魏孝文帝改革是民族融合的典范。',
    difficulty: 2,
  },
  {
    chapterKey: 'history-bubian-7-3',
    questionKey: 'history-bubian-7-3-17',
    type: 'short_answer',
    questionText: '三国两晋南北朝时期有哪些重要的文化成就？',
    answer: '（1）书法：王羲之被称为"书圣"，代表作《兰亭集序》。（2）绘画：东晋顾恺之代表作《洛神赋图》《女史箴图》。（3）数学：南朝祖冲之在世界上首次将圆周率精确到小数点后第七位（3.1415926到3.1415927之间）。（4）农学：北朝贾思勰著有《齐民要术》。（5）地理：郦道元著有《水经注》。',
    explanation: '这一时期虽然政局动荡，但文化科技成就斐然。',
    difficulty: 3,
  },
  {
    chapterKey: 'history-bubian-7-3',
    questionKey: 'history-bubian-7-3-18',
    type: 'short_answer',
    questionText: '比较赤壁之战和淝水之战的异同。',
    answer: '相同点：都是南方政权以少胜多打败北方政权的著名战役。不同点：（1）赤壁之战（208年）是孙刘联军打败曹操，奠定三国鼎立局面；（2）淝水之战（383年）是东晋打败前秦苻坚，使前秦迅速瓦解，东晋得以巩固统治，南北对峙局面延续。',
    explanation: '这两场战役都是历史上以少胜多的经典战役，对中国历史格局产生了深远影响。',
    difficulty: 3,
  },
  {
    chapterKey: 'history-bubian-7-3',
    questionKey: 'history-bubian-7-3-19',
    type: 'short_answer',
    questionText: '这一时期的民族融合有何历史意义？',
    answer: '三国两晋南北朝时期是民族大融合时期。北方少数民族内迁与汉族杂居，在生产、生活、文化上相互交流学习。北魏孝文帝改革更是大大加速了民族融合的进程。民族融合为隋唐时期的大一统和多民族国家的发展奠定了基础，丰富了中华民族的文化内涵。',
    explanation: '民族融合是这一时期最重要的历史趋势之一。',
    difficulty: 3,
  },

  // matching 2题
  {
    chapterKey: 'history-bubian-7-3',
    questionKey: 'history-bubian-7-3-20',
    type: 'matching',
    questionText: '请将三国政权与其建立者和都城匹配。',
    answer: '魏—曹丕—洛阳；蜀汉—刘备—成都；吴—孙权—建业（建康）',
    explanation: '三国各自的建立者和都城。',
    difficulty: 1,
    pairs: '[["魏","曹丕—洛阳"],["蜀汉","刘备—成都"],["吴","孙权—建业"]]',
  },
  {
    chapterKey: 'history-bubian-7-3',
    questionKey: 'history-bubian-7-3-21',
    type: 'matching',
    questionText: '请将下列人物与其成就匹配。',
    answer: '王羲之—书圣，《兰亭集序》；祖冲之—圆周率精确到第七位；贾思勰—《齐民要术》；顾恺之—《洛神赋图》；郦道元—《水经注》',
    explanation: '这些是三国两晋南北朝时期的重要文化人物及成就。',
    difficulty: 2,
    pairs: '[["王羲之","书圣，兰亭集序"],["祖冲之","圆周率精确到第七位"],["贾思勰","齐民要术"],["顾恺之","洛神赋图"],["郦道元","水经注"]]',
  },

  // ========== 8-0 隋唐时期 (28题) ==========

  // choice 12题
  {
    chapterKey: 'history-bubian-8-0',
    questionKey: 'history-bubian-8-0-0',
    type: 'choice',
    questionText: '隋朝统一全国的时间是（）',
    answer: 'B',
    explanation: '581年杨坚建立隋朝，589年隋灭陈，统一全国。',
    difficulty: 1,
    options: '["A. 581年","B. 589年","C. 618年","D. 627年"]',
  },
  {
    chapterKey: 'history-bubian-8-0',
    questionKey: 'history-bubian-8-0-1',
    type: 'choice',
    questionText: '隋朝大运河的中心是（）',
    answer: 'C',
    explanation: '隋炀帝开凿大运河，以洛阳为中心，北达涿郡（北京），南至余杭（杭州），全长2700多千米。',
    difficulty: 1,
    options: '["A. 长安","B. 建康","C. 洛阳","D. 开封"]',
  },
  {
    chapterKey: 'history-bubian-8-0',
    questionKey: 'history-bubian-8-0-2',
    type: 'choice',
    questionText: '科举制正式诞生于（）',
    answer: 'A',
    explanation: '隋炀帝时设进士科，标志着科举制的正式诞生。',
    difficulty: 1,
    options: '["A. 隋朝","B. 唐朝","C. 宋朝","D. 明朝"]',
  },
  {
    chapterKey: 'history-bubian-8-0',
    questionKey: 'history-bubian-8-0-3',
    type: 'choice',
    questionText: '唐朝的建立者是（）',
    answer: 'D',
    explanation: '618年，李渊在太原起兵，建立唐朝，定都长安。',
    difficulty: 1,
    options: '["A. 李世民","B. 李治","C. 杨坚","D. 李渊"]',
  },
  {
    chapterKey: 'history-bubian-8-0',
    questionKey: 'history-bubian-8-0-4',
    type: 'choice',
    questionText: '唐太宗的年号是（）',
    answer: 'B',
    explanation: '李世民（唐太宗）的年号为"贞观"，他在位期间政治清明、经济发展，史称"贞观之治"。',
    difficulty: 1,
    options: '["A. 开元","B. 贞观","C. 开宝","D. 武德"]',
  },
  {
    chapterKey: 'history-bubian-8-0',
    questionKey: 'history-bubian-8-0-5',
    type: 'choice',
    questionText: '中国历史上唯一的女皇帝是（）',
    answer: 'C',
    explanation: '武则天是中国历史上唯一的女皇帝，她在位期间社会经济继续发展，史称"政启开元，治宏贞观"。',
    difficulty: 1,
    options: '["A. 慈禧太后","B. 萧太后","C. 武则天","D. 吕后"]',
  },
  {
    chapterKey: 'history-bubian-8-0',
    questionKey: 'history-bubian-8-0-6',
    type: 'choice',
    questionText: '唐朝鼎盛时期（开元盛世）的皇帝是（）',
    answer: 'A',
    explanation: '唐玄宗统治前期，年号开元，政治稳定、经济繁荣、文化灿烂，唐朝进入鼎盛时期，史称"开元盛世"。',
    difficulty: 1,
    options: '["A. 唐玄宗","B. 唐太宗","C. 唐高宗","D. 唐中宗"]',
  },
  {
    chapterKey: 'history-bubian-8-0',
    questionKey: 'history-bubian-8-0-7',
    type: 'choice',
    questionText: '唐代完善科举制的关键措施是（）',
    answer: 'D',
    explanation: '唐太宗扩充国学规模，武则天开创殿试和武举，唐玄宗将诗赋作为进士科主要内容，使科举制更加完善。',
    difficulty: 2,
    options: '["A. 设进士科","B. 设明经科","C. 废除九品中正制","D. 增加考试科目，完善考试制度"]',
  },
  {
    chapterKey: 'history-bubian-8-0',
    questionKey: 'history-bubian-8-0-8',
    type: 'choice',
    questionText: '唐朝时被称为"诗仙"的诗人是（）',
    answer: 'B',
    explanation: '李白，字太白，被称为"诗仙"，其诗风豪迈奔放，想象丰富。',
    difficulty: 1,
    options: '["A. 杜甫","B. 李白","C. 白居易","D. 王维"]',
  },
  {
    chapterKey: 'history-bubian-8-0',
    questionKey: 'history-bubian-8-0-9',
    type: 'choice',
    questionText: '唐朝对外交往频繁，下列史实体现这一特点的是（）',
    answer: 'D',
    explanation: '唐朝对外交往广泛，鉴真东渡日本、玄奘西行天竺、遣唐使来华等都是唐朝对外交往的体现。',
    difficulty: 1,
    options: '["A. 张骞出使西域","B. 郑和下西洋","C. 丝绸之路开通","D. 鉴真东渡和玄奘西行"]',
  },
  {
    chapterKey: 'history-bubian-8-0',
    questionKey: 'history-bubian-8-0-10',
    type: 'choice',
    questionText: '唐朝灭亡后，进入的时代是（）',
    answer: 'A',
    explanation: '907年唐朝灭亡，中国进入五代十国的分裂时期。',
    difficulty: 1,
    options: '["A. 五代十国","B. 两宋时期","C. 辽宋夏金","D. 元朝"]',
  },
  {
    chapterKey: 'history-bubian-8-0',
    questionKey: 'history-bubian-8-0-11',
    type: 'choice',
    questionText: '唐太宗之所以能开创"贞观之治"，与他实行的治国思想密切相关，其思想核心是（）',
    answer: 'C',
    explanation: '唐太宗吸取隋亡教训，认识到"舟所以比人君，水所以比黎庶，水能载舟，亦能覆舟"，以民本思想治国。',
    difficulty: 3,
    options: '["A. 法家思想","B. 墨家思想","C. 民本思想","D. 道家思想"]',
  },

  // fill 6题
  {
    chapterKey: 'history-bubian-8-0',
    questionKey: 'history-bubian-8-0-12',
    type: 'fill',
    questionText: '______年，隋朝______下令开凿大运河，以______为中心。',
    answer: '605；隋炀帝；洛阳',
    explanation: '605年起，隋炀帝开凿大运河，以洛阳为中心，北达涿郡，南至余杭。',
    difficulty: 1,
  },
  {
    chapterKey: 'history-bubian-8-0',
    questionKey: 'history-bubian-8-0-13',
    type: 'fill',
    questionText: '唐太宗时期，最著名的谏臣是______，被唐太宗誉为"______"。',
    answer: '魏征；人镜（一面镜子）',
    explanation: '魏征敢于直言进谏，前后进谏200多次，唐太宗说他是一面可以知得失的镜子。',
    difficulty: 1,
    acceptableAnswers: '["魏征；人镜","魏征；一面镜子"]',
  },
  {
    chapterKey: 'history-bubian-8-0',
    questionKey: 'history-bubian-8-0-14',
    type: 'fill',
    questionText: '唐朝由盛转衰的转折点是______，发生在______年。',
    answer: '安史之乱；755',
    explanation: '755年安禄山和史思明发动叛乱，史称安史之乱，是唐朝由盛转衰的转折点。',
    difficulty: 1,
  },
  {
    chapterKey: 'history-bubian-8-0',
    questionKey: 'history-bubian-8-0-15',
    type: 'fill',
    questionText: '唐朝完善科举制的三件大事是：唐太宗______，武则天______，唐玄宗______。',
    answer: '扩充国学规模；首创殿试和武举；以诗赋取士',
    explanation: '三位帝王分别从不同方面完善了科举制。',
    difficulty: 2,
  },
  {
    chapterKey: 'history-bubian-8-0',
    questionKey: 'history-bubian-8-0-16',
    type: 'fill',
    questionText: '唐朝的农业生产工具中，重要的新式工具有______和______。',
    answer: '曲辕犁；筒车',
    explanation: '唐朝时，农民改进了犁的构造，制成曲辕犁；还创制了筒车，用于灌溉。',
    difficulty: 1,
  },
  {
    chapterKey: 'history-bubian-8-0',
    questionKey: 'history-bubian-8-0-17',
    type: 'fill',
    questionText: '被称为"诗圣"的诗人是______，其诗被称为"______"。',
    answer: '杜甫；诗史',
    explanation: '杜甫的诗反映了唐朝由盛转衰的社会现实，被称为"诗史"。',
    difficulty: 1,
  },

  // short_answer 7题
  {
    chapterKey: 'history-bubian-8-0',
    questionKey: 'history-bubian-8-0-18',
    type: 'short_answer',
    questionText: '简述大运河的概况和历史意义。',
    answer: '概况：大运河以洛阳为中心，北达涿郡（北京），南至余杭（杭州），全长2700多千米，分为永济渠、通济渠、邗沟、江南河四段，连接了海河、黄河、淮河、长江、钱塘江五大水系。意义：大大促进了南北经济文化的交流和发展，是古代世界上最长的运河。',
    explanation: '大运河是隋朝最重要的工程之一，对后世产生了深远影响。',
    difficulty: 2,
  },
  {
    chapterKey: 'history-bubian-8-0',
    questionKey: 'history-bubian-8-0-19',
    type: 'short_answer',
    questionText: '唐太宗有哪些治国措施使唐朝出现"贞观之治"？',
    answer: '（1）政治上：虚心纳谏，知人善任（重用魏征、房玄龄、杜如晦）。（2）经济上：减轻赋税和劳役，鼓励发展农业生产。（3）法律上：修订法律，减轻刑罚。（4）文化教育上：扩充国学规模。（5）民族关系上：实行开明的民族政策，被各族首领尊为"天可汗"。',
    explanation: '唐太宗的治国措施全面而有效，开创了"贞观之治"的盛世局面。',
    difficulty: 2,
  },
  {
    chapterKey: 'history-bubian-8-0',
    questionKey: 'history-bubian-8-0-20',
    type: 'short_answer',
    questionText: '科举制创立和发展的大致过程是怎样的？',
    answer: '（1）隋朝：隋文帝开始用分科考试的方法选拔官员；隋炀帝设进士科，科举制正式诞生。（2）唐朝：唐太宗扩充国学，增加考试科目；武则天首创殿试和武举；唐玄宗以诗赋取士，科举制更加完善。（3）科举制的意义：打破了门第限制，使出身低微但有才能的人可以参与政权，扩大了统治基础，促进了教育和文化的发展。',
    explanation: '科举制从隋朝创立到唐朝完善，对中国历史影响深远。',
    difficulty: 2,
  },
  {
    chapterKey: 'history-bubian-8-0',
    questionKey: 'history-bubian-8-0-21',
    type: 'short_answer',
    questionText: '唐朝对外交往有哪些重要史实？说明了什么？',
    answer: '（1）日本多次派遣唐使来中国学习。（2）鉴真六次东渡日本，传播佛法和文化。（3）玄奘西行天竺取经，著成《大唐西域记》。（4）长安是国际大都市，许多外国商人和学者云集。这说明唐朝实行开放包容的对外政策，经济文化领先世界，对亚洲各国产生了深远影响。',
    explanation: '唐朝的开放和繁荣吸引了世界各地的人们前来交流和访问。',
    difficulty: 2,
  },
  {
    chapterKey: 'history-bubian-8-0',
    questionKey: 'history-bubian-8-0-22',
    type: 'short_answer',
    questionText: '唐朝由盛转衰的原因有哪些？',
    answer: '（1）根本原因：唐玄宗后期追求享乐，怠于政事，任用奸臣。（2）直接原因：755年安史之乱，使唐朝社会经济遭受严重破坏。（3）后期：藩镇割据、宦官专权、朋党之争，进一步削弱了唐朝的统治。907年唐朝灭亡。',
    explanation: '安史之乱是唐朝由盛转衰的转折点，之后的藩镇割据等加速了唐朝的衰落。',
    difficulty: 3,
  },
  {
    chapterKey: 'history-bubian-8-0',
    questionKey: 'history-bubian-8-0-23',
    type: 'short_answer',
    questionText: '简述唐朝文学方面的成就。',
    answer: '唐朝是中国古典诗歌的黄金时代。（1）李白被称为"诗仙"，代表作有《早发白帝城》《蜀道难》等，诗风豪迈奔放。（2）杜甫被称为"诗圣"，其诗被称为"诗史"，代表作有"三吏""三别"等。（3）白居易被称为"诗魔"，主张"文章合为时而著，歌诗合为事而作"，代表作有《长恨歌》《琵琶行》等。',
    explanation: '唐诗是中国文学史上最辉煌的篇章之一。',
    difficulty: 2,
  },
  {
    chapterKey: 'history-bubian-8-0',
    questionKey: 'history-bubian-8-0-24',
    type: 'short_answer',
    questionText: '隋朝和秦朝有哪些相似之处？',
    answer: '（1）都结束了长期分裂的局面，实现了全国统一。（2）都创立了对后世影响深远的制度（秦朝创立中央集权制，隋朝创立科举制）。（3）都修建了伟大的工程（秦朝修长城，隋朝开运河）。（4）都因暴政而速亡（秦二世而亡，隋二世而亡）。（5）继起的朝代都吸取了教训，出现了盛世（汉之文景之治和武帝盛世，唐之贞观之治和开元盛世）。',
    explanation: '秦隋两朝有许多相似之处，都是短命但影响深远的统一王朝。',
    difficulty: 3,
  },

  // matching 3题
  {
    chapterKey: 'history-bubian-8-0',
    questionKey: 'history-bubian-8-0-25',
    type: 'matching',
    questionText: '请将下列历史事件与其特征匹配。',
    answer: '贞观之治—政治清明，经济发展；开元盛世—唐朝鼎盛；安史之乱—由盛转衰；科举制诞生—选拔人才的制度变革',
    explanation: '这些是隋唐时期的重要事件及其特征。',
    difficulty: 1,
    pairs: '[["贞观之治","政治清明，经济发展"],["开元盛世","唐朝鼎盛"],["安史之乱","由盛转衰"],["科举制诞生","选拔人才的制度变革"]]',
  },
  {
    chapterKey: 'history-bubian-8-0',
    questionKey: 'history-bubian-8-0-26',
    type: 'matching',
    questionText: '请将下列历史人物与其主要事迹匹配。',
    answer: '隋文帝—统一全国，创立科举雏形；唐太宗—贞观之治；武则天—中国唯一女皇帝，开殿试；唐玄宗—开元盛世；魏征—直言进谏',
    explanation: '隋唐时期的重要人物及事迹。',
    difficulty: 2,
    pairs: '[["隋文帝","统一全国，创立科举雏形"],["唐太宗","贞观之治"],["武则天","唯一女皇帝，开殿试"],["唐玄宗","开元盛世"],["魏征","直言进谏"]]',
  },
  {
    chapterKey: 'history-bubian-8-0',
    questionKey: 'history-bubian-8-0-27',
    type: 'matching',
    questionText: '请将下列诗人与其称号和风格匹配。',
    answer: '李白—诗仙—豪迈奔放；杜甫—诗圣—沉郁顿挫（诗史）；白居易—诗魔—通俗易懂',
    explanation: '三位伟大诗人的不同风格。',
    difficulty: 2,
    pairs: '[["李白","诗仙—豪迈奔放"],["杜甫","诗圣—沉郁顿挫"],["白居易","诗魔—通俗易懂"]]',
  },

  // ========== 8-1 宋元时期 (26题) ==========

  // choice 12题
  {
    chapterKey: 'history-bubian-8-1',
    questionKey: 'history-bubian-8-1-0',
    type: 'choice',
    questionText: '北宋的建立者是（）',
    answer: 'A',
    explanation: '960年，赵匡胤在陈桥驿发动兵变，黄袍加身，建立宋朝，定都开封（东京），史称北宋。',
    difficulty: 1,
    options: '["A. 赵匡胤","B. 赵光义","C. 赵构","D. 李煜"]',
  },
  {
    chapterKey: 'history-bubian-8-1',
    questionKey: 'history-bubian-8-1-1',
    type: 'choice',
    questionText: '北宋加强中央集权的突出特点是（）',
    answer: 'C',
    explanation: '北宋实行重文轻武政策，文臣担任各级长官，地方知州由文官担任，武将受多方牵制。',
    difficulty: 2,
    options: '["A. 削弱地方","B. 分散相权","C. 重文轻武","D. 强化军事"]',
  },
  {
    chapterKey: 'history-bubian-8-1',
    questionKey: 'history-bubian-8-1-2',
    type: 'choice',
    questionText: '北宋著名的变法改革是（）',
    answer: 'B',
    explanation: '1069年，宋神宗任用王安石变法，主要内容有募役法、方田均税法、农田水利法等。',
    difficulty: 1,
    options: '["A. 商鞅变法","B. 王安石变法","C. 庆历新政","D. 张居正改革"]',
  },
  {
    chapterKey: 'history-bubian-8-1',
    questionKey: 'history-bubian-8-1-3',
    type: 'choice',
    questionText: '北宋时期四川地区出现的世界上最早的纸币是（）',
    answer: 'D',
    explanation: '北宋前期，四川地区出现的"交子"是世界上最早的纸币。',
    difficulty: 1,
    options: '["A. 会子","B. 银票","C. 宝钞","D. 交子"]',
  },
  {
    chapterKey: 'history-bubian-8-1',
    questionKey: 'history-bubian-8-1-4',
    type: 'choice',
    questionText: '南宋的都城在（）',
    answer: 'A',
    explanation: '1127年赵构建立南宋，定都临安（今杭州）。',
    difficulty: 1,
    options: '["A. 临安","B. 东京（开封）","C. 建康","D. 长安"]',
  },
  {
    chapterKey: 'history-bubian-8-1',
    questionKey: 'history-bubian-8-1-5',
    type: 'choice',
    questionText: '岳飞是南宋著名的抗金名将，下列关于岳飞的说法正确的是（）',
    answer: 'B',
    explanation: '岳飞率领的岳家军在郾城大败金军主力，收复许多失地。后被宋高宗和秦桧以"莫须有"的罪名杀害。',
    difficulty: 1,
    options: '["A. 他收复了全部失地","B. 他在郾城大败金军","C. 他是北宋人","D. 他被金军俘虏"]',
  },
  {
    chapterKey: 'history-bubian-8-1',
    questionKey: 'history-bubian-8-1-6',
    type: 'choice',
    questionText: '元朝的建立者是（）',
    answer: 'C',
    explanation: '1271年，忽必烈改国号为元，建立了元朝。1279年元灭南宋，统一全国。',
    difficulty: 1,
    options: '["A. 成吉思汗","B. 拖雷","C. 忽必烈","D. 蒙哥"]',
  },
  {
    chapterKey: 'history-bubian-8-1',
    questionKey: 'history-bubian-8-1-7',
    type: 'choice',
    questionText: '元朝创设的管辖台湾的行政机构是（）',
    answer: 'A',
    explanation: '元朝设置澎湖巡检司，负责管辖澎湖和琉球（今台湾），这是历史上中央政府首次在台湾地区正式建立行政机构。',
    difficulty: 1,
    options: '["A. 澎湖巡检司","B. 台湾府","C. 台湾省","D. 福建总督"]',
  },
  {
    chapterKey: 'history-bubian-8-1',
    questionKey: 'history-bubian-8-1-8',
    type: 'choice',
    questionText: '宋元时期，我国的科技领先世界，被称为中国古代四大发明中的三项（造纸术除外）在这一时期有了重大发展，它们是（）',
    answer: 'D',
    explanation: '指南针、火药、活字印刷术在宋元时期得到重大发展和应用，并传播到世界各地。',
    difficulty: 1,
    options: '["A. 造纸术、火药、指南针","B. 印刷术、造纸术、火药","C. 指南针、造纸术、印刷术","D. 活字印刷术、指南针、火药"]',
  },
  {
    chapterKey: 'history-bubian-8-1',
    questionKey: 'history-bubian-8-1-9',
    type: 'choice',
    questionText: '北宋毕昇发明的技术是（）',
    answer: 'B',
    explanation: '北宋毕昇发明活字印刷术，用胶泥制成单个的活字，排版印刷，大大提高了印刷效率。',
    difficulty: 1,
    options: '["A. 雕版印刷术","B. 活字印刷术","C. 造纸术","D. 司南"]',
  },
  {
    chapterKey: 'history-bubian-8-1',
    questionKey: 'history-bubian-8-1-10',
    type: 'choice',
    questionText: '南宋时期，经济重心南移完成，当时最重要的粮仓是（）',
    answer: 'A',
    explanation: '南宋时，太湖流域成为全国的粮仓，民间流传"苏湖熟，天下足"的谚语。',
    difficulty: 1,
    options: '["A. 太湖流域","B. 黄河流域","C. 珠江流域","D. 淮河流域"]',
  },
  {
    chapterKey: 'history-bubian-8-1',
    questionKey: 'history-bubian-8-1-11',
    type: 'choice',
    questionText: '元朝实行的地方行政制度是（）',
    answer: 'C',
    explanation: '元朝实行行省制度，在中央设中书省，在地方设行中书省（简称行省），影响深远。',
    difficulty: 1,
    options: '["A. 郡县制","B. 分封制","C. 行省制","D. 三司制"]',
  },

  // fill 5题
  {
    chapterKey: 'history-bubian-8-1',
    questionKey: 'history-bubian-8-1-12',
    type: 'fill',
    questionText: '960年，______在______发动兵变，建立______朝。',
    answer: '赵匡胤；陈桥驿；宋（北宋）',
    explanation: '赵匡胤陈桥兵变，建立北宋。',
    difficulty: 1,
    acceptableAnswers: '["赵匡胤；陈桥驿；宋","赵匡胤；陈桥驿；北宋"]',
  },
  {
    chapterKey: 'history-bubian-8-1',
    questionKey: 'history-bubian-8-1-13',
    type: 'fill',
    questionText: '北宋前期，四川地区出现的______是世界上最早的纸币。',
    answer: '交子',
    explanation: '交子出现在北宋四川地区，比欧洲纸币早600多年。',
    difficulty: 1,
  },
  {
    chapterKey: 'history-bubian-8-1',
    questionKey: 'history-bubian-8-1-14',
    type: 'fill',
    questionText: '1271年，______建立______朝；______年，元朝统一全国。',
    answer: '忽必烈；元；1279',
    explanation: '忽必烈1271年建立元朝，1279年灭南宋统一全国。',
    difficulty: 1,
  },
  {
    chapterKey: 'history-bubian-8-1',
    questionKey: 'history-bubian-8-1-15',
    type: 'fill',
    questionText: '宋代把使______用于航海，______大大促进了世界航海事业的发展。',
    answer: '指南针；指南针',
    explanation: '宋代指南针广泛应用于航海，后经阿拉伯人传入欧洲。',
    difficulty: 1,
  },
  {
    chapterKey: 'history-bubian-8-1',
    questionKey: 'history-bubian-8-1-16',
    type: 'fill',
    questionText: '北宋时期著名的史学家______主持编写了______，这是一部______体通史。',
    answer: '司马光；《资治通鉴》；编年',
    explanation: '司马光编写的《资治通鉴》是一部编年体通史巨著，记述了从战国到五代的历史。',
    difficulty: 2,
    acceptableAnswers: '["司马光；资治通鉴；编年"]',
  },

  // short_answer 7题
  {
    chapterKey: 'history-bubian-8-1',
    questionKey: 'history-bubian-8-1-17',
    type: 'short_answer',
    questionText: '简述北宋加强中央集权的措施。',
    answer: '（1）军事上：解除将领兵权，杯酒释兵权；将精锐部队编入禁军，由皇帝直接掌控。（2）政治上：在中央，设参知政事、枢密使、三司使分割宰相的行政权、军权和财权；在地方，派文臣担任知州，设通判监督。（3）经济上：取消节度使收税的权力，由中央控制财赋。（4）思想文化上：重文轻武，科举制规模扩大，重视文臣。',
    explanation: '北宋的措施有效地防止了武将专权，但也导致官僚机构臃肿和军队战斗力下降。',
    difficulty: 2,
  },
  {
    chapterKey: 'history-bubian-8-1',
    questionKey: 'history-bubian-8-1-18',
    type: 'short_answer',
    questionText: '简述王安石变法的主要内容和目的。',
    answer: '目的：摆脱统治危机，实现富国强兵。内容：（1）募役法：以钱代役，减轻农民负担。（2）方田均税法：重新丈量土地，按亩纳税，防止偷逃。（3）农田水利法：鼓励兴修水利。（4）保甲法：把农民编为保甲，农闲时训练。结果：变法在一定程度上增加了政府收入，增强了军事力量，但由于触犯了大官僚大地主的利益，遭到强烈反对，最终失败。',
    explanation: '王安石变法旨在富国强兵，但因阻力过大而失败。',
    difficulty: 2,
  },
  {
    chapterKey: 'history-bubian-8-1',
    questionKey: 'history-bubian-8-1-19',
    type: 'short_answer',
    questionText: '宋元时期有哪些重要的科技成就？',
    answer: '（1）活字印刷术：北宋毕昇发明活字印刷术，比欧洲早约400年。（2）指南针：宋代将指南针用于航海。（3）火药：宋元时期火药武器广泛用于战争，后传入欧洲。（4）沈括撰写《梦溪笔谈》，被誉为"中国科学史上的里程碑"。（5）郭守敬编成《授时历》，测定的回归年长度与现代非常接近。',
    explanation: '宋元科技成就举世瞩目，三大发明在此时期传播到世界各地。',
    difficulty: 2,
  },
  {
    chapterKey: 'history-bubian-8-1',
    questionKey: 'history-bubian-8-1-20',
    type: 'short_answer',
    questionText: '宋朝经济繁荣表现在哪些方面？',
    answer: '（1）农业：占城稻引入，水稻产量大面积提高；太湖流域"苏湖熟，天下足"。（2）手工业：瓷器（五大名窑）、丝织业发达。（3）商业：打破市坊界限，出现早市夜市；纸币"交子"出现；海外贸易空前发达，设立市舶司管理。（4）城市：开封和临安是当时世界上著名的大都市。',
    explanation: '宋代商品经济高度发展，在当时世界上处于领先地位。',
    difficulty: 2,
  },
  {
    chapterKey: 'history-bubian-8-1',
    questionKey: 'history-bubian-8-1-21',
    type: 'short_answer',
    questionText: '元朝实行了哪些治理全国的制度和措施？',
    answer: '（1）政治：实行行省制度，加强中央对地方的控制。（2）边疆管理：设澎湖巡检司管辖台湾；设宣政院管辖西藏（政教事务）。（3）交通：开凿新运河（会通河、通惠河）；开辟海运航线。（4）民族政策：实行民族分化政策，将全国人民分为四等：蒙古人、色目人、汉人、南人。',
    explanation: '元朝疆域辽阔，在制度和措施上有许多创新。',
    difficulty: 3,
  },
  {
    chapterKey: 'history-bubian-8-1',
    questionKey: 'history-bubian-8-1-22',
    type: 'short_answer',
    questionText: '宋代词作最为著名的两位词人是谁？各有何特点？',
    answer: '（1）苏轼：北宋豪放派词人，词风气势豪迈、雄健奔放，代表作有《念奴娇·赤壁怀古》《水调歌头》等。（2）李清照：两宋之交的婉约派词人，词风委婉细腻、感情真挚，代表作有《如梦令》《声声慢》等。此外，辛弃疾是南宋豪放派代表，词风慷慨激昂，抒发爱国情怀。',
    explanation: '宋词是中国文学的重要成就，苏轼、李清照、辛弃疾等人成就最高。',
    difficulty: 2,
  },
  {
    chapterKey: 'history-bubian-8-1',
    questionKey: 'history-bubian-8-1-23',
    type: 'short_answer',
    questionText: '南宋经济发展的主要原因是什么？产生了什么重要影响？',
    answer: '原因：（1）北方人口大量南迁，带来劳动力和先进技术。（2）南方自然条件优越。（3）南方战乱较少。（4）南宋政府鼓励发展经济。影响：经济重心南移在南宋完成，南方成为全国的经济中心。太湖流域成为天下粮仓，南方手工业和商业繁荣，促进了海上贸易的发展。',
    explanation: '经济重心南移是中国古代经济格局的重大变化。',
    difficulty: 3,
  },

  // matching 2题
  {
    chapterKey: 'history-bubian-8-1',
    questionKey: 'history-bubian-8-1-24',
    type: 'matching',
    questionText: '请将下列政权与其建立者和都城匹配。',
    answer: '北宋—赵匡胤—开封；南宋—赵构—临安；辽—耶律阿保机—上京；金—完颜阿骨打—会宁',
    explanation: '宋辽金各政权的建立者和都城。',
    difficulty: 2,
    pairs: '[["北宋","赵匡胤—开封"],["南宋","赵构—临安"],["辽","耶律阿保机—上京"],["金","完颜阿骨打—会宁"]]',
  },
  {
    chapterKey: 'history-bubian-8-1',
    questionKey: 'history-bubian-8-1-25',
    type: 'matching',
    questionText: '请将下列四大发明与其发明或发展的时期及贡献匹配。',
    answer: '造纸术—西汉发明、东汉蔡伦改进—促进文化传播；活字印刷术—北宋毕昇发明—促进文化传播；指南针—战国司南、宋用于航海—促进航海；火药—唐末用于军事、宋元发展—改变战争方式',
    explanation: '四大发明的时代及其历史贡献。',
    difficulty: 2,
    pairs: '[["造纸术","西汉发明，东汉改进—促进文化传播"],["活字印刷术","北宋毕昇发明—促进文化传播"],["指南针","战国司南，宋用于航海—促进航海"],["火药","唐末用于军事—改变战争方式"]]',
  },

  // ========== 8-2 明清时期 (24题) ==========

  // choice 11题
  {
    chapterKey: 'history-bubian-8-2',
    questionKey: 'history-bubian-8-2-0',
    type: 'choice',
    questionText: '明朝的建立者是（）',
    answer: 'A',
    explanation: '1368年，朱元璋在应天府（南京）称帝，建立明朝。',
    difficulty: 1,
    options: '["A. 朱元璋","B. 朱棣","C. 朱允炆","D. 朱高炽"]',
  },
  {
    chapterKey: 'history-bubian-8-2',
    questionKey: 'history-bubian-8-2-1',
    type: 'choice',
    questionText: '明朝加强皇权的措施中，最重要的是（）',
    answer: 'D',
    explanation: '明太祖废除丞相制度，权分六部，皇帝直接掌管政务，这是中国古代政治制度的重大变化。',
    difficulty: 1,
    options: '["A. 设锦衣卫","B. 八股取士","C. 设内阁","D. 废除丞相制度"]',
  },
  {
    chapterKey: 'history-bubian-8-2',
    questionKey: 'history-bubian-8-2-2',
    type: 'choice',
    questionText: '明朝科举考试规定的格式是（）',
    answer: 'B',
    explanation: '明朝科举考试实行八股取士，题目必须来自四书五经，答题格式为八股文。',
    difficulty: 1,
    options: '["A. 诗赋","B. 八股文","C. 策论","D. 经义"]',
  },
  {
    chapterKey: 'history-bubian-8-2',
    questionKey: 'history-bubian-8-2-3',
    type: 'choice',
    questionText: '郑和下西洋最远到达（）',
    answer: 'C',
    explanation: '郑和于1405—1433年七次下西洋，最远到达非洲东海岸和红海沿岸。',
    difficulty: 1,
    options: '["A. 东南亚","B. 印度","C. 非洲东海岸和红海沿岸","D. 欧洲"]',
  },
  {
    chapterKey: 'history-bubian-8-2',
    questionKey: 'history-bubian-8-2-4',
    type: 'choice',
    questionText: '明朝防御北方蒙古的军事工程是（）',
    answer: 'A',
    explanation: '明朝大规模修筑长城，东起鸭绿江畔，西至嘉峪关，今天的长城多为明朝修筑。',
    difficulty: 1,
    options: '["A. 长城","B. 大运河","C. 灵渠","D. 郑和宝船"]',
  },
  {
    chapterKey: 'history-bubian-8-2',
    questionKey: 'history-bubian-8-2-5',
    type: 'choice',
    questionText: '明朝末年，从美洲传入中国的农作物有（）',
    answer: 'D',
    explanation: '明朝中后期，玉米、甘薯、马铃薯、花生等高产作物从美洲传入中国，促进了农业的发展。',
    difficulty: 1,
    options: '["A. 水稻和小麦","B. 粟和黍","C. 高粱和谷子","D. 玉米和甘薯"]',
  },
  {
    chapterKey: 'history-bubian-8-2',
    questionKey: 'history-bubian-8-2-6',
    type: 'choice',
    questionText: '明朝中后期出现的资本主义萌芽主要体现在（）',
    answer: 'B',
    explanation: '明朝中后期，江南地区的丝织业中出现了"机户出资，机工出力"的雇佣关系，标志着资本主义萌芽的出现。',
    difficulty: 2,
    options: '["A. 农业领域","B. 手工业领域","C. 商业领域","D. 交通运输领域"]',
  },
  {
    chapterKey: 'history-bubian-8-2',
    questionKey: 'history-bubian-8-2-7',
    type: 'choice',
    questionText: '清朝的建立者是（）',
    answer: 'A',
    explanation: '1616年努尔哈赤建立后金，1636年皇太极改国号为清，1644年清军入关，逐步统一全国。',
    difficulty: 1,
    options: '["A. 皇太极","B. 努尔哈赤","C. 顺治帝","D. 康熙帝"]',
  },
  {
    chapterKey: 'history-bubian-8-2',
    questionKey: 'history-bubian-8-2-8',
    type: 'choice',
    questionText: '清朝加强君主专制的措施中，设立的中枢权力机构是（）',
    answer: 'C',
    explanation: '雍正帝设立军机处，军机大臣只负责跪受笔录、传达皇帝旨意，标志着君主专制达到顶峰。',
    difficulty: 1,
    options: '["A. 内阁","B. 六部","C. 军机处","D. 南书房"]',
  },
  {
    chapterKey: 'history-bubian-8-2',
    questionKey: 'history-bubian-8-2-9',
    type: 'choice',
    questionText: '清朝实行的思想文化专制政策是（）',
    answer: 'D',
    explanation: '清朝大兴文字狱，从思想上严密控制知识分子，摧残了文化，阻碍了社会的进步。',
    difficulty: 1,
    options: '["A. 焚书坑儒","B. 罢黜百家","C. 八股取士","D. 文字狱"]',
  },
  {
    chapterKey: 'history-bubian-8-2',
    questionKey: 'history-bubian-8-2-10',
    type: 'choice',
    questionText: '清朝前期，为巩固统一多民族国家，康熙帝采取的措施中不包括（）',
    answer: 'B',
    explanation: '康熙帝平定三藩叛乱、收复台湾（设台湾府）、抗击沙俄入侵（签订《尼布楚条约》）、册封达赖和班禅。闭关锁国不是康熙帝的举措。',
    difficulty: 2,
    options: '["A. 收复台湾","B. 实行闭关锁国","C. 签订《尼布楚条约》","D. 平定三藩叛乱"]',
  },

  // fill 5题
  {
    chapterKey: 'history-bubian-8-2',
    questionKey: 'history-bubian-8-2-11',
    type: 'fill',
    questionText: '明朝开国皇帝______在应天府称帝，国号______。',
    answer: '朱元璋；明',
    explanation: '1368年朱元璋称帝，建立明朝，定都应天府（南京）。',
    difficulty: 1,
  },
  {
    chapterKey: 'history-bubian-8-2',
    questionKey: 'history-bubian-8-2-12',
    type: 'fill',
    questionText: '明朝______（皇帝）设立______，标志着君主专制达到了顶峰。',
    answer: '雍正帝（清世宗）；军机处',
    explanation: '雍正帝设军机处，所有军政大事均由皇帝一人裁决。',
    difficulty: 1,
    acceptableAnswers: '["雍正帝；军机处","雍正；军机处","清世宗；军机处"]',
  },
  {
    chapterKey: 'history-bubian-8-2',
    questionKey: 'history-bubian-8-2-13',
    type: 'fill',
    questionText: '______年，郑和第一次下西洋，此后先后______次远航。',
    answer: '1405；七（7）',
    explanation: '1405年郑和第一次下西洋，到1433年先后七次远航。',
    difficulty: 1,
    acceptableAnswers: '["1405；七","1405；7"]',
  },
  {
    chapterKey: 'history-bubian-8-2',
    questionKey: 'history-bubian-8-2-14',
    type: 'fill',
    questionText: '清朝前期，______帝收复台湾，设立了______，隶属福建省。',
    answer: '康熙；台湾府',
    explanation: '1683年康熙帝派兵收复台湾，1684年设台湾府，隶属福建省。',
    difficulty: 1,
    acceptableAnswers: '["康熙帝；台湾府","康熙；台湾府"]',
  },
  {
    chapterKey: 'history-bubian-8-2',
    questionKey: 'history-bubian-8-2-15',
    type: 'fill',
    questionText: '明朝小说四大名著中，______是中国古典小说的高峰。',
    answer: '《红楼梦》',
    explanation: '《红楼梦》是清代曹雪芹所著，是中国古典小说的巅峰之作。',
    difficulty: 1,
  },

  // short_answer 6题
  {
    chapterKey: 'history-bubian-8-2',
    questionKey: 'history-bubian-8-2-16',
    type: 'short_answer',
    questionText: '明朝加强君主权力的措施有哪些？',
    answer: '（1）政治上：废除丞相制度，权分六部，皇帝直接掌管朝政；设锦衣卫（由皇帝直接指挥）和东厂等特务机构，监视官民。（2）思想文化上：实行八股取士，限制知识分子的思想；大兴文字狱，严格控制文化。（3）地方上：废行省，设三司（布政使司、按察使司、都指挥使司）分权。',
    explanation: '明朝通过多方面措施强化君主专制，皇帝集权达到新的高度。',
    difficulty: 2,
  },
  {
    chapterKey: 'history-bubian-8-2',
    questionKey: 'history-bubian-8-2-17',
    type: 'short_answer',
    questionText: '郑和下西洋的目的、经过和历史意义。',
    answer: '目的：提高明朝在国外的地位和威望，"示中国富强"，同时也用中国的货物去换取海外的奇珍。经过：1405—1433年，郑和率船队七次下西洋，最远到达非洲东海岸和红海沿岸，到过亚非30多个国家和地区。意义：比欧洲航海家的远航早半个多世纪，是中国航海史上的壮举；促进了与亚非各国的经济文化交流；展示了明朝的国力和航海技术。',
    explanation: '郑和下西洋是世界航海史上的伟大壮举。',
    difficulty: 2,
  },
  {
    chapterKey: 'history-bubian-8-2',
    questionKey: 'history-bubian-8-2-18',
    type: 'short_answer',
    questionText: '清朝前期是怎样巩固统一多民族国家的？',
    answer: '（1）平定三藩叛乱，巩固南方统治。（2）康熙帝收复台湾，设台湾府，隶属福建省。（3）康熙帝抗击沙俄入侵，签订《尼布楚条约》，从法律上肯定了黑龙江和乌苏里江流域包括库页岛在内的广大地区是中国领土。（4）册封达赖和班禅，加强对西藏的管理。（5）平定大小和卓叛乱，设伊犁将军管辖新疆地区。清朝前期疆域辽阔，奠定了中国今天的版图基础。',
    explanation: '清朝前期对边疆地区的治理巩固了统一多民族国家。',
    difficulty: 3,
  },
  {
    chapterKey: 'history-bubian-8-2',
    questionKey: 'history-bubian-8-2-19',
    type: 'short_answer',
    questionText: '清朝实行"闭关锁国"政策的原因和影响。',
    answer: '原因：（1）根本原因：自给自足的自然经济，不需要外来商品。（2）统治者担心外来势力与沿海居民勾结危及统治。（3）防范西方殖民者的侵略活动。影响：（1）积极：对西方殖民者的侵略活动起到一定的自卫作用。（2）消极：限制了对外贸易和航海事业的发展；阻碍了中外文化交流；使中国逐渐落后于世界潮流。',
    explanation: '闭关锁国政策使中国错过了与世界同步发展的机遇。',
    difficulty: 2,
  },
  {
    chapterKey: 'history-bubian-8-2',
    questionKey: 'history-bubian-8-2-20',
    type: 'short_answer',
    questionText: '明朝和清朝君主专制加强的表现和影响。',
    answer: '明朝：（1）废除丞相，权分六部。（2）设锦衣卫和东厂等特务机构。（3）八股取士。（4）大兴文字狱。清朝：（1）设军机处，皇权达到顶峰。（2）大兴文字狱，压制知识分子。（3）闭关锁国。影响：君主专制空前加强，在巩固多民族国家统一方面起到积极作用，但也严重阻碍了社会进步和资本主义萌芽的发展，使中国逐渐落后于世界潮流。',
    explanation: '明清君主专制的强化是历史的双刃剑。',
    difficulty: 3,
  },
  {
    chapterKey: 'history-bubian-8-2',
    questionKey: 'history-bubian-8-2-21',
    type: 'short_answer',
    questionText: '明清时期文学方面有哪些重要成就？',
    answer: '（1）明朝：罗贯中《三国演义》是我国第一部长篇历史演义小说；施耐庵《水浒传》是我国第一部以农民起义为题材的长篇小说；吴承恩《西游记》是一部浪漫主义的长篇神话小说。（2）清朝：曹雪芹《红楼梦》是我国古典小说的高峰，具有高度的思想性和艺术性。此外还有戏曲方面的成就，如汤显祖的《牡丹亭》等。',
    explanation: '明清小说达到了中国古典文学的巅峰。',
    difficulty: 2,
  },

  // matching 2题
  {
    chapterKey: 'history-bubian-8-2',
    questionKey: 'history-bubian-8-2-22',
    type: 'matching',
    questionText: '请将下列明清皇帝与其主要功绩匹配。',
    answer: '明太祖—废除丞相，建立明朝；明成祖—迁都北京，派郑和下西洋；康熙帝—收复台湾，签《尼布楚条约》；雍正帝—设军机处',
    explanation: '明清几位重要皇帝的主要功绩。',
    difficulty: 2,
    pairs: '[["明太祖","废除丞相，建立明朝"],["明成祖","迁都北京，派郑和下西洋"],["康熙帝","收复台湾，签尼布楚条约"],["雍正帝","设军机处"]]',
  },
  {
    chapterKey: 'history-bubian-8-2',
    questionKey: 'history-bubian-8-2-23',
    type: 'matching',
    questionText: '请将下列名著与其作者和朝代匹配。',
    answer: '《三国演义》—罗贯中—明朝；《水浒传》—施耐庵—明朝；《西游记》—吴承恩—明朝；《红楼梦》—曹雪芹—清朝',
    explanation: '中国古典四大名著的作者和朝代。',
    difficulty: 1,
    pairs: '[["三国演义","罗贯中—明朝"],["水浒传","施耐庵—明朝"],["西游记","吴承恩—明朝"],["红楼梦","曹雪芹—清朝"]]',
  },

  // ========== 8-3 中国开始沦为半殖民地半封建社会 (24题) ==========

  // choice 11题
  {
    chapterKey: 'history-bubian-8-3',
    questionKey: 'history-bubian-8-3-0',
    type: 'choice',
    questionText: '中国近代史的开端是（）',
    answer: 'B',
    explanation: '1840年鸦片战争爆发，中国开始沦为半殖民地半封建社会，标志着中国近代史的开端。',
    difficulty: 1,
    options: '["A. 虎门销烟","B. 鸦片战争","C. 太平天国运动","D. 第二次鸦片战争"]',
  },
  {
    chapterKey: 'history-bubian-8-3',
    questionKey: 'history-bubian-8-3-1',
    type: 'choice',
    questionText: '虎门销烟的领导人是（）',
    answer: 'A',
    explanation: '1839年6月，林则徐在虎门海滩当众销毁收缴的鸦片，这一壮举被称为虎门销烟。',
    difficulty: 1,
    options: '["A. 林则徐","B. 魏源","C. 关天培","D. 陈化成"]',
  },
  {
    chapterKey: 'history-bubian-8-3',
    questionKey: 'history-bubian-8-3-2',
    type: 'choice',
    questionText: '中国近代史上第一个不平等条约是（）',
    answer: 'C',
    explanation: '1842年，中英签订《南京条约》，这是中国近代史上第一个丧权辱国的不平等条约。',
    difficulty: 1,
    options: '["A. 《北京条约》","B. 《天津条约》","C. 《南京条约》","D. 《马关条约》"]',
  },
  {
    chapterKey: 'history-bubian-8-3',
    questionKey: 'history-bubian-8-3-3',
    type: 'choice',
    questionText: '在《南京条约》中，清政府被迫开放的五个通商口岸不包括（）',
    answer: 'D',
    explanation: '《南京条约》开放广州、厦门、福州、宁波、上海五处为通商口岸。',
    difficulty: 1,
    options: '["A. 广州","B. 福州","C. 上海","D. 北京"]',
  },
  {
    chapterKey: 'history-bubian-8-3',
    questionKey: 'history-bubian-8-3-4',
    type: 'choice',
    questionText: '第二次鸦片战争中，洗劫并火烧圆明园的是（）',
    answer: 'B',
    explanation: '1860年，英法联军攻入北京，抢劫并火烧了圆明园。',
    difficulty: 1,
    options: '["A. 英军","B. 英法联军","C. 法军","D. 八国联军"]',
  },
  {
    chapterKey: 'history-bubian-8-3',
    questionKey: 'history-bubian-8-3-5',
    type: 'choice',
    questionText: '太平天国运动爆发的标志是（）',
    answer: 'A',
    explanation: '1851年，洪秀全在广西金田村发动起义，建号太平天国。',
    difficulty: 1,
    options: '["A. 金田起义","B. 永安建制","C. 定都天京","D. 北伐西征"]',
  },
  {
    chapterKey: 'history-bubian-8-3',
    questionKey: 'history-bubian-8-3-6',
    type: 'choice',
    questionText: '太平天国的革命纲领性文件是（）',
    answer: 'C',
    explanation: '1853年太平天国颁布《天朝田亩制度》。',
    difficulty: 2,
    options: '["A. 《资政新篇》","B. 《临时约法》","C. 《天朝田亩制度》","D. 《海国图志》"]',
  },
  {
    chapterKey: 'history-bubian-8-3',
    questionKey: 'history-bubian-8-3-7',
    type: 'choice',
    questionText: '标志着太平天国由盛转衰的事件是（）',
    answer: 'D',
    explanation: '1856年天京事变，太平天国元气大伤，由盛转衰。',
    difficulty: 2,
    options: '["A. 金田起义","B. 北伐失败","C. 颁布天朝田亩制度","D. 天京事变"]',
  },
  {
    chapterKey: 'history-bubian-8-3',
    questionKey: 'history-bubian-8-3-8',
    type: 'choice',
    questionText: '"开眼看世界"的第一人是（）',
    answer: 'B',
    explanation: '林则徐编成《四洲志》，被称为"开眼看世界的第一人"。',
    difficulty: 1,
    options: '["A. 魏源","B. 林则徐","C. 严复","D. 洪仁玕"]',
  },
  {
    chapterKey: 'history-bubian-8-3',
    questionKey: 'history-bubian-8-3-9',
    type: 'choice',
    questionText: '魏源编写的著作是（）',
    answer: 'A',
    explanation: '魏源编成《海国图志》，提出"师夷长技以制夷"。',
    difficulty: 1,
    options: '["A. 《海国图志》","B. 《天演论》","C. 《四洲志》","D. 《资政新篇》"]',
  },
  {
    chapterKey: 'history-bubian-8-3',
    questionKey: 'history-bubian-8-3-10',
    type: 'choice',
    questionText: '鸦片战争中在虎门英勇抗敌牺牲的将领是（）',
    answer: 'C',
    explanation: '关天培在虎门炮台抗英战斗中壮烈牺牲。',
    difficulty: 2,
    options: '["A. 林则徐","B. 陈化成","C. 关天培","D. 邓世昌"]',
  },

  // fill 5题
  {
    chapterKey: 'history-bubian-8-3',
    questionKey: 'history-bubian-8-3-11',
    type: 'fill',
    questionText: '______年，______领导虎门销烟。',
    answer: '1839；林则徐',
    explanation: '1839年6月林则徐虎门销烟。',
    difficulty: 1,
  },
  {
    chapterKey: 'history-bubian-8-3',
    questionKey: 'history-bubian-8-3-12',
    type: 'fill',
    questionText: '《南京条约》中，清政府割______给英国，赔款______银元。',
    answer: '香港岛；2100万',
    explanation: '《南京条约》割让香港岛，赔款2100万银元。',
    difficulty: 1,
  },
  {
    chapterKey: 'history-bubian-8-3',
    questionKey: 'history-bubian-8-3-13',
    type: 'fill',
    questionText: '第二次鸦片战争发生在______年到______年。',
    answer: '1856；1860',
    explanation: '1856年英法联军发动第二次鸦片战争。',
    difficulty: 1,
  },
  {
    chapterKey: 'history-bubian-8-3',
    questionKey: 'history-bubian-8-3-14',
    type: 'fill',
    questionText: '魏源在《海国图志》中提出了______的主张。',
    answer: '师夷长技以制夷',
    explanation: '魏源主张学习西方先进技术来抵御外国侵略。',
    difficulty: 1,
  },
  {
    chapterKey: 'history-bubian-8-3',
    questionKey: 'history-bubian-8-3-15',
    type: 'fill',
    questionText: '太平天国定都______（今南京）。',
    answer: '天京',
    explanation: '1853年太平军定都天京（南京）。',
    difficulty: 1,
  },

  // short_answer 6题
  {
    chapterKey: 'history-bubian-8-3',
    questionKey: 'history-bubian-8-3-16',
    type: 'short_answer',
    questionText: '简述鸦片战争爆发的原因。',
    answer: '根本原因：英国为了打开中国市场，倾销工业品，掠夺原料。直接原因：林则徐虎门销烟，英国以此为借口发动战争。',
    explanation: '鸦片战争是英国为了打开中国大门而蓄意发动的侵略战争。',
    difficulty: 2,
  },
  {
    chapterKey: 'history-bubian-8-3',
    questionKey: 'history-bubian-8-3-17',
    type: 'short_answer',
    questionText: '《南京条约》的主要内容及其对中国的影响。',
    answer: '内容：割香港岛给英国；赔款2100万银元；开放广州、厦门、福州、宁波、上海五口通商；协定关税。影响：中国开始沦为半殖民地半封建社会。',
    explanation: '《南京条约》使中国的主权和领土完整遭到严重破坏。',
    difficulty: 2,
  },
  {
    chapterKey: 'history-bubian-8-3',
    questionKey: 'history-bubian-8-3-18',
    type: 'short_answer',
    questionText: '第二次鸦片战争比第一次危害更大的表现。',
    answer: '（1）丧失更多领土：沙俄割占中国150多万平方千米领土。（2）侵略势力扩大到北方。（3）火烧圆明园。（4）通商口岸增多，侵略势力深入内地。',
    explanation: '第二次鸦片战争使中国半殖民地化程度进一步加深。',
    difficulty: 3,
  },
  {
    chapterKey: 'history-bubian-8-3',
    questionKey: 'history-bubian-8-3-19',
    type: 'short_answer',
    questionText: '太平天国运动的历史意义和失败原因。',
    answer: '意义：是中国历史上规模最宏大的一次农民战争，沉重打击了清朝统治和外国侵略势力。失败原因：农民阶级的局限性；天京事变使力量削弱；战略失误；中外反动势力联合镇压。',
    explanation: '太平天国运动显示了农民阶级的巨大革命力量。',
    difficulty: 3,
  },
  {
    chapterKey: 'history-bubian-8-3',
    questionKey: 'history-bubian-8-3-20',
    type: 'short_answer',
    questionText: '简述林则徐、魏源"开眼看世界"的主要活动。',
    answer: '林则徐设立译馆编成《四洲志》，被称为"开眼看世界的第一人"。魏源编撰《海国图志》，提出"师夷长技以制夷"。他们的思想开启了近代中国向西方学习的潮流。',
    explanation: '林则徐和魏源是近代中国第一批"开眼看世界"的人。',
    difficulty: 2,
  },
  {
    chapterKey: 'history-bubian-8-3',
    questionKey: 'history-bubian-8-3-21',
    type: 'short_answer',
    questionText: '鸦片战争给中国社会带来了哪些变化？',
    answer: '（1）社会性质：从封建社会开始沦为半殖民地半封建社会。（2）主要矛盾：增加了外国资本主义与中华民族的矛盾。（3）革命任务：由反封建变为反帝反封建。（4）经济结构：自然经济开始解体。',
    explanation: '鸦片战争是中国历史的转折点。',
    difficulty: 3,
  },

  // matching 2题
  {
    chapterKey: 'history-bubian-8-3',
    questionKey: 'history-bubian-8-3-22',
    type: 'matching',
    questionText: '请将下列不平等条约与其签订的战争匹配。',
    answer: '《南京条约》—鸦片战争；《天津条约》—第二次鸦片战争；《北京条约》—第二次鸦片战争',
    explanation: '这些不平等条约分别签订于两次鸦片战争。',
    difficulty: 2,
    pairs: '[["南京条约","鸦片战争"],["天津条约","第二次鸦片战争"],["北京条约","第二次鸦片战争"]]',
  },
  {
    chapterKey: 'history-bubian-8-3',
    questionKey: 'history-bubian-8-3-23',
    type: 'matching',
    questionText: '请将下列历史人物与其主要事迹匹配。',
    answer: '林则徐—虎门销烟；魏源—编写《海国图志》；洪秀全—领导太平天国运动；关天培—虎门抗英牺牲',
    explanation: '这一时期重要历史人物及其事迹。',
    difficulty: 1,
    pairs: '[["林则徐","虎门销烟"],["魏源","编写海国图志"],["洪秀全","领导太平天国运动"],["关天培","虎门抗英牺牲"]]',
  },

  // ========== 9-0 近代化的早期探索 (24题) ==========

  // choice 11题
  {
    chapterKey: 'history-bubian-9-0',
    questionKey: 'history-bubian-9-0-0',
    type: 'choice',
    questionText: '洋务运动的口号是（）',
    answer: 'A',
    explanation: '洋务运动前期以"自强"为口号，后期以"求富"为口号。',
    difficulty: 1,
    options: '["A. 自强、求富","B. 变法图强","C. 民主共和","D. 三民主义"]',
  },
  {
    chapterKey: 'history-bubian-9-0',
    questionKey: 'history-bubian-9-0-1',
    type: 'choice',
    questionText: '洋务派在中央的代表人物是（）',
    answer: 'B',
    explanation: '洋务派在中央以恭亲王奕欣为代表。',
    difficulty: 1,
    options: '["A. 曾国藩","B. 奕欣（恭亲王）","C. 李鸿章","D. 张之洞"]',
  },
  {
    chapterKey: 'history-bubian-9-0',
    questionKey: 'history-bubian-9-0-2',
    type: 'choice',
    questionText: '洋务运动中李鸿章创办的民用工业是（）',
    answer: 'C',
    explanation: '李鸿章创办了轮船招商局、开平矿务局等民用工业。',
    difficulty: 2,
    options: '["A. 江南制造总局","B. 安庆内军械所","C. 轮船招商局","D. 福州船政局"]',
  },
  {
    chapterKey: 'history-bubian-9-0',
    questionKey: 'history-bubian-9-0-3',
    type: 'choice',
    questionText: '戊戌变法的时间是（）',
    answer: 'D',
    explanation: '1898年6月至9月，光绪帝实行变法，历时103天，史称"百日维新"。',
    difficulty: 1,
    options: '["A. 1895年","B. 1894年","C. 1900年","D. 1898年"]',
  },
  {
    chapterKey: 'history-bubian-9-0',
    questionKey: 'history-bubian-9-0-4',
    type: 'choice',
    questionText: '公车上书的直接原因是（）',
    answer: 'A',
    explanation: '1895年《马关条约》签订后，康有为、梁启超联合举人上书。',
    difficulty: 1,
    options: '["A. 《马关条约》的签订","B. 甲午中日战争爆发","C. 戊戌政变","D. 八国联军侵华"]',
  },
  {
    chapterKey: 'history-bubian-9-0',
    questionKey: 'history-bubian-9-0-5',
    type: 'choice',
    questionText: '辛亥革命的指导思想是（）',
    answer: 'B',
    explanation: '孙中山提出三民主义——民族、民权、民生。',
    difficulty: 1,
    options: '["A. 自强求富","B. 三民主义","C. 变法维新","D. 实业救国"]',
  },
  {
    chapterKey: 'history-bubian-9-0',
    questionKey: 'history-bubian-9-0-6',
    type: 'choice',
    questionText: '中国第一个资产阶级革命政党是（）',
    answer: 'C',
    explanation: '1905年孙中山在日本成立中国同盟会。',
    difficulty: 1,
    options: '["A. 兴中会","B. 华兴会","C. 中国同盟会","D. 光复会"]',
  },
  {
    chapterKey: 'history-bubian-9-0',
    questionKey: 'history-bubian-9-0-7',
    type: 'choice',
    questionText: '中华民国成立的时间是（）',
    answer: 'A',
    explanation: '1912年1月1日，孙中山在南京就任临时大总统。',
    difficulty: 1,
    options: '["A. 1912年1月1日","B. 1911年10月10日","C. 1912年2月12日","D. 1913年"]',
  },
  {
    chapterKey: 'history-bubian-9-0',
    questionKey: 'history-bubian-9-0-8',
    type: 'choice',
    questionText: '戊戌变法失败后甘愿为变法牺牲的维新人士是（）',
    answer: 'D',
    explanation: '谭嗣同拒绝逃走，甘愿为变法流血牺牲。',
    difficulty: 1,
    options: '["A. 康有为","B. 梁启超","C. 严复","D. 谭嗣同"]',
  },
  {
    chapterKey: 'history-bubian-9-0',
    questionKey: 'history-bubian-9-0-9',
    type: 'choice',
    questionText: '辛亥革命最伟大的历史功绩是（）',
    answer: 'B',
    explanation: '辛亥革命推翻了清王朝，终结了两千多年君主专制制度。',
    difficulty: 2,
    options: '["A. 推翻了帝国主义统治","B. 推翻了封建君主专制制度","C. 改变了社会性质","D. 实现了民族独立"]',
  },
  {
    chapterKey: 'history-bubian-9-0',
    questionKey: 'history-bubian-9-0-10',
    type: 'choice',
    questionText: '洋务运动失败的标志是（）',
    answer: 'A',
    explanation: '1895年北洋舰队全军覆没，标志着洋务运动破产。',
    difficulty: 2,
    options: '["A. 甲午战争北洋舰队覆灭","B. 戊戌变法失败","C. 辛亥革命爆发","D. 八国联军侵华"]',
  },

  // fill 5题
  {
    chapterKey: 'history-bubian-9-0',
    questionKey: 'history-bubian-9-0-11',
    type: 'fill',
    questionText: '洋务运动中创办的军事工业有______、______等。',
    answer: '安庆内军械所；江南制造总局',
    explanation: '曾国藩创办安庆内军械所，李鸿章创办江南制造总局。',
    difficulty: 1,
    acceptableAnswers: '["江南制造总局；安庆内军械所"]',
  },
  {
    chapterKey: 'history-bubian-9-0',
    questionKey: 'history-bubian-9-0-12',
    type: 'fill',
    questionText: '1895年，康有为、梁启超发起______，拉开了______运动的序幕。',
    answer: '公车上书；维新变法',
    explanation: '公车上书是维新变法运动的起点。',
    difficulty: 1,
  },
  {
    chapterKey: 'history-bubian-9-0',
    questionKey: 'history-bubian-9-0-13',
    type: 'fill',
    questionText: '______年10月10日，______起义爆发。',
    answer: '1911；武昌',
    explanation: '1911年10月10日武昌起义爆发。',
    difficulty: 1,
    acceptableAnswers: '["1911；武昌起义"]',
  },
  {
    chapterKey: 'history-bubian-9-0',
    questionKey: 'history-bubian-9-0-14',
    type: 'fill',
    questionText: '三民主义包括______、______、______。',
    answer: '民族主义；民权主义；民生主义',
    explanation: '三民主义是辛亥革命的指导思想。',
    difficulty: 1,
  },
  {
    chapterKey: 'history-bubian-9-0',
    questionKey: 'history-bubian-9-0-15',
    type: 'fill',
    questionText: '辛亥革命后颁布了______，具有______性质。',
    answer: '《中华民国临时约法》；资产阶级民主共和',
    explanation: '1912年3月颁布《中华民国临时约法》。',
    difficulty: 2,
  },

  // short_answer 6题
  {
    chapterKey: 'history-bubian-9-0',
    questionKey: 'history-bubian-9-0-16',
    type: 'short_answer',
    questionText: '简述洋务运动的内容和评价。',
    answer: '内容：创办军事工业（自强）、民用工业（求富）、筹建海军、兴办学堂派遣留学生。评价：没有使中国富强，但引进了西方技术，客观上促进了民族资本主义发展。',
    explanation: '洋务运动是中国近代化的开端。',
    difficulty: 2,
  },
  {
    chapterKey: 'history-bubian-9-0',
    questionKey: 'history-bubian-9-0-17',
    type: 'short_answer',
    questionText: '简述戊戌变法的主要内容。',
    answer: '政治：改革政府机构，裁撤冗员。经济：鼓励私人兴办工矿企业。文化教育：开办新式学堂，创办报刊。军事：训练新式军队。',
    explanation: '戊戌变法虽失败但起了思想启蒙作用。',
    difficulty: 2,
  },
  {
    chapterKey: 'history-bubian-9-0',
    questionKey: 'history-bubian-9-0-18',
    type: 'short_answer',
    questionText: '辛亥革命的历史意义。',
    answer: '推翻了清王朝和封建君主专制制度；建立了中华民国；颁布了《临时约法》；推动了思想解放，民主共和观念深入人心。',
    explanation: '辛亥革命是中国近代史上伟大的资产阶级民主革命。',
    difficulty: 2,
  },
  {
    chapterKey: 'history-bubian-9-0',
    questionKey: 'history-bubian-9-0-19',
    type: 'short_answer',
    questionText: '辛亥革命为什么既有成功又失败？',
    answer: '成功：推翻了清王朝和君主专制，建立中华民国。失败：没有改变半殖民地半封建社会性质，革命果实被袁世凯窃取。',
    explanation: '资产阶级两面性的体现。',
    difficulty: 3,
  },
  {
    chapterKey: 'history-bubian-9-0',
    questionKey: 'history-bubian-9-0-20',
    type: 'short_answer',
    questionText: '比较洋务运动、戊戌变法和辛亥革命的探索方式。',
    answer: '洋务运动：地主阶级学习西方技术。戊戌变法：资产阶级维新派学习西方制度，主张君主立宪。辛亥革命：资产阶级革命派武装革命建立共和国。三者代表了向西方学习的三个层次。',
    explanation: '体现了中国人向西方学习从器物到制度的过程。',
    difficulty: 3,
  },
  {
    chapterKey: 'history-bubian-9-0',
    questionKey: 'history-bubian-9-0-21',
    type: 'short_answer',
    questionText: '戊戌变法失败的原因。',
    answer: '（1）资产阶级维新派力量弱小。（2）触犯顽固派利益。（3）缺乏群众基础。（4）袁世凯出卖。',
    explanation: '说明资产阶级改良道路在中国行不通。',
    difficulty: 3,
  },

  // matching 2题
  {
    chapterKey: 'history-bubian-9-0',
    questionKey: 'history-bubian-9-0-22',
    type: 'matching',
    questionText: '请将下列运动与其领导阶级和口号匹配。',
    answer: '洋务运动—地主阶级—自强求富；戊戌变法—资产阶级维新派—变法图强；辛亥革命—资产阶级革命派—三民主义',
    explanation: '三次探索分别由不同阶级领导。',
    difficulty: 2,
    pairs: '[["洋务运动","地主阶级—自强求富"],["戊戌变法","资产阶级维新派—变法图强"],["辛亥革命","资产阶级革命派—三民主义"]]',
  },
  {
    chapterKey: 'history-bubian-9-0',
    questionKey: 'history-bubian-9-0-23',
    type: 'matching',
    questionText: '请将下列人物与其所属运动及事迹匹配。',
    answer: '曾国藩—洋务运动—创办安庆内军械所；康有为—戊戌变法—公车上书；孙中山—辛亥革命—成立同盟会；谭嗣同—戊戌变法—为变法牺牲',
    explanation: '这些人物分别参与了不同探索。',
    difficulty: 2,
    pairs: '[["曾国藩","洋务运动—安庆内军械所"],["康有为","戊戌变法—公车上书"],["孙中山","辛亥革命—同盟会"],["谭嗣同","戊戌变法—为变法牺牲"]]',
  },

  // ========== 9-1 新民主主义革命的开始 (28题) ==========

  // choice 13题
  {
    chapterKey: 'history-bubian-9-1',
    questionKey: 'history-bubian-9-1-0',
    type: 'choice',
    questionText: '标志着中国新民主主义革命开端的历史事件是（）',
    answer: 'B',
    explanation: '1919年五四运动标志着中国新民主主义革命的开端。五四运动是一次彻底的反帝反封建的爱国运动，中国工人阶级开始登上政治舞台。',
    difficulty: 1,
    options: '["A. 辛亥革命","B. 五四运动","C. 中国共产党成立","D. 北伐战争"]',
  },
  {
    chapterKey: 'history-bubian-9-1',
    questionKey: 'history-bubian-9-1-1',
    type: 'choice',
    questionText: '五四运动爆发的直接原因是（）',
    answer: 'A',
    explanation: '1919年巴黎和会上中国外交的失败（列强将德国在山东的权益转让给日本）是五四运动爆发的直接原因。',
    difficulty: 1,
    options: '["A. 巴黎和会上中国外交的失败","B. 北洋军阀的黑暗统治","C. 新文化运动的推动","D. 马克思主义在中国的传播"]',
  },
  {
    chapterKey: 'history-bubian-9-1',
    questionKey: 'history-bubian-9-1-2',
    type: 'choice',
    questionText: '中国共产党第一次全国代表大会召开的时间和地点是（）',
    answer: 'C',
    explanation: '1921年7月，中国共产党第一次全国代表大会在上海（后转移到浙江嘉兴南湖的游船上）秘密召开，标志着中国共产党的诞生。',
    difficulty: 1,
    options: '["A. 1920年，北京","B. 1921年，北京","C. 1921年，上海","D. 1922年，广州"]',
  },
  {
    chapterKey: 'history-bubian-9-1',
    questionKey: 'history-bubian-9-1-3',
    type: 'choice',
    questionText: '中共一大选举产生的中央局书记是（）',
    answer: 'A',
    explanation: '中共一大选举产生了中央领导机构——中央局，陈独秀当选为中央局书记。',
    difficulty: 2,
    options: '["A. 陈独秀","B. 李大钊","C. 毛泽东","D. 周恩来"]',
  },
  {
    chapterKey: 'history-bubian-9-1',
    questionKey: 'history-bubian-9-1-4',
    type: 'choice',
    questionText: '黄埔军校成立的时间是（）',
    answer: 'B',
    explanation: '1924年5月，在苏联和中国共产党的帮助下，孙中山在广州黄埔创办了中国国民党陆军军官学校，简称黄埔军校。',
    difficulty: 1,
    options: '["A. 1923年","B. 1924年","C. 1925年","D. 1926年"]',
  },
  {
    chapterKey: 'history-bubian-9-1',
    questionKey: 'history-bubian-9-1-5',
    type: 'choice',
    questionText: '北伐战争的主要对象不包括（）',
    answer: 'D',
    explanation: '北伐战争的主要对象是吴佩孚、孙传芳、张作霖三派军阀。',
    difficulty: 1,
    options: '["A. 吴佩孚","B. 孙传芳","C. 张作霖","D. 袁世凯"]',
  },
  {
    chapterKey: 'history-bubian-9-1',
    questionKey: 'history-bubian-9-1-6',
    type: 'choice',
    questionText: '北伐战争中，国民革命军第四军被誉为"铁军"的主要原因是（）',
    answer: 'C',
    explanation: '北伐战争中，叶挺率领的第四军独立团英勇善战，屡建战功，第四军因此被誉为"铁军"。',
    difficulty: 2,
    options: '["A. 装备最精良","B. 人数最多","C. 叶挺独立团英勇善战","D. 由黄埔军校毕业生组成"]',
  },
  {
    chapterKey: 'history-bubian-9-1',
    questionKey: 'history-bubian-9-1-7',
    type: 'choice',
    questionText: '1927年，蒋介石在上海发动的反革命政变是（）',
    answer: 'A',
    explanation: '1927年4月12日，蒋介石在上海发动"四一二"反革命政变，大肆捕杀共产党人和革命群众，标志着国共合作全面破裂。',
    difficulty: 1,
    options: '["A. 四一二反革命政变","B. 七一五反革命政变","C. 马日事变","D. 中山舰事件"]',
  },
  {
    chapterKey: 'history-bubian-9-1',
    questionKey: 'history-bubian-9-1-8',
    type: 'choice',
    questionText: '南昌起义的时间和主要领导人包括（）',
    answer: 'B',
    explanation: '1927年8月1日，周恩来、贺龙、叶挺、朱德、刘伯承等人领导发动南昌起义，打响了武装反抗国民党反动派的第一枪。',
    difficulty: 1,
    options: '["A. 1927年7月，毛泽东、周恩来","B. 1927年8月，周恩来、贺龙、叶挺","C. 1927年9月，毛泽东","D. 1928年4月，朱德、陈毅"]',
  },
  {
    chapterKey: 'history-bubian-9-1',
    questionKey: 'history-bubian-9-1-9',
    type: 'choice',
    questionText: '中国共产党独立领导武装斗争、创建人民军队的开始是（）',
    answer: 'C',
    explanation: '南昌起义打响了武装反抗国民党反动派的第一枪，是中国共产党独立领导武装斗争、创建人民军队的开始。',
    difficulty: 1,
    options: '["A. 秋收起义","B. 井冈山会师","C. 南昌起义","D. 遵义会议"]',
  },
  {
    chapterKey: 'history-bubian-9-1',
    questionKey: 'history-bubian-9-1-10',
    type: 'choice',
    questionText: '秋收起义后，毛泽东率部向何处进军，开辟了中国革命的第一个农村革命根据地（）',
    answer: 'D',
    explanation: '1927年秋收起义受挫后，毛泽东率部向井冈山进军，建立了井冈山革命根据地，这是中国第一个农村革命根据地。',
    difficulty: 1,
    options: '["A. 延安","B. 遵义","C. 瑞金","D. 井冈山"]',
  },
  {
    chapterKey: 'history-bubian-9-1',
    questionKey: 'history-bubian-9-1-11',
    type: 'choice',
    questionText: '"星星之火，可以燎原"这一论断指的是（）',
    answer: 'A',
    explanation: '毛泽东在1930年写了《星星之火，可以燎原》，阐明了农村包围城市、武装夺取政权的革命道路。',
    difficulty: 2,
    options: '["A. 农村革命根据地的建立和发展","B. 工人运动的兴起","C. 北伐战争的胜利","D. 五四运动的蓬勃发展"]',
  },
  {
    chapterKey: 'history-bubian-9-1',
    questionKey: 'history-bubian-9-1-12',
    type: 'choice',
    questionText: '井冈山会师后合编为中国工农红军第四军，军长是（）',
    answer: 'B',
    explanation: '1928年4月，朱德、陈毅率部与毛泽东领导的工农革命军在井冈山会师，合编为工农红军第四军，朱德任军长，毛泽东任党代表。',
    difficulty: 2,
    options: '["A. 毛泽东","B. 朱德","C. 彭德怀","D. 林彪"]',
  },

  // fill 6题
  {
    chapterKey: 'history-bubian-9-1',
    questionKey: 'history-bubian-9-1-13',
    type: 'fill',
    questionText: '五四运动的两大任务是______和______。',
    answer: '外争主权、内除国贼',
    explanation: '五四运动中，学生们提出"外争主权，内除国贼"的口号。',
    difficulty: 1,
    acceptableAnswers: '["外争主权、内除国贼","外争主权、内惩国贼"]',
  },
  {
    chapterKey: 'history-bubian-9-1',
    questionKey: 'history-bubian-9-1-14',
    type: 'fill',
    questionText: '______年7月，中国共产党第一次全国代表大会在______召开，标志着中国共产党的诞生。',
    answer: '1921、上海',
    explanation: '1921年7月中共一大在上海召开，标志着中国共产党诞生。',
    difficulty: 1,
  },
  {
    chapterKey: 'history-bubian-9-1',
    questionKey: 'history-bubian-9-1-15',
    type: 'fill',
    questionText: '黄埔军校把______教育和______教育结合起来。',
    answer: '政治、军事',
    explanation: '黄埔军校最大的特点是把政治教育和军事教育放到同等重要的地位。',
    difficulty: 1,
    acceptableAnswers: '["政治、军事","军事、政治"]',
  },
  {
    chapterKey: 'history-bubian-9-1',
    questionKey: 'history-bubian-9-1-16',
    type: 'fill',
    questionText: '______起义打响了武装反抗国民党反动派的第一枪，______起义创建了第一个农村革命根据地。',
    answer: '南昌、秋收',
    explanation: '南昌起义打响武装反抗第一枪；秋收起义后毛泽东率部上井冈山创建第一个农村革命根据地。',
    difficulty: 2,
  },
  {
    chapterKey: 'history-bubian-9-1',
    questionKey: 'history-bubian-9-1-17',
    type: 'fill',
    questionText: '中国共产党开辟的中国革命道路是______包围______、______夺取政权的道路。',
    answer: '农村、城市、武装',
    explanation: '中国共产党开辟了农村包围城市、武装夺取政权的革命道路。',
    difficulty: 2,
  },
  {
    chapterKey: 'history-bubian-9-1',
    questionKey: 'history-bubian-9-1-18',
    type: 'fill',
    questionText: '1928年4月，毛泽东与______、______率领的部队在井冈山会师。',
    answer: '朱德、陈毅',
    explanation: '1928年4月，朱德、陈毅率领南昌起义剩余部队与毛泽东领导的工农革命军在井冈山会师。',
    difficulty: 1,
    acceptableAnswers: '["朱德、陈毅","陈毅、朱德"]',
  },

  // short_answer 7题
  {
    chapterKey: 'history-bubian-9-1',
    questionKey: 'history-bubian-9-1-19',
    type: 'short_answer',
    questionText: '为什么说五四运动是新民主主义革命的开端？',
    answer: '①五四运动是一次彻底的反帝反封建的爱国运动；②中国工人阶级第一次作为独立的政治力量登上历史舞台；③具有广泛的群众基础；④为马克思主义在中国的传播创造了条件，为中共成立准备了思想和干部条件。',
    explanation: '五四运动标志着中国工人阶级登上政治舞台，中国革命从此由旧民主主义革命走向新民主主义革命。',
    difficulty: 2,
  },
  {
    chapterKey: 'history-bubian-9-1',
    questionKey: 'history-bubian-9-1-20',
    type: 'short_answer',
    questionText: '中国共产党成立的历史意义是什么？',
    answer: '中国共产党的成立是中国历史上开天辟地的大事。自从有了中国共产党，中国革命的面貌就焕然一新了。有了坚强的领导核心和马克思主义的科学指导，提出了彻底的反帝反封建的民主革命纲领。',
    explanation: '中国共产党的诞生使中国革命有了正确领导核心和科学指导思想。',
    difficulty: 2,
  },
  {
    chapterKey: 'history-bubian-9-1',
    questionKey: 'history-bubian-9-1-21',
    type: 'short_answer',
    questionText: '简述北伐战争的胜利进军及其原因。',
    answer: '北伐战争从1926年开始，基本推翻了北洋军阀的统治。胜利原因：①国共合作建立了革命统一战线；②共产党员和共青团员发挥了先锋模范作用；③工农群众大力支持；④北伐将士英勇作战；⑤苏联的援助。',
    explanation: '北伐战争的胜利是国共合作和工农群众支持共同作用的结果。',
    difficulty: 3,
  },
  {
    chapterKey: 'history-bubian-9-1',
    questionKey: 'history-bubian-9-1-22',
    type: 'short_answer',
    questionText: '南昌起义有什么重大历史意义？',
    answer: '①打响了武装反抗国民党反动派的第一枪；②是中国共产党独立领导武装斗争的开始；③标志着创建人民军队的开端；④8月1日后来被定为建军节。',
    explanation: '南昌起义是中国共产党独立领导武装斗争的开端。',
    difficulty: 2,
  },
  {
    chapterKey: 'history-bubian-9-1',
    questionKey: 'history-bubian-9-1-23',
    type: 'short_answer',
    questionText: '毛泽东为什么要率部上井冈山？开辟井冈山革命根据地有什么意义？',
    answer: '原因：秋收起义攻打城市受挫后，毛泽东决定向敌人力量薄弱的农村进军。意义：①创建了中国第一个农村革命根据地；②开辟了农村包围城市、武装夺取政权的革命道路；③找到了中国革命的正确方向。',
    explanation: '向井冈山进军是革命战略的重大转变，为中国革命开辟了全新道路。',
    difficulty: 3,
  },
  {
    chapterKey: 'history-bubian-9-1',
    questionKey: 'history-bubian-9-1-24',
    type: 'short_answer',
    questionText: '大革命失败的教训是什么？',
    answer: '教训：①中国共产党必须掌握革命的领导权；②必须掌握革命的武装（枪杆子里面出政权）；③必须建立巩固的工农联盟，团结一切可以团结的力量。',
    explanation: '大革命的失败给中国共产党留下了深刻的教训。',
    difficulty: 3,
  },
  {
    chapterKey: 'history-bubian-9-1',
    questionKey: 'history-bubian-9-1-25',
    type: 'short_answer',
    questionText: '比较南昌起义和秋收起义的异同。',
    answer: '相同点：都是中国共产党领导的武装反抗国民党反动派的起义。不同点：①南昌起义以城市为目标，秋收起义失败后转向农村；②南昌起义后部队南下广东，秋收起义后上了井冈山；③南昌起义标志独立领导武装斗争开始，秋收起义开辟了农村包围城市的道路。',
    explanation: '两者共同标志着中国共产党开始独立领导武装斗争。',
    difficulty: 3,
  },

  // matching 2题
  {
    chapterKey: 'history-bubian-9-1',
    questionKey: 'history-bubian-9-1-26',
    type: 'matching',
    questionText: '请将下列历史事件与其对应的时间和意义匹配。',
    answer: '五四运动—1919年—新民主主义革命开端；中共一大—1921年—中国共产党成立；南昌起义—1927年8月—创建人民军队；井冈山会师—1928年—壮大革命力量',
    explanation: '这些事件都是新民主主义革命早期的重要里程碑。',
    difficulty: 2,
    pairs: '[["五四运动","1919年—新民主主义革命开端"],["中共一大","1921年—中国共产党成立"],["南昌起义","1927年8月—创建人民军队"],["井冈山会师","1928年—壮大革命力量"]]',
  },
  {
    chapterKey: 'history-bubian-9-1',
    questionKey: 'history-bubian-9-1-27',
    type: 'matching',
    questionText: '请将下列人物与其相关事件匹配。',
    answer: '陈独秀—中共一大中央局书记；周恩来—南昌起义领导者、黄埔军校政治部主任；朱德—南昌起义领导者、井冈山会师；叶挺—北伐铁军独立团团长',
    explanation: '这些人物在新民主主义革命早期发挥了重要作用。',
    difficulty: 2,
    pairs: '[["陈独秀","中共一大中央局书记"],["周恩来","南昌起义领导者、黄埔军校政治部主任"],["朱德","南昌起义领导者、井冈山会师"],["叶挺","北伐铁军独立团团长"]]',
  },

  // ========== 9-2 中华民族的抗日战争 (24题) ==========

  // choice 11题
  {
    chapterKey: 'history-bubian-9-2',
    questionKey: 'history-bubian-9-2-0',
    type: 'choice',
    questionText: '标志着中国局部抗战开始的事件是（）',
    answer: 'A',
    explanation: '1931年9月18日，日本关东军制造了九一八事变，标志着中国人民局部抗战的开始。',
    difficulty: 1,
    options: '["A. 九一八事变","B. 西安事变","C. 七七事变","D. 八一三事变"]',
  },
  {
    chapterKey: 'history-bubian-9-2',
    questionKey: 'history-bubian-9-2-1',
    type: 'choice',
    questionText: '标志着中国全民族抗战开始的事件是（）',
    answer: 'C',
    explanation: '1937年7月7日，日军进攻卢沟桥（七七事变），中国守军奋起抵抗，标志着全民族抗战的开始。',
    difficulty: 1,
    options: '["A. 九一八事变","B. 西安事变","C. 七七事变","D. 淞沪会战"]',
  },
  {
    chapterKey: 'history-bubian-9-2',
    questionKey: 'history-bubian-9-2-2',
    type: 'choice',
    questionText: '西安事变发生后，中国共产党主张怎样解决（）',
    answer: 'B',
    explanation: '中国共产党从全民族利益出发，主张和平解决西安事变，促成国共两党再次合作。',
    difficulty: 1,
    options: '["A. 武力讨伐蒋介石","B. 和平解决","C. 杀害蒋介石","D. 放任不管"]',
  },
  {
    chapterKey: 'history-bubian-9-2',
    questionKey: 'history-bubian-9-2-3',
    type: 'choice',
    questionText: '抗日战争中，中国军队取得的第一次大捷是（）',
    answer: 'A',
    explanation: '1937年9月，八路军第一一五师在平型关取得平型关大捷，是抗战以来中国军队取得的第一次大捷。',
    difficulty: 1,
    options: '["A. 平型关大捷","B. 台儿庄战役","C. 百团大战","D. 忻口会战"]',
  },
  {
    chapterKey: 'history-bubian-9-2',
    questionKey: 'history-bubian-9-2-4',
    type: 'choice',
    questionText: '台儿庄战役的主要指挥者是（）',
    answer: 'B',
    explanation: '1938年春，李宗仁指挥中国军队在台儿庄取得胜利，是抗战以来正面战场的最大规模胜利。',
    difficulty: 2,
    options: '["A. 蒋介石","B. 李宗仁","C. 薛岳","D. 张自忠"]',
  },
  {
    chapterKey: 'history-bubian-9-2',
    questionKey: 'history-bubian-9-2-5',
    type: 'choice',
    questionText: '百团大战的指挥者是（）',
    answer: 'C',
    explanation: '1940年8月，在彭德怀指挥下，八路军组织100多个团发动百团大战。',
    difficulty: 1,
    options: '["A. 朱德","B. 林彪","C. 彭德怀","D. 刘伯承"]',
  },
  {
    chapterKey: 'history-bubian-9-2',
    questionKey: 'history-bubian-9-2-6',
    type: 'choice',
    questionText: '1945年8月，宣布无条件投降的国家是（）',
    answer: 'D',
    explanation: '1945年8月15日，日本天皇宣布无条件投降；9月2日签署投降书。',
    difficulty: 1,
    options: '["A. 德国","B. 意大利","C. 中国","D. 日本"]',
  },
  {
    chapterKey: 'history-bubian-9-2',
    questionKey: 'history-bubian-9-2-7',
    type: 'choice',
    questionText: '抗日民族统一战线初步形成的标志性事件是（）',
    answer: 'B',
    explanation: '西安事变的和平解决标志着抗日民族统一战线的初步形成。',
    difficulty: 2,
    options: '["A. 九一八事变","B. 西安事变和平解决","C. 七七事变","D. 中共七大"]',
  },
  {
    chapterKey: 'history-bubian-9-2',
    questionKey: 'history-bubian-9-2-8',
    type: 'choice',
    questionText: '抗日战争胜利的根本原因是（）',
    answer: 'A',
    explanation: '抗日战争胜利的根本原因是国共合作，建立抗日民族统一战线，全民族团结抗战。',
    difficulty: 2,
    options: '["A. 国共合作，全民族团结抗战","B. 美国投放原子弹","C. 苏联出兵东北","D. 日本国内矛盾激化"]',
  },
  {
    chapterKey: 'history-bubian-9-2',
    questionKey: 'history-bubian-9-2-9',
    type: 'choice',
    questionText: '日军制造的"南京大屠杀"发生在哪一年（）',
    answer: 'B',
    explanation: '1937年12月，日军攻陷南京后进行了长达六周的大屠杀，遇难者达30万人以上。',
    difficulty: 1,
    options: '["A. 1936年","B. 1937年","C. 1938年","D. 1940年"]',
  },
  {
    chapterKey: 'history-bubian-9-2',
    questionKey: 'history-bubian-9-2-10',
    type: 'choice',
    questionText: '中共七大召开的时间是（）',
    answer: 'C',
    explanation: '1945年4月至6月，中共七大在延安召开，确立了毛泽东思想为党的指导思想。',
    difficulty: 2,
    options: '["A. 1938年","B. 1942年","C. 1945年","D. 1946年"]',
  },

  // fill 5题
  {
    chapterKey: 'history-bubian-9-2',
    questionKey: 'history-bubian-9-2-11',
    type: 'fill',
    questionText: '1936年12月12日，______和______发动西安事变，扣押蒋介石，逼蒋联共抗日。',
    answer: '张学良、杨虎城',
    explanation: '张学良和杨虎城发动西安事变，目的是逼蒋介石停止内战、联共抗日。',
    difficulty: 1,
    acceptableAnswers: '["张学良、杨虎城","杨虎城、张学良"]',
  },
  {
    chapterKey: 'history-bubian-9-2',
    questionKey: 'history-bubian-9-2-12',
    type: 'fill',
    questionText: '1937年12月，日军攻陷______，进行了长达六周的______，遇难者达30万人以上。',
    answer: '南京、大屠杀',
    explanation: '南京大屠杀遇难人数达30万以上。',
    difficulty: 1,
  },
  {
    chapterKey: 'history-bubian-9-2',
    questionKey: 'history-bubian-9-2-13',
    type: 'fill',
    questionText: '在正面战场上，______战役是抗战以来取得的最大规模胜利。',
    answer: '台儿庄',
    explanation: '1938年台儿庄战役是正面战场的最大规模胜利。',
    difficulty: 1,
  },
  {
    chapterKey: 'history-bubian-9-2',
    questionKey: 'history-bubian-9-2-14',
    type: 'fill',
    questionText: '1940年，______指挥八路军发动______大战，这是抗战以来中国军队主动出击的最大规模战役。',
    answer: '彭德怀、百团',
    explanation: '百团大战由彭德怀指挥，八路军出动约100个团兵力。',
    difficulty: 2,
  },
  {
    chapterKey: 'history-bubian-9-2',
    questionKey: 'history-bubian-9-2-15',
    type: 'fill',
    questionText: '中共七大确立______为党的指导思想。',
    answer: '毛泽东思想',
    explanation: '1945年中共七大确立毛泽东思想为全党的指导思想。',
    difficulty: 1,
  },

  // short_answer 6题
  {
    chapterKey: 'history-bubian-9-2',
    questionKey: 'history-bubian-9-2-16',
    type: 'short_answer',
    questionText: '简述九一八事变的时间、经过及其影响。',
    answer: '时间：1931年9月18日。经过：日本关东军炸毁南满铁路柳条湖段路轨，诬称是中国军队所为，进攻沈阳城。影响：标志着中国人民局部抗战的开始，也是十四年抗战的起点。',
    explanation: '九一八事变是中国人民抗日战争的起点，揭开了世界反法西斯战争的序幕。',
    difficulty: 2,
  },
  {
    chapterKey: 'history-bubian-9-2',
    questionKey: 'history-bubian-9-2-17',
    type: 'short_answer',
    questionText: '西安事变和平解决有什么重大意义？',
    answer: '①标志着十年内战基本结束，抗日民族统一战线初步形成；②为国共第二次合作奠定了基础；③体现了中国共产党以民族大义为重；④成为扭转时局的关键。',
    explanation: '西安事变的和平解决是时局转变的关键。',
    difficulty: 2,
  },
  {
    chapterKey: 'history-bubian-9-2',
    questionKey: 'history-bubian-9-2-18',
    type: 'short_answer',
    questionText: '抗日战争中，正面战场和敌后战场各有什么重要战役？它们之间有什么关系？',
    answer: '正面战场：淞沪会战、台儿庄战役等，主要由国民党军队承担。敌后战场：平型关大捷、百团大战等，由共产党领导的八路军、新四军承担。两者相互配合、协同作战，共同构成中国抗战的整体。',
    difficulty: 3,
  },
  {
    chapterKey: 'history-bubian-9-2',
    questionKey: 'history-bubian-9-2-19',
    type: 'short_answer',
    questionText: '列举抗日战争胜利的历史意义。',
    answer: '①是近代以来中国人民反抗外敌入侵取得的第一次完全胜利；②是中华民族由衰败走向复兴的转折点；③大大增强了民族自信心和自豪感；④中国抗战是世界反法西斯战争的重要组成部分；⑤提高了中国的国际地位。',
    explanation: '抗日战争的胜利具有深远的国际意义和国内意义。',
    difficulty: 2,
  },
  {
    chapterKey: 'history-bubian-9-2',
    questionKey: 'history-bubian-9-2-20',
    type: 'short_answer',
    questionText: '中国共产党在抗日战争中发挥了什么作用？',
    answer: '①是全民族抗战的中流砥柱；②倡导建立和坚持抗日民族统一战线；③开辟和发展敌后战场；④制定正确的战略战术；⑤在敌后建立抗日根据地。',
    explanation: '中国共产党在抗战中发挥了中流砥柱作用。',
    difficulty: 3,
  },
  {
    chapterKey: 'history-bubian-9-2',
    questionKey: 'history-bubian-9-2-21',
    type: 'short_answer',
    questionText: '中国人民抗日战争为什么能够取得胜利？',
    answer: '根本原因：中国共产党领导的抗日民族统一战线，全民族团结抗战。其他原因：①中国共产党发挥中流砥柱作用；②伟大民族精神的支撑；③正义的反侵略战争得到国际社会支持；④正面战场和敌后战场相互配合。',
    explanation: '全民族团结抗战是根本原因。',
    difficulty: 3,
  },

  // matching 2题
  {
    chapterKey: 'history-bubian-9-2',
    questionKey: 'history-bubian-9-2-22',
    type: 'matching',
    questionText: '请将下列抗日战争中的重要战役与其相关信息匹配。',
    answer: '平型关大捷—1937年9月—八路军、第一次大捷；台儿庄战役—1938年春—正面战场最大规模胜利；百团大战—1940年8月—彭德怀、主动出击最大规模',
    explanation: '这三个战役分别代表敌后战场和正面战场的重大胜利。',
    difficulty: 1,
    pairs: '[["平型关大捷","1937年9月—八路军、第一次大捷"],["台儿庄战役","1938年春—正面战场最大规模胜利"],["百团大战","1940年8月—彭德怀、主动出击最大规模"]]',
  },
  {
    chapterKey: 'history-bubian-9-2',
    questionKey: 'history-bubian-9-2-23',
    type: 'matching',
    questionText: '请将下列重要事件按时间先后排列并简要标注意义。',
    answer: '九一八事变—1931年—局部抗战开始；西安事变—1936年—统一战线初步形成；七七事变—1937年—全民族抗战开始；日本投降—1945年—抗战胜利',
    explanation: '按时间排列可以了解抗日战争从开始到胜利的全过程。',
    difficulty: 2,
    pairs: '[["九一八事变","1931年—局部抗战开始"],["西安事变","1936年—统一战线初步形成"],["七七事变","1937年—全民族抗战开始"],["日本投降","1945年—抗战胜利"]]',
  },

  // ========== 9-3 人民解放战争的胜利 (22题) ==========

  // choice 10题
  {
    chapterKey: 'history-bubian-9-3',
    questionKey: 'history-bubian-9-3-0',
    type: 'choice',
    questionText: '重庆谈判中，国共双方签订的协定是（）',
    answer: 'B',
    explanation: '1945年8月至10月，国共双方在重庆谈判，签订了"双十协定"。',
    difficulty: 1,
    options: '["A. 共同纲领","B. 双十协定","C. 停战协定","D. 重庆协定"]',
  },
  {
    chapterKey: 'history-bubian-9-3',
    questionKey: 'history-bubian-9-3-1',
    type: 'choice',
    questionText: '人民解放战争初期，国民党军队重点进攻的地区是（）',
    answer: 'A',
    explanation: '1947年春，国民党对陕北和山东两个解放区实行重点进攻。',
    difficulty: 2,
    options: '["A. 陕北和山东","B. 东北和华北","C. 中原和华东","D. 西南和华南"]',
  },
  {
    chapterKey: 'history-bubian-9-3',
    questionKey: 'history-bubian-9-3-2',
    type: 'choice',
    questionText: '揭开人民解放战争战略进攻序幕的战役是（）',
    answer: 'C',
    explanation: '1947年6月底，刘伯承、邓小平率领晋冀鲁豫解放军主力千里挺进大别山。',
    difficulty: 1,
    options: '["A. 辽沈战役","B. 淮海战役","C. 刘邓大军挺进大别山","D. 平津战役"]',
  },
  {
    chapterKey: 'history-bubian-9-3',
    questionKey: 'history-bubian-9-3-3',
    type: 'choice',
    questionText: '三大战役中，最先打响的是（）',
    answer: 'A',
    explanation: '三大战役顺序：辽沈战役（1948年9月）、淮海战役（1948年11月）、平津战役（1948年11月）。',
    difficulty: 1,
    options: '["A. 辽沈战役","B. 淮海战役","C. 平津战役","D. 渡江战役"]',
  },
  {
    chapterKey: 'history-bubian-9-3',
    questionKey: 'history-bubian-9-3-4',
    type: 'choice',
    questionText: '辽沈战役中，人民解放军攻克的关键城市是（）',
    answer: 'B',
    explanation: '林彪、罗荣桓指挥东北解放军攻克锦州，封闭了国民党军队退入关内的通道。',
    difficulty: 2,
    options: '["A. 沈阳","B. 锦州","C. 长春","D. 大连"]',
  },
  {
    chapterKey: 'history-bubian-9-3',
    questionKey: 'history-bubian-9-3-5',
    type: 'choice',
    questionText: '三大战役中，规模最大、歼敌最多的是（）',
    answer: 'C',
    explanation: '淮海战役是三大战役中规模最大、歼敌最多的战役，共歼敌约55万人。',
    difficulty: 1,
    options: '["A. 辽沈战役","B. 平津战役","C. 淮海战役","D. 渡江战役"]',
  },
  {
    chapterKey: 'history-bubian-9-3',
    questionKey: 'history-bubian-9-3-6',
    type: 'choice',
    questionText: '平津战役中，北平和平解放是通过什么方式实现的（）',
    answer: 'D',
    explanation: '通过军事打击和政治争取，傅作义率部接受和平改编，北平和平解放。',
    difficulty: 1,
    options: '["A. 武力攻城","B. 国民党主动撤军","C. 国际调停","D. 和平谈判改编"]',
  },
  {
    chapterKey: 'history-bubian-9-3',
    questionKey: 'history-bubian-9-3-7',
    type: 'choice',
    questionText: '人民解放军发起渡江战役的时间是（）',
    answer: 'A',
    explanation: '1949年4月，百万雄师横渡长江，4月23日解放南京。',
    difficulty: 1,
    options: '["A. 1949年4月","B. 1949年5月","C. 1949年3月","D. 1948年12月"]',
  },
  {
    chapterKey: 'history-bubian-9-3',
    questionKey: 'history-bubian-9-3-8',
    type: 'choice',
    questionText: '人民解放战争中，土地改革颁布的重要文件是（）',
    answer: 'B',
    explanation: '1947年颁布《中国土地法大纲》，规定废除封建剥削的土地制度，实行耕者有其田。',
    difficulty: 2,
    options: '["A. 《共同纲领》","B. 《中国土地法大纲》","C. 《双十协定》","D. 《论联合政府》"]',
  },
  {
    chapterKey: 'history-bubian-9-3',
    questionKey: 'history-bubian-9-3-9',
    type: 'choice',
    questionText: '解放战争中国民党军队迅速溃败的根本原因是（）',
    answer: 'C',
    explanation: '国民党发动反人民的内战，失去了民心。得民心者得天下，失民心者失天下。',
    difficulty: 2,
    options: '["A. 武器装备落后","B. 将领指挥无能","C. 失去民心","D. 美国援助不足"]',
  },

  // fill 4题
  {
    chapterKey: 'history-bubian-9-3',
    questionKey: 'history-bubian-9-3-10',
    type: 'fill',
    questionText: '1947年6月底，______、______率领刘邓大军挺进大别山，揭开了战略进攻的序幕。',
    answer: '刘伯承、邓小平',
    explanation: '刘邓大军千里挺进大别山，揭开了战略进攻的序幕。',
    difficulty: 1,
    acceptableAnswers: '["刘伯承、邓小平","邓小平、刘伯承"]',
  },
  {
    chapterKey: 'history-bubian-9-3',
    questionKey: 'history-bubian-9-3-11',
    type: 'fill',
    questionText: '三大战役中，东北解放军发动的战役是______战役，共歼敌______万余人。',
    answer: '辽沈、47',
    explanation: '辽沈战役共歼敌47万余人，解放了东北全境。',
    difficulty: 2,
  },
  {
    chapterKey: 'history-bubian-9-3',
    questionKey: 'history-bubian-9-3-12',
    type: 'fill',
    questionText: '1949年4月23日，人民解放军解放______，标志着统治中国______年的国民党政权覆灭。',
    answer: '南京、22',
    explanation: '人民解放军占领南京，南京国民政府覆灭。',
    difficulty: 1,
  },
  {
    chapterKey: 'history-bubian-9-3',
    questionKey: 'history-bubian-9-3-13',
    type: 'fill',
    questionText: '平津战役中，______率部接受和平改编，使______得以和平解放。',
    answer: '傅作义、北平',
    explanation: '傅作义率北平守军接受和平改编，北平和平解放。',
    difficulty: 1,
  },

  // short_answer 5题
  {
    chapterKey: 'history-bubian-9-3',
    questionKey: 'history-bubian-9-3-14',
    type: 'short_answer',
    questionText: '简述三大战役的名称、时间及歼敌人数。',
    answer: '辽沈战役：1948年9月至11月，歼敌47万余人。淮海战役：1948年11月至1949年1月，歼敌约55万人。平津战役：1948年11月至1949年1月，歼敌和改编52万余人。共歼敌154万余人。',
    explanation: '三大战役共歼敌154万余人，奠定了解放战争在全国胜利的基础。',
    difficulty: 2,
  },
  {
    chapterKey: 'history-bubian-9-3',
    questionKey: 'history-bubian-9-3-15',
    type: 'short_answer',
    questionText: '人民解放战争为什么能迅速取得胜利？',
    answer: '①中国共产党的正确领导；②人民解放军英勇作战；③人民群众大力支持；④解放区土地改革调动了农民积极性；⑤统一战线策略正确运用；⑥国民党腐败失去民心。',
    explanation: '解放战争的胜利是人心向背的结果。',
    difficulty: 2,
  },
  {
    chapterKey: 'history-bubian-9-3',
    questionKey: 'history-bubian-9-3-16',
    type: 'short_answer',
    questionText: '刘邓大军挺进大别山有什么战略意义？',
    answer: '①揭开了战略进攻的序幕；②直接威胁国民党统治中心南京和武汉；③像尖刀插入敌人心脏，牵制大量敌军；④由战略防御转入战略进攻；⑤形成了全国性战略进攻态势。',
    explanation: '挺进大别山是解放战争的重要转折点。',
    difficulty: 3,
  },
  {
    chapterKey: 'history-bubian-9-3',
    questionKey: 'history-bubian-9-3-17',
    type: 'short_answer',
    questionText: '北平和平解放有什么重要意义？',
    answer: '①使北平这座历史文化名城免遭战火破坏；②使200万人民免受战争苦难；③为和平解放其他地区树立了榜样；④体现了中共灵活运用政治争取的策略。',
    explanation: '北平和平解放既保全了古城，又减少了伤亡。',
    difficulty: 2,
  },
  {
    chapterKey: 'history-bubian-9-3',
    questionKey: 'history-bubian-9-3-18',
    type: 'short_answer',
    questionText: '解放战争时期土地改革有什么作用和意义？',
    answer: '《中国土地法大纲》颁布后，解放区进行土地改革，废除封建剥削土地制度，实行耕者有其田。农民分到土地后生产热情高涨，踊跃参军参战、支援前线，为解放战争胜利奠定了群众基础。',
    explanation: '土地改革赢得了农民对革命的支持。',
    difficulty: 3,
  },

  // matching 3题
  {
    chapterKey: 'history-bubian-9-3',
    questionKey: 'history-bubian-9-3-19',
    type: 'matching',
    questionText: '请将三大战役与其关键城市匹配。',
    answer: '辽沈战役—锦州（关门打狗）；淮海战役—徐州（围歼敌军主力）；平津战役—北平（和平解放）',
    explanation: '三大战役的关键城市各不相同，战略目标也不同。',
    difficulty: 1,
    pairs: '[["辽沈战役","锦州（关门打狗）"],["淮海战役","徐州（围歼敌军主力）"],["平津战役","北平（和平解放）"]]',
  },
  {
    chapterKey: 'history-bubian-9-3',
    questionKey: 'history-bubian-9-3-20',
    type: 'matching',
    questionText: '请将下列解放战争中的事件按时间先后排列。',
    answer: '重庆谈判—1945年8月；转战陕北—1947年；刘邓挺进大别山—1947年6月；三大战役—1948年9月至1949年1月；渡江战役—1949年4月',
    explanation: '按时间顺序排列事件有助于了解解放战争的全过程。',
    difficulty: 2,
    pairs: '[["重庆谈判","1945年8月"],["转战陕北","1947年"],["刘邓挺进大别山","1947年6月"],["三大战役","1948年9月至1949年1月"],["渡江战役","1949年4月"]]',
  },
  {
    chapterKey: 'history-bubian-9-3',
    questionKey: 'history-bubian-9-3-21',
    type: 'matching',
    questionText: '请将下列解放战争的重要人物与其事迹匹配。',
    answer: '刘伯承—千里挺进大别山；林彪—指挥辽沈战役；傅作义—北平和平改编；陈毅—参与指挥淮海战役',
    explanation: '这些将领在解放战争中发挥了重要作用。',
    difficulty: 2,
    pairs: '[["刘伯承","千里挺进大别山"],["林彪","指挥辽沈战役"],["傅作义","北平和平改编"],["陈毅","参与指挥淮海战役"]]',
  },
];

export async function seedHistoryBubianQuestions(): Promise<number> {
  const chapters = await prisma.chapter.findMany({
    where: { chapterKey: { startsWith: 'history-bubian' } },
  });
  const keyToId = new Map<string, string>();
  for (const ch of chapters) {
    keyToId.set(ch.chapterKey, ch.id);
  }

  const records = questions
    .map(q => {
      const chapterId = keyToId.get(q.chapterKey);
      if (!chapterId) return null;
      const { chapterKey: _, ...data } = q;
      return { ...data, chapterId };
    })
    .filter(Boolean);

  const BATCH_SIZE = 500;
  let inserted = 0;
  for (let i = 0; i < records.length; i += BATCH_SIZE) {
    const batch = records.slice(i, i + BATCH_SIZE);
    const result = await prisma.question.createMany({
      data: batch,
      skipDuplicates: true,
    });
    inserted += result.count;
  }
  console.log(`[seed-history-bubian] 共插入 ${inserted} 道历史人教版题目`);
  return inserted;
}
