/**
 * 物理人教版初中题目种子数据
 *
 * 涵盖 8~9 年级共 8 个章节，总计 202 道题。
 * 章节对应 seed-data.ts 中 physics-renjiao 的定义：
 *   8年级：声现象(20)、光现象(28)、透镜及其应用(24)、物态变化(22)
 *   9年级：内能(20)、电流和电路(28)、电压和电阻(28)、电功率(32)
 *
 * 题型分布：choice ~45% | fill ~25% | short_answer ~20% | true_false ~10%
 * 难度分布：difficulty 1(基础) ~40% | 2(中等) ~40% | 3(提高) ~20%
 */

import { prisma } from '../src/config/database.js';

// ---------- 类型定义 ----------

interface RawQuestion {
  questionKey: string;
  type: 'choice' | 'fill' | 'short_answer' | 'true_false';
  questionText: string;
  answer: string;
  explanation: string;
  difficulty: 1 | 2 | 3;
  options?: string;   // JSON 字符串，仅 choice 题使用
  pairs?: string;     // JSON 字符串，仅 matching 题使用
  acceptableAnswers?: string; // JSON 字符串，fill 题可接受的其他答案
}

// ========== 8-0 声现象 (20题) ==========

const chapter8_0: RawQuestion[] = [
  // ---- choice 9题 ----
  {
    questionKey: 'physics-renjiao-8-0-0',
    type: 'choice',
    questionText: '声音是由物体的____产生的。',
    answer: 'B',
    explanation: '声音是由物体振动产生的。一切发声的物体都在振动，振动停止，发声也停止。',
    difficulty: 1,
    options: '["A. 运动", "B. 振动", "C. 转动", "D. 摆动"]',
  },
  {
    questionKey: 'physics-renjiao-8-0-1',
    type: 'choice',
    questionText: '声音的传播需要____，真空中____传播声音。',
    answer: 'A',
    explanation: '声音的传播需要介质（固体、液体、气体），真空不能传声。月球上没有空气，宇航员只能通过无线电交流。',
    difficulty: 1,
    options: '["A. 介质；不能", "B. 空气；能", "C. 介质；能", "D. 声源；不能"]',
  },
  {
    questionKey: 'physics-renjiao-8-0-2',
    type: 'choice',
    questionText: '一般情况下，声音在固体、液体、气体中的传播速度关系是（）',
    answer: 'C',
    explanation: '一般情况下，声音的传播速度：v固 > v液 > v气。在15°C空气中声速约为340m/s。',
    difficulty: 1,
    options: '["A. v气 > v液 > v固", "B. v液 > v气 > v固", "C. v固 > v液 > v气", "D. v固 > v气 > v液"]',
  },
  {
    questionKey: 'physics-renjiao-8-0-3',
    type: 'choice',
    questionText: '关于声速，下列说法正确的是（）',
    answer: 'B',
    explanation: '15°C时空气中的声速约为340m/s。声速受温度影响，温度越高声速越大。声速与介质的种类有关。',
    difficulty: 1,
    options: '["A. 声速在任何介质中都是340m/s", "B. 15°C时空气中声速约为340m/s", "C. 声速与温度无关", "D. 声音在真空中传播最快"]',
  },
  {
    questionKey: 'physics-renjiao-8-0-4',
    type: 'choice',
    questionText: '音调的高低取决于声音的（）',
    answer: 'A',
    explanation: '音调的高低取决于声源振动的频率。频率越高，音调越高；频率越低，音调越低。',
    difficulty: 1,
    options: '["A. 频率", "B. 振幅", "C. 响度", "D. 音色"]',
  },
  {
    questionKey: 'physics-renjiao-8-0-5',
    type: 'choice',
    questionText: '响度的大小取决于声源的（）',
    answer: 'B',
    explanation: '响度的大小取决于声源的振幅。振幅越大，响度越大；振幅越小，响度越小。响度还与距离声源的远近有关。',
    difficulty: 1,
    options: '["A. 频率", "B. 振幅", "C. 音调", "D. 音色"]',
  },
  {
    questionKey: 'physics-renjiao-8-0-6',
    type: 'choice',
    questionText: '"闻其声而知其人"，这主要是依据声音的哪个特性来判断的（）',
    answer: 'C',
    explanation: '不同人的声带结构不同，发出的声音的音色不同。"闻其声而知其人"是依据音色来分辨的。',
    difficulty: 2,
    options: '["A. 音调", "B. 响度", "C. 音色", "D. 频率"]',
  },
  {
    questionKey: 'physics-renjiao-8-0-7',
    type: 'choice',
    questionText: '下列事例中，属于在声源处减弱噪声的是（）',
    answer: 'D',
    explanation: '在声源处减弱噪声是从发声体处控制噪声。给摩托车安装消声器是在声源处减弱噪声。A是在传播过程中减弱，B、C是在人耳处减弱。',
    difficulty: 2,
    options: '["A. 在公路两旁植树", "B. 戴上防噪声耳罩", "C. 关闭门窗", "D. 给摩托车安装消声器"]',
  },
  {
    questionKey: 'physics-renjiao-8-0-8',
    type: 'choice',
    questionText: '利用超声波可以除去人体内的结石，这说明声波能够（）',
    answer: 'B',
    explanation: '超声波具有能量，可以粉碎人体内的结石。这说明声波能够传递能量。',
    difficulty: 2,
    options: '["A. 传递信息", "B. 传递能量", "C. 在真空中传播", "D. 产生回声"]',
  },

  // ---- fill 5题 ----
  {
    questionKey: 'physics-renjiao-8-0-9',
    type: 'fill',
    questionText: '声音在15°C空气中的传播速度约为____m/s。',
    answer: '340',
    explanation: '在15°C的空气中，声音的传播速度约为340m/s，这是一个需要记住的常数。',
    difficulty: 1,
    acceptableAnswers: '["340"]',
  },
  {
    questionKey: 'physics-renjiao-8-0-10',
    type: 'fill',
    questionText: '声音的三要素分别是音调、____和____。',
    answer: '响度、音色',
    explanation: '声音的三个特性：音调（与频率有关）、响度（与振幅和距离有关）、音色（与发声体材料和结构有关）。',
    difficulty: 1,
    acceptableAnswers: '["响度、音色", "响度，音色", "音色、响度", "音色，响度"]',
  },
  {
    questionKey: 'physics-renjiao-8-0-11',
    type: 'fill',
    questionText: '人耳能听到的声音频率范围是____Hz到____Hz。',
    answer: '20、20000',
    explanation: '人耳的听觉频率范围是20Hz到20000Hz。高于20000Hz的叫超声波，低于20Hz的叫次声波。',
    difficulty: 1,
    acceptableAnswers: '["20、20000", "20，20000"]',
  },
  {
    questionKey: 'physics-renjiao-8-0-12',
    type: 'fill',
    questionText: '频率高于20000Hz的声波叫做____，频率低于20Hz的声波叫做____。',
    answer: '超声波、次声波',
    explanation: '高于20000Hz为超声波，低于20Hz为次声波，两者人耳都听不到。',
    difficulty: 2,
    acceptableAnswers: '["超声波、次声波", "超声波，次声波"]',
  },
  {
    questionKey: 'physics-renjiao-8-0-13',
    type: 'fill',
    questionText: '控制噪声的三种途径：在____处减弱、在____中减弱、在____处减弱。',
    answer: '声源、传播过程、人耳',
    explanation: '控制噪声的三个途径：在声源处减弱（如消声器）、在传播过程中减弱（如隔音墙）、在人耳处减弱（如耳罩）。',
    difficulty: 2,
    acceptableAnswers: '["声源、传播过程、人耳", "声源，传播过程，人耳"]',
  },

  // ---- short_answer 4题 ----
  {
    questionKey: 'physics-renjiao-8-0-14',
    type: 'short_answer',
    questionText: '某人站在山崖前大喊一声，经过2s后听到回声。已知声音在空气中的传播速度为340m/s，求人与山崖之间的距离。',
    answer: '声音往返总路程 s = vt = 340m/s × 2s = 680m。人与山崖的距离 d = s/2 = 680m/2 = 340m。',
    explanation: '回声是声音的反射。声音从人传到山崖再反射回人，往返一次。距离 = 声速 × 时间 / 2。',
    difficulty: 2,
  },
  {
    questionKey: 'physics-renjiao-8-0-15',
    type: 'short_answer',
    questionText: '甲同学把耳朵贴在长铁管的一端，乙同学在另一端敲一下铁管，甲同学听到了两次响声。请解释原因。',
    answer: '声音在固体中传播速度比在空气中快。敲击铁管时，声音同时通过铁管和空气传播，由于在铁管中传播速度快，先到达甲同学耳朵，所以甲同学听到了两次响声。',
    explanation: '声音在不同介质中传播速度不同，v固 > v气。同一声源通过不同介质传到同一位置，速度快的先到达。',
    difficulty: 2,
  },
  {
    questionKey: 'physics-renjiao-8-0-16',
    type: 'short_answer',
    questionText: '用超声波测位仪（声呐）探测海底深度，已知超声波在海水中的传播速度为1500m/s，从发出信号到接收到回声信号经过4s，求海底深度。',
    answer: '声音往返总路程 s = vt = 1500m/s × 4s = 6000m。海底深度 d = s/2 = 6000m/2 = 3000m。',
    explanation: '声呐原理与回声测距相同。超声波从海面传到海底再反射回来，深度 = 声速 × 时间 / 2。',
    difficulty: 3,
  },
  {
    questionKey: 'physics-renjiao-8-0-17',
    type: 'short_answer',
    questionText: '为什么我们能够分辨出不同乐器的声音？请用物理知识解释。',
    answer: '不同乐器的发声体材料、结构不同，即使演奏同一首曲子（音调相同），它们发出的声音的音色也不同。音色是由发声体的材料和结构决定的，因此我们能通过音色来分辨不同的乐器。',
    explanation: '音色是声音的第三个特性，取决于发声体的材料和结构。不同乐器即使发出相同音调的声音，音色也不同。',
    difficulty: 2,
  },

  // ---- true_false 2题 ----
  {
    questionKey: 'physics-renjiao-8-0-18',
    type: 'true_false',
    questionText: '声音可以在真空中传播。',
    answer: '错误',
    explanation: '声音的传播需要介质，真空中没有介质，因此声音不能在真空中传播。',
    difficulty: 1,
  },
  {
    questionKey: 'physics-renjiao-8-0-19',
    type: 'true_false',
    questionText: '只要物体振动，我们就一定能听到声音。',
    answer: '错误',
    explanation: '物体振动产生声音，但人耳能听到的声音频率范围为20~20000Hz。如果振动频率不在这个范围内（如超声波或次声波），或者没有传播介质，人就听不到。',
    difficulty: 2,
  },
];

// ========== 8-1 光现象 (28题) ==========

const chapter8_1: RawQuestion[] = [
  // ---- choice 13题 ----
  {
    questionKey: 'physics-renjiao-8-1-0',
    type: 'choice',
    questionText: '光在真空中的传播速度约为（）',
    answer: 'C',
    explanation: '光在真空中的传播速度约为3×10⁸m/s，这是物理学中重要的常数。',
    difficulty: 1,
    options: '["A. 3×10⁶m/s", "B. 3×10⁷m/s", "C. 3×10⁸m/s", "D. 3×10⁹m/s"]',
  },
  {
    questionKey: 'physics-renjiao-8-1-1',
    type: 'choice',
    questionText: '下列现象中，属于光的直线传播的是（）',
    answer: 'A',
    explanation: '影子的形成是光的直线传播现象。B是光的反射，C是光的折射，D是光的色散。',
    difficulty: 1,
    options: '["A. 影子的形成", "B. 水中倒影", "C. 池水看起来变浅", "D. 雨后彩虹"]',
  },
  {
    questionKey: 'physics-renjiao-8-1-2',
    type: 'choice',
    questionText: '光的反射定律中，反射角____入射角。',
    answer: 'B',
    explanation: '光的反射定律：反射光线、入射光线和法线在同一平面内；反射光线和入射光线分居法线两侧；反射角等于入射角。',
    difficulty: 1,
    options: '["A. 大于", "B. 等于", "C. 小于", "D. 不确定"]',
  },
  {
    questionKey: 'physics-renjiao-8-1-3',
    type: 'choice',
    questionText: '一束光射到平面镜上，入射角为30°，则反射角为（）',
    answer: 'C',
    explanation: '由反射定律可知，反射角等于入射角，所以反射角也为30°。',
    difficulty: 1,
    options: '["A. 15°", "B. 20°", "C. 30°", "D. 60°"]',
  },
  {
    questionKey: 'physics-renjiao-8-1-4',
    type: 'choice',
    questionText: '下列哪种现象属于光的折射（）',
    answer: 'B',
    explanation: '从水中看岸上的物体变高了，是因为光从空气进入水中时发生折射。A是直线传播，C是反射，D是色散（折射的特例，但通常单独归类）。',
    difficulty: 1,
    options: '["A. 小孔成像", "B. 从水中看岸上物体变高", "C. 平面镜成像", "D. 镜花水月"]',
  },
  {
    questionKey: 'physics-renjiao-8-1-5',
    type: 'choice',
    questionText: '平面镜所成的像是（）',
    answer: 'A',
    explanation: '平面镜成的是正立、等大的虚像，像与物关于镜面对称。',
    difficulty: 1,
    options: '["A. 正立、等大的虚像", "B. 正立、放大的虚像", "C. 倒立、等大的实像", "D. 倒立、缩小的实像"]',
  },
  {
    questionKey: 'physics-renjiao-8-1-6',
    type: 'choice',
    questionText: '人站在平面镜前2m处，人在镜中的像到人的距离是（）',
    answer: 'C',
    explanation: '人距镜2m，像距镜也为2m（物像等距），所以人到像的距离为2+2=4m。',
    difficulty: 1,
    options: '["A. 1m", "B. 2m", "C. 4m", "D. 8m"]',
  },
  {
    questionKey: 'physics-renjiao-8-1-7',
    type: 'choice',
    questionText: '下列关于光的说法正确的是（）',
    answer: 'D',
    explanation: '光年不是时间单位而是长度单位（光在一年内传播的距离）。A错：光只有在均匀介质中才沿直线传播；B错：漫反射也遵循反射定律；C错：反射角等于入射角。',
    difficulty: 2,
    options: '["A. 光总是沿直线传播", "B. 镜面反射遵循反射定律，漫反射不遵循", "C. 反射角大于入射角", "D. 光年是长度单位"]',
  },
  {
    questionKey: 'physics-renjiao-8-1-8',
    type: 'choice',
    questionText: '池水看起来比实际深度浅，这是因为光从水中射入空气时发生了（）',
    answer: 'B',
    explanation: '光从水中射入空气时发生折射，折射角大于入射角，人看到的池底像是实际池底的虚像，位置比实际池底高，所以池水看起来变浅了。',
    difficulty: 2,
    options: '["A. 反射", "B. 折射", "C. 直线传播", "D. 散射"]',
  },
  {
    questionKey: 'physics-renjiao-8-1-9',
    type: 'choice',
    questionText: '红、绿、蓝三种色光被称为（）',
    answer: 'A',
    explanation: '红、绿、蓝是光的三原色（色光三原色），按不同比例混合可以得到各种颜色的光。',
    difficulty: 1,
    options: '["A. 光的三原色", "B. 颜料的三原色", "C. 光的三基色", "D. 彩虹的三色"]',
  },
  {
    questionKey: 'physics-renjiao-8-1-10',
    type: 'choice',
    questionText: '下列哪个是颜料的三原色（）',
    answer: 'C',
    explanation: '颜料的三原色是红、黄、蓝（品红、黄、青）。注意颜料三原色与色光三原色不同。',
    difficulty: 2,
    options: '["A. 红、绿、蓝", "B. 红、绿、黄", "C. 红、黄、蓝", "D. 红、白、蓝"]',
  },
  {
    questionKey: 'physics-renjiao-8-1-11',
    type: 'choice',
    questionText: '白色光通过三棱镜后分解成多种色光，这种现象叫做（）',
    answer: 'B',
    explanation: '白光通过三棱镜分解成红、橙、黄、绿、蓝、靛、紫七种色光的现象叫做光的色散，是牛顿发现的。',
    difficulty: 1,
    options: '["A. 光的反射", "B. 光的色散", "C. 光的折射", "D. 光的衍射"]',
  },
  {
    questionKey: 'physics-renjiao-8-1-12',
    type: 'choice',
    questionText: '关于红外线和紫外线，下列说法正确的是（）',
    answer: 'A',
    explanation: '红外线的主要特性是热效应，紫外线的主要特性是化学效应。红外线可用于遥控器、夜视仪；紫外线可用于杀菌消毒。',
    difficulty: 2,
    options: '["A. 红外线具有热效应", "B. 紫外线具有热效应", "C. 红外线肉眼可见", "D. 紫外线肉眼可见"]',
  },

  // ---- fill 7题 ----
  {
    questionKey: 'physics-renjiao-8-1-13',
    type: 'fill',
    questionText: '光在真空中的传播速度为____m/s，合____km/s。',
    answer: '3×10⁸、3×10⁵',
    explanation: '光速c=3×10⁸m/s=3×10⁵km/s。',
    difficulty: 1,
    acceptableAnswers: '["3×10⁸、3×10⁵", "3e8、3e5", "300000000、300000"]',
  },
  {
    questionKey: 'physics-renjiao-8-1-14',
    type: 'fill',
    questionText: '入射光线与平面镜的夹角为40°，则入射角为____°，反射角为____°。',
    answer: '50、50',
    explanation: '入射角是入射光线与法线的夹角，不是与镜面的夹角。入射角=90°-40°=50°，反射角=入射角=50°。',
    difficulty: 2,
    acceptableAnswers: '["50、50", "50，50"]',
  },
  {
    questionKey: 'physics-renjiao-8-1-15',
    type: 'fill',
    questionText: '平面镜成像的特点是：像与物大小____，像到镜面的距离____物到镜面的距离，所成的像是____像。',
    answer: '相等、等于、虚',
    explanation: '平面镜成像特点：等大、等距、虚像、像物连线垂直于镜面。',
    difficulty: 1,
    acceptableAnswers: '["相等、等于、虚", "相等，等于，虚"]',
  },
  {
    questionKey: 'physics-renjiao-8-1-16',
    type: 'fill',
    questionText: '太阳光通过三棱镜后，在白屏上自上而下依次呈现____、____、黄、绿、蓝、靛、____七种颜色。',
    answer: '红、橙、紫',
    explanation: '白光色散后从上到下为：红、橙、黄、绿、蓝、靛、紫。红光偏折最小，紫光偏折最大。',
    difficulty: 2,
    acceptableAnswers: '["红、橙、紫", "红，橙，紫"]',
  },
  {
    questionKey: 'physics-renjiao-8-1-17',
    type: 'fill',
    questionText: '我们能从各个方向看到本身不发光的物体，是因为光在这些物体表面发生了____反射。',
    answer: '漫',
    explanation: '表面粗糙的物体将光反射向各个方向，这种反射叫做漫反射。漫反射使我们能从各个方向看到物体。',
    difficulty: 1,
    acceptableAnswers: '["漫"]',
  },
  {
    questionKey: 'physics-renjiao-8-1-18',
    type: 'fill',
    questionText: '排纵队时，如果看到前面的一位同学挡住了所有同学，队就排直了，这是利用了光的____原理。',
    answer: '直线传播',
    explanation: '光沿直线传播，当挡住了后面所有人时，说明所有人在同一条直线上。',
    difficulty: 2,
    acceptableAnswers: '["直线传播"]',
  },
  {
    questionKey: 'physics-renjiao-8-1-19',
    type: 'fill',
    questionText: '电影院放映电影时，银幕用白色粗糙的布制作，这利用了光的____反射，使各个方向的观众都能看到。',
    answer: '漫',
    explanation: '白色粗糙银幕使光发生漫反射，让各个角落的观众都能看到画面。',
    difficulty: 2,
    acceptableAnswers: '["漫"]',
  },

  // ---- short_answer 6题 ----
  {
    questionKey: 'physics-renjiao-8-1-20',
    type: 'short_answer',
    questionText: '一束光线与水平面成30°角射来，若用平面镜使反射光线沿水平方向射出，求平面镜与水平面之间的夹角。',
    answer: '有两种情况：(1) 反射光线水平向右（与入射光线在同一侧），入射光线与水平面成30°角，则入射角=90°-30°=60°。反射角也为60°，法线与水平面夹角为60°，平面镜与水平面夹角=90°-60°=30°。(2) 反射光线水平向左（与入射光线在法线两侧），入射角=30°，反射角=30°，法线与水平面夹角=30°，平面镜与水平面夹角=90°-30°=60°。',
    explanation: '需要分两种情况讨论：反射光线水平向右或水平向左。利用反射定律和几何关系求解。',
    difficulty: 3,
  },
  {
    questionKey: 'physics-renjiao-8-1-21',
    type: 'short_answer',
    questionText: '身高1.6m的人站在平面镜前，要想看到自己的全身像，平面镜至少要多高？平面镜应该怎样放置？',
    answer: '平面镜至少需要0.8m（身高的一半）。平面镜的顶端应与头顶和眼睛之间的中点平齐，底端应与脚底和眼睛之间的中点平齐。平面镜应竖直放置。',
    explanation: '根据平面镜成像的对称性，要看到全身像，镜子的最小高度为人身高的一半，放置在从头顶到脚底的中点位置。',
    difficulty: 3,
  },
  {
    questionKey: 'physics-renjiao-8-1-22',
    type: 'short_answer',
    questionText: '为什么雨后天空会出现彩虹？请用光学知识解释。',
    answer: '雨后天空中悬浮着许多小水滴，太阳光射入水滴时发生折射，白光被分解成红、橙、黄、绿、蓝、靛、紫七种色光，这就是光的色散现象。因此我们看到天空出现彩虹。',
    explanation: '彩虹是太阳光经过空气中的小水滴折射和色散形成的自然现象。',
    difficulty: 2,
  },
  {
    questionKey: 'physics-renjiao-8-1-23',
    type: 'short_answer',
    questionText: '小明在湖边看到"鱼在云中游"的景象，他所看到的"鱼"和"云"分别是什么光学现象？',
    answer: '看到的"鱼"是光的折射形成的虚像。鱼反射的光从水中射入空气时发生折射，折射光线进入人眼，人逆着折射光线看去看到的是鱼的虚像，位置比实际鱼的位置高。看到的"云"是光的反射（平面镜成像）形成的虚像。云反射的光射到水面发生反射，人看到的是云的虚像。',
    explanation: '水中看鱼是折射现象，水面倒影是反射现象。两种现象都是虚像，但成因不同。',
    difficulty: 3,
  },
  {
    questionKey: 'physics-renjiao-8-1-24',
    type: 'short_answer',
    questionText: '一束光从空气射向水面，已知入射角为45°，折射角为32°。若入射角增大到60°，折射角将如何变化？为什么？',
    answer: '折射角将大于32°但小于60°。因为光从空气（光疏介质）射入水（光密介质）时，折射角小于入射角，但折射角随入射角的增大而增大。当入射角从45°增大到60°时，折射角也相应增大，但仍小于入射角。',
    explanation: '光从光疏介质进入光密介质时，折射角<入射角，且折射角随入射角的增大而增大。',
    difficulty: 3,
  },
  {
    questionKey: 'physics-renjiao-8-1-25',
    type: 'short_answer',
    questionText: '小孔成像说明光具有什么性质？小孔成像的像有什么特点？',
    answer: '小孔成像说明光沿直线传播。小孔成像的特点：成的是倒立的实像。像的大小取决于物距和像距的关系：物距大于像距时成缩小的像，物距等于像距时成等大的像，物距小于像距时成放大的像。',
    explanation: '小孔成像是由光的直线传播形成的，像的形状与物体相同，但上下左右颠倒。',
    difficulty: 2,
  },

  // ---- true_false 2题 ----
  {
    questionKey: 'physics-renjiao-8-1-26',
    type: 'true_false',
    questionText: '光年是时间的单位。',
    answer: '错误',
    explanation: '光年是长度单位，是光在真空中一年内传播的距离，约9.46×10¹²km。',
    difficulty: 1,
  },
  {
    questionKey: 'physics-renjiao-8-1-27',
    type: 'true_false',
    questionText: '漫反射不遵循光的反射定律。',
    answer: '错误',
    explanation: '镜面反射和漫反射都遵循光的反射定律。漫反射只是因为反射面粗糙，各法线方向不同，使反射光线射向各个方向。',
    difficulty: 2,
  },
];

// ========== 8-2 透镜及其应用 (24题) ==========

const chapter8_2: RawQuestion[] = [
  // ---- choice 11题 ----
  {
    questionKey: 'physics-renjiao-8-2-0',
    type: 'choice',
    questionText: '凸透镜对光线具有____作用，凹透镜对光线具有____作用。',
    answer: 'A',
    explanation: '凸透镜（中间厚边缘薄）对光线有会聚作用，凹透镜（中间薄边缘厚）对光线有发散作用。',
    difficulty: 1,
    options: '["A. 会聚、发散", "B. 发散、会聚", "C. 会聚、会聚", "D. 发散、发散"]',
  },
  {
    questionKey: 'physics-renjiao-8-2-1',
    type: 'choice',
    questionText: '在探究凸透镜成像的实验中，当蜡烛距凸透镜30cm时，在光屏上得到倒立缩小的清晰像，则该凸透镜的焦距可能是（）',
    answer: 'B',
    explanation: '物距u=30cm，成倒立缩小实像，说明u>2f，即30>2f，f<15cm。B选项f=10cm满足条件。',
    difficulty: 2,
    options: '["A. 20cm", "B. 10cm", "C. 15cm", "D. 18cm"]',
  },
  {
    questionKey: 'physics-renjiao-8-2-2',
    type: 'choice',
    questionText: '照相机利用了凸透镜成____像的原理。',
    answer: 'A',
    explanation: '照相机：物距u>2f，成倒立、缩小的实像。',
    difficulty: 1,
    options: '["A. 倒立、缩小的实", "B. 倒立、放大的实", "C. 正立、放大的虚", "D. 正立、缩小的虚"]',
  },
  {
    questionKey: 'physics-renjiao-8-2-3',
    type: 'choice',
    questionText: '投影仪（幻灯机）利用了凸透镜成____像的原理。',
    answer: 'B',
    explanation: '投影仪：f<u<2f，成倒立、放大的实像。投影片要倒着放才能在屏幕上看到正立的像。',
    difficulty: 1,
    options: '["A. 倒立、缩小的实", "B. 倒立、放大的实", "C. 正立、放大的虚", "D. 正立、等大的虚"]',
  },
  {
    questionKey: 'physics-renjiao-8-2-4',
    type: 'choice',
    questionText: '放大镜利用了凸透镜成____像的原理。',
    answer: 'C',
    explanation: '放大镜：u<f，成正立、放大的虚像。使用时物体需放在焦点以内。',
    difficulty: 1,
    options: '["A. 倒立、缩小的实", "B. 倒立、放大的实", "C. 正立、放大的虚", "D. 倒立、缩小的虚"]',
  },
  {
    questionKey: 'physics-renjiao-8-2-5',
    type: 'choice',
    questionText: '当物体从距凸透镜2倍焦距以外向焦点移动的过程中，像的变化情况是（）',
    answer: 'D',
    explanation: '当物距从大于2f逐渐减小到接近f的过程中，像距逐渐增大，像逐渐变大。但像始终是倒立的实像。',
    difficulty: 2,
    options: '["A. 像逐渐变小", "B. 像先变小后变大", "C. 像大小不变", "D. 像逐渐变大"]',
  },
  {
    questionKey: 'physics-renjiao-8-2-6',
    type: 'choice',
    questionText: '关于近视眼和远视眼，下列说法正确的是（）',
    answer: 'A',
    explanation: '近视眼成像在视网膜前方，用凹透镜矫正；远视眼成像在视网膜后方，用凸透镜矫正。',
    difficulty: 2,
    options: '["A. 近视眼用凹透镜矫正", "B. 远视眼用凹透镜矫正", "C. 近视眼成像在视网膜后方", "D. 正常眼成像不在视网膜上"]',
  },
  {
    questionKey: 'physics-renjiao-8-2-7',
    type: 'choice',
    questionText: '凸透镜的焦距为10cm，物体放在距透镜25cm处，所成的像是（）',
    answer: 'A',
    explanation: 'f=10cm，u=25cm>2f=20cm，所以成倒立、缩小的实像。',
    difficulty: 2,
    options: '["A. 倒立、缩小的实像", "B. 倒立、放大的实像", "C. 正立、放大的虚像", "D. 正立、缩小的虚像"]',
  },
  {
    questionKey: 'physics-renjiao-8-2-8',
    type: 'choice',
    questionText: '在探究凸透镜成像规律实验中，已知凸透镜焦距为10cm，当蜡烛距透镜15cm时，光屏上能得到（）',
    answer: 'B',
    explanation: 'f=10cm，u=15cm，满足f<u<2f（10<15<20），成倒立、放大的实像。',
    difficulty: 2,
    options: '["A. 倒立缩小的实像", "B. 倒立放大的实像", "C. 正立放大的虚像", "D. 正立缩小的虚像"]',
  },
  {
    questionKey: 'physics-renjiao-8-2-9',
    type: 'choice',
    questionText: '显微镜的物镜和目镜分别是（）',
    answer: 'C',
    explanation: '显微镜物镜成倒立放大的实像（f<u<2f），目镜成正立放大的虚像（u<f），两者都是凸透镜。',
    difficulty: 3,
    options: '["A. 凹透镜、凸透镜", "B. 凸透镜、凹透镜", "C. 凸透镜、凸透镜", "D. 凹透镜、凹透镜"]',
  },
  {
    questionKey: 'physics-renjiao-8-2-10',
    type: 'choice',
    questionText: '望远镜的物镜和目镜分别是（）',
    answer: 'A',
    explanation: '开普勒望远镜物镜和目镜都是凸透镜。物镜成倒立缩小的实像，目镜成正立放大的虚像。',
    difficulty: 3,
    options: '["A. 都是凸透镜", "B. 物镜凸透镜、目镜凹透镜", "C. 都是凹透镜", "D. 物镜凹透镜、目镜凸透镜"]',
  },

  // ---- fill 6题 ----
  {
    questionKey: 'physics-renjiao-8-2-11',
    type: 'fill',
    questionText: '凸透镜的焦点到光心的距离叫做____，用字母____表示。',
    answer: '焦距、f',
    explanation: '凸透镜的焦点到光心的距离叫焦距，用字母f表示。焦距越短，折光能力越强。',
    difficulty: 1,
    acceptableAnswers: '["焦距、f", "焦距，f"]',
  },
  {
    questionKey: 'physics-renjiao-8-2-12',
    type: 'fill',
    questionText: '凸透镜成实像时，物距增大，像距____，像____。',
    answer: '减小、变小',
    explanation: '凸透镜成实像时，物距增大则像距减小，像变小。物像异侧移动方向相同。',
    difficulty: 2,
    acceptableAnswers: '["减小、变小", "减小，变小"]',
  },
  {
    questionKey: 'physics-renjiao-8-2-13',
    type: 'fill',
    questionText: '人的眼睛像一架____，晶状体和角膜共同作用相当于一个____。',
    answer: '照相机、凸透镜',
    explanation: '人眼的晶状体和角膜相当于凸透镜，视网膜相当于光屏，来自物体的光经折射后成像在视网膜上。',
    difficulty: 1,
    acceptableAnswers: '["照相机、凸透镜", "照相机，凸透镜"]',
  },
  {
    questionKey: 'physics-renjiao-8-2-14',
    type: 'fill',
    questionText: '近视眼看不清远处的物体，需要用____透镜来矫正；远视眼看不清近处的物体，需要用____透镜来矫正。',
    answer: '凹、凸',
    explanation: '近视眼用凹透镜（使光线适当发散），远视眼用凸透镜（使光线适当会聚）。',
    difficulty: 1,
    acceptableAnswers: '["凹、凸", "凹，凸"]',
  },
  {
    questionKey: 'physics-renjiao-8-2-15',
    type: 'fill',
    questionText: '凸透镜焦距为12cm，当物体放在距透镜____cm处时，能成等大的实像。',
    answer: '24',
    explanation: '成等大实像的条件是u=2f=2×12cm=24cm。',
    difficulty: 2,
    acceptableAnswers: '["24"]',
  },
  {
    questionKey: 'physics-renjiao-8-2-16',
    type: 'fill',
    questionText: '凸透镜焦距为10cm，将物体放在距透镜8cm处，能看到一个____立、____的____像。',
    answer: '正、放大、虚',
    explanation: 'u=8cm<f=10cm，成正立、放大的虚像，像和物在透镜同侧。',
    difficulty: 2,
    acceptableAnswers: '["正、放大、虚", "正，放大，虚"]',
  },

  // ---- short_answer 5题 ----
  {
    questionKey: 'physics-renjiao-8-2-17',
    type: 'short_answer',
    questionText: '在探究"凸透镜成像规律"的实验中，已知凸透镜焦距为10cm。当蜡烛距透镜30cm时，求像距，并说明像的性质。',
    answer: '由透镜成像公式 1/f = 1/u + 1/v，1/10 = 1/30 + 1/v，1/v = 1/10 - 1/30 = 3/30 - 1/30 = 2/30 = 1/15，v = 15cm。因为u=30cm>2f=20cm，所以成倒立、缩小的实像，像距为15cm。',
    explanation: '代入透镜成像公式，u>2f时成倒立缩小的实像，f<v<2f。验证：1/10=0.1，1/30+1/15=1/30+2/30=3/30=1/10，正确。',
    difficulty: 3,
  },
  {
    questionKey: 'physics-renjiao-8-2-18',
    type: 'short_answer',
    questionText: '在做凸透镜成像实验时，蜡烛、凸透镜、光屏应按什么顺序排列？光屏上的像最清晰时满足什么条件？',
    answer: '蜡烛、凸透镜、光屏从左到右依次排列在同一直线上（光具座上）。光屏上的像最清晰时，满足透镜成像公式1/f=1/u+1/v，此时光屏到透镜的距离正好等于像距v。',
    explanation: '实验时需调节三者中心大致在同一高度（等高共轴），使像成在光屏中央。移动光屏直到像最清晰。',
    difficulty: 2,
  },
  {
    questionKey: 'physics-renjiao-8-2-19',
    type: 'short_answer',
    questionText: '老花镜的镜片是什么透镜？为什么戴上老花镜能看清近处的文字？',
    answer: '老花镜的镜片是凸透镜。远视眼（老花眼）由于晶状体折光能力太弱，近处物体的像成在视网膜后方。戴上凸透镜后，凸透镜先对光线进行一次会聚，使经过晶状体折射后的像刚好成在视网膜上，因此能看清近处文字。',
    explanation: '老花眼是远视眼的一种，成像在视网膜后方，需要用凸透镜增加会聚能力来矫正。',
    difficulty: 2,
  },
  {
    questionKey: 'physics-renjiao-8-2-20',
    type: 'short_answer',
    questionText: '凸透镜焦距为10cm，一物体放在距透镜35cm处，请用透镜成像公式计算像距，并说明像的性质。',
    answer: '由公式1/f=1/u+1/v：1/10=1/35+1/v，1/v=1/10-1/35=7/70-2/70=5/70=1/14，v=14cm。因为u=35cm>2f=20cm，成倒立、缩小的实像，像在透镜另一侧14cm处。',
    explanation: 'u>2f，成倒立缩小实像，f<v<2f。验证：1/10=0.1，1/35+1/14=2/70+5/70=7/70=1/10，正确。',
    difficulty: 3,
  },
  {
    questionKey: 'physics-renjiao-8-2-21',
    type: 'short_answer',
    questionText: '在凸透镜成像实验中，如果用纸遮住凸透镜的上半部分，光屏上的像会发生什么变化？',
    answer: '光屏上仍能成完整的像，但像会比原来暗一些。因为凸透镜的每一部分都能成像，遮住上半部分只是减少了通过透镜的光量，不影响像的完整性和位置。',
    explanation: '透镜各部分都能独立成像，遮住一部分只影响像的亮度，不影响像的形状和位置。',
    difficulty: 2,
  },

  // ---- true_false 2题 ----
  {
    questionKey: 'physics-renjiao-8-2-22',
    type: 'true_false',
    questionText: '凸透镜只能成实像，不能成虚像。',
    answer: '错误',
    explanation: '凸透镜既能成实像（u>f时），也能成虚像（u<f时）。放大镜就是利用凸透镜成正立放大虚像的原理。',
    difficulty: 1,
  },
  {
    questionKey: 'physics-renjiao-8-2-23',
    type: 'true_false',
    questionText: '物体在凸透镜焦点以外成实像，在焦点以内成虚像。',
    answer: '正确',
    explanation: '当u>f时，凸透镜成实像（倒立）；当u<f时，成正立放大的虚像。焦点是实像和虚像的分界点。',
    difficulty: 2,
  },
];

// ========== 8-3 物态变化 (22题) ==========

const chapter8_3: RawQuestion[] = [
  // ---- choice 10题 ----
  {
    questionKey: 'physics-renjiao-8-3-0',
    type: 'choice',
    questionText: '下列物态变化中，属于液化现象的是（）',
    answer: 'B',
    explanation: '液化是气体变为液体的过程。A是升华，B是液化（水蒸气遇冷变成小水滴），C是熔化，D是凝华。',
    difficulty: 1,
    options: '["A. 樟脑丸变小", "B. 冰镇饮料瓶外壁"出现水珠", "C. 冰雪消融", "D. 霜的形成"]',
  },
  {
    questionKey: 'physics-renjiao-8-3-1',
    type: 'choice',
    questionText: '下列物态变化中，属于升华现象的是（）',
    answer: 'A',
    explanation: '升华是固体直接变为气体的过程。A是升华（冰冻衣服变干是冰直接变成水蒸气），B是液化，C是熔化，D是凝华。',
    difficulty: 1,
    options: '["A. 冰冻的衣服变干", "B. 草叶上的露珠", "C. 铁块熔化成铁水", "D. 窗玻璃上的冰花"]',
  },
  {
    questionKey: 'physics-renjiao-8-3-2',
    type: 'choice',
    questionText: '下列物态变化中，需要吸热的是（）',
    answer: 'C',
    explanation: '熔化、汽化、升华需要吸热；凝固、液化、凝华需要放热。C熔化是吸热过程。',
    difficulty: 1,
    options: '["A. 水结冰", "B. 水蒸气液化", "C. 冰熔化成水", "D. 霜的形成"]',
  },
  {
    questionKey: 'physics-renjiao-8-3-3',
    type: 'choice',
    questionText: '夏天，从冰箱里拿出的饮料瓶"出汗"，这是____现象。',
    answer: 'B',
    explanation: '瓶壁"出汗"是空气中的水蒸气遇到冷的瓶壁液化成小水珠附着在瓶壁上，属于液化现象。',
    difficulty: 1,
    options: '["A. 熔化", "B. 液化", "C. 汽化", "D. 凝华"]',
  },
  {
    questionKey: 'physics-renjiao-8-3-4',
    type: 'choice',
    questionText: '北方冬天晾在户外的湿衣服会变硬，这是____现象。',
    answer: 'A',
    explanation: '湿衣服中的水凝固成冰，衣服变硬，属于凝固现象。',
    difficulty: 1,
    options: '["A. 凝固", "B. 凝华", "C. 液化", "D. 升华"]',
  },
  {
    questionKey: 'physics-renjiao-8-3-5',
    type: 'choice',
    questionText: '下列说法正确的是（）',
    answer: 'C',
    explanation: '晶体在熔化过程中温度不变（有熔点），非晶体在熔化过程中温度持续上升（无固定熔点）。冰、海波是晶体；蜡、玻璃、沥青是非晶体。',
    difficulty: 2,
    options: '["A. 所有固体都有固定的熔点", "B. 晶体在熔化过程中温度不断升高", "C. 冰是晶体，有固定的熔点", "D. 非晶体没有熔化过程"]',
  },
  {
    questionKey: 'physics-renjiao-8-3-6',
    type: 'choice',
    questionText: '水的沸点在标准大气压下是（）',
    answer: 'B',
    explanation: '在标准大气压下，水的沸点是100°C。沸点随气压的增大而升高，随气压的减小而降低。',
    difficulty: 1,
    options: '["A. 90°C", "B. 100°C", "C. 110°C", "D. 120°C"]',
  },
  {
    questionKey: 'physics-renjiao-8-3-7',
    type: 'choice',
    questionText: '夏天扇扇子，人感到凉爽，这是因为扇子（）',
    answer: 'C',
    explanation: '扇扇子加快了人体表面空气的流动速度，加快了汗液的蒸发（蒸发吸热），使人体表面温度降低，感到凉爽。扇子不能降低空气温度。',
    difficulty: 2,
    options: '["A. 降低了空气温度", "B. 降低了人体温度", "C. 加快了汗液蒸发", "D. 减小了空气湿度"]',
  },
  {
    questionKey: 'physics-renjiao-8-3-8',
    type: 'choice',
    questionText: '下列措施中，能使蒸发变快的是（）',
    answer: 'D',
    explanation: '影响蒸发快慢的因素：温度越高、表面积越大、表面空气流速越快，蒸发越快。D提高了温度，加快了蒸发。',
    difficulty: 1,
    options: '["A. 把酒精装在密封瓶中", "B. 把湿衣服展开", "C. 用电吹风吹湿头发（冷风档）", "D. 把湿衣服放在阳光下晾"]',
  },
  {
    questionKey: 'physics-renjiao-8-3-9',
    type: 'choice',
    questionText: '冬天，窗户玻璃的____（填"内"或"外"）表面会出现冰花，这是____现象。',
    answer: 'A',
    explanation: '冬天室内温度高，室内水蒸气温度高遇到冷的玻璃凝华成小冰晶，附着在玻璃内表面。这是凝华现象。',
    difficulty: 2,
    options: '["A. 内、凝华", "B. 外、凝华", "C. 内、凝固", "D. 外、凝固"]',
  },

  // ---- fill 6题 ----
  {
    questionKey: 'physics-renjiao-8-3-10',
    type: 'fill',
    questionText: '物质从固态变为液态叫做____，从液态变为固态叫做____。',
    answer: '熔化、凝固',
    explanation: '固态→液态是熔化（吸热），液态→固态是凝固（放热）。',
    difficulty: 1,
    acceptableAnswers: '["熔化、凝固", "熔化，凝固"]',
  },
  {
    questionKey: 'physics-renjiao-8-3-11',
    type: 'fill',
    questionText: '物质从液态变为气态叫做____，从气态变为液态叫做____。',
    answer: '汽化、液化',
    explanation: '液态→气态是汽化（吸热），气态→液态是液化（放热）。汽化包括蒸发和沸腾两种方式。',
    difficulty: 1,
    acceptableAnswers: '["汽化、液化", "汽化，液化"]',
  },
  {
    questionKey: 'physics-renjiao-8-3-12',
    type: 'fill',
    questionText: '物质从固态直接变为气态叫做____，从气态直接变为固态叫做____。',
    answer: '升华、凝华',
    explanation: '固态→气态是升华（吸热），气态→固态是凝华（放热）。',
    difficulty: 1,
    acceptableAnswers: '["升华、凝华", "升华，凝华"]',
  },
  {
    questionKey: 'physics-renjiao-8-3-13',
    type: 'fill',
    questionText: '在标准大气压下，冰的熔点是____°C，水的沸点是____°C。',
    answer: '0、100',
    explanation: '标准大气压下，冰的熔点（水的凝固点）为0°C，水的沸点为100°C。',
    difficulty: 1,
    acceptableAnswers: '["0、100", "0，100"]',
  },
  {
    questionKey: 'physics-renjiao-8-3-14',
    type: 'fill',
    questionText: '汽化有____和____两种方式。',
    answer: '蒸发、沸腾',
    explanation: '汽化有两种方式：蒸发（在任何温度下都能发生，只在液体表面进行）和沸腾（在一定温度下发生，在液体表面和内部同时进行）。',
    difficulty: 1,
    acceptableAnswers: '["蒸发、沸腾", "蒸发，沸腾"]',
  },
  {
    questionKey: 'physics-renjiao-8-3-15',
    type: 'fill',
    questionText: '沸腾是在液体____和____同时发生的剧烈汽化现象，沸腾时温度____。',
    answer: '表面、内部、不变',
    explanation: '沸腾在液体表面和内部同时发生，是剧烈的汽化现象。液体沸腾时继续吸热但温度保持不变（沸点）。',
    difficulty: 2,
    acceptableAnswers: '["表面、内部、不变", "表面，内部，不变"]',
  },

  // ---- short_answer 4题 ----
  {
    questionKey: 'physics-renjiao-8-3-16',
    type: 'short_answer',
    questionText: '在"观察水的沸腾"实验中，水沸腾时温度计示数为98°C，此时气压____（填"高于"、"等于"或"低于"）标准大气压。如果继续加热，水的温度将如何变化？',
    answer: '水在98°C时沸腾，低于标准大气压下的沸点100°C，说明此时气压低于标准大气压。水沸腾后如果继续加热，温度将保持在98°C不变，因为沸腾时温度保持在沸点不变。',
    explanation: '气压越低沸点越低。水沸腾时继续吸热但温度不变。',
    difficulty: 2,
  },
  {
    questionKey: 'physics-renjiao-8-3-17',
    type: 'short_answer',
    questionText: '被100°C的水蒸气烫伤比被100°C的水烫伤更严重，为什么？',
    answer: '因为100°C的水蒸气液化成100°C的水时要放出大量的热（液化放热）。所以水蒸气烫伤时，除了100°C的水放热外，还多了液化放出的热量，因此烫伤更严重。',
    explanation: '水蒸气液化时释放热量，这是额外的热量来源，使得水蒸气烫伤比同温度的水烫伤更严重。',
    difficulty: 3,
  },
  {
    questionKey: 'physics-renjiao-8-3-18',
    type: 'short_answer',
    questionText: '请解释"下雪不冷化雪冷"的物理道理。',
    answer: '下雪是空气中水蒸气凝华成小冰晶的过程，凝华需要放热，使周围空气温度略有升高，所以下雪时不觉得特别冷。化雪是雪（固态冰）熔化成水的过程，熔化需要吸热，从周围空气中吸收大量热量，导致气温下降，所以化雪时感到冷。',
    explanation: '凝华放热→下雪不冷；熔化吸热→化雪冷。',
    difficulty: 3,
  },
  {
    questionKey: 'physics-renjiao-8-3-19',
    type: 'short_answer',
    questionText: '夏天打开冰棒的包装纸后会看到"白气"，这些"白气"是什么？是怎样形成的？',
    answer: '"白气"不是水蒸气（水蒸气是无色看不见的），而是空气中温度较高的水蒸气遇到冰棒周围的冷空气，液化成的大量小水滴（悬浮在空气中），看起来像"白气"。',
    explanation: '"白气"是小水滴（液态），是水蒸气遇冷液化形成的。注意区分水蒸气（看不见）和"白气"（看得见的小水滴）。',
    difficulty: 2,
  },

  // ---- true_false 2题 ----
  {
    questionKey: 'physics-renjiao-8-3-20',
    type: 'true_false',
    questionText: '所有固体都有固定的熔点。',
    answer: '错误',
    explanation: '只有晶体才有固定的熔点（如冰、海波、各种金属）。非晶体（如蜡、玻璃、沥青、松香）没有固定的熔点，熔化过程中温度持续上升。',
    difficulty: 2,
  },
  {
    questionKey: 'physics-renjiao-8-3-21',
    type: 'true_false',
    questionText: '蒸发和沸腾都是汽化现象，都需要吸热。',
    answer: '正确',
    explanation: '蒸发和沸腾都是液态变为气态的汽化现象，都需要吸收热量。区别在于：蒸发在任何温度下发生，只在液体表面；沸腾在沸点发生，在液体表面和内部同时进行。',
    difficulty: 1,
  },
];

// ========== 9-0 内能 (20题) ==========

const chapter9_0: RawQuestion[] = [
  // ---- choice 9题 ----
  {
    questionKey: 'physics-renjiao-9-0-0',
    type: 'choice',
    questionText: '物体的内能是（）',
    answer: 'A',
    explanation: '内能是物体内部所有分子热运动的动能和分子势能的总和。一切物体都有内能。',
    difficulty: 1,
    options: '["A. 物体内部所有分子动能和分子势能的总和", "B. 物体运动时具有的能", "C. 物体速度越大内能越大", "D. 只有运动的物体才有内能"]',
  },
  {
    questionKey: 'physics-renjiao-9-0-1',
    type: 'choice',
    questionText: '下列事例中，属于做功改变物体内能的是（）',
    answer: 'B',
    explanation: 'A、C、D都是热传递改变内能。B是做功改变内能（摩擦生热，机械能转化为内能）。',
    difficulty: 1,
    options: '["A. 用热水袋取暖", "B. 冬天搓手取暖", "C. 把食物放入冰箱", "D. 铁块放在火炉上加热"]',
  },
  {
    questionKey: 'physics-renjiao-9-0-2',
    type: 'choice',
    questionText: '关于温度、内能和热量，下列说法正确的是（）',
    answer: 'C',
    explanation: '温度反映分子热运动的剧烈程度；内能是所有分子动能和势能的总和；热量是热传递过程中传递能量的多少。物体温度升高，内能增大；但内能增大不一定温度升高（如晶体熔化时）。',
    difficulty: 2,
    options: '["A. 物体温度升高，一定吸收了热量", "B. 物体温度不变，内能一定不变", "C. 物体温度升高，内能一定增大", "D. 物体内能增大，温度一定升高"]',
  },
  {
    questionKey: 'physics-renjiao-9-0-3',
    type: 'choice',
    questionText: '水的比热容是4.2×10³J/(kg·°C)，其物理意义是（）',
    answer: 'A',
    explanation: '比热容的物理意义：1kg的某种物质温度升高（或降低）1°C所吸收（或放出）的热量。水的比热容4.2×10³J/(kg·°C)表示1kg水温度升高1°C吸收的热量为4.2×10³J。',
    difficulty: 1,
    options: '["A. 1kg水温度升高1°C吸收的热量为4.2×10³J", "B. 1kg水温度升高1°C吸收的热量为4.2×10³J/kg", "C. 1kg水吸收4.2×10³J热量温度升高1°C", "D. 水的温度升高1°C吸收4.2×10³J热量"]',
  },
  {
    questionKey: 'physics-renjiao-9-0-4',
    type: 'choice',
    questionText: '下列物质中，比热容最大的是（）',
    answer: 'D',
    explanation: '水的比热容是常见物质中最大的，为4.2×10³J/(kg·°C)。水的比热容大这一特性有很多实际应用。',
    difficulty: 1,
    options: '["A. 铁", "B. 铝", "C. 砂石", "D. 水"]',
  },
  {
    questionKey: 'physics-renjiao-9-0-5',
    type: 'choice',
    questionText: '质量为2kg的水温度从20°C升高到70°C，吸收的热量是（）',
    answer: 'B',
    explanation: 'Q=cmΔt=4.2×10³×2×(70-20)=4.2×10³×2×50=4.2×10³×100=4.2×10⁵J。',
    difficulty: 2,
    options: '["A. 2.1×10⁵J", "B. 4.2×10⁵J", "C. 8.4×10⁵J", "D. 1.05×10⁵J"]',
  },
  {
    questionKey: 'physics-renjiao-9-0-6',
    type: 'choice',
    questionText: '热机的四个冲程中，把内能转化为机械能的是（）',
    answer: 'C',
    explanation: '内燃机的四个冲程：吸气、压缩、做功、排气。其中做功冲程中高温高压燃气推动活塞做功，将内能转化为机械能。压缩冲程是将机械能转化为内能。',
    difficulty: 2,
    options: '["A. 吸气冲程", "B. 压缩冲程", "C. 做功冲程", "D. 排气冲程"]',
  },
  {
    questionKey: 'physics-renjiao-9-0-7',
    type: 'choice',
    questionText: '下列关于热值的说法正确的是（）',
    answer: 'A',
    explanation: '热值是1kg某种燃料完全燃烧释放的热量，是燃料本身的特性，与燃料的质量和是否完全燃烧无关。',
    difficulty: 2,
    options: '["A. 热值是燃料本身的特性，与质量无关", "B. 燃料的质量越大热值越大", "C. 燃烧越充分热值越大", "D. 热值与燃料的种类无关"]',
  },
  {
    questionKey: 'physics-renjiao-9-0-8',
    type: 'choice',
    questionText: '关于分子热运动，下列说法正确的是（）',
    answer: 'B',
    explanation: '一切物质的分子都在不停地做无规则运动（布朗运动），温度越高分子运动越剧烈。A错：分子运动是微观的，肉眼看不见；C错：0°C的冰分子也在运动；D错：扩散现象说明分子在运动。',
    difficulty: 2,
    options: '["A. 我们能看到灰尘在空中飞舞，这就是分子运动", "B. 温度越高，分子无规则运动越剧烈", "C. 0°C时分子停止运动", "D. 扩散现象不能说明分子在运动"]',
  },

  // ---- fill 5题 ----
  {
    questionKey: 'physics-renjiao-9-0-9',
    type: 'fill',
    questionText: '改变物体内能的两种方式是____和____。',
    answer: '做功、热传递',
    explanation: '做功和热传递是改变物体内能的两种方式。做功是能量的转化，热传递是能量的转移。二者在改变内能上是等效的。',
    difficulty: 1,
    acceptableAnswers: '["做功、热传递", "做功，热传递", "热传递、做功", "热传递，做功"]',
  },
  {
    questionKey: 'physics-renjiao-9-0-10',
    type: 'fill',
    questionText: '水的比热容为4.2×10³J/(kg·°C)，将5kg的水温度升高10°C，需要吸收____J的热量。',
    answer: '210000',
    explanation: 'Q=cmΔt=4.2×10³×5×10=4.2×10³×50=2.1×10⁵J=210000J。',
    difficulty: 2,
    acceptableAnswers: '["210000", "2.1×10⁵", "2.1e5"]',
  },
  {
    questionKey: 'physics-renjiao-9-0-11',
    type: 'fill',
    questionText: '内燃机的一个工作循环由____、____、____和____四个冲程组成。',
    answer: '吸气、压缩、做功、排气',
    explanation: '内燃机一个工作循环包含四个冲程：吸气冲程、压缩冲程、做功冲程、排气冲程。在一个工作循环中，活塞往复运动两次，曲轴转两周，对外做功一次。',
    difficulty: 1,
    acceptableAnswers: '["吸气、压缩、做功、排气", "吸气，压缩，做功，排气"]',
  },
  {
    questionKey: 'physics-renjiao-9-0-12',
    type: 'fill',
    questionText: '汽油机的压缩冲程中，____能转化为____能。',
    answer: '机械、内',
    explanation: '压缩冲程中，活塞压缩气缸内的混合气体做功，将机械能转化为气体的内能，使气体温度升高。',
    difficulty: 2,
    acceptableAnswers: '["机械、内", "机械，内"]',
  },
  {
    questionKey: 'physics-renjiao-9-0-13',
    type: 'fill',
    questionText: '扩散现象说明分子在____运动，温度越高，扩散越____。',
    answer: '不停地做无规则、快',
    explanation: '扩散现象是不同物质相互接触时彼此进入对方的现象，说明分子在不停地做无规则运动。温度越高，分子运动越快，扩散越快。',
    difficulty: 1,
    acceptableAnswers: '["不停地做无规则、快", "不停地做无规则，快"]',
  },

  // ---- short_answer 4题 ----
  {
    questionKey: 'physics-renjiao-9-0-14',
    type: 'short_answer',
    questionText: '完全燃烧0.5kg的干木柴（热值为1.2×10⁷J/kg），能释放多少热量？若这些热量全部被10kg的水吸收，水温能升高多少？',
    answer: '释放的热量 Q放 = mq = 0.5kg × 1.2×10⁷J/kg = 6×10⁶J。水温升高 Δt = Q吸/(cm) = 6×10⁶J / (4.2×10³J/(kg·°C) × 10kg) = 6×10⁶ / 4.2×10⁴ ≈ 142.9°C。',
    explanation: 'Q放=mq求出释放热量，再由Q吸=cmΔt求出温升。注意实际中水温不可能升高这么多（水会沸腾），此题为理论计算。',
    difficulty: 3,
  },
  {
    questionKey: 'physics-renjiao-9-0-15',
    type: 'short_answer',
    questionText: '质量为0.5kg的铝块，温度从30°C加热到130°C，共吸收了多少热量？[c铝=0.88×10³J/(kg·°C)]',
    answer: 'Q = cmΔt = 0.88×10³J/(kg·°C) × 0.5kg × (130°C - 30°C) = 0.88×10³ × 0.5 × 100 = 0.88×10³ × 50 = 4.4×10⁴J。',
    explanation: '直接套用公式Q=cmΔt，注意Δt=130-30=100°C。验证：0.88×10³×0.5=440，440×100=44000=4.4×10⁴J，正确。',
    difficulty: 2,
  },
  {
    questionKey: 'physics-renjiao-9-0-16',
    type: 'short_answer',
    questionText: '沿海地区昼夜温差较小，而内陆地区昼夜温差较大，请用比热容的知识解释。',
    answer: '水的比热容比砂石、泥土大得多。沿海地区多水，白天吸收大量热量温度升高不多，夜晚放出大量热量温度降低不多，因此昼夜温差小。内陆地区地面多为砂石，比热容小，吸收同样的热量温度升高多，放出同样的热量温度降低多，因此昼夜温差大。',
    explanation: '比热容大的物质温度变化小（"温度稳定"），比热容小的物质温度变化大。水的比热容远大于砂石。',
    difficulty: 3,
  },
  {
    questionKey: 'physics-renjiao-9-0-17',
    type: 'short_answer',
    questionText: '将质量为100g、温度为100°C的铁块投入200g、20°C的水中，达到热平衡后，混合温度是多少？[c铁=0.46×10³J/(kg·°C)，c水=4.2×10³J/(kg·°C)]',
    answer: '设混合温度为t。铁块放热：Q放=c铁m铁(100-t)=0.46×10³×0.1×(100-t)=46(100-t)。水吸热：Q吸=c水m水(t-20)=4.2×10³×0.2×(t-20)=840(t-20)。由Q放=Q吸：46(100-t)=840(t-20)，4600-46t=840t-16800，4600+16800=840t+46t，21400=886t，t≈24.2°C。',
    explanation: '热平衡方程Q放=Q吸，注意质量单位换算（g→kg）。验证：46×(100-24.2)=46×75.8=3486.8；840×(24.2-20)=840×4.2=3528。近似相等（四舍五入误差），计算正确。',
    difficulty: 3,
  },

  // ---- true_false 2题 ----
  {
    questionKey: 'physics-renjiao-9-0-18',
    type: 'true_false',
    questionText: '0°C的冰没有内能。',
    answer: '错误',
    explanation: '任何物体在任何温度下都有内能。0°C的冰，其分子仍在做无规则运动，具有分子动能；分子间也有相互作用力，具有分子势能。所以0°C的冰也有内能。',
    difficulty: 1,
  },
  {
    questionKey: 'physics-renjiao-9-0-19',
    type: 'true_false',
    questionText: '物体吸收热量，温度一定升高。',
    answer: '错误',
    explanation: '物体吸收热量温度不一定升高。例如晶体在熔化过程中虽然吸热，但温度保持在熔点不变；水在沸腾过程中吸热但温度不变。',
    difficulty: 2,
  },
];

// ========== 9-1 电流和电路 (28题) ==========

const chapter9_1: RawQuestion[] = [
  // ---- choice 13题 ----
  {
    questionKey: 'physics-renjiao-9-1-0',
    type: 'choice',
    questionText: '下列物体中属于导体的是（）',
    answer: 'A',
    explanation: '导体容易导电，如金属、人体、大地、酸碱盐溶液。B橡皮、C塑料、D干木头都是绝缘体。',
    difficulty: 1,
    options: '["A. 铜", "B. 橡皮", "C. 塑料", "D. 干木头"]',
  },
  {
    questionKey: 'physics-renjiao-9-1-1',
    type: 'choice',
    questionText: '电路中有持续电流的条件是（）',
    answer: 'C',
    explanation: '电路中有持续电流需要两个条件：有电源（提供电压）和电路是闭合的通路。',
    difficulty: 1,
    options: '["A. 只要有电源", "B. 只要有用电器", "C. 有电源且电路为通路", "D. 有开关且开关断开"]',
  },
  {
    questionKey: 'physics-renjiao-9-1-2',
    type: 'choice',
    questionText: '下列关于电流的说法正确的是（）',
    answer: 'B',
    explanation: '电流是电荷的定向移动形成的。规定正电荷定向移动的方向为电流方向。在金属导体中，自由电子定向移动方向与电流方向相反。',
    difficulty: 2,
    options: '["A. 电流方向是电子定向移动的方向", "B. 电流方向是正电荷定向移动的方向", "C. 只有正电荷移动才能形成电流", "D. 电流是电荷的无规则运动形成的"]',
  },
  {
    questionKey: 'physics-renjiao-9-1-3',
    type: 'choice',
    questionText: '两个灯泡串联在电路中，则通过两个灯泡的电流（）',
    answer: 'A',
    explanation: '串联电路中电流处处相等，所以通过两个灯泡的电流大小相同。',
    difficulty: 1,
    options: '["A. 相等", "B. 不相等", "C. 第一个灯泡的大", "D. 第二个灯泡的大"]',
  },
  {
    questionKey: 'physics-renjiao-9-1-4',
    type: 'choice',
    questionText: '两个灯泡并联在电路中，则通过两个灯泡的电流（）',
    answer: 'B',
    explanation: '并联电路中干路电流等于各支路电流之和。但各支路的电流不一定相等（除非两个灯泡完全相同）。',
    difficulty: 1,
    options: '["A. 一定相等", "B. 不一定相等", "C. 干路电流等于支路电流", "D. 支路电流之和小于干路电流"]',
  },
  {
    questionKey: 'physics-renjiao-9-1-5',
    type: 'choice',
    questionText: '1A等于多少mA？（）',
    answer: 'C',
    explanation: '电流单位换算：1A=1000mA=10⁶μA。',
    difficulty: 1,
    options: '["A. 10mA", "B. 100mA", "C. 1000mA", "D. 10000mA"]',
  },
  {
    questionKey: 'physics-renjiao-9-1-6',
    type: 'choice',
    questionText: '电流表使用时，应____联在待测电路中。',
    answer: 'A',
    explanation: '电流表使用规则：串联在待测电路中；电流"正进负出"；不能直接接在电源两极（会短路）；选择合适的量程。',
    difficulty: 1,
    options: '["A. 串", "B. 并", "C. 混", "D. 任意"]',
  },
  {
    questionKey: 'physics-renjiao-9-1-7',
    type: 'choice',
    questionText: '在如图所示的电路中，要使小灯泡L₁和L₂串联，则开关的状态应为（）',
    answer: 'A',
    explanation: '串联电路只有一条路径。使两灯串联，需闭合S₁、断开S₂和S₃，让电流只经过一条路径通过两个灯泡。',
    difficulty: 2,
    options: '["A. 闭合S₁，断开S₂和S₃", "B. 闭合S₂，断开S₁和S₃", "C. 闭合S₁和S₂，断开S₃", "D. 三个开关都闭合"]',
  },
  {
    questionKey: 'physics-renjiao-9-1-8',
    type: 'choice',
    questionText: '关于串、并联电路，下列说法正确的是（）',
    answer: 'D',
    explanation: '串联电路：电流处处相等，总电压等于各部分电压之和。并联电路：各支路两端电压相等，干路电流等于各支路电流之和。',
    difficulty: 2,
    options: '["A. 串联电路各部分电压相等", "B. 并联电路各支路电流相等", "C. 串联电路总电流等于各部分电流之和", "D. 并联电路各支路两端电压相等"]',
  },
  {
    questionKey: 'physics-renjiao-9-1-9',
    type: 'choice',
    questionText: '某电路中干路电流为1.2A，通过L₁的电流为0.5A，则通过L₂的电流为（）',
    answer: 'B',
    explanation: '由题意可知L₁和L₂并联（因为支路电流之和等于干路电流）。I₂=I干-I₁=1.2A-0.5A=0.7A。',
    difficulty: 2,
    options: '["A. 0.5A", "B. 0.7A", "C. 1.2A", "D. 1.7A"]',
  },
  {
    questionKey: 'physics-renjiao-9-1-10',
    type: 'choice',
    questionText: '一个开关同时控制两个灯泡，这两个灯泡（）',
    answer: 'D',
    explanation: '一个开关同时控制两个灯泡，串联和并联都可以实现。串联时开关控制整个电路；并联时开关在干路上也能控制所有灯泡。',
    difficulty: 2,
    options: '["A. 一定是串联", "B. 一定是并联", "C. 既不是串联也不是并联", "D. 可能串联也可能并联"]',
  },
  {
    questionKey: 'physics-renjiao-9-1-11',
    type: 'choice',
    questionText: '下列做法中符合安全用电原则的是（）',
    answer: 'C',
    explanation: 'A错：湿手触电危险；B错：水是导体，电器着火不能用水灭火；D错：开关应接在火线上。C正确：金属外壳应接地。',
    difficulty: 2,
    options: '["A. 用湿手拔插头", "B. 电器着火用水灭火", "C. 金属外壳用电器要接地", "D. 开关接在零线上"]',
  },
  {
    questionKey: 'physics-renjiao-9-1-12',
    type: 'choice',
    questionText: '如图所示电路，已知A₁的示数为0.8A，A₂的示数为0.3A，则通过L₁的电流为（）',
    answer: 'A',
    explanation: 'A₁测干路电流=0.8A，A₂测L₂支路电流=0.3A，则L₁的电流=I干-I₂=0.8-0.3=0.5A。',
    difficulty: 3,
    options: '["A. 0.5A", "B. 0.3A", "C. 0.8A", "D. 1.1A"]',
  },

  // ---- fill 7题 ----
  {
    questionKey: 'physics-renjiao-9-1-13',
    type: 'fill',
    questionText: '电流的国际单位是____，用符号____表示。',
    answer: '安培、A',
    explanation: '电流的国际单位是安培（A），简称安。常用单位还有毫安(mA)和微安(μA)。',
    difficulty: 1,
    acceptableAnswers: '["安培、A", "安培，A"]',
  },
  {
    questionKey: 'physics-renjiao-9-1-14',
    type: 'fill',
    questionText: '250mA =____A。',
    answer: '0.25',
    explanation: '1A=1000mA，所以250mA=250/1000A=0.25A。',
    difficulty: 1,
    acceptableAnswers: '["0.25"]',
  },
  {
    questionKey: 'physics-renjiao-9-1-15',
    type: 'fill',
    questionText: '串联电路中，电流处处____；并联电路中，干路电流等于各____电流之和。',
    answer: '相等、支路',
    explanation: '串联电路特点：电流处处相等。并联电路特点：干路电流=各支路电流之和，各支路电压相等。',
    difficulty: 1,
    acceptableAnswers: '["相等、支路", "相等，支路"]',
  },
  {
    questionKey: 'physics-renjiao-9-1-16',
    type: 'fill',
    questionText: '使用电流表时，电流应从____接线柱流入，从____接线柱流出。',
    answer: '正、负',
    explanation: '电流表使用时，电流必须从"+"接线柱流入，从"-"接线柱流出，否则指针会反偏，可能损坏电流表。',
    difficulty: 1,
    acceptableAnswers: '["正、负", "正，负", "+、-", "+，-"]',
  },
  {
    questionKey: 'physics-renjiao-9-1-17',
    type: 'fill',
    questionText: '在并联电路中，若通过两条支路的电流分别为0.3A和0.4A，则干路电流为____A。',
    answer: '0.7',
    explanation: '并联电路干路电流等于各支路电流之和：I干=I₁+I₂=0.3+0.4=0.7A。',
    difficulty: 2,
    acceptableAnswers: '["0.7"]',
  },
  {
    questionKey: 'physics-renjiao-9-1-18',
    type: 'fill',
    questionText: '电路的三种状态分别是____、____和____。',
    answer: '通路、断路、短路',
    explanation: '通路：正常接通的电路，有电流通过。断路：某处断开，电路中无电流。短路：电流不经过用电器直接回到电源，电流很大，会损坏电源。',
    difficulty: 1,
    acceptableAnswers: '["通路、断路、短路", "通路，断路，短路"]',
  },
  {
    questionKey: 'physics-renjiao-9-1-19',
    type: 'fill',
    questionText: '家庭电路的电压为____V，对人体的安全电压不高于____V。',
    answer: '220、36',
    explanation: '我国家庭电路电压为220V。经验表明，只有不高于36V的电压对人体才是安全的。',
    difficulty: 1,
    acceptableAnswers: '["220、36", "220，36"]',
  },

  // ---- short_answer 6题 ----
  {
    questionKey: 'physics-renjiao-9-1-20',
    type: 'short_answer',
    questionText: '请画出两个小灯泡L₁和L₂并联、开关S控制整个电路的电路图设计说明。',
    answer: '电路设计：电源正极出发，经开关S到达分支点，分支为两条支路：一条经L₁、另一条经L₂，两条支路汇合后回到电源负极。开关S接在干路上，控制整个电路。L₁和L₂互不影响。',
    explanation: '并联电路各支路独立工作，互不影响。开关在干路上控制所有支路。',
    difficulty: 2,
  },
  {
    questionKey: 'physics-renjiao-9-1-21',
    type: 'short_answer',
    questionText: '如何用电流表判断两个灯泡是串联还是并联？',
    answer: '将电流表分别接入两个灯泡所在位置：如果两次测量电流值相等，说明是串联（串联电路电流处处相等）；如果两次测量电流值不相等，说明是并联（并联电路各支路电流一般不相等）。',
    explanation: '利用串联电路电流处处相等、并联电路各支路电流一般不相等的特点来判断。',
    difficulty: 3,
  },
  {
    questionKey: 'physics-renjiao-9-1-22',
    type: 'short_answer',
    questionText: '在串联电路中，如果其中一个灯泡灯丝断了，另一个灯泡还能发光吗？为什么？并联电路呢？',
    answer: '串联电路中，一个灯泡灯丝断了，另一个灯泡不能发光。因为串联电路只有一条路径，断路后整个电路都没有电流。并联电路中，一个灯泡灯丝断了，另一个灯泡仍能发光。因为并联电路各支路独立，一条支路断路不影响其他支路。',
    explanation: '串联电路各元件相互影响，并联电路各支路互不影响。这是串并联电路的重要区别。',
    difficulty: 2,
  },
  {
    questionKey: 'physics-renjiao-9-1-23',
    type: 'short_answer',
    questionText: '某同学连接电路时，将电流表的"-"和"0.6"两个接线柱接入电路，指针偏转到最大刻度的1/3处，则通过电路的电流是多少？',
    answer: '使用的是0~0.6A量程。该量程每小格为0.02A，分度值为0.02A。指针偏转到最大刻度的1/3处，即0.6A×1/3=0.2A。所以通过电路的电流为0.2A。',
    explanation: '电流表0~0.6A量程分度值为0.02A，0~3A量程分度值为0.1A。根据指针位置读数即可。',
    difficulty: 2,
  },
  {
    questionKey: 'physics-renjiao-9-1-24',
    type: 'short_answer',
    questionText: '为什么不允许用导线直接把电源两极连接起来？',
    answer: '用导线直接连接电源两极会造成电源短路。此时电路中电阻极小（只有导线电阻），根据欧姆定律I=U/R，电流会非常大，会烧坏电源和导线，甚至引起火灾，十分危险。',
    explanation: '电源短路是电路连接中的严重错误，会产生极大的电流，损坏电源和导线，必须严格避免。',
    difficulty: 2,
  },
  {
    questionKey: 'physics-renjiao-9-1-25',
    type: 'short_answer',
    questionText: '如图所示的电路，L₁和L₂并联，电流表A₁测量通过L₁的电流，A₂测量通过L₂的电流，A测量干路电流。已知A₁示数为0.4A，A₂示数为0.6A，求A的示数。',
    answer: 'L₁和L₂并联，A₁测L₁电流=0.4A，A₂测L₂电流=0.6A。干路电流等于各支路电流之和，所以A的示数=0.4A+0.6A=1.0A。',
    explanation: '并联电路中干路电流=各支路电流之和。',
    difficulty: 2,
  },

  // ---- true_false 2题 ----
  {
    questionKey: 'physics-renjiao-9-1-26',
    type: 'true_false',
    questionText: '绝缘体在任何条件下都不能导电。',
    answer: '错误',
    explanation: '绝缘体不容易导电，但在特定条件下（如高温、高压、潮湿等）也可以变成导体。例如玻璃常温下是绝缘体，加热到红热状态就能导电。',
    difficulty: 2,
  },
  {
    questionKey: 'physics-renjiao-9-1-27',
    type: 'true_false',
    questionText: '在并联电路中，各支路两端的电压相等。',
    answer: '正确',
    explanation: '并联电路的基本特点之一：各支路两端电压相等，且等于电源电压（忽略导线电阻）。',
    difficulty: 1,
  },
];

// ========== 9-2 电压和电阻 (28题) ==========

const chapter9_2: RawQuestion[] = [
  // ---- choice 13题 ----
  {
    questionKey: 'physics-renjiao-9-2-0',
    type: 'choice',
    questionText: '电压是使电路中____的原因。',
    answer: 'A',
    explanation: '电压是使电路中自由电荷定向移动形成电流的原因。电源是提供电压的装置。',
    difficulty: 1,
    options: '["A. 产生电流", "B. 产生电荷", "C. 消耗电能", "D. 产生电阻"]',
  },
  {
    questionKey: 'physics-renjiao-9-2-1',
    type: 'choice',
    questionText: '一节干电池的电压为（）',
    answer: 'B',
    explanation: '一节干电池电压为1.5V，一节铅蓄电池电压为2V，家庭电路电压220V，安全电压不高于36V。',
    difficulty: 1,
    options: '["A. 1V", "B. 1.5V", "C. 2V", "D. 220V"]',
  },
  {
    questionKey: 'physics-renjiao-9-2-2',
    type: 'choice',
    questionText: '电压表使用时应____联在待测电路两端。',
    answer: 'A',
    explanation: '电压表应并联在待测电路两端。电流表串联，电压表并联，这是基本使用规则。',
    difficulty: 1,
    options: '["A. 并", "B. 串", "C. 混", "D. 任意"]',
  },
  {
    questionKey: 'physics-renjiao-9-2-3',
    type: 'choice',
    questionText: '在串联电路中，总电压与各部分电压的关系是（）',
    answer: 'C',
    explanation: '串联电路中，总电压等于各部分电路两端电压之和，即U=U₁+U₂+...。',
    difficulty: 1,
    options: '["A. U=U₁=U₂", "B. U=U₁-U₂", "C. U=U₁+U₂", "D. U>U₁+U₂"]',
  },
  {
    questionKey: 'physics-renjiao-9-2-4',
    type: 'choice',
    questionText: '影响导体电阻大小的因素不包括（）',
    answer: 'D',
    explanation: '导体的电阻大小取决于导体的材料、长度和横截面积，还受温度影响。与电压和电流无关，电阻是导体本身的性质。',
    difficulty: 1,
    options: '["A. 材料种类", "B. 长度", "C. 横截面积", "D. 通过的电流"]',
  },
  {
    questionKey: 'physics-renjiao-9-2-5',
    type: 'choice',
    questionText: '将一根导体均匀拉长后，它的电阻将（）',
    answer: 'B',
    explanation: '均匀拉长后，导体长度变长（电阻变大），同时横截面积变小（电阻也变大），两个因素都使电阻增大，所以电阻变大。',
    difficulty: 2,
    options: '["A. 变小", "B. 变大", "C. 不变", "D. 无法确定"]',
  },
  {
    questionKey: 'physics-renjiao-9-2-6',
    type: 'choice',
    questionText: '滑动变阻器是通过改变接入电路中导体的____来改变电阻的。',
    answer: 'C',
    explanation: '滑动变阻器是通过改变接入电路中电阻丝的长度来改变电阻的。滑片移动改变有效长度，从而改变电阻。',
    difficulty: 1,
    options: '["A. 材料", "B. 横截面积", "C. 长度", "D. 温度"]',
  },
  {
    questionKey: 'physics-renjiao-9-2-7',
    type: 'choice',
    questionText: '两个电阻R₁=10Ω和R₂=20Ω串联，总电阻为（）',
    answer: 'A',
    explanation: '串联电路总电阻等于各电阻之和：R=R₁+R₂=10+20=30Ω。',
    difficulty: 2,
    options: '["A. 30Ω", "B. 15Ω", "C. 6.67Ω", "D. 200Ω"]',
  },
  {
    questionKey: 'physics-renjiao-9-2-8',
    type: 'choice',
    questionText: '两个电阻R₁=6Ω和R₂=12Ω并联，总电阻为（）',
    answer: 'B',
    explanation: '并联电路总电阻：1/R=1/R₁+1/R₂=1/6+1/12=2/12+1/12=3/12=1/4，R=4Ω。',
    difficulty: 3,
    options: '["A. 18Ω", "B. 4Ω", "C. 3Ω", "D. 8Ω"]',
  },
  {
    questionKey: 'physics-renjiao-9-2-9',
    type: 'choice',
    questionText: '关于电阻，下列说法正确的是（）',
    answer: 'D',
    explanation: '电阻是导体本身的性质，取决于材料、长度、横截面积和温度，与是否通电无关。A错：导体和绝缘体没有绝对界限；B错：电阻与电压电流无关；C错：铜的导电性比铁好，电阻比铁小。',
    difficulty: 2,
    options: '["A. 导体有电阻，绝缘体没有电阻", "B. 通过导体的电流越大，电阻越小", "C. 铜导线的电阻一定比铁导线大", "D. 电阻是导体本身的性质"]',
  },
  {
    questionKey: 'physics-renjiao-9-2-10',
    type: 'choice',
    questionText: '一个滑动变阻器标有"50Ω 1.5A"字样，表示该变阻器的电阻变化范围是____，允许通过的最大电流为____。',
    answer: 'A',
    explanation: '"50Ω 1.5A"表示最大电阻为50Ω（最小电阻接近0），允许通过的最大电流为1.5A。使用时不能超过最大电流。',
    difficulty: 2,
    options: '["A. 0~50Ω、1.5A", "B. 0~50A、1.5Ω", "C. 50Ω~100Ω、1.5A", "D. 0~1.5Ω、50A"]',
  },
  {
    questionKey: 'physics-renjiao-9-2-11',
    type: 'choice',
    questionText: '串联电路中，电阻大的导体两端的电压____。',
    answer: 'B',
    explanation: '串联电路中电流处处相等，由U=IR可知，电阻越大，其两端的电压越大。电压分配与电阻成正比。',
    difficulty: 2,
    options: '["A. 越小", "B. 越大", "C. 不变", "D. 为零"]',
  },
  {
    questionKey: 'physics-renjiao-9-2-12',
    type: 'choice',
    questionText: '在"探究影响电阻大小因素"的实验中，采用的研究方法是（）',
    answer: 'C',
    explanation: '探究影响电阻大小的因素时，需要控制其他因素不变，只改变其中一个因素来研究它对电阻的影响，这种方法叫做控制变量法。',
    difficulty: 2,
    options: '["A. 类比法", "B. 等效替代法", "C. 控制变量法", "D. 模型法"]',
  },

  // ---- fill 7题 ----
  {
    questionKey: 'physics-renjiao-9-2-13',
    type: 'fill',
    questionText: '电压的国际单位是____，用符号____表示。',
    answer: '伏特、V',
    explanation: '电压的国际单位是伏特（V），简称伏。常用单位还有千伏(kV)和毫伏(mV)。1kV=1000V，1V=1000mV。',
    difficulty: 1,
    acceptableAnswers: '["伏特、V", "伏特，V"]',
  },
  {
    questionKey: 'physics-renjiao-9-2-14',
    type: 'fill',
    questionText: '电阻的国际单位是____，用符号____表示。',
    answer: '欧姆、Ω',
    explanation: '电阻的国际单位是欧姆（Ω），简称欧。常用单位还有千欧(kΩ)和兆欧(MΩ)。1kΩ=1000Ω，1MΩ=1000kΩ。',
    difficulty: 1,
    acceptableAnswers: '["欧姆、Ω", "欧姆，Ω"]',
  },
  {
    questionKey: 'physics-renjiao-9-2-15',
    type: 'fill',
    questionText: '3.6kV =____V。',
    answer: '3600',
    explanation: '1kV=1000V，所以3.6kV=3.6×1000V=3600V。',
    difficulty: 1,
    acceptableAnswers: '["3600"]',
  },
  {
    questionKey: 'physics-renjiao-9-2-16',
    type: 'fill',
    questionText: '串联电路中，总电阻等于各分电阻之____；并联电路中，总电阻的倒数等于各分电阻____之和。',
    answer: '和、倒数',
    explanation: '串联：R=R₁+R₂+...；并联：1/R=1/R₁+1/R₂+...。',
    difficulty: 2,
    acceptableAnswers: '["和、倒数", "和，倒数"]',
  },
  {
    questionKey: 'physics-renjiao-9-2-17',
    type: 'fill',
    questionText: '将两个5Ω的电阻串联，总电阻为____Ω；将它们并联，总电阻为____Ω。',
    answer: '10、2.5',
    explanation: '串联：R=5+5=10Ω。并联：1/R=1/5+1/5=2/5，R=2.5Ω。',
    difficulty: 2,
    acceptableAnswers: '["10、2.5", "10，2.5"]',
  },
  {
    questionKey: 'physics-renjiao-9-2-18',
    type: 'fill',
    questionText: '滑动变阻器在电路中的作用是改变电路中的____和____。',
    answer: '电流、电压',
    explanation: '滑动变阻器通过改变电阻来改变电路中的电流，进而改变各部分电路两端的电压。',
    difficulty: 1,
    acceptableAnswers: '["电流、电压", "电流，电压", "电压、电流", "电压，电流"]',
  },
  {
    questionKey: 'physics-renjiao-9-2-19',
    type: 'fill',
    questionText: '导体的电阻与导体的____、____和____有关，还受____影响。',
    answer: '材料、长度、横截面积、温度',
    explanation: '电阻取决于导体的材料、长度和横截面积。一般来说，同种材料，越长电阻越大，越粗电阻越小。大多数导体温度升高电阻增大。',
    difficulty: 2,
    acceptableAnswers: '["材料、长度、横截面积、温度", "材料，长度，横截面积，温度"]',
  },

  // ---- short_answer 6题 ----
  {
    questionKey: 'physics-renjiao-9-2-20',
    type: 'short_answer',
    questionText: '一个电阻为10Ω的导体，通过它的电流为2A，求它两端的电压。',
    answer: '由欧姆定律 U=IR=2A×10Ω=20V。',
    explanation: '欧姆定律：U=IR。已知I=2A，R=10Ω，代入得U=20V。',
    difficulty: 1,
  },
  {
    questionKey: 'physics-renjiao-9-2-21',
    type: 'short_answer',
    questionText: '一个导体两端的电压为6V，通过的电流为0.3A，求该导体的电阻。',
    answer: '由欧姆定律 I=U/R，得 R=U/I=6V/0.3A=20Ω。',
    explanation: '欧姆定律变形公式：R=U/I。已知U=6V，I=0.3A，R=6/0.3=20Ω。',
    difficulty: 1,
  },
  {
    questionKey: 'physics-renjiao-9-2-22',
    type: 'short_answer',
    questionText: 'R₁=5Ω和R₂=10Ω串联在6V的电源上，求电路中的电流和R₁两端的电压。',
    answer: '总电阻 R=R₁+R₂=5+10=15Ω。电路中的电流 I=U/R=6V/15Ω=0.4A。R₁两端的电压 U₁=IR₁=0.4A×5Ω=2V。',
    explanation: '串联电路总电阻R=R₁+R₂，由欧姆定律求电流，再由U=IR求各部分电压。验证：U₂=0.4×10=4V，U₁+U₂=2+4=6V=U，正确。',
    difficulty: 2,
  },
  {
    questionKey: 'physics-renjiao-9-2-23',
    type: 'short_answer',
    questionText: 'R₁=12Ω和R₂=6Ω并联在6V的电源上，求干路电流和通过R₁的电流。',
    answer: '并联电路各支路电压相等，U₁=U₂=6V。通过R₁的电流I₁=U/R₁=6V/12Ω=0.5A。通过R₂的电流I₂=U/R₂=6V/6Ω=1A。干路电流I=I₁+I₂=0.5A+1A=1.5A。',
    explanation: '并联电路各支路电压等于电源电压，分别求各支路电流后相加得干路电流。',
    difficulty: 2,
  },
  {
    questionKey: 'physics-renjiao-9-2-24',
    type: 'short_answer',
    questionText: '在"探究导体电阻与长度的关系"实验中，应该控制哪些因素不变？如何改变长度？',
    answer: '应该控制导体的材料和横截面积不变，同时保持温度相同（控制变量法）。改变长度的方法：将一根长导体逐步截短，分别接入电路测量电阻（通过电压表和电流表的示数计算R=U/I）；或者使用同一根导线的不同长度部分。',
    explanation: '控制变量法：研究一个因素对电阻的影响时，必须控制其他因素不变。',
    difficulty: 3,
  },
  {
    questionKey: 'physics-renjiao-9-2-25',
    type: 'short_answer',
    questionText: 'R₁=20Ω和R₂=30Ω串联接在10V电源上。求：(1)电路中的电流；(2)R₁和R₂两端的电压分别是多少。',
    answer: '(1) 总电阻 R=20+30=50Ω，电流 I=U/R=10V/50Ω=0.2A。(2) U₁=IR₁=0.2A×20Ω=4V，U₂=IR₂=0.2A×30Ω=6V。验证：4+6=10V=电源电压，正确。',
    explanation: '串联电路中电流相等，总电压等于各部分电压之和。',
    difficulty: 2,
  },

  // ---- true_false 2题 ----
  {
    questionKey: 'physics-renjiao-9-2-26',
    type: 'true_false',
    questionText: '导体的电阻与它两端的电压成正比，与通过它的电流成反比。',
    answer: '错误',
    explanation: '电阻是导体本身的性质，由材料、长度、横截面积和温度决定，与电压和电流无关。R=U/I只是计算电阻的方法，不能说电阻与电压成正比、与电流成反比。',
    difficulty: 3,
  },
  {
    questionKey: 'physics-renjiao-9-2-27',
    type: 'true_false',
    questionText: '并联电路的总电阻一定小于其中任何一个支路的电阻。',
    answer: '正确',
    explanation: '并联电路相当于增加了导体的横截面积，总电阻比任何一个分电阻都小。例如R₁和R₂并联，1/R=1/R₁+1/R₂>1/R₁，所以R<R₁，同理R<R₂。',
    difficulty: 2,
  },
];

// ========== 9-3 电功率 (32题) ==========

const chapter9_3: RawQuestion[] = [
  // ---- choice 14题 ----
  {
    questionKey: 'physics-renjiao-9-3-0',
    type: 'choice',
    questionText: '电功率的物理意义是表示（）',
    answer: 'A',
    explanation: '电功率是表示电流做功快慢的物理量。电功率越大，电流做功越快。',
    difficulty: 1,
    options: '["A. 电流做功的快慢", "B. 电流做功的多少", "C. 电流的大小", "D. 电压的大小"]',
  },
  {
    questionKey: 'physics-renjiao-9-3-1',
    type: 'choice',
    questionText: '电功率的计算公式P=UI中，U的单位是V，I的单位是A，则P的单位是（）',
    answer: 'C',
    explanation: 'P=UI，当U的单位为V、I的单位为A时，P的单位为W（瓦特）。1W=1V·A。',
    difficulty: 1,
    options: '["A. J", "B. C", "C. W", "D. N"]',
  },
  {
    questionKey: 'physics-renjiao-9-3-2',
    type: 'choice',
    questionText: '1kW·h等于多少焦耳？（）',
    answer: 'B',
    explanation: '1kW·h=1000W×3600s=3.6×10⁶J。这是电功（电能）的常用单位。',
    difficulty: 1,
    options: '["A. 3.6×10³J", "B. 3.6×10⁶J", "C. 3.6×10⁹J", "D. 3.6J"]',
  },
  {
    questionKey: 'physics-renjiao-9-3-3',
    type: 'choice',
    questionText: '一个标有"220V 100W"的灯泡，正常工作时的电流约为（）',
    answer: 'A',
    explanation: '正常工作指在额定电压下工作。I=P/U=100W/220V≈0.45A。',
    difficulty: 2,
    options: '["A. 0.45A", "B. 2.2A", "C. 100A", "D. 0.22A"]',
  },
  {
    questionKey: 'physics-renjiao-9-3-4',
    type: 'choice',
    questionText: '一个标有"220V 60W"的灯泡接在110V的电路中，它的实际功率约为（）',
    answer: 'C',
    explanation: '灯泡电阻R=U额²/P额=220²/60≈806.7Ω。实际功率P实=U实²/R=110²/806.7≈12100/806.7≈15W。也可以用比例法：P实=(U实/U额)²×P额=(110/220)²×60=(1/2)²×60=15W。',
    difficulty: 3,
    options: '["A. 60W", "B. 30W", "C. 15W", "D. 120W"]',
  },
  {
    questionKey: 'physics-renjiao-9-3-5',
    type: 'choice',
    questionText: '下列关于焦耳定律的说法正确的是（）',
    answer: 'A',
    explanation: '焦耳定律Q=I²Rt，电流产生的热量与电流的平方成正比，与电阻成正比，与通电时间成正比。',
    difficulty: 2,
    options: '["A. Q=I²Rt", "B. Q=UIt", "C. Q=IRt", "D. Q=I²R/t"]',
  },
  {
    questionKey: 'physics-renjiao-9-3-6',
    type: 'choice',
    questionText: '电炉丝热得发红，而与它串联的导线几乎不热，原因是（）',
    answer: 'B',
    explanation: '电炉丝与导线串联，电流相同。但电炉丝的电阻远大于导线的电阻，由Q=I²Rt可知，在相同时间内电炉丝产生的热量远大于导线产生的热量。',
    difficulty: 2,
    options: '["A. 通过电炉丝的电流大", "B. 电炉丝的电阻比导线大得多", "C. 电炉丝的电压小", "D. 导线的散热比电炉丝快"]',
  },
  {
    questionKey: 'physics-renjiao-9-3-7',
    type: 'choice',
    questionText: '下列家用电器中，属于利用电流热效应工作的是（）',
    answer: 'D',
    explanation: '电流的热效应是电流通过导体时发热的现象。电饭锅是利用电流的热效应来加热食物的。A是电磁效应，B、C主要不是利用热效应。',
    difficulty: 1,
    options: '["A. 电铃", "B. 电视机", "C. 洗衣机", "D. 电饭锅"]',
  },
  {
    questionKey: 'physics-renjiao-9-3-8',
    type: 'choice',
    questionText: '标有"6V 3W"的小灯泡，它的正常工作电阻为（）',
    answer: 'A',
    explanation: 'R=U²/P=6²/3=36/3=12Ω。',
    difficulty: 2,
    options: '["A. 12Ω", "B. 18Ω", "C. 2Ω", "D. 0.5Ω"]',
  },
  {
    questionKey: 'physics-renjiao-9-3-9',
    type: 'choice',
    questionText: '一个"220V 100W"的灯泡和一个"220V 40W"的灯泡串联在220V电路中，则（）',
    answer: 'C',
    explanation: '100W灯泡电阻R₁=220²/100=484Ω，40W灯泡电阻R₂=220²/40=1210Ω。串联时电流相等，40W灯泡电阻大，分得电压多，实际功率P=I²R更大，所以40W的灯泡更亮。',
    difficulty: 3,
    options: '["A. 100W的灯泡更亮", "B. 两个灯泡一样亮", "C. 40W的灯泡更亮", "D. 都不亮"]',
  },
  {
    questionKey: 'physics-renjiao-9-3-10',
    type: 'choice',
    questionText: '电功的国际单位是（）',
    answer: 'B',
    explanation: '电功的国际单位是焦耳(J)，常用单位是千瓦时(kW·h)，也叫"度"。1kW·h=3.6×10⁶J。',
    difficulty: 1,
    options: '["A. 瓦特(W)", "B. 焦耳(J)", "C. 安培(A)", "D. 伏特(V)"]',
  },
  {
    questionKey: 'physics-renjiao-9-3-11',
    type: 'choice',
    questionText: '下列关于安全用电的说法正确的是（）',
    answer: 'A',
    explanation: 'A正确：家庭电路中保险丝熔断可能是短路或用电器总功率过大。B错：发现有人触电应先切断电源，不能直接用手拉。C错：使用测电笔时手要接触笔尾金属体。D错：开关应接在火线和用电器之间。',
    difficulty: 2,
    options: '["A. 保险丝熔断可能是电路短路", "B. 发现有人触电应立即用手拉开", "C. 使用测电笔时手不能接触笔尾", "D. 开关可以接在零线上"]',
  },
  {
    questionKey: 'physics-renjiao-9-3-12',
    type: 'choice',
    questionText: '某用电器的额定功率为100W，每天正常工作2h，一个月（30天）消耗的电能为（）',
    answer: 'B',
    explanation: 'W=Pt=100W×2h×30=200W×30h=6000W·h=6kW·h。',
    difficulty: 2,
    options: '["A. 6J", "B. 6kW·h", "C. 60kW·h", "D. 0.6kW·h"]',
  },
  {
    questionKey: 'physics-renjiao-9-3-13',
    type: 'choice',
    questionText: '测电笔的作用是（）',
    answer: 'C',
    explanation: '测电笔用于辨别火线和零线。使用时笔尖接触电线，手接触笔尾金属体，氖管发光的是火线，不发光的是零线。',
    difficulty: 1,
    options: '["A. 测量电压大小", "B. 测量电流大小", "C. 辨别火线和零线", "D. 切断电源"]',
  },

  // ---- fill 8题 ----
  {
    questionKey: 'physics-renjiao-9-3-14',
    type: 'fill',
    questionText: '电功率的公式P=W/t中，W的单位是____，t的单位是s，P的单位是____。',
    answer: '焦耳(J)、瓦特(W)',
    explanation: '电功率P=W/t，W用焦耳(J)，t用秒(s)，P用瓦特(W)。1W=1J/s。',
    difficulty: 1,
    acceptableAnswers: '["焦耳(J)、瓦特(W)", "焦耳，瓦特", "J、W"]',
  },
  {
    questionKey: 'physics-renjiao-9-3-15',
    type: 'fill',
    questionText: '一个"220V 1000W"的电暖器正常工作2小时，消耗的电能为____kW·h。',
    answer: '2',
    explanation: 'W=Pt=1kW×2h=2kW·h。注意先换算单位：1000W=1kW。',
    difficulty: 1,
    acceptableAnswers: '["2"]',
  },
  {
    questionKey: 'physics-renjiao-9-3-16',
    type: 'fill',
    questionText: '1kW·h =____J。',
    answer: '3600000',
    explanation: '1kW·h=1000W×3600s=3600000J=3.6×10⁶J。',
    difficulty: 1,
    acceptableAnswers: '["3600000", "3.6×10⁶", "3.6e6"]',
  },
  {
    questionKey: 'physics-renjiao-9-3-17',
    type: 'fill',
    questionText: '一个电烙铁的铭牌标有"36V 60W"，它在正常工作1分钟内产生的热量为____J。',
    answer: '3600',
    explanation: '正常工作1分钟（60s）消耗的电能全部转化为热量：W=Q=Pt=60W×60s=3600J。',
    difficulty: 2,
    acceptableAnswers: '["3600"]',
  },
  {
    questionKey: 'physics-renjiao-9-3-18',
    type: 'fill',
    questionText: '焦耳定律的公式是Q=____。',
    answer: 'I²Rt',
    explanation: '焦耳定律：电流通过导体产生的热量Q=I²Rt，其中I为电流，R为电阻，t为通电时间。',
    difficulty: 1,
    acceptableAnswers: '["I²Rt", "I^2Rt"]',
  },
  {
    questionKey: 'physics-renjiao-9-3-19',
    type: 'fill',
    questionText: '标有"12V 6W"的灯泡，正常工作时通过灯丝的电流为____A。',
    answer: '0.5',
    explanation: 'I=P/U=6W/12V=0.5A。',
    difficulty: 2,
    acceptableAnswers: '["0.5"]',
  },
  {
    questionKey: 'physics-renjiao-9-3-20',
    questionText: '家庭电路中，保险丝的作用是当电路中电流过大时自动____，起到保护电路的作用。',
    type: 'fill',
    answer: '熔断',
    explanation: '保险丝是用熔点较低的铅锑合金制成的，当电路中电流过大时，保险丝因温度升高而自动熔断，切断电路，起到保护作用。',
    difficulty: 1,
    acceptableAnswers: '["熔断", "断开"]',
  },
  {
    questionKey: 'physics-renjiao-9-3-21',
    type: 'fill',
    questionText: '一个电阻为20Ω的导体，通过的电流为3A，在10s内产生的热量为____J。',
    answer: '1800',
    explanation: 'Q=I²Rt=3²×20×10=9×20×10=1800J。',
    difficulty: 2,
    acceptableAnswers: '["1800"]',
  },

  // ---- short_answer 6题 ----
  {
    questionKey: 'physics-renjiao-9-3-22',
    type: 'short_answer',
    questionText: '一个"220V 100W"的灯泡正常工作5小时，消耗多少电能？合多少kW·h？',
    answer: 'W=Pt=100W×5h=500W·h=0.5kW·h=0.5×3.6×10⁶J=1.8×10⁶J。消耗电能为1.8×10⁶J，合0.5kW·h（即0.5度电）。',
    explanation: 'W=Pt，注意单位换算。100W=0.1kW，W=0.1kW×5h=0.5kW·h。',
    difficulty: 1,
  },
  {
    questionKey: 'physics-renjiao-9-3-23',
    type: 'short_answer',
    questionText: '一个电热器的电阻为44Ω，接在220V的电路中，通电10分钟产生多少热量？',
    answer: '通过电热器的电流 I=U/R=220V/44Ω=5A。产生的热量 Q=I²Rt=5²×44×(10×60)=25×44×600=1100×600=660000J=6.6×10⁵J。',
    explanation: '先用欧姆定律求电流，再用焦耳定律求热量。注意时间单位换算：10分钟=600秒。验证：也可用Q=U²t/R=220²×600/44=48400×600/44=1100×600=660000J，正确。',
    difficulty: 2,
  },
  {
    questionKey: 'physics-renjiao-9-3-24',
    type: 'short_answer',
    questionText: 'R₁=10Ω和R₂=20Ω串联在12V的电源上，求：(1)电路中的电流；(2)R₁和R₂各自消耗的电功率。',
    answer: '(1) 总电阻 R=10+20=30Ω，电流 I=U/R=12V/30Ω=0.4A。(2) P₁=I²R₁=0.4²×10=0.16×10=1.6W。P₂=I²R₂=0.4²×20=0.16×20=3.2W。验证：P总=UI=12×0.4=4.8W，P₁+P₂=1.6+3.2=4.8W，正确。',
    explanation: '串联电路中电流相等，各电阻消耗的功率可用P=I²R计算。总功率等于各部分功率之和。',
    difficulty: 2,
  },
  {
    questionKey: 'physics-renjiao-9-3-25',
    type: 'short_answer',
    questionText: '一个家庭有"220V 40W"灯泡3盏，"220V 60W"电视机1台，"220V 1000W"电饭锅1个。若这些用电器同时正常工作2小时，共消耗多少kW·h的电能？',
    answer: '总功率 P=3×40W+60W+1000W=120+60+1000=1180W=1.18kW。消耗电能 W=Pt=1.18kW×2h=2.36kW·h。',
    explanation: '并联电路中总功率等于各用电器功率之和。注意换算为kW再计算kW·h。',
    difficulty: 2,
  },
  {
    questionKey: 'physics-renjiao-9-3-26',
    type: 'short_answer',
    questionText: '一个"6V 3W"的小灯泡和一个"6V 6W"的小灯泡并联在6V电源上，求它们各自的电流和总电流。',
    answer: '灯泡L₁(3W)：I₁=P₁/U=3W/6V=0.5A。灯泡L₂(6W)：I₂=P₂/U=6W/6V=1A。总电流 I=I₁+I₂=0.5+1=1.5A。',
    explanation: '并联电路各支路电压相等（均等于电源电压6V），分别求各支路电流，再求和。',
    difficulty: 2,
  },
  {
    questionKey: 'physics-renjiao-9-3-27',
    type: 'short_answer',
    questionText: '一段电阻丝的电阻为10Ω，通过的电流为5A，求它在5分钟内消耗的电能和产生的热量（假设电能全部转化为内能）。',
    answer: '电能 W=Pt=I²Rt=5²×10×(5×60)=25×10×300=75000J=7.5×10⁴J。因为电能全部转化为内能，所以产生的热量 Q=W=7.5×10⁴J。',
    explanation: '当电能全部转化为内能时，Q=W=Pt=I²Rt=UIt。注意时间换算：5分钟=300秒。',
    difficulty: 2,
  },

  // ---- true_false 4题 ----
  {
    questionKey: 'physics-renjiao-9-3-28',
    type: 'true_false',
    questionText: '用电器的额定功率只有一个，实际功率可以有无数个。',
    answer: '正确',
    explanation: '额定功率是用电器在额定电压下的功率，只有一个。实际功率取决于实际电压，实际电压不同，实际功率就不同，所以实际功率可以有无数个。',
    difficulty: 2,
  },
  {
    questionKey: 'physics-renjiao-9-3-29',
    type: 'true_false',
    questionText: '千瓦时（kW·h）是电功率的单位。',
    answer: '错误',
    explanation: '千瓦时（kW·h）是电功（电能）的单位，不是电功率的单位。电功率的单位是瓦特(W)或千瓦(kW)。',
    difficulty: 1,
  },
  {
    questionKey: 'physics-renjiao-9-3-30',
    type: 'true_false',
    questionText: '额定电压越高的用电器，额定功率一定越大。',
    answer: '错误',
    explanation: '额定功率P=UI，虽然U大，但如果I很小，P也可能不大。例如一个LED灯的额定电压220V但额定功率可能只有5W，而一个电炉的额定电压220V但额定功率可达2000W。所以额定功率由额定电压和额定电流共同决定。',
    difficulty: 2,
  },
  {
    questionKey: 'physics-renjiao-9-3-31',
    type: 'true_false',
    questionText: '电流通过导体产生的热量与电流的平方成正比。',
    answer: '正确',
    explanation: '由焦耳定律Q=I²Rt可知，在电阻和通电时间不变的情况下，电流产生的热量与电流的平方成正比。电流增大为原来的2倍，热量增大为原来的4倍。',
    difficulty: 2,
  },
];

// ========== 章节映射与导出函数 ==========

const chapterKeyToData: Record<string, RawQuestion[]> = {
  'physics-renjiao-8-0': chapter8_0,
  'physics-renjiao-8-1': chapter8_1,
  'physics-renjiao-8-2': chapter8_2,
  'physics-renjiao-8-3': chapter8_3,
  'physics-renjiao-9-0': chapter9_0,
  'physics-renjiao-9-1': chapter9_1,
  'physics-renjiao-9-2': chapter9_2,
  'physics-renjiao-9-3': chapter9_3,
};

export async function seedPhysicsRenjiaoQuestions(): Promise<number> {
  // 1. 查找所有物理人教版章节
  const chapters = await prisma.chapter.findMany({
    where: { chapterKey: { startsWith: 'physics-renjiao' } },
  });

  // 2. 构建 chapterKey -> chapterId 映射
  const keyToId = new Map<string, string>();
  for (const ch of chapters) {
    keyToId.set(ch.chapterKey, ch.id);
  }

  // 3. 收集所有待插入的记录
  const records: Array<{
    chapterId: string;
    questionKey: string;
    type: string;
    questionText: string;
    answer: string;
    explanation: string;
    difficulty: number;
    options?: string;
    pairs?: string;
    acceptableAnswers?: string;
    isActive: boolean;
  }> = [];

  for (const [chapterKey, questions] of Object.entries(chapterKeyToData)) {
    const chapterId = keyToId.get(chapterKey);
    if (!chapterId) {
      console.warn(`[seed-physics-renjiao] 章节 "${chapterKey}" 未找到，跳过 ${questions.length} 道题`);
      continue;
    }

    for (const q of questions) {
      records.push({
        chapterId,
        questionKey: q.questionKey,
        type: q.type,
        questionText: q.questionText,
        answer: q.answer,
        explanation: q.explanation,
        difficulty: q.difficulty,
        options: q.options,
        pairs: q.pairs,
        acceptableAnswers: q.acceptableAnswers,
        isActive: true,
      });
    }
  }

  // 4. 批量插入（分批处理以适配 SQLite 限制）
  const BATCH_SIZE = 500;
  let inserted = 0;
  for (let i = 0; i < records.length; i += BATCH_SIZE) {
    const batch = records.slice(i, i + BATCH_SIZE);
    const result = await prisma.question.createMany({
      data: batch,
      skipDuplicates: true,
    });
    inserted += result.count;
  }

  console.log(`[seed-physics-renjiao] 共插入 ${inserted} 道物理人教版题目`);
  return inserted;
}